### ISSUE TITLE
Bash completions shouldn't exclude `help` command

### ISSUE THREAD

**Issue by voithos** [spf13/cobra#1000]
There appears to be an explicit check in the bash completion code that excludes the help command: https://github.com/spf13/cobra/blob/b04b5bfc50cbb6c036d2115ed55ea1bccdaf82a9/bash_completions.go#L326

This means that the resulting completion script doesn't show `help` as a valid cobra command, which seems unnecessary? This is also not present in the zsh completions generator.

**Comment by jharshman** [comment]
This is interesting.  Thank you @voithos for bringing this to my attention.  I will do some digging to see if there is a reason as to _why_ this was done.

**Comment by jharshman** [comment]
This was done a while ago in #128.

@eparis, you didn't give a description in your PR.  Can you shed some light on the reasoning behind excluding the autogenerated `help` command?

**Comment by eparis** [comment]
that was a while ago!

I think I, at the time, didn't want to generate documentation for an autogenerated help command. Nor did I want to include a 'see also' section if the only command was the autogenerated help command.

I guess I'd be fine with it showing up in bash completions. But I don't think we should have a -help man/md page for any autogenerated help command...

**Comment by jharshman** [comment]
@eparis thanks for the insight.
I agree that it shouldn't show up in man pages but I see no harm in it showing up in the bash autocompletion.

@voithos go ahead and cut a PR for this and I'll review.

**Comment by voithos** [comment]
This is still relevant. (For the bot)
