### ISSUE TITLE
invalid input ignored at end of a valid cobra command 

### ISSUE THREAD

**Issue by rathorea** [spf13/cobra#1011]
Hi All,

I have defined a command that should look like this:
./binary param1 param2

So when the user enters this:
./binary param1 param2 paramX 

The parser code somehow ignores paramX and executes the command as if user had entered:
./binary param1 param2

What am I missing? Any suggested way to fix this?

Thanks

**Comment by umarcor** [comment]
@rathorea, see https://github.com/spf13/cobra#positional-and-custom-arguments for instructions of how to limit the number of accepted parameters to two. I think that you might want to use `ExactArgs` and, optionally, `ExactValidArgs`.

Ref #841

**Comment by johnSchnake** [comment]
Seems asked and answered; closing.
