### ISSUE TITLE
Parent Command Details in Child command

### ISSUE THREAD

**Issue by kshitij299** [spf13/cobra#1015]
A command can have multiple parents. While executing `Run` of a command, is there a way to know which parent command was used?

Usecase: I want to write a single child command and add multiple parents to it, and then have it behave based on the parent which was used to call it.

**Comment by WuShaoQiang** [comment]
I think the best way you do that is to generate subcommands for each parents.
```
// It is a function to generate subcommand, so each subcommands have different address
func subC() *cobra.Command {
    return &cobra.Command{}
}

p1 := &cobra.Command{}
p2 := &cobra.Command{}
p1.AddCommand(subC())
p2.AddCommand(subC()) 
```

Is that what you want?

**Comment by rfinner** [comment]
This may be related to the new issue I have reported:

app get schedule

returns: schedule parent is get
** AND **

app create schedule

returns: schedule parent is get
for the following code:

var scheduleCmd = &cobra.Command{
Use: "schedule",
Run: func(cmd *cobra.Command, args []string) {
fmt.Println("schedule parent is ", cmd.Parent().Use)
},
}

func init() {
createCmd.AddCommand(scheduleCmd)
getCmd.AddCommand(scheduleCmd)
}

The reverse is also true if I reverse the order AddCommand. cmd.Parent() returns the LAST parent added, regardless of the actual command's parent.

**Comment by johnSchnake** [comment]
Seems like a question with relevant comments linked. Closing per #1600; feel free to reopen if you still have questions or issues.
