### ISSUE TITLE
unexpected "unknown flag" but flag appears in --help

### ISSUE THREAD

**Issue by pdbogen** [spf13/cobra#1021]
`demo.go`:

```go
package main

import (
	"github.com/spf13/cobra"
)

func main() {
	var root = &cobra.Command{Use: "demo"}
	var sub = &cobra.Command{Use: "sub", Run: func(*cobra.Command, []string) {}}
	sub.LocalFlags().Bool("test", false, "blah blah")
	root.AddCommand(sub)
	root.Execute()
}
```

```
$ go run demo.go sub --test
Error: unknown flag: --test
Usage:
  demo sub [flags]

Flags:
  -h, --help   help for sub
      --test   blah blah
```

I expect I'm doing something wrong, but it's not clear what, and moreover, it's very confusing that `--test` is listed in help but throws an error.

**Comment by WuShaoQiang** [comment]
I think the `LocalFlags` is for read-only use.

**Comment by pdbogen** [comment]
Ah, I think you're right. Just found this in the readme:

> Local Flags
> A flag can also be assigned locally which will only apply to that specific command.
> `localCmd.Flags().StringVarP(&Source, "source", "s", "", "Source directory to read from")`

Maybe a note in the godoc for `LocalFlags()` would be appropriate, noting it's intended to be read-only and directing to `Flags()`?

**Comment by WuShaoQiang** [comment]
The code shows only `Flags` and `PersistentFlags` will be parsed.
So what's your purpose of using `LocalFlags` for writing?

**Comment by pdbogen** [comment]
I was mistaken in trying to use `LocalFlags`; I should have been using `Flags`. I no longer think there's a bug here, but I do still think the documentation around these could be improved.
