### ISSUE TITLE
Is there a way to escape flag input?

### ISSUE THREAD

**Issue by shairozan** [spf13/cobra#1025]
Let's say I have a flag called `app_options`. I want to basically take whatever raw string is provided there and use it to hand to a binary underneath my application. 

Ergo if the CLI app I'm calling is `do_the_thing`, I want to pass the options from `app_options` to `do_the_thing`.

Ie
`do_the_thing [app_options]`

specifying `--app_options "-maxlim=0"` only yields a value of `0` for the `app_options` flag as if the rest of the string had been captured as a flag itself. 

Is there a way to specify an unescaped or unparsed string such that the above would pass the entirety of `maxlim=0` into the cobra flag?

**Comment by fulviodenza** [comment]
Is there any update about this issue?
I'm having the same trouble, I described it here https://stackoverflow.com/questions/70146280/cannot-insert-dash-in-cobra-parameters

**Comment by fulviodenza** [comment]
Found a solution, the user will need to add a "--" to the command

**Comment by marckhouzam** [comment]
You may also be interested in the Interspersed option of pflag: https://github.com/spf13/pflag/blob/d5e0c0615acee7028e1e2740a11102313be88de1/flag.go#L1208

**Comment by marckhouzam** [comment]
There's an explanation of the interspersed option in this issue https://github.com/spf13/cobra/issues/1307#issue-777308697

**Comment by johnSchnake** [comment]
Sounds like this got resolved. Closing.
