### ISSUE TITLE
Adding dynamic commands

### ISSUE THREAD

**Issue by yordis** [spf13/cobra#1026]
Hey there,

I am new into Go, and probably they are some barriers, so excuse my ignorance.

I want to use Go as my primary CLI tool, mainly because of the single binary.

But this exact reason I am confused about how I could inject dynamic commands after the CLI is bundled into a single binary.

Is there any way to accomplish this?
How could I extend the CLI by injecting more CLI plugins or something like that?

It would be amazing to add some documentation about this somewhere in the package docs.

Thanks in advance.

**Comment by marckhouzam** [comment]
There are many approaches.
You could look at how other Cobra programs do it to get ideas.
For example:
Kubectl - https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/
Helm - https://helm.sh/docs/topics/plugins/

**Comment by yordis** [comment]
@marckhouzam thank you very much, this definitely helps me to continue figuring out the path I could take.

Also,

Would it be beneficial if cobra handles this use case?

I feel this is such a common feature to have

**Comment by marckhouzam** [comment]
I'll let the maintainers answer.

One issue may be that as you may notice, kubectl and helm took different approaches for plugins. If Cobra provided a framework for plugins it would become opinionated on how plugins should be handled.

**Comment by jharshman** [comment]
While an interesting problem to think about, at this point in time I don't think it's something we want to tackle. Perhaps sometime in the future we could provide something, but it would have to not break current implementations like the ones @marckhouzam has mentioned.
