### ISSUE TITLE
Scrape remaining args as a value for a flag

### ISSUE THREAD

**Issue by BrendanThompson** [spf13/cobra#1042]
Say you have the following:

```
foo bar --title "Some title"
```

However you want to be able to also execute:

```
foo bar "some title"
```

Is that something that is supported with Cobra, I couldn't find any documentation pertaining to this? I assume it _would_ in theory be possible by scraping out the `args` however I am not sure of the behaviour where there are other flags in the command, such as:

```
foo bar --something "yes" --other "meow" "some title"
foo bar "some title" --other "meow"
```

Rather unsure how to approach this.

**Comment by jharshman** [comment]
This is behavior that would come out of processing the contents of `args`.
Not something that is explicitly supported / enabled by the cobra package.

**Comment by dionysius** [comment]
Does not sound undoable to me, but yes, you have to merge that yourself together. In theory:
Your `barCmd = &cobra.Command{...}` has `Args: cobra.MaximumNArgs(1)` as well as some sort of a `barCmd.Flags().StringVar(&title, "title", "", "description")` and when it is `Run: func(cmd *cobra.Command, args []string) {...}` you do a custom local variable either loading your flag `mytitle := title` or your argument `mytitle := args[0]`.
