### ISSUE TITLE
Support for short flags only

### ISSUE THREAD

**Issue by cornfeedhobo** [spf13/cobra#1043]
This issue is not specific to cobra, but [I've had a PR open on pflags](https://github.com/spf13/pflag/pull/171) since 2018. I'd really like to get some attention on this finally.

**Comment by jharshman** [comment]
I understand your frustration. But please don't cross post issues in other repositories here.

**Comment by cornfeedhobo** [comment]
@jharshman I completely understand, but I do hope you understand. After all, I waited 2 years. Which brings up a question... Does pflags need a new home and would cobra be willing to switch? It seems like that repo is owned by the same person but is only receiving sparse attention. I've had chats on some of the issues where users say they just maintain forks at this point and don't use cobra. That doesn't feel like a healthy situation and it'd be nice if the issue got some attention.
