### ISSUE TITLE
Discuss the reliance on spf13/pflag

### ISSUE THREAD

**Issue by cornfeedhobo** [spf13/cobra#1050]
I've been using cobra for a few years now. It's great. However, I've reached the point that I'm concerned about the reliance upon [spf13/pflag](https://github.com/spf13/pflag).

For example, there is a [failing test for `SetOutput` that I've had a PR open for over a year](https://github.com/spf13/pflag/pull/225). Thankfully that function is known to be good and hasn't been touched in a long time, but the fact that there is a failing test and a small unmerged PR to fix it for over a years in concerning. The only updates that repo does receive, seem to be internally created and motivated, meaning there is no hope in sight for the 30 open PRs to be addressed.

I would like to discuss the option of moving to a new fork of pflag. I'd be happy to create one and maintain it.

I know I created a similar issue to get attention to short flags, because it seems that @jharshman has merge rights there as well, but the issue was immediately closed (understandably). This time I am framing this issue as specific to cobra. Please do not immediately close this issue. This deserves an open discussion.

**Comment by jharshman** [comment]
@cornfeedhobo I do not have merge rights to plfag as I am not a maintainer there.

**Comment by cornfeedhobo** [comment]
@jharshman Oh, my apologies for my misunderstanding.

**Comment by jharshman** [comment]
@cornfeedhobo no worries - like I said in the previous issue you opened, I definitely can understand your frustration. I will raise the issue with @spf13 and see what can be done.
I do not think forking pflag is the correct answer.

For the time being, please be patient.

**Comment by jharshman** [comment]
This has been resolved - I will start to triage issues on pflag.
