### ISSUE TITLE
StringToString flag parsing

### ISSUE THREAD

**Issue by MohamedBeydoun** [spf13/cobra#1051]
When using the StringToStringP (and StringToString) flag, square brackets aren't included when retrieving the input:

```go
func init() {
        rootCmd.AddCommand(testCmd)
	...
	testCmd.Flags().StringToStringP("fields", "f", map[string]string{}, "description")
        ...
}
```

The following commands return a map with `foo=bar and foo=` respectively
```bash
$ root test -f foo=bar[]
$ root test -f foo=[]
```

The following commands return a map with `foo=bar[],hello=world and foo=[],hello=world` respectively
```bash
$ root test -f foo=bar[],hello=world
$ root test -f foo=[],hello=world
```

**Comment by jharshman** [comment]
@MohamedBeydoun this is not handled by Cobra but rather by Pflag. Please file your issue there.
github.com/spf13/pflag.
