### ISSUE TITLE
Undefined variables in README.md example (`addCmd` and `initCmd`)

### ISSUE THREAD

**Issue by mattalexander-pantheon** [spf13/cobra#1052]
The variables `addCmd` and `initCmd` are used in the README.md example, but the variables are not declared in the example code.

**Comment by jharshman** [comment]
The example code is meant to be an excerpt of some generated code to give the reader a general idea. It is not meant to be copied and pasted. However, if you think a more complete example would be useful, please submit a PR for this change.

**Comment by johnSchnake** [comment]
Closing due to lack of any other activity/feedback. Feel free to reopen or a PR for such an issue.
