### ISSUE TITLE
cobra CLI  tool doesn't handle Go modules well

### ISSUE THREAD

**Issue by bdoner** [spf13/cobra#1054]
I'm trying to make a go module outside of my GOPATH using cobra for sub commands. Sadly cobra doesn't seem to handle modules well.

Console output trying to create a go module and initialize cobra:

    C:\>mkdir example

    C:\>cd example

    C:\example>go mod init github.com/bdoner/example
    go: creating new go.mod: module github.com/bdoner/example

    C:\example>dir
    Volume in drive C has no label.
    Volume Serial Number is 7E39-A7E1

    Directory of C:\example

    09/03/2020  10:44    <DIR>          .
    09/03/2020  10:44    <DIR>          ..
    09/03/2020  10:44                42 go.mod
                1 File(s)             42 bytes
                2 Dir(s)  160,236,781,568 bytes free

    C:\example>cobra init
    Error: Rel: can't make C:\example relative to

    C:\example>cobra init .
    Error: Rel: can't make C:\example relative to

    C:\example>cobra init github.com/bdoner/example
    Your Cobra application is ready at
    C:\Users\******\code\Go\src\github.com\bdoner\example <-- Created Cobra application in my $GOPATH

    Give it a try by going there and running `go run main.go`.
    Add commands to it by running `cobra add [cmdname]`.

    C:\example>dir
    Volume in drive C has no label.
    Volume Serial Number is 7E39-A7E1

    Directory of C:\example

    09/03/2020  10:44    <DIR>          .
    09/03/2020  10:44    <DIR>          ..
    09/03/2020  10:44                42 go.mod
                1 File(s)             42 bytes
                2 Dir(s)  160,236,367,872 bytes free

    C:\example>

**Comment by jharshman** [comment]
What version of cobra generator are you using?
Please take a look at the instructions for using the generator.
https://github.com/spf13/cobra/blob/master/cobra/README.md#cobra-init
