### ISSUE TITLE
Disable / Bypass "unknown command" message when running an unknown command

### ISSUE THREAD

**Issue by cfi2017** [spf13/cobra#1055]
I'm writing a library wrapper around cobra for [discordgo](https://github.com/bwmarrin/discordgo).

The library works by invoking a user provided command factory that needs to return a root command.

The problem I'm running into is that when a user invokes a command using something like !test, and "test" is not a valid subcommand, cobra outputs `Error: unknown command "test" for "!"`.  
While this is intended behaviour, discord bot best practices state that invalid commands should not be output due to possible conflicts:  
https://github.com/meew0/discord-bot-best-practices (Rule 6)

This is only an issue because the root command use is the bot prefix (so `!`, for example). On unix, the root command would be unique (since it's the name of the binary), but on discord, multiple bots can share the same prefix.

My current approach looks something like this 
```go
if !root.IsAvailableCommand() && !root.IsAdditionalHelpTopicCommand() {
  // error function with ErrInvalidCommand
  return
}
```
before invoking the command.

This is rather cumbersome and hard to understand, and I am not certain it will catch every use case.

Is there a cleaner way to solve this problem?

Source code is here: https://github.com/cfi2017/dgcobra

**Comment by jharshman** [comment]
@cfi2017 , have you tried setting `SilenceErrors` or `SilenceUsage` on the Command?
