### ISSUE TITLE
Additional help topic commands now return "subcommand is required" error

### ISSUE THREAD

**Issue by ob-stripe** [spf13/cobra#1056]
#922 changed the behavior of all non-runnable commands, including additional help topic commands.

They now return the new `ErrSubCommandRequired` error, which by default results in `subcommand is required` being displayed and exiting with status 1. Both are incorrect for additional help topic commands, whose entire purpose is to display a help message.

Can we restore the previous behavior for additional help topic commands? Naively, something like this:

```patch
	if !c.Runnable() {
-		return ErrSubCommandRequired
+		if c.IsAdditionalHelpTopicCommand() {
+			return flag.ErrHelp
+		} else {
+			return ErrSubCommandRequired
+		}
	}
```

cc @bruceadowns

**Comment by bruceadowns** [comment]
At first glance, I'm in agreement with refining the change to _not_ consider an additional help topic commands an error.

It would help to see some examples and their expected behavior.

**Comment by ob-stripe** [comment]
Hi @bruceadowns, thanks and sorry for the delayed reply.

A concrete example would be the `resources` command in the [`stripe`](https://github.com/stripe/stripe-cli) CLI utility: https://github.com/stripe/stripe-cli/blob/master/pkg/cmd/resources.go

This command doesn't define a `Run` function or any subcommands (i.e. it's an "additional help topic" command). With cobra 0.0.5, the command behaves as expected:
```sh
$ go run cmd/stripe/main.go resources
Available commands:
  3d_secure
  ...
  webhook_endpoints

Use "stripe [command] --help" for more information about a command.

$ echo $?
0
```

After upgrading to cobra 0.0.6, a `subcommand is required` error is output and the process exits with status 1 instead:
```
 Available commands:
  3d_secure
  ...
  webhook_endpoints

Use "stripe [command] --help" for more information about a command.
subcommand is required
exit status 1

$ echo $?
1
```

Does that make sense? I can provide a minimal self-contained example project if you'd prefer.

If you agree that it makes sense, should I open a PR with the patch I proposed in the first comment, or would you have a more involved solution in mind?

**Comment by bruceadowns** [comment]
That makes perfect sense, thanks for the clarification. I'd recommend opening a PR, using your proposed solution, with any relatable tests.
