### ISSUE TITLE
How to invoke a subcommand by default

### ISSUE THREAD

**Issue by yeahdongcn** [spf13/cobra#1060]
I'm wondering whether a command could be able to call its subcommand by default. The commands hierarchy can be described as the following:

rootCmd (A) ->
   Cmd (B) ->
      Subcommand 1 (C)
      Subcommand 2 (D)

If I don't specify the actual subcommand, say type `A B -args`, is it possible to validate and invoke `A B C -args`?

**Comment by umarcor** [comment]
See #725.
