### ISSUE TITLE
Custom value flag definition should allow to pass-in default value

### ISSUE THREAD

**Issue by anson627** [spf13/cobra#1067]
flag.Var and flag.VarP do not take default value as input argument. This is inconsistent with other flags: e.g. 
flag.IntVar(&flagvar, "flagname", 1234, "help message for flagname") can be called like this, and 1234 is the default value for flagvar

one potential solution I can think of, is to take default value as string, and uses value.Set to parse default value string: e.g.
flag.Var(&flagvar, "flagname", "1234", "help message for flagname") can be called like this, and "1234" can be passed to Value.Set() to set default value of flagvar

**Comment by jharshman** [comment]
This would be handled by the pflag library not cobra. Please submit your issue at github.com/spf13/pflag.
