### ISSUE TITLE
`ErrSubCommandRequired` is no longer exported

### ISSUE THREAD

**Issue by stgraber** [spf13/cobra#1069]
Hi,

The `lxd` client has logic checking for that particular error being returned, starting a few hours ago, our builds broke as this error is no longer exported.

**Comment by stgraber** [comment]
That revert which was pushed today is the culprit.

It does fix the need for special handling of cases where ErrSubCommandRequire would previously appear, but its complete removal also means that anyone with mitigation for it in place is now finding themselves broken.

**Comment by jharshman** [comment]
@stgraber If you need this you can pin to 0.0.6, however this change will be reverted going forward.

**Comment by jharshman** [comment]
@stgraber I'm going to go ahead and close this issue. Looks like you've already resolved it on your end. Feel free to reach back out.
