### ISSUE TITLE
Choices for flags

### ISSUE THREAD

**Issue by brutalgg** [spf13/cobra#1081]
I'm trying to implement something like the following from python argparse using cobra.
`parser.add_argument('-l', dest='loglevel', choices=['error', 'warning', 'info', 'debug'], default='error', help='Logging level. Default is error')`

From digging through the documentation I don't think anything like this exists so I wanted to see if something like this has been considered as a feature?

**Comment by jharshman** [comment]
Cobra uses github.com/spf13/pflag for all of it's flag operations. Your issue sounds similar to this one:
https://github.com/spf13/pflag/issues/236

**Comment by brutalgg** [comment]
Thank you for that information. I'll add my support to the issue in pflag and close this issue.
