### ISSUE TITLE
How to check if flag was set or not?

### ISSUE THREAD

**Issue by Serhioromano** [spf13/cobra#1086]
I have Bool type flag and when I use `cmd.Flags().Get()` it is hard to understand if flag if false or flag is not set?

**Comment by jharshman** [comment]
@Serhioromano this would be a question for github.com/spf13/pflag. However, I think this should answer: https://godoc.org/github.com/spf13/pflag#FlagSet.GetBool

**Comment by Serhioromano** [comment]
No that will not solve my problem. Imagine I use viper for configuration and flag as an alternative. I want a flag to override viper loaded settings. 

Imagine my default flag state is `true` and in the configuration it is false

When I use `cmd.Flags().GetBool()` I'll get `true` if the flag is not set, but I do not know if the flag was set in cli or not. 

Imagine in parameters I have true but I set flag false and the default for flag is also false. When I get `cmd.Flags().GetBool()` I get always false but I do not know if it is default value or flag was set. Because if the flag is set then I override parameter if the flag was not set I sleep override.

In viper, you have IsSet or InConfig. I think same for flags would be nice to have to know if the flag is in the config for this CLI command and if it was passed in CLI command

**Comment by lhttjdr** [comment]
We need it in the following example.
- option is not set
- option is set without any value
- option is set with a value
```shell
cli                    # output to console
cli --output           # output to file with default file name
cli --output=xxx.txt   # output to file xxx.txt
```

Is it possible now?

**Comment by marckhouzam** [comment]
Would this help:
https://github.com/spf13/pflag/blob/7b22f689a41a1727c42eb02aaa1492d26402c592/flag.go#L177

Used here:
https://github.com/spf13/cobra/blob/11ba63fc3bc37818c471fc7912783e6909da4645/command.go#L989

**Comment by Serhioromano** [comment]
@marckhouzam looks good. Not exactly what I thnk should be done, but myight help in some cases.

**Comment by migueleliasweb** [comment]
For posterity:

If your case of checking if the flag is within Cobra (which uses `pflag` internally), you can do the following:

```golang
var myCmd = &cobra.Command{
	Use: "merge-options",
	Run: func(cmd *cobra.Command, args []string) {
            if cmd.Flags().Lookup("my-flag-name").Changed {
                // do something if the user actually set the flag
            }
}
``
