### ISSUE TITLE
[Bug][Contributor workflow] Github actions labeler doesn't work for forks

### ISSUE THREAD

**Issue by jpmcb** [spf13/cobra#1092]
I've noticed that the labeler Github action isn't working. [Here's an example](https://github.com/spf13/cobra/pull/1044/checks?check_run_id=583192945)

It looks like the `actions/labeler` Github action won't work with PRs opened from forks (for security reasons): https://github.com/actions/labeler/issues/12

And looks like this was recently clarified: https://github.com/actions/labeler/commit/2b75d22987baa8b9fb023106fe3a4d90648b7104

A few workarounds:
- https://github.com/kaxil/boring-cyborg in use by [apache airflow](https://github.com/apache/airflow/blob/master/.github/boring-cyborg.yml)
- https://github.com/marketplace/actions/periodic-labeler in use by [cloud alchemy](https://github.com/cloudalchemy/ansible-prometheus/blob/master/.github/workflows/labeler.yml)

@xchapter7x I know you looked at the labeler previously in https://github.com/spf13/cobra/pull/1074 - Any thoughts here?

**Comment by xchapter7x** [comment]
seems like the `periodic-labeler` would wrap what we have now, and make it work as intended.

the `boring-cyborg` might be better long term, as it seems to have more logic and features. 

id maybe implement `periodic-labeler` as a bugfix, and then explore future enhancements to the feature set with things like `boring-cyborg` or anything else that might be available in the marketplace.

**Comment by xchapter7x** [comment]
This PR should address this bug: https://github.com/spf13/cobra/pull/1097
