### ISSUE TITLE
subcommand immediately exits when calling external program

### ISSUE THREAD

**Issue by divramod** [spf13/cobra#1105]
Hey, thx for the awesome tool!

I just started with cobra and golang and have a weired (not understood by me) behaivior of subcommands.

at first i created two commands (parent: config and sub config-edit).

both commands are starting fine, i can see the initial output of the function beeing called.

Now i wanted to start vim from the subcommand with the following code:

```
tool config edit
```

```
//Package cmd ...
package cmd

import (
	dlog "dp/utils/log"
	"fmt"
	"os"
	"os/exec"

	"github.com/spf13/cobra"
)

// configEditCmd represents the configEdit command
var configEditCmd = &cobra.Command{
	Use:   "configEdit",
	Short: "",
	Long:  ``,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("configEdit called")
		home, err := os.UserHomeDir()
		if err != nil {
			dlog.Err(err.Error())
		}
		editCmd := exec.Command("vim", home+"/.config/config.yaml")
		editCmd.Stdout = os.Stdout
		editCmd.Stdin = os.Stdin
		editCmd.Stderr = os.Stderr
		editCmd.Run()
	},
}

func init() {
	configCmd.AddCommand(configEditCmd)
}
```

After doing that, vim does not start, but i can see, that the function was called because of the fmt output.

If i put the same code in the parent command and start it with ```tool config``` vim will open just fine. I experienced that with other cli tools besides vim too. Can anyone explain that to me or give me a hint?

```
//Package cmd ...
package cmd

import (
	dlog "dp/utils/log"
	"os"
	"os/exec"

	"github.com/spf13/cobra"
)

// configCmd represents the config command
var configCmd = &cobra.Command{
	Use:     "config",
	Short:   "A brief description of your command",
	Aliases: []string{"c"},
	Long:    ``,
	Run: func(cmd *cobra.Command, args []string) {
		home, err := os.UserHomeDir()
		if err != nil {
			dlog.Err(err.Error())
		}
		editCmd := exec.Command("vim", home+"/.config/config.yaml")
		editCmd.Stdout = os.Stdout
		editCmd.Stdin = os.Stdin
		editCmd.Stderr = os.Stderr
		editCmd.Run()
	},
}

func init() {
	rootCmd.AddCommand(configCmd)
}

```

**Comment by mislav** [comment]
I can't tell what causes it, but it would be helpful if you handled the error from `editCmd.Run()`. Maybe right now it's reporting something, but you are discarding it.

**Comment by johnSchnake** [comment]
Closing due to time and lack of activity (motivated by #1600). If you still have problems (or found your solution) feel free to comment here and/or reopen.
