### ISSUE TITLE
cobra init cmd documentation seems to be incorrrect

### ISSUE THREAD

**Issue by wfernandes** [spf13/cobra#1107]
As I was playing around with `cobra init` I noticed the help documentation seems to be at odds with the [cobra/README](https://github.com/spf13/cobra/blob/11ba63fc3bc37818c471fc7912783e6909da4645/cobra/README.md#cobra-init) documentation.

The `cobra init --help` prints out the following:
```
  * If a name is provided, it will be created in the current directory;
  * If no name is provided, the current directory will be assumed;
  * If a relative path is provided, it will be created inside $GOPATH
    (e.g. github.com/spf13/hugo);
  * If an absolute path is provided, it will be created;
  * If the directory already exists but is empty, it will be used.

Init will not use an existing directory with contents.
```

However, as I was using the command and reading through the documentation, the following statements seem to be incorrect. 
```
  * If a relative path is provided, it will be created inside $GOPATH
    (e.g. github.com/spf13/hugo);
  * If an absolute path is provided, it will be created;

Init will not use an existing directory with contents.
```

Upon inspection of the code, we seem to be prepending the current working directory to the argument passed in. 
https://github.com/spf13/cobra/blob/11ba63fc3bc37818c471fc7912783e6909da4645/cobra/cmd/init.go#L46-L58

So I guess the question here is: **what is the expected behavior? Is to initialize a project in the current working directory? Or should we be supporting relative paths in GOPATH and absolute paths?**

**Comment by jharshman** [comment]
I think the text in the readme does a good job depicting it's behavior:
> ... You can either run it in your current application directory or you can specify a relative path to an existing project. If the directory does not exist, it will be created for you.

However, as you have brought up, these comments should be fixed. Namely the comment that `init` will not use an existing directory with contents. As it is, init will overwrite conflicting contents in a directory.
>   * If a relative path is provided, it will be created inside $GOPATH
    (e.g. github.com/spf13/hugo);
>  * If an absolute path is provided, it will be created;
>
> Init will not use an existing directory with contents.
