### ISSUE TITLE
Expose annotations in the Cobra API

### ISSUE THREAD

**Issue by bep** [spf13/cobra#111]
Ref. the bashcompletion sample:

```
 annotations := []string{"json", "yaml", "yml"}
    annotation := make(map[string][]string)
    annotation[cobra.BashCompFilenameExt] = annotations

    flag := &pflag.Flag{
        Name:        "filename",
        Shorthand:   "f",
        Usage:       usage,
        Value:       value,
        DefValue:    value.String(),
        Annotations: annotation,
    }
    cmd.Flags().AddFlag(flag)
```

There are a couple of issues with this:

1) It's incomplete. What is `value`?
2) It's kind of missing the point of `Cobra` being the abstraction it is.

2) would maybe be fine if the Value types in `pflag` were exported.

**Comment by eparis** [comment]
I don't think I understand the complaint.  Your complaint is about how I'm showing to create a pflag?  Would you rather I had:

```go
//Assuming there is a flag defined named "filename"

flag := cmd.Flags().lookup("filename")
flag.Annotations = annotation
```

Is that better? Would you rather I showed the cmd.Flags().String() form instead of a static declaration?

**Comment by bep** [comment]
My starting point was this:

- I have a command with some flags added with the convenient BoolVar methods.
- I want to add some annotations to one of the flags to make the bashcompletions more ... complete

The example above is of very little help to me. It doesn't compile without adding some Value implementation.

So, making the doc example not depend on a lot of what-ifs would be a start -- but the Flag.Annotations seem to have been added without thinking too hard about how to add it, given all the factory methods with no annotations arg.

**Comment by bep** [comment]
But it's not very important ... I was in a slightly bad mood when I wrote this. The lookup pattern in the example would make this easier to use.
