### ISSUE TITLE
Argument containing space doesn't parse correctly via PersistentFlags().GetString()

### ISSUE THREAD

**Issue by MonstraG** [spf13/cobra#1114]
I have the following (simplified) code to get the arg value:
```golang
var cmd = &cobra.Command{
	Use: "name",
	Run: func(cmd *cobra.Command, args []string) {
		flagValue, _ := cmd.PersistentFlags().GetString("name")
		println(flagValue)
	},
}

func init() {
	cmd.PersistentFlags().String("name", "", "usage string")
}
```

I've tried following constructions
```
run --name=abc def    [parses as `abc`]
run --name='abc def'  [parses as `'abc`]
run --name="abc def"  [parses as `"abc`]
run --name 'abc def'  [parses as `'abc`]
run --name "abc def"  [parses as `"abc`]
````

**Comment by AnatolyRugalev** [comment]
The same issue goes with args. You can't pass space separated strong as an argument using space escaping, sinle or double quotes. E.g ./cmd 'long argument' will make two arguments instead of expected one. This is especially annoying when working with paths

**Comment by Hetann** [comment]
Any news on this?

**Comment by MonstraG** [comment]
Just to note: I've ended up basically url-escaping my path argument.

**Comment by johnSchnake** [comment]
What OS are you on?

I'm on a mac and all 4 of those invocations worked fine:
```
➜ ./tmp run --name="hello there"
hello there
➜ ./tmp run --name='abc def'
abc def
➜ ./tmp run --name 'abc def'
abc def
➜ ./tmp run --name "abc def"
abc def
```

Going to close for now in case this was just resolved via other changes over the last ~2y. If you are still having the problem on your machine, reopen and let me know the OS and we can go from there.

**Comment by DirkTheDaring** [comment]
Issue happens to me on Linux 
 github.com/spf13/cobra v1.5.0 // indirect
`	statusCmd.Flags().StringVar(&statusOptions.Match, "match", "", "match")`
and the following output code
`		fmt.Fprintf(os.Stderr, "BUG?: >%v<\n", statusOptions.Match)`
result in  the following output 
BUG?: >This<
instead of "This is a test"

**Comment by marckhouzam** [comment]
What was your input to the command line?

(And out of curiosity, what are you using that makes Cobra an "indirect" import).

**Comment by DirkTheDaring** [comment]
not sure about the indirect import, first time i ever looked into it since I started using cobra.
commandline as described above is simple "./cmdname --match "This is a test"  ...  (I filter a list of names, and I stumbled about this because after debugging it did to take strings which contained a space, or to be exact only the first one)

**Comment by DirkTheDaring** [comment]
Additional information:
I did quick check on windows.  It works fine there!

**Comment by DirkTheDaring** [comment]
additional TEST: i have prefixed "This is a test" with a space: " This is a test".  Still leads to the same results as above ">This<" with the leading space removed.

**Comment by DirkTheDaring** [comment]
Please close the issue.
I have tricked myself with some shell magic (where is rerouted the command to another script to add some ENV variables). This script contain as call 'cmd $*' to the original command  which of course does not work for arguments which contains spaces, as the recommendation is to use 'cmd "$@"'.   

Sorry for being stupid. please close the issue.

**Comment by marckhouzam** [comment]
It happens to the best of us 😄 .
Thanks for following up.
