### ISSUE TITLE
Document usage for fish completion

### ISSUE THREAD

**Issue by mayankshah1607** [spf13/cobra#1115]
Now that https://github.com/spf13/cobra/pull/1048 has been merged, it would be nice to have some documentation around how to generate completion scripts for `fish` shell :)

**Comment by marckhouzam** [comment]
We have this for now: https://github.com/spf13/cobra/blob/master/fish_completions.md

And PR #1070 completely re-organises the documentation around completion.

You can read the proposed new documentation here for now:
Completion in general: https://github.com/VilledeMontreal/cobra/blob/feat/zshCompletionV2/shell_completions.md
Fish section: https://github.com/VilledeMontreal/cobra/blob/feat/zshCompletionV2/shell_completions.md#fish-completions

If you have any suggestion to improve the doc, please do comment on the PR.
Thank you

**Comment by mayankshah1607** [comment]
Thanks for the quick response, @marckhouzam !
Can we add a link in the readme, like [this](https://github.com/spf13/cobra#generating-zsh-completions) ? Becomes a lot easier to find :)
Thanks

**Comment by marckhouzam** [comment]
> Can we add a link in the readme, like [this](https://github.com/spf13/cobra#generating-zsh-completions) ? Becomes a lot easier to find :)

PR #1070 is reworking all the doc for completion.  But I don't know if/when it will be accepted.  In the mean time you could always post a PR to add the link you suggest to the main README.

**Comment by marckhouzam** [comment]
Now that #1070 has been merged we have better docs for fish completion.  An example is given here:
https://github.com/spf13/cobra/blame/master/shell_completions.md#L57

I believe this issue can be closed. /cc @jpmcb
