### ISSUE TITLE
ValidArgsFunction work in bash but not in zsh

### ISSUE THREAD

**Issue by alejandrojnm** [spf13/cobra#1116]
I have this function that works perfectly in bash but not in zsh.

```
ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		if len(args) != 0 {
			return nil, cobra.ShellCompDirectiveNoFileComp
		}
		return getDomainList(toComplete), cobra.ShellCompDirectiveNoFileComp
	},
```

**Comment by marckhouzam** [comment]
Zsh support for `ValidArgsFunction` is being added to zsh in #1070.

**Comment by alejandrojnm** [comment]
Yes i know, i use the v1.0.0 of cobra, but it still doesn't work, Do I need something else?

**Comment by marckhouzam** [comment]
PR #1070 has not been merged yet 😄, so you cannot use `ValidArgsFunction` with Zsh right now.

**Comment by alejandrojnm** [comment]
Thank you very much, I will leave the function implemented in any way, until the PR are merged

**Comment by marckhouzam** [comment]
@alejandrojnm If you are satisfied with the explanation, could you close this issue?  Thank you.
