### ISSUE TITLE
Taking struct as input in Flags

### ISSUE THREAD

**Issue by raju249** [spf13/cobra#1119]
I am working on a CLI where I have to accept a flag as JSON body

Example:
```go run cli.go  --parent.child1=value1 --parent.child2=value2 --parent.child2=value3 ...```

HERE, `value2` and `value3`  is also a JSON structure. Basically, any `--parent.child2` values are in JSON format. But they are to be accepted in below format.
```
"key1=somevalue1; key2=somevalue2; key3=somevalue3, somevalue4"
```
 and they are to be converted to below format
```
value2 = {"key1":"somevalue1", "key2":"somevalue2", "key3":["somevalue3", "somevalue4"] // key3 is an array }
```

This need to result in the following JSON for the backend server
```
parent: {
        "child1" : value1,
        "child2" : [
            value2,
            value3,
            ...
        ]
  }

```

I searched for documentation online, could not find it 🤔 

Any help in form of online examples, DIY docs would be helpful 🙏 

Thanks

**Comment by jharshman** [comment]
@raju249 the way you might try to go about this is to handle the incoming variables as a slice of bytes and then attempt to decode that byte slice into a structure that you have defined in your program.  

Let me know if that helps.
