### ISSUE TITLE
functions in fish shell completion auto-generated file should not contain "-" character

### ISSUE THREAD

**Issue by umbynos** [spf13/cobra#1121]
As asked by @marckhouzam [here](https://github.com/spf13/cobra/pull/1117#issuecomment-631455437), I'm opening this issue.
I'm working on [this PR](https://github.com/arduino/arduino-cli/pull/663) and I noticed a problem with the auto-generated cobra completion file for fish shell: If the root command to complete contains a dash character in the name "-" (e.g. `arduino-cli`) the autocompletion will not work because of function naming (a function called `__arduino-cli_comp_do_file_comp` is created). For reference: https://github.com/fish-shell/fish-shell/issues/1206

To fix this I simply replaced "-" with "_" [here](https://github.com/arduino/arduino-cli/pull/663/commits/525cab25fd2ca6c486243fc3f6b838c885905e1f). But maybe it's better to fix this behaviour in cobra? Something like: if the command name contains a dash character automatically is replaced with an underscore.

**Comment by marckhouzam** [comment]
Thanks @umbynos.
I noticed that Cobra's bash completion was replacing `:` for commands.
https://github.com/spf13/cobra/blob/94a87a7b83bda98e918cf7a4793f41372a5e4139/bash_completions.go#L350
  It does not affect Fish, but if the program has a `:` in the name (not a good idea, but supported), it would cause problems.

I will post a PR that replaces both `-` and `:` for fish completion.

**Comment by marckhouzam** [comment]
Fix in #1122
