### ISSUE TITLE
<space>[tab][tab] executes the command handler instead of just autocomplete

### ISSUE THREAD

**Issue by shettysurajk** [spf13/cobra#1127]
When a command is complete with all keywords <space> [tab][tab] executes the command handler.
Instead it should just autocomplete.

**Comment by marckhouzam** [comment]
Hi.
Can you give a specific example of what you mean?
What version of Cobra are you using?
What shell?

**Comment by shettysurajk** [comment]
Example:

command subcommand <space> [tab][tab]
-> executes the RunE function

Cobra version: 0.0.3

Shell: Bash

**Comment by marckhouzam** [comment]
Cobra 0.0.3 is a pretty old version.
Could you try with 1.0?

**Comment by shettysurajk** [comment]
I did try with 1.0. Same behavior seen.

**Comment by marckhouzam** [comment]
How did you generate and load the bash completion script for the program?

Can you provide a small program to reproduce the problem?

**Comment by samirsss** [comment]
Bump on this one

Here's our sample auto-completion bash script

_efa()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    COMP_WORDS[COMP_CWORD]=""
    input=$(${COMP_WORDS[@]} 2>/dev/null | awk '{print $1}')
    declare -a opt
    flag=0
    for i in ${input[@]}
    do
      if [ "$i" == "Available" ]
          then flag=1
      elif [ "$i" == "Flags:" ]
          then flag=0
      elif [ $flag -eq 1 ]
          then opt=( "${opt[@]}" $i )
      fi
    done
    opts="${opt[@]}"
    if [[ ${cur} == * ]] ; then
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
        return 0
    fi
}
complete -F _efa efa

**Comment by marckhouzam** [comment]
@samirsss Cobra can generate the completion script for your program. But the example you have seems to be a script not generated by Cobra.
