### ISSUE TITLE
Add options to the shell completion to hide persistent flags on subcommands

### ISSUE THREAD

**Issue by Luap99** [spf13/cobra#1132]
It would be great to have a option to exclude persistent flags in the shell tab completion on its subcommands. It would also be helpful to add a option to disable the suggestion with the equal sign, so that the flag is only shown once.
When working with many flags it would be helpful to have these options so the shell doesn't suggest that much.

**Comment by marckhouzam** [comment]
> It would be great to have a option to exclude persistent flags in the shell tab completion on its subcommands.

I wonder if this is a good idea.  Persistent flags are meant to be applicable to the command and all its sub-commands.  This allows the user to use the flag anywhere in the sub-command tree.
For example, a `--debug` flag could be made persistent from the root command.  So you could do:
- `program --debug`
- `program subcmd1 --debug`
- `program subcmd1 subcmd2 --debug`

A user would benefit from being able to complete the `--debug` flag in each of these cases.

However, a different idea along the same lines would be for completion to only suggest a flag if it was not already used.  So:
- `program subcmd1 [tab]` would suggest `--debug`
but
- `program --debug subcmd1 [tab] ` would not suggest it

This is what Cobra's current zsh completion does now and is also what #1070 is implementing for zsh/fish completion.

However, bash completion does not do that but could be improved.

> It would also be helpful to add a option to disable the suggestion with the equal sign, so that the flag is only shown once.

I agree with this.  Suggesting both `--flag` and `--flag=` forces the user to *always* have to type either an `=` or a space after the flag name.  Furthermore, boolean flags and shortname flags don't show the `=` form.

#1070 has turned off the `=` form for zsh and fish completion (see https://github.com/spf13/cobra/pull/1070/files#r422680307).  However, bash completion does not do that but could be improved.

**Comment by Luap99** [comment]
I agree but i we have many persistent flags on the main command which are rarley used and only a few flags on the subccomand which are importent. So an option to change this behavior would be very helpful.

**Comment by johnSchnake** [comment]
Based on what you're describing its just coincidental that they are persistent flags on a parent command. The reason you want to hide them is because they happen to not be particularly useful in your specific use case.

At that point I think you'll have to just either work with the existing behavior or provide custom help to order/present your flags as you want.

Closing as motivated by #1600.
