### ISSUE TITLE
How do I get the flag of the currently executing command?

### ISSUE THREAD

**Issue by fullstack-zhangpeng** [spf13/cobra#1133]
I didn't see that description in the article.

Looking forward to your reply

**Comment by marckhouzam** [comment]
I'm not sure of the correct way to do this. The one way I know of is to loop over all flags and check if `flag.Change` is true which seems to indicate the flag is present.  See here:
https://github.com/spf13/cobra/blob/ed7b60e2987d2cd54d6a391379e33effdacdadf9/command.go#L993

I'd love to hear of a better way if there is one.

**Comment by jharshman** [comment]
@fullstack-zhangpeng, does @marckhouzam's answer suffice? If not, can you give a more detailed example of what you're trying to accomplish?

**Comment by fullstack-zhangpeng** [comment]
close issue
