### ISSUE TITLE
WARNING: go-md2man does not handle node type HTMLSpan

### ISSUE THREAD

**Issue by MichaelMure** [spf13/cobra#1137]
When generating Markdown documentation for https://github.com/MichaelMure/git-bug, I get this warning: `WARNING: go-md2man does not handle node type HTMLSpan`

My understanding is that it's because I'm using `<arg>` in `Command.Use` to indicate an argument, in addition to `[]` to indicate an optional element:

```go
var pushCmd = &cobra.Command{
	Use:     "push [<remote>]",
	Short:   "Push bugs update to a git remote.",
	PreRunE: loadRepo,
	RunE:    runPush,
}
```

Could you clarify what is the expected format for `Command.Use` if any ?

**Comment by jpmcb** [comment]
I would consider using _only_ brackets `[ some-command ]` as a best practice. So instead, I would do:
```
Use:     "push [remote]",
```
This is a really good reference for command line usage syntax: https://www.ibm.com/support/knowledgecenter/SSZJPZ_8.5.0/com.ibm.swg.im.iis.common.doc/common/command_conventions.html

Going to go ahead and close this as the error from go-md2man is not unexpected

**Comment by MichaelMure** [comment]
Ha thanks.

Would you consider having those rules in the documentation or in the code for the next person?

**Comment by jpmcb** [comment]
Not a bad idea! If you'd like to open a PR for that, feel free to tag me and I will review 🙏
