### ISSUE TITLE
[Question] How to implement streamed output, like the '-f' in 'kubectl logs -f'

### ISSUE THREAD

**Issue by RexG** [spf13/cobra#1141]
many thanks

**Comment by mwxxhdb** [comment]
@RexG 
I'm not a expert of golang, here is my solution hope this can help you.
```go
cmd := exec.Command("kubectl", "logs", "-f")
cmd.Stdout = os.Stdout
cmd.Stderr = os.Stderr
cmd.Stdin = os.Stdin
cmd.Run()
```

**Comment by RexG** [comment]
thank you, @mwxxhdb 

actually, i was trying to implement something like what `kubectl logs -f` do

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/logs/logs.go#L336

but which is kind of complex, a easier way will be much better
