### ISSUE TITLE
How should you return errors from commands?

### ISSUE THREAD

**Issue by Xeoncross** [spf13/cobra#1148]
I don't see anything in the documentation about returning errors (the function signature has a void return as well).

Are you supposed to just fmt.Print/log.Print/Zap/Logrus/etc.. yourself from inside the function?

Should you use `cmd.PrintErr()` or some other command? 

Can someone update the `/README.md` with pointers?

**Comment by marckhouzam** [comment]
Are you maybe looking for the `RunE` field, which allows to return an error?

**Comment by erdaltsksn** [comment]
For the simplest form, you may use the following:

```go
fmt.Println("Something went wrong")
fmt.Println(err.Error())
os.Exit(1)
```

You can use my library [erdaltsksn/cui](https://github.com/erdaltsksn/cui) as a ui library if please.

```go
cui.Error("Something went wrong", err)
```

<img width="725" alt="cui-ss" src="https://user-images.githubusercontent.com/22197800/86353791-857ad480-bc70-11ea-8797-07e4c763064a.png">
