### ISSUE TITLE
Override -h flag

### ISSUE THREAD

**Issue by blacktop** [spf13/cobra#1155]
Is there a way for me to override the -h (normally help cmd) flag for a single command?  I have a command where `-h` is the most intuitive short version of the `--header` flag, but `-h` is already the `--help` flag.

Thank you for your help and an amazing tool.

**Comment by eparis** [comment]
I believe if you manually define a --help flag without the -h shorthand you can us -h in your flag.

**Comment by johnSchnake** [comment]
Seems like this got resolved. Closing.
