### ISSUE TITLE
zsh completion doesn't work

### ISSUE THREAD

**Issue by kraymond37** [spf13/cobra#1165]
I create a completion command as [this](https://chromium.googlesource.com/external/github.com/spf13/cobra/+/HEAD/shell_completions.md) said. Bash completion works well, in contrast, zsh doesn't work. 
Did I miss something?  I like cobra very much, and really wish it could work.

**Comment by Luap99** [comment]
How do you load your completion script?
I think you need to do `yourprogram completion zsh > "${fpath[1]}/_yourprogram"`

**Comment by marckhouzam** [comment]
@Luap99 is probably right and it points out that the documentation is mis-leading:
https://github.com/spf13/cobra/blame/master/shell_completions.md#L36
I'll post a PR.

**Comment by kraymond37** [comment]
@Luap99 Thanks. I found `source` didn't work, and `yourprogram completion zsh > "${fpath[1]}/_yourprogram"` didn't work either. Both `yourprogram completion zsh > "${fpath[1]}/_yourprogram"` and `compinit` should be executed, and sometimes also need to relogin shell.

**Comment by marckhouzam** [comment]
> Thanks. I found `source` didn't work, and `yourprogram completion zsh > "${fpath[1]}/_yourprogram"` didn't work either. Both `yourprogram completion zsh > "${fpath[1]}/_yourprogram"` and `compinit` should be executed, and sometimes also need to relogin shell.

Thanks @kraymond37, we have updated #1169 to include that information.
If that is satisfactory, would you mind closing this issue here?
