### ISSUE TITLE
Complete subcommands after local flag

### ISSUE THREAD

**Issue by Luap99** [spf13/cobra#1170]
Currently the custom completion does not complete subcommands after a local flag was given.
I think this is wrong since a program can use subcommands even when there were local flags on the root/parent command given.

https://github.com/spf13/cobra/blob/b95db644ed1c0e183a90d8509ef2f9a5d51cc29b/custom_completions.go#L283-L287

**Comment by Luap99** [comment]
@marckhouzam Is there a special reason for this? Otherwise i would like to change this behavior.

**Comment by marckhouzam** [comment]
> Is there a special reason for this? Otherwise i would like to change this behavior.

Yes this is on purpose for local flags. If a command has a local flags it does not get inherited by a subcommand, so it would be wrong to suggest subcommands as they will fail with the error "unknown flag".

However for persistent flags, which are inherited by subcommands, we do complete subcommands.

Makes sense?

**Comment by Luap99** [comment]
Yes that makes sence.

However in the podman it works like this:
`podman --remote ps -a` remote is a local flag on the root cmd here.

I found out that this works because `TraverseChildren` is set to true on the root cmd so i would say the completion logic should respect TraverseChildren too.

I can open a PR if you agree?

**Comment by marckhouzam** [comment]
Aha. I'm not familiar with the `TraverseChildren` logic.  You may have found a scenario that was missed.  Yes please go ahead and file a PR.  Thanks!

**Comment by marckhouzam** [comment]
@Luap99 could you check if the case you mention works with bash completion?

**Comment by marckhouzam** [comment]
That is strange. I mimicked the local flag behavior on what was done in the current bash completion... See #288

**Comment by Luap99** [comment]
I also noticed there is bug when you have a local boolean flag there is no subcommand completion but after you provide one argument subcommands are suggested. This doesn't happen with a Persistent Flag.

**Comment by Luap99** [comment]
> I also noticed there is bug when you have a local boolean flag there is no subcommand completion but after you provide one argument subcommands are suggested.

Nevermind my test setup was wrong ;)
It works for local boolean flags, but for local flags with arguments subcommands are still getting completed. So it is inconsistent.

**Comment by marckhouzam** [comment]
> > @Luap99 could you check if the case you mention works with bash completion?
> 
> Yes it does work but regardless of whether `TraverseChildren` is set or not.

I've looked further into this and it seems to be a bug with the current bash completion.
When using a boolean flag or the `=` form for a flag (e.g. integer), sub-commands are not shown after a local flag as expected, but when using the no-`=` form, it does complete:
```
bash-5.0$ ./testprog --local 1 [tab][tab]
child1      completion  help
# Sub-commands are completed when they shouldn't

bash-5.0$ ./testprog --local=1 [tab][tab]
[file completion is done]
# Sub-commands are NOT completed as expected

bash-5.0$ ./testprog --bool [tab][tab]
[file completion is done]
# Sub-commands are NOT completed as expected
```
My guess is that this bug was introduced along the way as the bash completion script evolved.
I will open an issue to keep track of this.

**Comment by marckhouzam** [comment]
I've opened #1172 for the discrepancy with bash.
