### ISSUE TITLE
windows flag parse error

### ISSUE THREAD

**Issue by hard88** [spf13/cobra#1177]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.5 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code></summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wrh/Library/Caches/go-build"
GOENV="/Users/wrh/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/wrh/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ry/j69gs315519fm5twbxlv50hr0000gp/T/go-build653498298=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

<pre>
//  kk.go

func main() {
	cmd := NewKKCmd()
	cmd.Execute()
}

func NewKKCmd() *cobra.Command {
	var (
		arg1 string
		arg2 string
		dir  string
	)

	cmd := &cobra.Command{
		Use: "kk",
		Run: func(cmd *cobra.Command, args []string) {
			log.Println(arg1, arg2, dir)
		},
	}

	cmd.Flags().StringVar(&arg1, "arg1", "", "")
	cmd.Flags().StringVar(&arg2, "arg2", "", "")
	cmd.Flags().StringVar(&dir, "dir", "", "")

	return cmd
}
</pre>

<pre>
// main.go

func main() {
	shell := `kk.exe --arg1=1 --arg2=2 --dir="C:\Program File"`
	cmd := exec.Command("cmd", "/C", shell)
	data, err := cmd.CombinedOutput()
	log.Println(string(data), err)
}

</pre>

I build main.exe and kk.exe for my windows 7 machine, and run main.exe.

### What did you expect to see?

arg1 = 1
arg2 = 2
dir = C:\Program Files

### What did you see instead?

arg1 = 1
arg2 = 2
dir = "C:\Program

**Comment by Luap99** [comment]
Why do you not call the exe directly?
```
exec.Command("kk.exe", "--arg1=1", "--arg2=2", "--dir=C:\Program File")
```

This should also work:
```
shell := `kk.exe --arg1=1 --arg2=2 "--dir=C:\Program File"`
```
