### ISSUE TITLE
Example usage of ValidArgsFunc

### ISSUE THREAD

**Issue by infixint943** [spf13/cobra#1178]
Could a simple example for `ValidArgsFunc` be given, as it's not clear what exactly we ought to do in it.
A simple example could be listing all `.go` files in the current directory.

Thanks for this library!

**Comment by Luap99** [comment]
There are examples in the [shell_completions.md](https://github.com/spf13/cobra/blob/master/shell_completions.md) file.

> A simple example could be listing all .go files in the current directory.
```
func AutocompleteGoFiles(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
	return []string{"go"}, ShellCompDirectiveFilterFileExt
}
```

**Comment by infixint943** [comment]
Yes, thanks a lot! Maybe adding it to the readme for better visibility?

**Comment by wfernandes** [comment]
@infixint943 I hope the information in `shell_completions.md` was useful. 
@Luap99 thanks for helping out. 

Since `ValidArgsFunction` is related to shell completion, it makes sense to have it in the `shell_completions.md` file. I believe the original intent was to avoid adding more information to the main README. What do you think?

**Comment by infixint943** [comment]
Yes, that makes sense.
One last request is to state (in the README) that custom completions don't work on zsh, unless you use the master branch. If you could create a new release, it would be much better!

Thanks for the support!

**Comment by wfernandes** [comment]
@infixint943 If you can create a PR adding that note in the README and tag me in it I can take a look at it. Thanks.

Also, we are working on creating a proposal on how we are going to cut releases and support versioning regarding Golang for example. As soon as those guidelines are up, we will plan for cutting future releases.
Until then I think your note/warning in our README would be useful.

**Comment by wfernandes** [comment]
I'll close this issue since it seems to be resolved. Thanks!
