### ISSUE TITLE
when one flag assigned many times,return error

### ISSUE THREAD

**Issue by NoGroceries** [spf13/cobra#1186]
`mycmd data upload -n flag1 -n flag2`

when flag "n" assigned two times, I want return error to warning user instead of the last value

**Comment by eparis** [comment]
you'd have to define your own custom flag type (in pflag) and inside your Set() function you've have to see if pflag.Changed is true and return error if so

**Comment by johnSchnake** [comment]
Asked and answered. For completeness I'll just state that this isn't the default since some flags are defined to append multiple values. Again, you can redefine this behavior if you have a strict use-case.
