### ISSUE TITLE
new zsh completion prefers flags over nouns

### ISSUE THREAD

**Issue by trusch** [spf13/cobra#1189]
When I setup dynamic auto completion of positional arguments in my code like this:

```
var createCmd = &cobra.Command{
	Use:               "create",
	Short:             "create creates the whole stack or just single components",
	Long:              `create creates the whole stack or just single components.`,
	ValidArgsFunction: validServices,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("create", args[0])
	},
}

func validServices(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
	args, err := getServiceNames(cmd)
	if err != nil {
		return nil, cobra.ShellCompDirectiveError
	}
	return args, cobra.ShellCompDirectiveDefault
}

func init() {
	rootCmd.AddCommand(createCmd)
}
```

I just get completions for the persistent flags inherited from the root command but the `ValidArgsFunction` seems to be never called.

Version was v1.0.1-0.20200811123951-5cdf8e26ba70 (master from today)

**Comment by marckhouzam** [comment]
You can debug by trying:
`<program> __complete create ""<ENTER>`

If it doesn't show any service names but only the directive `:0` then your`ValidArgsFunction` is not running the proper completions. You can add `cobra.CompDebug()` traces in your `ValidArgsFunction` to debug further.

**Comment by knrt10** [comment]
This is occuring for me too

```go
ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		if len(args) != 0 {
			return nil, cobra.ShellCompDirectiveNoFileComp
		}

		return components.ListNames(), cobra.ShellCompDirectiveNoFileComp
	},
```

Flags are preferred over my list. And even the below

```bash
./lokoctl __complete component apply""                                            
apply	Deploy or update a component
:0
Completion ended with directive: ShellCompDirectiveDefault
```

returns with `ShellCompDirectiveDefault`. It should return with `ShellCompDirectiveNoFileComp`

**Comment by knrt10** [comment]
Also this happens when I register zsh using `GenZshCompletion()`. But when registering [like this](https://github.com/kinvolk/lokomotive/pull/880/files?file-filters%5B%5D=.md&file-filters%5B%5D=.txt#diff-f07a465f5e469171466204740f27c8f7R88). It works fine

**Comment by marckhouzam** [comment]
> And even the below
> 
> ```shell
> ./lokoctl __complete component apply""                                            
> apply	Deploy or update a component
> :0
> Completion ended with directive: ShellCompDirectiveDefault
> ```
> 
> returns with `ShellCompDirectiveDefault`. It should return with `ShellCompDirectiveNoFileComp`

You are missing a space in your command-line before the quotes.  Try
```
./lokoctl __complete component apply ""  
```
does it return what you expected?

**Comment by marckhouzam** [comment]
> Also this happens when I register zsh using `GenZshCompletion()`. But when registering [like this](https://github.com/kinvolk/lokomotive/pull/880/files?file-filters%5B%5D=.md&file-filters%5B%5D=.txt#diff-f07a465f5e469171466204740f27c8f7R88). It works fine

Ok, I understand now.
Cobra 1.0.0 does not support `ValidArgsFunction` for `zsh`.  That is why it wasn't working for you.  When you use the bash completion instead and convert it to zsh, it does work because Cobra 1.0 does support `ValidArgsFunction` for bash.

Once Cobra does its next release, you will be able to use `GenZshCompletion()` as it will then fully support `ValidArgsFunction`

**Comment by marckhouzam** [comment]
@trusch Any luck with your issue?  If it is resolved, would you mind closing this issue?

**Comment by knrt10** [comment]
Thank you @marckhouzam for your help.

**Comment by marckhouzam** [comment]
Cobra 1.1.1 is out with full zsh completion.

I think this issue has been answered and can be closed.

**Comment by marckhouzam** [comment]
@trusch Have you tried with Cobra 1.1.1?  I expect it will fix you problem.  If so, do you mind closing this issue?

**Comment by andebor** [comment]
Switching from 1.0.0 to 1.1.1 fixed it for me. Thanks!
