### ISSUE TITLE
failed to install cobra generator and its dependencies

### ISSUE THREAD

**Issue by akayj** [spf13/cobra#1191]
### Go version
go1.15

### OS
macOS 10.15.3

### What have you done?
follow the [guides](https://github.com/spf13/cobra/#installing), run this command
`go get -u github.com/spf13/cobra/cobra`

### What happend?
`go: github.com/spf13/cobra/cobra upgrade => v0.0.0-20200815144417-81e0311edd0b
go get: github.com/spf13/cobra/cobra@v0.0.0-20200815144417-81e0311edd0b
requires
    github.com/spf13/cobra@v0.0.0: reading github.com/spf13/cobra/go.mod at revision v0.0.0: unknown revision v0.0.0
`

### expects
successfully install cobra generator and its deps

**Comment by jlhume** [comment]
+1

I found running `go get -u github.com/spf13/cobra` will bring in Cobra (without the generator), albeit I haven't tried to use it yet - possibly due to #1139 ?

**Comment by campusstella** [comment]
+1

**Comment by Adiqq** [comment]
Works with:

`go get github.com/spf13/cobra/cobra@v1.0.0`

**Comment by MichaelMure** [comment]
A solution could be to set an explicit version in `cobra/go.mod` (the secondary go.mod for the CLI tool) but the downside is that this version need to be updated each time a new version is published (and before tagging).

I suppose the `replace github.com/spf13/cobra => ../` would still work during development to make sure to use the local code with potential changes.

It's a bit silly that go modules try to get that `v0.0.0` version (and fail the whole process) while this version is explicitly overridden.

**Comment by akayj** [comment]
> A solution could be to set an explicit version in `cobra/go.mod` (the secondary go.mod for the CLI tool) but the downside is that this version need to be updated each time a new version is published (and before tagging).
> 
> I suppose the `replace github.com/spf13/cobra => ../` would still work during development to make sure to use the local code with potential changes.
> 
> It's a bit silly that go modules try to get that `v0.0.0` version (and fail the whole process) while this version is explicitly overridden.

Will this solution be marked in the doc later ?
For a dummy, I suppose a notice is welcomed.
