### ISSUE TITLE
Provide a StringToString flag parsing option that only allows flag repetitions

### ISSUE THREAD

**Issue by fbiville** [spf13/cobra#1193]
Currently, Cobra offers the `StringToString` function family to parse flags into a `map[string]string`.
The behavior of these functions is very similar to `StringSlice`, i.e., flags can be both aggregated and/or repeated as follows:

```
[...] --sts foo=bar,bar=qix --sts qix=foo
```
which would result in the following map:
```
foo -> bar
bar -> qix
qix -> foo
```

The limitation with this approach is that values can become ambiguous (some legit values could contain `=` and `,`). 
In some scenarios, for the same invocation as above, the desired result could be instead:
```
foo -> bar,bar=qix
qix -> foo
```

As far as I know, the latter result is not achievable out of the box with Cobra.

**Comment by Luap99** [comment]
I think flag issues should be reported here: https://github.com/spf13/pflag

**Comment by fbiville** [comment]
Thanks, opened https://github.com/spf13/pflag/issues/276 then.
