### ISSUE TITLE
Commands with empty Long duplicate the description in Markdown docs

### ISSUE THREAD

**Issue by marclop** [spf13/cobra#1194]
## Description

Due to the current logic on `doc.GenMarkdownCustom()`: https://github.com/spf13/cobra/blob/master/doc/md_docs.go#L62-L70, the Short description in a command is set to `Long` and duplicated in all the Markdown docs, adding no real value in the generated Markdown document.

## Proposed change

Instead of writing a duplicated string twice under different document sections, I believe it'd be ideal to skip writing the Synopsis header and the copied Short altogether. 

For a project I actively maintain, we've resorted to copying the functions locally and modifying the source code since there's no way to modify that part of the function without doing so, [see pull request](https://github.com/elastic/ecctl/pull/370).

```go
	buf.WriteString("## " + name + "\n\n")
	buf.WriteString(short + "\n\n")
	if len(cmd.Long) > 0 {
		buf.WriteString("### Synopsis\n\n")
		buf.WriteString(cmd.Long + "\n\n")
	}
```

I can make the change and open a Pull Request against master to do so if that's something the maintainers of this library deem appropriate.

**Comment by jpmcb** [comment]
Thanks for opening this issue @marclop - feel free to tackle this in a PR and tag me to review and I'll take a look!! Thanks for catching this!

**Comment by marclop** [comment]
Will post a PR then!
