### ISSUE TITLE
Not getting clean help output when using MarkFlagRequired

### ISSUE THREAD

**Issue by kalmufti** [spf13/cobra#1195]
Hi there,

When I run my app, MarkFlagRequired prints out this error ```(0x1637fe0,0xc0002f1e70)``` see below. What am I doing wrong or is there a way to clean up the help output?
```
func init() {
	rootCmd.AddCommand(fooCmd)
	fooCmd.Flags().StringP("bar", "b", "", "Bar command (Required)")
	fooCmd.MarkFlagRequired("bar")
}
```

```
go run main.go foo                                                                 
Error: required flag(s) "bar" not set
Usage:
   foo [flags]

Flags:
  -h, --help                help for foo
  -b, --bar string          Bar command (Required)

Global Flags:
      --config string   config file (default is $HOME/.test.yaml)

(0x1637fe0,0xc0002f1e70)
exit status 1
```

**Comment by kalmufti** [comment]
@jharshman, I'm using the Cobra command generator, I then edit the cmd/foo.go init function as I shown above. I don't get the error when I put everything in one file per your example.
```
mkdir test
cd test
cobra init --pkg-name test .
go mod init test
cobra add foo

test
├── LICENSE
├── cmd
│   ├── foo.go
│   └── root.go
├── go.mod
├── go.sum
└── main.go
```

**Comment by kalmufti** [comment]
I've figured out the cause, the command generator adds this execute function, I had changed the ```fmt.Println``` to ```println``` and that what caused the weird output ```(0x1637fe0,0xc0002f1e70)```. Think I will just remove that ```os.Exit(1)``` or change it to 0 to get cleaner output.
```
// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
```

**Comment by jharshman** [comment]
@kalmufti happy to hear you figured it out! I'm going to go ahead and close this issue.
