### ISSUE TITLE
Parsing ranges apart from single values

### ISSUE THREAD

**Issue by Gituser143** [spf13/cobra#1201]
Is there any functionality to parse ranges as flags. For example the namp tool takes a range of ports to scan `nmap HOST -p 10-100` 

This would scan ports in the range 10 to 100. Similar functionalities being implemented in cobra would be helpful!

**Comment by marckhouzam** [comment]
I believe that in your example it is `nmap` that figures out what to do when it gets a value of `10-100`.

What do you envision Cobra doing to help in such a case?

**Comment by Gituser143** [comment]
Cobra could have an option to parse flag ranges. A very naive approach I have in mind is as follows:
```go
func ParseRange(Range string) (int, int) {
	if strings.Contains(Range, "-") {
		Vals := strings.Split(Range, "-")

		if len(Vals) != 2 {
			log.Fatal("Failed while parsing ranges. Invalid port range format!")
		}

		var min, max int

		if strings.Compare(Vals[0], "") == 0 {
			min = 1
		} else {
			val, err := strconv.Atoi(Vals[0])
			if err != nil {
				fmt.Println("Failed to parse ranges!")
				log.Fatal(err)
			}
			min = val
		}

		if strings.Compare(Vals[1], "") == 0 {
			max = 65535
		} else {
			val, err := strconv.Atoi(Vals[1])
			if err != nil {
				fmt.Println("Failed to parse ranges!")
				log.Fatal(err)
			}
			max = val
		}

		return min, max

	} else {
		val, err := strconv.Atoi(portRange)
		if err != nil {
			fmt.Println("Failed to parse values!")
			log.Fatal(err)
		}

		return val, nil

	}
}
```

Here, we could take in a string value as a flag and parse it separately based on whether or not a `-` is present. Default values can be provided if in case vales on either side of the `-` are omitted.

**Comment by jpmcb** [comment]
I wonder if this may actually be a better issue for the `pflag` repo. Cobra is really just a wrapper for `pflag` and `viper`. Pflags may be able to define a "range" type flag that can be exposed back to cobra users.

**Comment by johnSchnake** [comment]
Totally fine if you want to reopen in pflag but I'd also suggest that since there hasn't been much activity on this it may be a pretty niche need.

As such, remember that you can easily define this behavior if you want it in your own app since you just have to create the `Range` type and satisfy the pflag.Value interface. 

```
type Value interface {
	String() string
	Set(string) error
	Type() string
}
```

You'd use your logic for parsing the value in the `Set` method and write the string/type methods depending on how you want the help to look.
