### ISSUE TITLE
validateRequiredFlags should be exposed?

### ISSUE THREAD

**Issue by bukowa** [spf13/cobra#1204]
When i override `Args: func(cmd *cobra.Command, args []string) (err error) {}` for a command then required flags are not validated, the solution is to validate flags in `Args`:
````golang
Args: func(cmd *cobra.Command, args []string) (err error) {

	// Validate required flags
	if err = ValidateRequiredFlags(cmd); err != nil {
		return err
	}
}
````

But this method is not exposed so i have to copy it. I think it should be exposed.
https://github.com/spf13/cobra/blob/8cfa4b4acf63ab83334178f96ac694d3ea24e231/command.go#L989-L1010

**Comment by marckhouzam** [comment]
@bukowa thanks for the report.  Can I ask what you mean exactly by "then required flags are not validated"?  Looking at the code, the function `validateRequiredFlags()` does get called even if you override the `Args` field (I didn't actually test it though).

**Comment by bukowa** [comment]
@marckhouzam thanks for interest, unfortunately i cannot replicate the problem

**Comment by marckhouzam** [comment]
Does that mean you don't need PR #1205 and you can close it?

**Comment by bukowa** [comment]
@marckhouzam maybe we could still expose that, is there a point that says we should not?

**Comment by marckhouzam** [comment]
Exposing extra functions creates more limitations in making changes, because anything that is exposed cannot be changed.
I'm not a maintainer, so it is not my decision, but I usually aim to only expose functions that are known to be valuable to extenders.

**Comment by bukowa** [comment]
@marckhouzam thanks!
