### ISSUE TITLE
cmd.Parent() returns the LAST parent added in code, regardless of the actual command's parent.

### ISSUE THREAD

**Issue by rfinner** [spf13/cobra#1206]
app get schedule
- returns: schedule parent is get

** AND **

app create schedule
- returns: schedule parent is get

for the following code:

var scheduleCmd = &cobra.Command{
	Use:   "schedule",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("schedule parent is ", cmd.Parent().Use)
	},
}

func init() {
	createCmd.AddCommand(scheduleCmd)
	getCmd.AddCommand(scheduleCmd)
}

The reverse is also true if I reverse the order AddCommand. cmd.Parent() returns the LAST parent added, regardless of the actual command's parent.

**Comment by Luap99** [comment]
You cannot do this. Each command can only have one parent. For your use case you would need to generate the command with a function and invoke it for each addcommand call. Like https://github.com/spf13/cobra/issues/1015#issuecomment-576574281

**Comment by rfinner** [comment]
Thanks!

Luap99 explained why answer in #1005 solves my use case:

Here is the code that works (I think it this right but beware that I am a newbie to cobra):

func newScheduleCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "schedule",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Println("schedule parent is ", cmd.Parent().Name())
			fmt.Println("schedule full path: ", cmd.CommandPath())
		},
	}
}
func init() {
	createCmd.AddCommand(newScheduleCmd())
	getCmd.AddCommand(newScheduleCmd())
}
