### ISSUE TITLE
How can I set a version dynamically?

### ISSUE THREAD

**Issue by BeyondEvil** [spf13/cobra#1221]
I'm trying to set the `Version` attribute on the `rootCmd` dynamically by using `ldflags`, but I'm failing.

Basically I have `root.go` in the `cmd` directory:

```go
package cmd

var AppVersion string
var rootCmd = &cobra.Command{
	Use:   "slack-cli",
	Short: "slack-cli interacts with Proxy Slack",
	Long:  "slack-cli is used to interact with messages in Proxy Slack",
        Version: AppVersion,
}
```

And then I run:

```bash
$ CGO_ENABLED=0 go build -a -ldflags "-X cmd/root.AppVersion=$GIT_TAG"
```

But I guess the `Version` attribute ends up being `nil`, because I get: `unknown flag: --version`

Any help would be appreciated. 🙏

**Comment by Luap99** [comment]
go just cares about the package name and not the file name. Try: `cmd.AppVersion=$GIT_TAG`

**Comment by BeyondEvil** [comment]
> go just cares about the package name and not the file name. Try: `cmd.AppVersion=$GIT_TAG`

Tried it. No go. :(

**Comment by Luap99** [comment]
Try the realative path to your `$GOPATH/src` usually something like this: `github.com/<user>/<repo>/cmd.AppVersion=$GIT_TAG`

**Comment by BeyondEvil** [comment]
NICE! That worked.

THANK YOU! ❤️
