### ISSUE TITLE
How to write shell completion function in Go

### ISSUE THREAD

**Issue by blueray453** [spf13/cobra#1222]
For example the following is a zsh completion function for command `foo`:

```
#compdef _foo foo
compadd first second third fourth
```

So, if we type `foo <tab>` in the zsh terminal, it suggests first second third fourth.

How can I do this using cobra?

**Comment by marckhouzam** [comment]
This documentation may help: https://github.com/spf13/cobra/blob/master/shell_completions.md
Note that is the latest/unreleased version of the documentation, but it should be correct to get you started.

**Comment by blueray453** [comment]
Thank you very much.
