### ISSUE TITLE
help flag does not reset on re-execution

### ISSUE THREAD

**Issue by dadrichem** [spf13/cobra#1225]
I have made a cli where the command is being executed multiple times.
All flags reset each time a command is executed except for the --help.\
Which thereafter is executed in all commands.

main file:
```
for true {

	// read cli line
	reader := bufio.NewReader(os.Stdin)
	input, _ := reader.ReadString('\n')

	// trim whitespaces
	input = strings.TrimSpace(input)

		
	if input != "" {
		// run command through root command
		command := cmd.NewRootCmd()
		command.SetArgs(strings.Split(input, " "))
		command.Execute()
	}
}
```

**Comment by marckhouzam** [comment]
I don't know if this could help but you can reset a flag after it's been marked as used.  Maybe you could do it for the help flag.
Here's an example
https://github.com/spf13/cobra/blob/8a63648dd905e5c96bee06e6851a894fc75aa058/custom_completions_test.go#L182

**Comment by jharshman** [comment]
@dadrichem, did what @marckhouzam suggest end up working for you?
