### ISSUE TITLE
Subcommand Code Generation Generating Bad Call to Parent

### ISSUE THREAD

**Issue by jollyrogue** [spf13/cobra#1227]
Creating a subcommand with a parent results in an `init` function which uses an incorrect variable name. `parent.AddCommand()` is generated instead of `parentCmd.AddCommand()`

### Info
- cobra v1.0.0
  - Installed via `go get`
- go version go1.14.7 linux/amd64
  - From Fedora 32 repos

### Steps to reproduce

1. Initialize the project with `cobra init ...`.
2. Move into the project directory. `cd ...`
3. Add a command with `cobra add fridge`. The project should build and run via `go run .`
4. Add a subcommand to the `list` command. `cobra add -p fridge eat` The project will now fail to build with the following error.
```
> go run . 
# github.com/someone/buggyproject/cmd
cmd/eat.go:25:2: undefined: fridge
```

The generated `init` function which is causing the problem:
```
func init() {
    fridge.AddCommand(eatCmd)
}
```

### Fixing the Problem

Appending `Cmd` to the name of the parent variable in the `init` function allows the project to compile and run again.
```
func init() {
    fridgeCmd.AddCommand(eatCmd)
}
```

**Comment by jharshman** [comment]
@jollyrogue, this is the behavior we are expecting. The `-p` flag expects the variable name of the parent command, not the command name itself. I'm not saying this is ideal and I could see this being a bit confusing.

```
 -p, --parent string   variable name of parent command for this command (default "rootCmd")
```

**Comment by jollyrogue** [comment]
Ah. Yeah, that's the problem.
