### ISSUE TITLE
Feature request: Required pflags

### ISSUE THREAD

**Issue by gregf** [spf13/cobra#123]
I would like to be able to set a pflag to a command and make it required to run.

**Comment by apriendeau** [comment]
I would create an issue at github.com/spf13/pflag because I believe what you are asking for would come from there. What I do is have a PreRun func that checks the validity of flags.

**Comment by gregf** [comment]
Forgot about the PreRun stuff, that will probably work just fine. I'm going to close this. Thanks for the help.
