### ISSUE TITLE
boolean value not work with `--test false`

### ISSUE THREAD

**Issue by yywing** [spf13/cobra#1230]
code:
```go
package main

import (
	"fmt"
	"github.com/spf13/cobra"
	"os"
)

var t bool

func main() {
	cmd := &cobra.Command{
		Short: "show flag value",
		Run: func(_ *cobra.Command, _ []string) {
			fmt.Printf("test: %v\n", t)
		},
	}

	cmd.Flags().BoolVarP(&t, "test", "t", true, "bool test")

	if err := cmd.Execute(); err != nil {
		os.Exit(1)
	}
}
```
output:
```bash
➜  flag go run main.go --test false
test: true
➜  flag go run main.go --test=false
test: false
```
why --test false not work?

**Comment by marckhouzam** [comment]
Hi @yywing.

For boolean flags, you need to use `--test=false`

This is because Cobra allows you to use a boolean flag without any value, so in the `--test false` form, Cobra wouldn't know if the false is a value for the flag or an argument for the command.

**Comment by yywing** [comment]
> Hi @yywing.
> 
> For boolean flags, you need to use `--test=false`
> 
> This is because Cobra allows you to use a boolean flag without any value, so in the `--test false` form, Cobra wouldn't know if the false is a value for the flag or an argument for the command.

THANKS， got it.

**Comment by marckhouzam** [comment]
@yywing great. Would you mind closing this issue (I don't have permissions to do it myself).
