### ISSUE TITLE
How to check what command was chosen

### ISSUE THREAD

**Issue by mydockergit** [spf13/cobra#1236]
I have this structure:  
```
main.go
  cmd
     |___  root.go
     |___  version.go
     |___  info.go
```  
I have two commands: `version` and `info`.  
When someone type `myapp.exe version` it prints the version of the program.  
How can I check in the program when the command `version` is being selected (and not `info`) ?

I am looking for a way to check `if version.Selected {...}`.

**Comment by jharshman** [comment]
@mydockergit, Can you explain more of your use case?
The command being used is reflected in the actions taken by the command. I'm having a hard time understanding in what scenario you would want to run `./myapp version` and check to see if the version command is being used.
