### ISSUE TITLE
Are negative numbers possible as arguments?

### ISSUE THREAD

**Issue by mbertschler** [spf13/cobra#124]
Can I use negative numbers as arguments for a command? Currently this happens:
```
$ cmd -123 
Failed running command ["cmd" "-123"]: unknown shorthand flag: '1' in -123
```
It is possible to run the command like this: `cmd -- -123`.

Is this usage possible with the current version of cobra or could a Command have a field `AllowNegativeArgs: true` to allow such a usage?

**Comment by eparis** [comment]
I think this is expected behavior and I don't really want to add a special case for it. This is how pretty much all unix commands work.
```
touch -123
touch: invalid option -- '1'
Try 'touch --help' for more information.
# touch -- -123
# ls
-123
# ls -123
ls: invalid option -- '2'
Try 'ls --help' for more information.
# ls -- -123
-123
# ls *
ls: invalid option -- '2'
Try 'ls --help' for more information.
```

**Comment by spf13** [comment]
Agree with @eparis

**Comment by mbertschler** [comment]
Okay so if this is the standard behavior then of course it ahould not be changed. I just asked because I never had to use -- before.

I was using the cli for cockroachdb where you can increment a counter with `cockroach kv inc counterkey 3` and then tried `cockroach kv inc counterkey -3`.

Is there any way to set an error message that is returned when wrong flags are set, or can I make it print the usage for the command? That would help increase the usability of this command for novice users like me.

**Comment by mbertschler** [comment]
this probably can be closed as wontfix
