### ISSUE TITLE
Args validation doesn't return validation error without a Run or RunE

### ISSUE THREAD

**Issue by vish91** [spf13/cobra#1241]
Can someone confirm if this is by design ? 
Just having a `Args: cobra.MininumNArgs()` on command without a `Run` or `RunE` does not actually work or return the argument validation failure error.
For example I am testing this on the root command setting minimum args to 1 and I run it it just shows me usage instead of giving the minimum `n` arguments required. 

```
var rootCmd = &cobra.Command{
	Use:   "app",
	Short: "test app",
	SilenceUsage: true,
	Args: cobra.MinimumNArgs(1),
}
func Execute() {
	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}
```

**Comment by marckhouzam** [comment]
You are correct.  Notice this code:
https://github.com/spf13/cobra/blob/40d34bca1bffe2f5e84b18d7fd94d5b3c02275a6/command.go#L812-L818

Where the first line checks if there is a `Run` or `RunE` function, and only if there is does it continue to the last line that calls `command. Args()`.

**Comment by vish91** [comment]
right. It's not by design though I think. I'm thinking about a root command which doesn't need a runnable and just has to check for arguments to delegate the execution to sub commands  @marckhouzam does that make sense to have it check those before it checks for runnable and returns error ?

**Comment by marckhouzam** [comment]
> right. It's not by design though I think. I'm thinking about a root command which doesn't need a runnable and just has to check for arguments to delegate the execution to sub commands @marckhouzam does that make sense to have it check those before it checks for runnable and returns error ?

If you specify an argument to the root command, then it wouldn't call a sub-command, and it would need a `Run` or `RunE`; and if you specify a sub-command, then there wouldn't be an argument.  Maybe I'm misunderstanding the scenario you are describing?

**Comment by vish91** [comment]
When I think of arguments to root command, from the use case I was testing it I thought of the subcommand also as an argument to the root command. So I'm wrong there I think. 
In which case if the subcommand if missing it will show the usage message and doesn't really get to the point of checking for arguments. 🤔

**Comment by marckhouzam** [comment]
The `execute ()` command where the check for args is done is called directly on the subcommand.  So, of there is a subcommand, it won't get called in the root.

So I believe the scenario you have in mind cannot happen.

If you can provide a piece of example code that triggers the scenario, it will clarify things for me.

**Comment by vish91** [comment]
gotcha. yeah you are right. Thanks for taking the time I'll close this issue 👍🏽
