### ISSUE TITLE
DisableFlagParsing for subcommand only

### ISSUE THREAD

**Issue by kaotika** [spf13/cobra#1242]
Is it somehow possible to disable flag parsing specific to a sub command (rootCmd flags should be parsed)?

```bash
./my-app run ls -alh
```
In the usecase the sub command `run` should execute `ls -alh`. But if I pass it without `DisableFlagParsing` cobra tries to parse `-alh` and will not find it.

**Comment by marckhouzam** [comment]
I'm not sure I understand your use case.  The example you give should work when setting `DisableFlagParsing` on the sub command only (not on the root command).

If you want to parse flags at the root and then not at the subcommand like this
`./my-app --flag run ls -alh`
you may want to try enabling`TraverseChildren` on the root command and `DisableFlagParsing` on the subcommand.

**Comment by kaotika** [comment]
I set `DisableFlagParsing` on the subcommand and explicitly allowed it on `RootCmd`.
If I do so, the execution stops with `unknown shorthand flag: 'a' in -alh` (understandably so far).

If I `DisableFlagParsing=true` and perform the parsing manually with `res := RootCmd.ParseFlags(args)` I'll go the same error message but without execution interruption. This solved the main problem.

I think I misunderstood the usage of `DisableFlagParsing`, cause I expected it to work like you discribed: Parse the rootCmd's flags but not the specific sub-command flags.

**Comment by marckhouzam** [comment]
You're right, when you set `DisableFlagParsing` on any command or subcommand, there will be no flag parsing at all.

If you try also enabling `TraverseChildren` on the root, you may get flag parsing up to the subcommand where you set `DisableFlagParsing` but I haven't actually tried it.

**Comment by kaotika** [comment]
Ah, this also did the job. Thanks!

**Comment by marckhouzam** [comment]
Great! If you're satisfied, would you mind closing the issue? I don't have permissions myself.
