### ISSUE TITLE
404 Page not found errors on https://cobra.dev

### ISSUE THREAD

**Issue by nlathia** [spf13/cobra#1243]
Hi, I was reading the docs on https://cobra.dev and spotted that there are a number of URLs that are returning a 404 page not found.

The ones I tried include:
- https://cobra.dev/doc/md_docs.md
- https://cobra.dev/doc/rest_docs.md
- https://cobra.dev/doc/man_docs.md
- https://cobra.dev/bash_completions.md

.. but I can still see the actual pages themselves here https://github.com/spf13/cobra/tree/master/doc so it looks like a minor issue. I didn't spot any docs on how to contribute to the docs 😅 so I thought I'd raise it here.

**Comment by umarcor** [comment]
@nlathia see #1244, #1245 and #1254.
