### ISSUE TITLE
Fish completion error

### ISSUE THREAD

**Issue by matejvasek** [spf13/cobra#1246]
```sh
Expected a command, but instead found a redirection
complete --do-complete "faas " &> /dev/null
```
I think it should be:
```sh
complete --do-complete "faas " 2> /dev/null
```

**Comment by matejvasek** [comment]
fish, version 3.0.2

**Comment by matejvasek** [comment]
With 3.1.2 it works well.

**Comment by matejvasek** [comment]
Seems that the `&>` redirect operator is supported in `3.1` and not in `3.0`.

**Comment by marckhouzam** [comment]
Thanks @matejvasek!
The Fish completion was tested with Fish 3.1. 
Does everything else seem to work properly with 3.0?

**Comment by matejvasek** [comment]
I gave it just short try, I does complete flags and also their parameters.
