### ISSUE TITLE
Cobra escapes arguments passed to commands

### ISSUE THREAD

**Issue by BeyondEvil** [spf13/cobra#1251]
What the title says.

If I pass in an argument (string) to a command like: `hello\nworld` and print it, I'm expecting:
```
hello
world
```

but instead I get:
```
hello\nworld
```

Printing the argument with `%q` reveals that the argument has been escaped like so: `hello\\nworld`

Is this by design or a bug?

Here's a small [repo](https://github.com/BeyondEvil/go-cobra-escaping) I created to help visualize the issue.

In the real world I'm building a Slack CLI and discovered this issue during the development of the `post-message` command. Where the first (and only) positional argument to the command is the message to be posted to a slack channel.

**Comment by Luap99** [comment]
Cobra doesn't do any special escaping, `%q` does
> %q	a double-quoted string safely escaped with Go syntax

source: https://golang.org/pkg/fmt/#hdr-Printing

**Comment by BeyondEvil** [comment]
> Cobra doesn't do any special escaping, `%q` does
> 
> > %q	a double-quoted string safely escaped with Go syntax
> 
> source: https://golang.org/pkg/fmt/#hdr-Printing

I see, well, regardless something is escaping the command line argument.

And it looks like it's GO itself...

This:
```go
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println(os.Args[1])
}
```

produces:
```
$ go run main.go "hello\nworld"
hello\nworld
```

Putting the argument through a `strings.ReplaceAll()` and replacing `\\n` with `\n` produces the expected outcome. 🤷‍♂️

**Comment by BeyondEvil** [comment]
Seems like the real culprit is `bash`. 

Passing in the argument escaping it with $ produces the expected output `$'hello\nworld'`
