### ISSUE TITLE
ValidArgsFunction receives nil Context 

### ISSUE THREAD

**Issue by lukasmalkmus** [spf13/cobra#1263]
The `ValidArgsFunction` as well as the flag completion functions receive a `*cobra.Command` with a `nil` `context.Context`, even if the root command is executed with `ExecuteCommand()`.

**Comment by marckhouzam** [comment]
@lukasmalkmus you are right.  This was missed in the implementation.  Feel like submitting a PR?

**Comment by lukasmalkmus** [comment]
Will do. Do you think I should incorporate https://github.com/spf13/cobra/issues/1260 ?
