### ISSUE TITLE
Allow the Simpler and Safer complete -C foo foo Pattern for Completion

### ISSUE THREAD

**Issue by rwxrob** [spf13/cobra#1266]
It's 2020. We don't need to put completions into /etc/ anymore. In fact, all the completion code should be *in* the program itself that can easily detect that it is being run in completion context (sensing `COMP_LINE` for example). All that anyone should need is something like the following in their `.bashrc` where `foo` is the name of a command that imports Cobra.

```sh
complete -C foo foo
```

For more information RTFM on Bash under Programmable Completion.

**Comment by marckhouzam** [comment]
@rwxrob Cobra is actually not that far from what you are kindly suggesting.

Cobra provides the `__complete` command which one can call to obtain completions.  You can try it will `helm` for example:
```
helm __complete s<ENTER>
```
Have you tried using `complete -C` with this `__complete` command?  I'd be curious to know if it works.

However Cobra also provides more advanced completion controls. For example these controls allow the program to tell bash not to perform file completion, or not to add a space after the completion.  I wonder if it is possible to achieve that using `complete -C`?

**Comment by rwxrob** [comment]
Thanks for the pointer. I'll look into it and report. If so, I'll reconsider Cobra provided it possesses the possibility for full natural language command lines in addition to the traditional getopt variety. Last I checked it cannot do that.

**Comment by marckhouzam** [comment]
> Thanks for the pointer. I'll look into it and report. If so, I'll reconsider Cobra provided it possesses the possibility for full natural language command lines in addition to the traditional getopt variety. Last I checked it cannot do that.

Do you mean:
```
helm --namespace myNamespace
helm --kube-context prod
helm --debug
```
If so, you're good to go.

**Comment by marckhouzam** [comment]
@rwxrob where you able to get Cobra to work with `complete -C`.  I tried myself, and I couldn't even get `complete -C` to behave as I would have expected with a two-line script.

If you could give an example of how to use `complete -C` that would be great.

**Comment by rwxrob** [comment]
This is not possible with Cobra because it does not detect Bash completion context (COMP_LINE being set in the env). The closest is adding an eval to one's bashrc, which will have to do.

**Comment by tristanmorgan** [comment]
psudo code of how the bash completions work (with the complete -C style) is:

```
$ command sub other prev curr<tab> more later

COMP_LINE = "command sub other prev curr more later"
COMP_POINT = 27 (cursor index)
ARGV = [command command curr prev]
```
so the command needs to accept its own name as a sub command.
