### ISSUE TITLE
Empty alias breaks bash completion

### ISSUE THREAD

**Issue by carlpett** [spf13/cobra#1269]
I noticed in a project using cobra that setting an empty alias breaks the generated bash completion. They had something like this:
```go
	var cmd = &cobra.Command{
		Use:     "check-update",
		Short:   "Check for latest releases",
		Long:    ``,
		Aliases: []string{"update",""},
		RunE: func(cmd *cobra.Command, args []string) error {
			return CheckUpdate(cmd, version, build, false)
		},
	}
```

This results in bash-completion writing syntactically incorrect scripts: https://github.com/spf13/cobra/blob/86f8bfd7fef868a174e1b606783bd7f5c82ddf8f/bash_completions.go#L605-L609

Here's what the output looks like
```bash
_example_root_command()
{
    last_command="example"

    command_aliases=()

    commands=()
    commands+=("check-update")
    if [[ -z "${BASH_VERSION}" || "${BASH_VERSINFO[0]}" -gt 3 ]]; then
        command_aliases+=("")        # <---
        aliashash[""]="check-update" # <---
        command_aliases+=("update")
        aliashash["update"]="check-update"
    fi
```

Trying to use tab completion with this causes an error:
```console
$ example <tab>-bash: aliashash[""]: bad array subscript
```

I poked around a bit in the code, looks like this could be checked in `command.AddCommand`, but would then have to panic. I'm not sure if there are legitimate reasons to have an empty alias?

**Comment by johnSchnake** [comment]
An empty alias? Is there a functional reason for that?

Due to the lack of follow up and uncertainty over this being a valid case I'll close as part of #1600. Feel free to reopen to discuss if you feel this is a problem that needs fixing.

**Comment by carlpett** [comment]
Maybe I was unclear - I doubt there's a reason to want to set it to empty. And it was a mistake in the project where I found it. My question here was more around if the completion generator should panic/error when it happens?
