### ISSUE TITLE
Bash completion: enhance multiple required flags management?

### ISSUE THREAD

**Issue by ArmandBENETEAU** [spf13/cobra#1277]
## Context
I am currently using Cobra project to develop a command line interface tool, and I'm really loving it. I found it really easy to use, the documentation is clear and there are a really large number of features. It is really great, thank you for that!

## Current behaviour
The CLI tool I am developing has some subcommands that have several required flags. In order to enhance the user experience, I have marked these flags as required using the `myCmd.MarkFlagRequired(flagName)` function. It allows the completion to suggest in priority these flags.

Let's say that the name of my application is **`cli-tool`** and my subcommand is **`subcmd`**. 
The flags are:

```bash
Flags:
  -r,  --reqf1 string    Required flag number 1
       --reqf2 string    Required flag number 2
  -o,  --optf1 string    Optional flag number 1
       --optf2 string    Optional flag number 2
```

When no flags have been set yet, the behaviour is as expected during completion.
The example here below illustrates that.

```bash
$ cli-tool subcmd -<tab><tab>
-r             --reqf1=        --reqf2=
```

But as soon as one required flag is filled, the completion stop suggesting the required flags.
The example here below illustrates that.

```bash
$ cli-tool subcmd -r firstValue -<tab><tab>
# Nothing is displayed
```

Finally, when all the required flags are given in the command line, the completion suggest all the available flags

```bash
$ cli-tool subcmd -r firstValue --reqf2=value2 -<tab><tab>
-r             --reqf1=        --reqf2=        -o        --optf1=        --optf2=
```

## Suggestion
As a user, I would expect that a command line tool completion suggest the required flags as long as all of them have not been filled in.
Therefore, in the second case here above we would have:

```bash
$ cli-tool subcmd -r firstValue -<tab><tab>
-r             --reqf1=        --reqf2=
```

I hope that my explanations are clear.
Thank you in advance for your answers!

**Comment by marckhouzam** [comment]
Hello @ArmandBENETEAU.  You make good points.

Currently, Cobra handles completions for the bash shell slightly differently than for the zsh or fish shell, which use a new approach.
I would like to know if the new approach follows your expectations.  Would you be able to try it out?  I think the simplest way for you to do this, especially if you don't have zsh or fish shell installed is to use the `__complete` command directly and test things out.  For example, you would do:
```
cli-tool __complete subcmd -r firstValue -<ENTER>
```
Then you would see what cobra would show as completions using the new approach (not bash).  See here for details: https://github.com/spf13/cobra/blob/master/shell_completions.md#debugging

If the new approach does follow what you expect, you may be interested in #1146 which moves bash completion to this new approach.

**Comment by ArmandBENETEAU** [comment]
Hello Marc,

Thank you for your quick answer!
I will definitely try this out and keep you informed about it.

Thanks again!

**Comment by ArmandBENETEAU** [comment]
Hi again @marckhouzam !

So, I've tried out what you gave me and it appears that the new approach completely follows my expectations! That's great!
Therefore, as you said, I'm completely interested by #1146 to be merged inside Cobra master.

Thank you Marc!
