### ISSUE TITLE
Same name subcommands

### ISSUE THREAD

**Issue by doru1004** [spf13/cobra#1278]
Hi,

Is it possible to have the following setup:

```
command sub_cmd1
command sub_cmd2 sub_cmd1
```

i.e. use the same name for the subcommands that are attached to different parent commands.

The problem I'm having is that when I use the 2nd command (`command sub_cmd2 sub_cmd1`) I am running into an error `Error: flag accessed but not defined: <some-flag>` where `<some-flag>` is one of the flags of the first command (`command sub_cmd1`).

As soon as I rename `sub_cmd1` in `command sub_cmd2 sub_cmd1` to something else, the command works as expected.

**Comment by Luap99** [comment]
Can you provide more context? Some example code to reproduce your issue would be great.

**Comment by doru1004** [comment]
I can try, I'll have to extract the bits out of a larger project. The first question is, is it possible to have the same name for subcommands with different parents without the danger of a clash between the two? Are all the generate files dumped in the same directory or will there be a hierarchy of directories created to match the subcommand ?

I already have the definition of the sub_cmd2 in a separate file. from where the sub_cmd1 is defined. Also the sub_cmd1 of sub_cmd2 is in another file.

**Comment by doru1004** [comment]
This is a related Stackoverflow post which asks about a similar situation: https://stackoverflow.com/questions/44940787/creating-sub-commands-with-the-same-name-in-go-w-cobra
No yet answered properly though.

**Comment by Luap99** [comment]
I don't know how the cobra generator works but this definitely works if you create source code yourself.

**Comment by doru1004** [comment]
The error message suggests that sub_cmd1 of sub_cmd2 overwrites sub_cmd1 of command. And it definitely has to do with the name being the same because changing the name of one of the sub_cmd1 commands means everything runs correctly.

**Comment by doru1004** [comment]
This is a rough sketch of my code.

root.go
```
subCmd1 = newSubCmd1(options)
command.AddCommand(subCmd1)
subCmd2 = newSubCmd2(options)
command.AddCommand(subCmd2)
subCmd2.AddCommand(newSubCmd2SubCmd1(options))
```

sub_cmd_1.go
```
func newSubCmd1(rootCmdOptions *RootCmdOptions) *cobra.Command {
	cmd := cobra.Command{
		Use:   "sub_cmd1 [flags]",
	}

	return &cmd
}
```

sub_cmd_2.go
```
func newSubCmd2(rootCmdOptions *RootCmdOptions) *cobra.Command {
	cmd := cobra.Command{
		Use:   "sub_cmd2 [sub-commands][flags]",
	}

	return &cmd
}
```

sub_cmd_2_sub_cmd_1.go

```
func newSubCmd2SubCmd1(rootCmdOptions *RootCmdOptions) (*cobra.Command) {
	cmd := cobra.Command{
		Use:     "sub_cmd1 [flags]",
	}

	return &cmd
}
```

**Comment by doru1004** [comment]
Any thoughts on this?

I think the code is nothing surprising but if I'm using it wrong it would be good to know.

**Comment by doru1004** [comment]
I resolved the issue and turns out it is not related to Cobra. Thanks for all the feedback.
