### ISSUE TITLE
Fish completions with `:4` and `:0` as options

### ISSUE THREAD

**Issue by caarlos0** [spf13/cobra#1279]
We recently enabled completions on goreleaser, and it works pretty well.

One of the issues we found, though, is that on fish it returns `:4` as an option, e.g.:

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/245435/98987172-a7c90c80-2504-11eb-9ac5-441f05455ca6.png">

If I choose `:4` and keep pressing TAB, it will keep completing `:0` forever:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/245435/98987217-bca5a000-2504-11eb-800c-7e9d62797a84.png">

Same happens for subcommands, e.g.:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/245435/98987300-d515ba80-2504-11eb-96a8-0a0872a1f502.png">

I think it might be related to the fact that we do some "hacky" stuff to make `release` be the default command instead of root (is there a better way of doing that?): https://github.com/goreleaser/goreleaser/blob/master/cmd/root.go#L30-L32

Anyway, not sure how much of this is a bug, how much is expected and how much is us doing things wrong.

**Comment by marckhouzam** [comment]
This sounds a lot like the problem described starting in this comment: https://github.com/spf13/cobra/pull/899#issuecomment-659283479

I hope it helps.

**Comment by marckhouzam** [comment]
@caarlos0 did you find the problem?

**Comment by caarlos0** [comment]
I have not 😔

**Comment by marckhouzam** [comment]
@caarlos0 I had a look.  goreleaser always prints an empty line at the very end of its output:
https://github.com/goreleaser/goreleaser/blob/f35534d9d7cbc2d69fcbd4edb78a5d668357fa60/cmd/root.go#L23

I don't believe the completion script is ready for that.  The completion script actually calls `goreleaser __complete <args>` (for example, for `goreleaser completion <TAB>` it will call `goreleaser __complete completion ""`) and parses the output.  But the script expects the last line to have a special meaning (the completion directive).  In this case, the extra empty line confuses the script.  Not sure why it works for zsh. I'll dig deeper and post a PR to handle this case.

Until there is a fix in Cobra, what you could do is avoid printing that empty line when the command is `__complete`.

**Comment by caarlos0** [comment]
yes, that was it! I would never guess hehe

Thanks @marckhouzam 🚀

**Comment by marckhouzam** [comment]
Fix posted in #1284

**Comment by marckhouzam** [comment]
PR #1284 waiting for review
