### ISSUE TITLE
Documentation not updated

### ISSUE THREAD

**Issue by samirshaik** [spf13/cobra#1283]
The documentation on this project is outdated. Do we have updated instructions or references on how to use this project to create GO CLI apps?

**Comment by marckhouzam** [comment]
Hi @samirshaik, is this what you are looking for?
https://github.com/spf13/cobra/blob/master/cobra/README.md

**Comment by johnSchnake** [comment]
Asked and answered. Plenty of other tickets for gaps in documentation but this ticket doesn't add anything new.
