### ISSUE TITLE
Repitition of autocompletion options with zsh

### ISSUE THREAD

**Issue by ArnoSen** [spf13/cobra#1288]
Hi, 

I got a user report in that with v1.1.1 nouns are shown twice when using zsh autocompletion.
I made a mini executable showing this behavior:

```
% clitest     
do               -- this is about do
help             -- Help about any command
do               dosomethingelse  while            zsh
```
You see that `do` is shown twice. I paste the full source code below.
I noticed that this behavior stops when I omit the `ValidArgs` property of the (in above case) rootcmd. 
Is this by design and should 'ValidArgs' no longer be used?
With bash completion I don't have this issue. 

Full source of my test program has been attached.

**Comment by ArnoSen** [comment]
[clitest.gz](https://github.com/spf13/cobra/files/5637027/clitest.gz)
Forgot to attach the source code in the first post...

**Comment by marckhouzam** [comment]
Hi @ArnoSen.

`ValidArgs` should only be used for completions Cobra does not know about.  So, in your case, it should be removed. 

Recently, we have made a change that automatically provides completions for commands AND validArgs.  Previously, if ValidArgs was defined, commands would not be shown (it may still be the case for bash).  This prevented proper completion for commands that had both subcommands and arguments.

I was not aware that some programs used ValidArgs as you do, and overrode the command completion by defining it in ValidArgs.

That being said, in your case, just remove ValidArgs and only use it if you want to add extra completions that are not commands or flags.

**Comment by ArnoSen** [comment]
Thanks, I will do that .
I am coming from a very old version of cobra and only recently upgraded to 1.1.1. Back in the days bash autocompletion would not work if ValidArgs was not specified.
