### ISSUE TITLE
PersistentPreRun not ran prior to running FlagCompletionFunc?

### ISSUE THREAD

**Issue by ArnoSen** [spf13/cobra#1291]
Hi,

For my autocompletion I depend on logic that is in my PersistentPreRun.
It looks like though that PersistentPreRun is not executed when doing argument autocompletion.

See below test application to demonstrate that.

So when I run below, I am getting a profile "myprofile" while I would expect to get profile "always use this profile" per the PersistentPreRun func.

```
$ clitest sub --profile=myprofile --arg=[tab][tab]
myprofile-option1                 persistentflag output: myprofile
```

Code:
```
package main

import (
        "fmt"
        "os"

        "github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
        Use:   "clitest",
        Short: "Hugo is a very fast static site generator",
        Long: `A Fast and Flexible Static Site Generator built with
                love by spf13 and friends in Go.
                Complete documentation is available at http://hugo.spf13.com`,
        Run: func(cmd *cobra.Command, args []string) {
                fmt.Printf("profile: %s\n", profile)
                cmd.Usage()
                // Do Stuff Here
        },
        PersistentPreRun: func(cmd *cobra.Command, args []string) {
                profile = "always use this profile"
                //fmt.Println("very important prerun")
        },
}

var subCmd = &cobra.Command{
        Use: "sub",
        Run: func(cmd *cobra.Command, args []string) {
                fmt.Println("processing sub")
                fmt.Printf("Profile is %q\n", cmd.Flags().Lookup("profile").Value)
        },
}

var auto = &cobra.Command{
        Use: "autocompletion",
        Run: func(cmd *cobra.Command, args []string) {
                rootCmd.GenBashCompletion(os.Stdout)
        },
}

func Execute() {
        if err := rootCmd.Execute(); err != nil {
                fmt.Fprintln(os.Stderr, err)
                os.Exit(1)
        }
}

var myFunc = func(cmd *cobra.Command, args []string, search string) ([]string, cobra.ShellCompDirective) {

        myProfile, err := cmd.Flags().GetString("profile")
        if err != nil {
                myProfile = err.Error()
        }

        return []string{
                fmt.Sprintf("%s-option1", profile),
                fmt.Sprintf("%q", fmt.Sprintf("persistentflag output: %s", myProfile)),
        }, 0
}

var profile string
var subArg string

func main() {
        rootCmd.AddCommand(subCmd)
        rootCmd.AddCommand(auto)
        rootCmd.PersistentFlags().StringVarP(&profile, "profile", "p", "", "profile to use")

        subCmd.Flags().StringVar(&subArg, "arg", "", "argument")
        subCmd.RegisterFlagCompletionFunc("arg", myFunc)
        Execute()
}

```

**Comment by marckhouzam** [comment]
That is an interesting scenario @ArnoSen.

A little background first. For `RegisterFlagCompletionFunc()` and `ValidArgsFunction`, when doing the completion, the completion script will call your program using the hidden `__complete` command to obtain the completions.  The `__complete` command is a subcommand of the root command.  Therefore, `PersistentPreRun` is called.  However, the `__complete` command must do all flag parsing itself, so it does this *after* `PersistentPreRun` has been called, here:
https://github.com/spf13/cobra/blob/7df62f7668c7fbeafd6dbb45ad0294f4ea08c0ec/custom_completions.go#L209-L212

In your particular case, you want the `PersistentPreRun` to overwrite the flag values, but the flag get parsed after and instead they overwrite the value set by `PersistentPreRun`.

I assume you want your `PersistentPreRun` to read the flags and then set a value based on them, which would then be used by the completion logic.  I think you can achieve what you want by having the function registered in  `RegisterFlagCompletionFunc()` call `PersistentPreRun` again.

**Comment by ArnoSen** [comment]
Thanks for explaining the internal workings @marckhouzam. I had noticed that the generated autocompletion script had changed. This gives more flexibility than can be used to make things like argument completion more easy.

I have been thinking about the solution that you proposed. It will be possible to implement it at least as a short term solution. For the longer run I have two concerns (neither of the two is more important so they are in random order):

- I use persistent flags for setting a connection string which I parse from a config file. I noticed that the command did no longer parse the connection settings that are needed to connect to the right backend against which  argument completions needed to be queried. The implication of this is that the command completion runs in another context/environment than the real command. This is confusing and can easily lead to errors. You need to remember to rerun PersistentPreRun. Also, it would be necessary to rerun the flag parsing for the autocompletion command after running the PersistentPreRun. This is because I think the added value of the PersistenPreRun is to set defaults for command variables that you can or cannot be overridden when running an actual command. Not rerunning the flag parsing of the autocompletion run, would mean that persistent vars can never be overwritten.

- to implement the solution you proposed, it is also necessary that a command that uses argument completion needs to access the function that contains the logic for the PersistentPreRun. How can this be done without using a package/global variable? I don't think that that is possible right now. I think it would be cleaner when somehow an object can be passed into a root command that can be accessed from a child command avoiding package/global vars. This is also useful for other scenarios. I think that a lot of use cases for Cobra is in a client-server architecture. Every command though would need to either instantiate a new client to connect to a server/backend or have have access to a reference to a client that was instantiated elsewhere. In my opinion, each command does not have to know how to instantiates a client and I prefer to have that in once place. The consequence is that I also need a package/global var that reference a client object. When looking at my current code, I have all my command in separated packages and subcommands are in another layer of packages but they all need references to the global scope where the client is located and I would need to add the PersistentPreRun as well.
