### ISSUE TITLE
Repitition of autocompletion in bash after args

### ISSUE THREAD

**Issue by heer-ambavi** [spf13/cobra#1293]
I have a command `upgrade [arg]` defined with `ValidArgsFunction` to autocomplete `arg`.
Another command is `get` which is a subcommand of `upgrade`.

Autocomplete for upgrade command shows:
`upgrade abc get get get`
That is the sub command `get` is repeated after `[arg]` completion. 

Ideally here after arg completion, `get` command shouldn't be shown at all in completion

**Comment by marckhouzam** [comment]
Thanks @heer-ambavi for the report.
I believe this is limited to bash completion (zsh and fish are not affected).
It can be fixed specifically for bash (would need a PR), but #1146 would also fix it.

**Comment by heer-ambavi** [comment]
Thanks @marckhouzam, any workaround for this?

**Comment by johnSchnake** [comment]
The linked PR has merged so I think this is completed. Closing. Feel free to reopen if the problem remains.
