### ISSUE TITLE
Please generate completion script for subcommand's aliases

### ISSUE THREAD

**Issue by hitzhangjie** [spf13/cobra#1296]
github.com/spf13/cobra v1.1.1

I use v1.1.1

$app completion bash > ~/.bash_$app
source ~/.bash_$app

There's no completion prompt for aliases of subcommands.

**Comment by marckhouzam** [comment]
A think this makes sense.  There's a bit of a discussion in #1014.

**Comment by hitzhangjie** [comment]
Thank you @marckhouzam ，I think I should choose a better and shorter command name.
I'll close this.
