### ISSUE TITLE
how to use powerShellCompletion

### ISSUE THREAD

**Issue by king-john** [spf13/cobra#1299]
The cobra version I use is 0.0.7 

Powershell version： 5.1 

I use `testcli completion powershell | Out-String | Invoke-Expression`,  but the completion is invalid on powershell . 

I refer to Generating shell completions.

How to use it？

**Comment by Luap99** [comment]
see #1229

**Comment by king-john** [comment]
@Luap99 
No solution found at #1229
My Completion Item Description is not empty.
My Completion didn't work.

**Comment by anthonyfok** [comment]
@king-john Your Cobra version of 0.0.7 is too old.

Please use v1.1.1, or better, yet,  or newer (master) e.g. by running `go get -u github.com/spf13/cobra@master` to get

    github.com/spf13/cobra v1.1.2-0.20210209210842-07445ea179fc

which contains @Luap99's latest enhancements to PowerShell completion.

Also, please read the excellent documentation at https://github.com/spf13/cobra/blob/master/shell_completions.md written by Marc Khouzam (@marckhouzam) and Paul Holzinger (@Luap99).  There is a near complete example which basically work out of the box.

Hope this helps!
