### ISSUE TITLE
How to validate flags when they get set?

### ISSUE THREAD

**Issue by gabyx** [spf13/cobra#1300]
I have the following flags setup:

```go
rootCmd.PersistentFlags().String("config", "",
		"JSON config according to the 'Arguments' struct.")

viper.BindPFlag("config", rootCmd.PersistentFlags().Lookup("config"))
```

How can we make cobra fail parsing when the flag value is empty, e.g. `--config=""` or `--config ""`.
How can we validate flags when they get parsed?
Can we set validation callbacks on the flags?

**Comment by hitzhangjie** [comment]
I usually validate the params in PreRunE if needed
