### ISSUE TITLE
custom completion should respect the flagset interspersed option

### ISSUE THREAD

**Issue by Luap99** [spf13/cobra#1307]
The flagset interspersed option indicates that flags which follow after the fist argument are also considered arguments and are not parsed as flag.

Consider this simple example:
```
package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Use: "testprog",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("rootCmd called")
	},
}

var subCmd = &cobra.Command{
	Use: "sub",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println(args)
	},
}

func main() {
	rootCmd.AddCommand(subCmd)
	flags := subCmd.Flags()
	flags.SetInterspersed(false)
	flags.Bool("test", false, "test flag")

	rootCmd.Execute()
}
```

The --test flag is added to args if an argument exists before:
```
$ ./testprog sub --test a
[a]
$ ./testprog sub a --test 
[a --test]
```

This is the expected behaviour however the custom completion logic does not respects this. It still provides flag completion even after the first arg is set.

```
$ ./testprog __complete sub a --t
--test  test flag
:4
Completion ended with directive: ShellCompDirectiveNoFileComp
```
This should not happen. Instead it should provide argument completion (e.g. ValidArgsFunction).

I looked at the code but I'm not sure how this could be implemented. The problem is that the interspersed option is not exported from the FlagSet so we cannot retrieve it.

@marckhouzam Any Ideas?

**Comment by Luap99** [comment]
The same thing also applies to arguments after `--`.

**Comment by Luap99** [comment]
OK I think I found a solution. We can parse the arguments with `finalCmd.ParseFlags(append(finalArgs, "--"))`. If the number of arguments is higher than before, we should not complete the flags because either `--` was set on a previous argument or an argument is set and "interspersed" is false.

**Comment by marckhouzam** [comment]
I'm guessing the `interspersed` setting and even the `--` marker are not respected the current bash completion logic either?  With you proposed fix, it would give another reason to fully move bash to Go completions, if I understand correctly.

**Comment by Luap99** [comment]
> I'm guessing the interspersed setting and even the -- marker are not respected the current bash completion logic either? With you proposed fix, it would give another reason to fully move bash to Go completions, if I understand correctly.

Yes it does not work with bash. I do not plan to implement it there given that we already have a working solution with your bashV2 PR.
