### ISSUE TITLE
SetOutput() doesn't work.

### ISSUE THREAD

**Issue by rikoroku** [spf13/cobra#1316]
## Environments

```bash
OS: macOS Big Sur Version 11.1
Chip: Apple M1
go: go1.16beta1 darwin/arm64
cobra: v1.1.1
```

## What's the problem
I want to test with a command which outs put a string as stdout.
But, I couldn't do that by using `SetOutput()` as follows.
This test has returned an empty string like "".
I hope it will return the string "1".

How can I do that? Would please teach me about this.

```golang
// agenda.go
package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

func agendaCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "agenda",
		Short: "...",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Println("1")
		},
	}
}
```

```golang
// agenda_test.go
package cmd

import (
	"bytes"
	"io/ioutil"
	"testing"
)

func Test_agendaCmd(t *testing.T) {
	b := new(bytes.Buffer)
	cmd := agendaCmd()
	cmd.SetOutput(b)
	cmd.Execute()

	out, err := ioutil.ReadAll(b)
	if err != nil {
		t.Fatal(err)
	}
	if string(out) != "1" {
		t.Fatalf("expected \"%s\" got \"%s\"", "1", string(out))
	}
}
```

**Comment by matanw** [comment]
to use the SetOutput, your RunE should do "cmd.Println" instead "fmt.Println". Means, this will work:
`
// agenda.go
package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

func agendaCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "agenda",
		Short: "...",
		Run: func(cmd *cobra.Command, args []string) {
			cmd.Println("1")
		},
	}
}

`
`// agenda_test.go
package cmd

import (
	"bytes"
	"io/ioutil"
	"testing"
)

func Test_agendaCmd(t *testing.T) {
	b := new(bytes.Buffer)
	cmd := agendaCmd()
	cmd.SetOutput(b)
	cmd.Execute()

	out, err := ioutil.ReadAll(b)
	if err != nil {
		t.Fatal(err)
	}
	if string(out) != "1\n" {
		t.Fatalf("expected \"%s\" got \"%s\"", "1", string(out))
	}
}`

bay the way, setOutput is depracted, use setOut (and still you need use cmd.PrintLn instead fmt.Println)

**Comment by jpmcb** [comment]
@matanw is correct. In order to print to the configured io.Writer used in SetOut, you'll want to use `cmd.Println` which is a public method on the Command struct. This uses `fmt.Sprintln` and the designated io.Writer. 

And yes, use `SetOut` as `SetOutput` is deprecated and will be removed in a future release.

Refer to "command.go" for further reading

Closing as question was answered! 🚀 best of luck!

**Comment by rikoroku** [comment]
I've could solve it from these answers.
TNK for your answering!
