### ISSUE TITLE
So apparently cobra depends on Apple Metal API

### ISSUE THREAD

**Issue by XANi** [spf13/cobra#1318]
https://github.com/spf13/cobra/blob/ff416ad438f79ee925809ff5e80fb796e23cb24b/go.sum#L13

https://godoc.org/dmitri.shuralyov.com/gpu/mtl

is that intended ?

**Comment by Tarliton** [comment]
Hello,

I have noticed this too.

It was added by viper in commit https://github.com/spf13/viper/commit/9c81997cb1908f9597ae77f71d3eaf33d1e14483 and published in version v.1.7.0.

go mod why in viper outputs this:
```bash
go mod why -m golang.org/x/exp
# golang.org/x/exp
github.com/spf13/viper/remote
github.com/bketelsen/crypt/config
github.com/bketelsen/crypt/backend/firestore
cloud.google.com/go/firestore
cloud.google.com/go
golang.org/x/exp/cmd/apidiff
```

It was added in exp here: https://github.com/golang/exp/commit/81c71964d733d2e3e2375a315c0e2fd4d162adc4.

**Comment by johnSchnake** [comment]
If this was added by viper then it should resolve itself since viper has been removed as a dependency and has moved to spf13/cobra-cli.

I dont see it in the mod or sum file now.
