### ISSUE TITLE
fatal error: concurrent map writes with RegisterFlagCompletionFunc

### ISSUE THREAD

**Issue by MichaelMure** [spf13/cobra#1320]
Cobra has a global map [here](https://github.com/spf13/cobra/blob/master/custom_completions.go#L21) to store completion function when those exists.

This global map is not protected in any way, which leads to `fatal error: concurrent map writes` when handling **multiple root command concurrently**. Yes, it's a little odd situation but it's a useful one to generate documentation/completion faster (ie, concurrently). Most of those documentation/completion generator will actually mutate things here and there in the commands, which makes them not thread-safe. Now, this global map for completion functions also make things no, thread-safe, even if you duplicated entirely your root command.

I see the following possible solutions:
- move this completion function (no map anymore) directly into `flag.Flag`. No more global, no more indirection, but that's another package.
- move the map into `cobra.Command`, to at least make be thread-safe when you have a copy of your `Command`
- add a mutex or use `sync.Map`.

Example code to trigger the issue:

```go
package main

import (
	"fmt"
	"sync"

	"github.com/spf13/cobra"
)

func main() {
	cmd := cobra.Command{}

	N := 2
	options := make([]string, N)

	var wg sync.WaitGroup
	for i := 0; i < N; i++ {
		flag := fmt.Sprintf("flag%d", i)
		cmd.Flags().StringVarP(&options[i], flag, "", "value", "usage")
		wg.Add(1)
		go func() {
			defer wg.Done()
			err := cmd.RegisterFlagCompletionFunc(flag, nil)
			if err != nil {
				panic(err)
			}
		}()
	}

	wg.Wait()

}
```

_Originally posted by @krobelus in https://github.com/spf13/cobra/issues/1290#issuecomment-767341378_

**Comment by Luap99** [comment]
The issue is not limited to the flagCompletionFunctions map. You can also easily reproduce with to following since the flags are also stored as map.
```golang
package main

import (
	"fmt"
	"sync"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func main() {
	cmd := cobra.Command{}

	N := 20

	var wg sync.WaitGroup
	for i := 0; i < N; i++ {
		flag := fmt.Sprintf("flag%d", i)
		wg.Add(1)
		go func() {
			defer wg.Done()
			cmd.Flags().StringP(flag, "", "value", "usage")
		}()
	}

	wg.Wait()

	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		fmt.Println(f.Name)
	})

}
```

**Comment by MichaelMure** [comment]
Still an issue.

**Comment by silenceshell** [comment]
we met this problem too.
