### ISSUE TITLE
DisableFlagParsing should disable creation of the help flag?

### ISSUE THREAD

**Issue by watk** [spf13/cobra#1328]
I expected this to be the default behaviour but maybe there's a good argument for how it is today.

If you add a command with DisableFlagParsing, then `help cmd` will list `-h` as a flag, but running `cmd -h` will not print the help, it'll invoke Run() with ['-h']. If it's the command's responsibility to parse all of the flags, I think it makes sense to not add flags automatically.

Here is a simplified example:
```go
package main
import "github.com/spf13/cobra"
func main() {
	cmd := &cobra.Command{
		Use:              "root",
		TraverseChildren: true,
	}
	sub := &cobra.Command{
		Use:                "sub",
		DisableFlagParsing: true,
		Run:                func(cmd *cobra.Command, args []string) {},
	}
	cmd.AddCommand(sub)
	cmd.SetArgs([]string{"help", "sub"})
	cmd.Execute()
}
```

The output is:
```
Usage:
  root sub [flags]

Flags:
  -h, --help   help for sub
```

Is there any better way to disable this help flag than this?
```go
	sub.InitDefaultHelpFlag()
	sub.Flags().MarkHidden("help")
```

**Comment by johnSchnake** [comment]
That is interesting. Thanks for showing a simple workaround for now.

I don't personally know of a reason you'd want to keep the help flag defined there if parsing is disabled. I'd be happy to review a PR if you (or someone else) can make the narrow change.

**Comment by watk** [comment]
Thanks, I'm no longer using cobra so feel free to close this given that there's a simple workaround anyway.
