### ISSUE TITLE
Feature: Option to disable a persistent required flag on an individual command

### ISSUE THREAD

**Issue by alexhowarth** [spf13/cobra#1330]
My particular use case is for a tool I'm writing that searches for devices on a network.

`./tool search`

This returns ip addresses of relevant devices on the network.

All other commands require an `ip` argument be passed:

```
./tool --ip 192.168.0.5 foo
./tool --ip 192.168.0.5 bar
```

There's a hack/workaround that works but it's not pretty.

Root command:

```
func init() {
        // all but 1 command require an ip argument
	rootCmd.PersistentFlags().StringVar(&ip, "ip", "", "ip")
	rootCmd.MarkPersistentFlagRequired("ip")
}
```

Search command:

```
var searchCmd = &cobra.Command{
	Use:   "search",
	Run: func(cmd *cobra.Command, args []string) {
		// do search
	},
	// hack to disable persistent required 'ip' flag
	PreRun: func(cmd *cobra.Command, args []string) {
		flags := cmd.InheritedFlags()
		flags.SetAnnotation("ip", cobra.BashCompOneRequiredFlag, []string{"false"})
	},
}
```

**Comment by datacharmer** [comment]
The implementation of `UnMarkInheritedFlagRequired` (or `MarkInheriteddFlagUnrequired`) would be straightforward.

```go
func (c *Command) MarkInheritedFlagUnrequired(name string) error {
	return c.InheritedFlags().SetAnnotation(name, BashCompOneRequiredFlag, []string{"false"})
}
```
(See the current method in [shell_completions.go](https://github.com/spf13/cobra/blob/1d71ff02701cb01f7e9980754da9c95cb92252d2/shell_completions.go#L7))


However, my suggestion of using `PreRun` is overkill.
The call to `SetAnnotation` for the depending command could be right next to the call to `MarkPersistentFlagRequired`.

For example:
```go
func init() {
        // all but 1 command require an ip argument
	rootCmd.PersistentFlags().StringVar(&ip, "ip", "", "ip")
	rootCmd.MarkPersistentFlagRequired("ip")
	searchCmd.InheritedFlags().SetAnnotation("ip", cobra.BashCompOneRequiredFlag, []string{"false"})
	// or, if MarkInheritedFlagUnrequired were implemented:
	searchCmd.MarkInheritedFlagUnrequired("url")
}
```

**Comment by alexhowarth** [comment]
@datacharmer 

I cannot get your suggestion to work. I believe `PreRun` may be relevant here.

Here's my fork with a failing test:

https://github.com/alexhowarth/cobra/commit/c91854b48658cb773bb768fa8e2f332233a5712b

```
➜  cobra git:(feature/1330-unmark-persistent-flag-required) go test -v -run TestInheritedPersistentNotRequiredFlags                      
=== RUN   TestInheritedPersistentNotRequiredFlags
    command_test.go:804: Unexpected output: required flag(s) "foo1" not set
--- FAIL: TestInheritedPersistentNotRequiredFlags (0.00s)
FAIL
exit status 1
FAIL    github.com/spf13/cobra  0.129s
```

**Comment by datacharmer** [comment]
@alexhowarth
it is failing because  the call to `MarkInheritedPersistentFlagNotRequired` happens before `parent.AddCommand(child)`.
 
At that stage, there are no inherited flags to modify.

**Comment by alexhowarth** [comment]
Fixed up the test.

@jharshman - if there's any interest in this feature I can create a pull request.
