### ISSUE TITLE
Use boolean flags explicitly

### ISSUE THREAD

**Issue by cmpsoares91** [spf13/cobra#1331]
For our use-case, I need to differentiate if a boolean flag is used or not.  So I can add default logic when the boolean flag hasn't been used:
```go
isActive, _ := cmd.Flags().GetBool("isActive")
if isFlagUsed("isActive") {
	isActive = someBoolValue
        //Do other stuff
}
```

Is this possible to accomplish?

Thanks for your help!

**Comment by eparis** [comment]
Is that cmd.Flags().Changed("isActive") ?

**Comment by johnSchnake** [comment]
Seems asked/answered. Please reopen if this didnt answer your question.
