### ISSUE TITLE
Persistent*Run hooks don't execute when `Run` not exit.

### ISSUE THREAD

**Issue by youngjuning** [spf13/cobra#1332]
```go
var rootCmd = &cobra.Command{
	...
        // Not work
	PersistentPostRun: func(cmd *cobra.Command, args []string) {
		fmt.Println("Root PersistentPostRun")
	},
}
```

So I must set void Run func

**Comment by marckhouzam** [comment]
Hi @youngjuning.  You are correct.
Before executing any PreRuns, Cobra makes sure the command can be run here:
https://github.com/spf13/cobra/blob/1d71ff02701cb01f7e9980754da9c95cb92252d2/command.go#L812

Are you facing a use case where this is a problem?

**Comment by youngjuning** [comment]
I just want run PersistentPostRun when Run not exit. Because I call checkUpgrade func in PersistentPostRun

**Comment by marckhouzam** [comment]
I think in that case your best solution is to define an empty Run, as you mentioned.

**Comment by youngjuning** [comment]
@magiconair Yes I just do like you say.
