### ISSUE TITLE
Bash completion does not work correct for redirections

### ISSUE THREAD

**Issue by Luap99** [spf13/cobra#1334]
From https://github.com/spf13/cobra/pull/1146#issuecomment-771587773 and https://github.com/spf13/cobra/pull/1146#issuecomment-772146642

> Running `tesprog mycommand > somefile[TAB]` does not work correct. It will write the completion
output of testprog __complete mycommand to the current file name and thus maybe overwrite an important file.

> If a ValidArgsFunction is defined on the final cobra command, the completion script, even the v1 version, will call the __complete command, with all arguments, including the > out redirect. So this bug you found also happens with current Go completions. For example helm completion bash defines a ValidArgsFunction to turn off file completion. So, when doing helm completion bash >out<TAB> (in bash completion v1), the go completion function will be triggered in the bash script and it will execute helm __completeNoDesc completion bash > out. This is where the out file gets overwritten. This of course happens all the time for bash v2 since it always uses Go completions.

**Comment by Luap99** [comment]
@marckhouzam I looked into possible solutions and found one.

The bash-completion package provides a `_init_completion` function here: https://github.com/scop/bash-completion/blob/9e98e2558c0625340013b123880ebb6bedc0d1b3/bash_completion#L796
This function is used by many completion scripts found in this repo. Its called like this:
```
    local cur prev words cword
    _init_completion || return
```

If we call this first we should never run into this issue.
This function takes care of the redirection case and also variable completion like `$S[TAB]`.

**Comment by Luap99** [comment]
OK looking at the v1 code. `_init_completion` is already called but only if it exists. https://github.com/spf13/cobra/blob/1d71ff02701cb01f7e9980754da9c95cb92252d2/bash_completions.go#L390-L394
I cannot reproduce this issue on my machine because `_init_completion` is defined. `bash-completion` version `2.8-9`

@marckhouzam I assume you tested this on macos and therefore you can reproduce this. https://github.com/spf13/cobra/blob/1d71ff02701cb01f7e9980754da9c95cb92252d2/bash_completions.go#L32-L38

**Comment by marckhouzam** [comment]
Thanks for reporting and investigating.
This definitely sounds like the correct solution for bash completion v2. We'll have to do better for MacOS for bash completion both v1 and v2.  Maybe simply imitating what the full `_init_completion()` does.

**Comment by Luap99** [comment]
I am not the biggest fan of code duplication. With quick online search I found this https://formulae.brew.sh/formula/bash-completion@2. So it should be available.

**Comment by marckhouzam** [comment]
I have started by adding a test for this bug to the cobra-completion-testing repo:
https://github.com/marckhouzam/cobra-completion-testing/commit/3bcef8b37f26d2ebfadca6ed9758c803b6cf266b

And it turns out the problem also happens on bash3, for which the `bash_completion` package does not seem to have the `_init_completion` function.

> I am not the biggest fan of code duplication. With quick online search I found this https://formulae.brew.sh/formula/bash-completion@2. So it should be available.

Thanks @Luap99!  I had `bash-completion@1` installed and was not aware the @2 package was available for Mac.
However, the package`bash-completion@2` requires bash > 4.2, which is not the standard install on Mac, which has `bash3` instead (I manually installed `bash4`).

So let's see if we can improve the situation for `bash3` ourselves within Cobra.

**Comment by Luap99** [comment]
I see, I do not use macos. I am fine with copying the code but the script should use the original function when available like it does currently.

**Comment by marckhouzam** [comment]
Still valid

**Comment by marckhouzam** [comment]
To clarify the status of this issue.  The problem only happens for bash < 4.2 or using the old bash-completions package.
I've come around and don't think we need to worry about such old versions.

In fact, the kubectl completion documentation mentions requirements of bash 4.1+ and the bash-completions@2 package: https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-mac/

**Comment by Luap99** [comment]
Given that this is a problem with the standard bash-completion functions and not with cobra, I close this one.
