### ISSUE TITLE
Is there an alternative way to init() here?

### ISSUE THREAD

**Issue by frederikhors** [spf13/cobra#1335]
I'm using this code:

```go
func init() {
  rootCmd.AddCommand(versionCmd)
}
```

but the linter: https://github.com/leighmcculloch/gochecknoinits in https://golangci-lint.run/usage/linters/ alerts me with:

```
don't use `init` function
```

How to fix this?

Is there an alternative way to `init()` here?

**Comment by frederikhors** [comment]
No stale.

**Comment by MichaelMure** [comment]
Have a look at https://github.com/spf13/cobra/issues/1336#issuecomment-781979299

**Comment by johnSchnake** [comment]
Closing since the larger discussion and alternatives are in the linked issue above.

**Comment by mloskot** [comment]
The simple pattern of constructor/factory functions may help, it also improves testability, see:
- https://github.com/spf13/cobra/issues/1041#issuecomment-1050938423 by @johnSchnake 
- https://gianarb.it/blog/golang-mockmania-cli-command-with-cobra
