### ISSUE TITLE
make a raw Args pass to the cobra as a Public variable , or add a Getter like GetArgs

### ISSUE THREAD

**Issue by mehrdadnd** [spf13/cobra#1341]
I see the function `SetArgs` 
```go
func (c *Command) SetArgs(a []string){...}
```
which is very helpful during the unit testing but is there any way for `GetArgs` to access all the raw arguments which have been reaching the Cobra?

**Comment by johnSchnake** [comment]
From lack of followup or reaction I'm going to close as part of #1600. If you still feel like this is something you would like addressed please reopen. It seems like a pretty small PR if you wanted to put it up (just a getter method) so we could review/discuss there if you would prefer. Having the PR up and ready to go makes it faster to address.
