### ISSUE TITLE
Setting either/or multiple flags as required?

### ISSUE THREAD

**Issue by aronchick** [spf13/cobra#1353]
Hi--

Is there any way to declare a group of flags as required where one or the other MUST be set, but not neither? I couldn't find anything in the docs - and it's pretty easy to just write the logic, but it'd be interesting to see if this was already built in.

**Comment by marckhouzam** [comment]
Hi @aronchick.  Unfortunately there is no built-in way of doing what you suggest.

**Comment by aronchick** [comment]
No worries, thanks for everything!


________________________________
