### ISSUE TITLE
Completions on positional arguments not working in Bash

### ISSUE THREAD

**Issue by craicoverflow** [spf13/cobra#1355]
**Shell (version)**: bash (5.0.17)
**Cobra vesion**: 1.1.1
**OS**: Linux

This does not happen in ZSH. Completions on positional arguments is not working for me in Bash. I have been using `ValidArgsFunction` but the issue is also present in `ValidArgs`.

## Steps to reproduce

1. Ensure you are running a Bash terminal.
1. Create a CLI using Cobra
2. Add a command. The minimun requirements is that the command uses [`ValidArgsFunction`](https://github.com/spf13/cobra/blob/652c755d3751109d878a9c8228c0bcb7aed0d4f5/command.go#L67) (or `ValidArgsFunction`).
3. Enable completions for the command
4. Install the CLI binary and invoke completions:

```shell
$ cobra-cli my-test-command <tab><tab>
```
5. The values defined in `ValidArgs` do not show up as suggestions.
6. Repeat steps 3-4 in ZSH and the completion suggestions will work.

**Comment by Luap99** [comment]
Can you provide a reproducer?

**Comment by craicoverflow** [comment]
Updated with steps to reproduce.

**Comment by tinyzimmer** [comment]
I may or may not be witnessing something similar, in that I'm trying to change the behavior of a `ValidArgsFunction` similar to `scp` style (such that i start off by completing available "hosts", followed by a colon and then completing remote paths). But for some reason, after I return the valid hosts with `cobra.ShellCompDirectiveNoSpace`, following iterations on the function come back with `toComplete` set to an empty string.

**Comment by tinyzimmer** [comment]
If it helps (I won't be making any changes for a little bit) [this is the code](https://github.com/tinyzimmer/kvdi/blob/main/pkg/cmd/sessions.go#L225) exhibiting the above behavior.

**Comment by marckhouzam** [comment]
@tinyzimmer I believe you are hitting a different problem.

My guess is that your problem is related to the `:`.  Bash completion usually breaks words up on a `:`.  You can confirm this by looking at the `COMP_WORDBREAKS` variable.  The bash script produced by Cobra works around this by using `__ltrim_colon_completions` but I believe this was overlooked when using `ValidArgsFunction`.

This case is handled properly in #1146 which implements a new version of bash completion, but it is not yet released.

I recommend you create a new issue to track the bug you found.

**Comment by marckhouzam** [comment]
@craicoverflow Would you be able to post the program that does not work for you?  The steps you mention remain pretty vague.  How did you enable completion?  How did you implement `ValidArgsFunction`?

**Comment by tinyzimmer** [comment]
@marckhouzam TIL a little more about bash completion, and that PR indeed looks very exciting. I'll probably hold off on creating a new issue, unless you think it would help to have one. I'm not in any rush and can wait for that PR to be released to address the issues on my end.
