### ISSUE TITLE
feature: is there a convenient way for cobra application to execute another cobra application?

### ISSUE THREAD

**Issue by hitzhangjie** [spf13/cobra#1361]
Hope to conveniently execute another cobra application B in current application A;
When run `A B`, then `A` executes `B`, and passing the input to `B`
When run `A B <tab>`, then `A` calls the API exposed by `B` to get the contained root cmd and childrens information. then `A` can generate a whole complete auto completion shellscript to process the `<tab>` properly.

I don't think whether this solution is good or not. It just maybe a solution for integrating other cobra applications.

**Comment by marckhouzam** [comment]
Hi @hitzhangjie.  I believe the first point you mention is the concept of plugins, where each `B` is a plugin of `A`. This is possible with Cobra although there is no explicit support for it.  You can refer to #1026.

Here are two examples of slightly different ways of supporting plugins:
Kubectl - https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/
Helm - https://helm.sh/docs/topics/plugins/

The second point is the support of shell completion for plugins.
Helm has implemented it's own solution as described here: https://helm.sh/docs/topics/plugins/#providing-shell-auto-completion
There has been discussions for kubectl here: https://github.com/kubernetes/kubernetes/issues/74178

I hope this helps.

**Comment by hitzhangjie** [comment]
@marckhouzam  Yes, it helps. Thank you very much.
