### ISSUE TITLE
Clearing the value of flags?

### ISSUE THREAD

**Issue by aronchick** [spf13/cobra#1367]
I'm doing some testing of Cobra command functions and in a particular test suite, a persistent flag is getting set (somewhere) and I can't figure out where. Rather than tracking it down, I thought it'd be more efficient to just wipe the values for all flags set - similar to the Viper command - `viper.Reset()`. Is there something like that? To be clear - ResetCommands() doesn't work because I still want all the flags to be there, just set to empty.

**Comment by ssVcJwV** [comment]
Is there any progress ?
