### ISSUE TITLE
How to write custom help command?

### ISSUE THREAD

**Issue by gennaro-tedesco** [spf13/cobra#1368]
In the [README file](https://github.com/spf13/cobra#defining-your-own-help) it is stated that one can fully customise the aspect and documentation of the `--help` commands, in particular
```
cmd.SetHelpCommand(cmd *Command)
cmd.SetHelpFunc(f func(*Command, []string))
cmd.SetHelpTemplate(s string)
```
however, it is a little unclear what exactly each of these single methods do and I was wondering if there is extensive documentation on how to 
```
cmd.SetHelpTemplate(s string)
```
The help pages being long strings, I suspect I want to pass a reference to a file rather than a string.

Where can I look up how to implement them?

**Comment by gennaro-tedesco** [comment]
Is this being looked at (otherwise we close)?

**Comment by jpmcb** [comment]
Hi @gennaro-tedesco - right now, there is not much documentation that exists outside of the library documentation itself. 

This can be found within the code itself or here: https://pkg.go.dev/github.com/spf13/cobra
