### ISSUE TITLE
[question/feature] turning cobra cli into fully ready (g)rpc service ?

### ISSUE THREAD

**Issue by bukowa** [spf13/cobra#1369]
What do you think about an idea; implementing a feature that would allow to expose CLI written in cobra as a ready grpc service to call our commands remotly?

**Comment by MichaelMure** [comment]
This is not such a crazy concept as it sounds. An example in the wild: the IPFS HTTP API is generated from the CLI tooling.

https://docs.ipfs.io/reference/http/api/
https://docs.ipfs.io/reference/cli/#ipfs

**Comment by johnSchnake** [comment]
Is this something that the main library would have to be concerned with or something that a tool would just add via wrapping the CLI?

On the surface this seems beyond the scope of the current library and unlikely to get implemented without a much larger conversation/reaction from other community members.

I'm going to close as motivated by #1600 but if you'd like to restart this discussion feel free to reopen it. Bandwidth to accomplish this would also be an issue I'm sure, though I am not aware of how intense of a change this is. Perhaps you can comment on that if you want to try and move this forward.
