### ISSUE TITLE
Powershell completion does not kick in with TAB when not typing any starting letter

### ISSUE THREAD

**Issue by saurabhaditya** [spf13/cobra#1370]
To replicate:
1. Make a command hidden by marking hidden to true:

```
var myCmd = &cobra.Command{
  ...
  Hidden: true
}
```

2. Generate PowerShell completion
3. Note that the PowerShell completion includes the hidden command, but the bash-completion does not.

**Comment by marckhouzam** [comment]
Thanks for the report @saurabhaditya.  Are you running Cobra 1.1.3?  Powershell completion has been greatly enhanced in 1.1.3 and should not, to my knowledge, show hidden commands.

**Comment by saurabhaditya** [comment]
Thank you for responding Marc!

The cobra at the head apparently autocompletes by the first character that the user enters. I was hoping to see the subcommands when pressing TAB. Is that possible?

Running `yext <TAB>` using the binary generated with cobra at head:
```
PS C:\Users\vagrant> yext .\.ssh\
```

Autocompletes kicks in when I press the first character:
`yext i<TAB>`:
```
PS C:\Users\vagrant> yext info
```

Is that expected?

**Comment by marckhouzam** [comment]
That's not right. It should complete subcommands even if the user didn't type anything.  Is there a way us to reproduce what you see?

**Comment by saurabhaditya** [comment]
To replicate,

1. yext.msi can be downloaded and installed on Windows from https://yext-cli-pub.s3.amazonaws.com/cli/windows/yext.msi
2. Please say yes to unsafe warnings, and allow the installer to finish running.
3. After that open a new powershell
4. Setup autocomplete by `yext completion powershell | Out-String | Invoke-Expression`
5. Type `yext <TAB>`, it did not autocomplete for me, when apparently it should.
6. Type `yext i<TAB>` that autocompletes as expected.

**Comment by marckhouzam** [comment]
Sorry for the delay @saurabhaditya.  I don't have a Windows machine but I installed `yext` on my Mac where I run powershell.

The completion seems to work as expected, except that there is a warning message "This is a beta version of the Yext Command Line Interface" which is printed for every yext command, and therefore is being treated as a completion by mistake.

The way Cobra completion works is that it calls `yext __complete <arguments>` or `yext __completeNoDesc <arguments>`.  Cobra provides these `__complete` and `__completeNoDesc` commands which print the relevant completions for the shell to use.  For example:
```
> yext __completeNoDesc in<ENTER>
This is a beta version of the Yext Command Line Interface

info
init
:4
Completion ended with directive: ShellCompDirectiveNoFileComp
```
Notice that the line "This is a beta version of the Yext Command Line Interface" is part of that output but should not be.

And if I mimic the case where the user has not typed anything:
```
> yext __completeNoDesc '"'
This is a beta version of the Yext Command Line Interface

completion
help
info
init
resources
service-users
version
:4
Completion ended with directive: ShellCompDirectiveNoFileComp
```
or using the actual shell completion
```
yext <TAB>
This is a beta version of the Yext Command Line Interface  init
                                                           resources
completion                                                 service-users
help                                                       version
info
```

**Comment by marckhouzam** [comment]
Are you still seeing the problem yourself?  If so, could it be related to the option you use for completion? 
```
        # PowerShell supports three different completion modes
        # - TabCompleteNext (default windows style - on each key press the next option is displayed)
        # - Complete (works like bash)
        # - MenuComplete (works like zsh)
        # You set the mode with Set-PSReadLineKeyHandler -Key Tab -Function <mode>
```

**Comment by saurabhaditya** [comment]
I am able to replicate what you see with `brew install powershell` on Mac
and then `pwsh`. I will try native next.

On pwsh on Mac:

PS /Users/asaurabh> yext
This is a beta version of the Yext Command Line Interface  init
                                                           resources
completion                                                 service-users
help                                                       version
info
PS /Users/asaurabh> yext
This is a beta version of the Yext Command Line Interface  init
                                                           resources
completion                                                 service-users
help                                                       version
info

**Comment by johnSchnake** [comment]
Based on the back and forth it sounds like this may not be an issue any more? Going to close but if you felt this was in error and just forgot to follow up, feel free to reopen.
