### ISSUE TITLE
undefined: io.StringWriter

### ISSUE THREAD

**Issue by Phosvan** [spf13/cobra#1374]
I honestly have no idea what I am doing and I am just not sure why this is not working. I am trying to get https://github.com/REVrobotics/SPARK-MAX-Server to work. I believe I have all the requirements. The only error I get when making the thing is this   - 

~/go/src/github.com/REVrobotics$ go get github.com/spf13/cobra/cobra
# github.com/spf13/cobra
../spf13/cobra/bash_completions.go:22:24: undefined: io.StringWriter
../spf13/cobra/bash_completions.go:383:26: undefined: io.StringWriter
../spf13/cobra/bash_completions.go:425:24: undefined: io.StringWriter
../spf13/cobra/bash_completions.go:437:27: undefined: io.StringWriter
../spf13/cobra/bash_completions.go:475:25: undefined: io.StringWriter
../spf13/cobra/bash_completions.go:486:20: undefined: io.StringWriter
../spf13/cobra/bash_completions.go:501:38: undefined: io.StringWriter
../spf13/cobra/bash_completions.go:527:21: undefined: io.StringWriter
../spf13/cobra/bash_completions.go:564:28: undefined: io.StringWriter
../spf13/cobra/bash_completions.go:589:29: undefined: io.StringWriter
../spf13/cobra/bash_completions.go:589:29: too many errors

For all that is holy, help would be ideal. I think I have figured out everything else i just have no idea why doing "make dep" or "make" or "go get github.com/spf13/cobra/cobra" results in this error. Any ideas or help would be fantastic. Thank you

**Comment by marckhouzam** [comment]
Hi @Phosvan.  I believe your problem is related to the fact that you must use Go version 1.14 or higher with Cobra.

**Comment by Phosvan** [comment]
> Hi @Phosvan.  I believe your problem is related to the fact that you must use Go version 1.14 or higher with Cobra.

You are correct. After all of headache, I went to an older version.

**Comment by marckhouzam** [comment]
If everything is resolved for you, would you mind closing this issue? Thanks.
