### ISSUE TITLE
Parameterised subcommand

### ISSUE THREAD

**Issue by paulhobbel** [spf13/cobra#1378]
Is it possible to have parameterised subcommands, I don't know the proper naming, but I have an example below
```
vumm mod <modname> grant <user> <permission>
```

I've searched the documentation and also previous issues, but failed to find anything

**Comment by marckhouzam** [comment]
I don't believe this is possible @paulhobbel.
  You could rearrange the arguments or use a flag:
`vumm mod grant <modname> <user> <permission>`
or
`vumm mod grant <user> <permission> <modname>`
or
`vumm mod --modname <modname> grant <user> <permission>`

But if we take a step back it seems like the main command in this example in the `grant` command and not the `mod` command.  So maybe it would be better to do something like:
`vumm grant --mod <modname> <user> <permission>`
or
`vumm grant <modname> <user> <permission>`

**Comment by paulhobbel** [comment]
Solved by switching it to just grant yea, the idea was to have multiple subcommands for "mods"

**Comment by marckhouzam** [comment]
Great, so if everything is working for you, could you close this issue @paulhobbel, I don't have permissions. Thanks.

**Comment by paulhobbel** [comment]
Will do, thanks for the help anyhow
