### ISSUE TITLE
Cobra prints the description text always

### ISSUE THREAD

**Issue by avinassh** [spf13/cobra#1383]
I must be doing something wrong, but whenever I run the cli, it prints the description text:

```golang
package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

type Conf struct {
	Name    string
	Length  uint32
	TimeOut uint32
}

var rooCmd = &cobra.Command{
	Use:   "cli",
	Short: "cli is a test cli test for cobra",
	Long:  `some long desc`,
}

var conf = &Conf{}

func init() {
	rootCmd.PersistentFlags().StringVarP(&conf.Name, "name", "n", "etc",
		"provide an user name")
	rootCmd.PersistentFlags().Uint32Var(&conf.Length, "len", 100, "")
	rootCmd.PersistentFlags().Uint32Var(&conf.TimeOut, "timeout", 200, "")
}

func execute() {
	if err := rooCmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func main() {
	execute()
	fmt.Println(conf)
}
```

here is what happens when I run it:

```shell
$ go run main.go
some long desc

&{etc 100 200}
```

Secondly, the default `--help` or `--version` doesn't seem to be working

```shell
 $ go run main.go --help
some long desc

&{etc 100 200}
```

```shell
$ go run main.go --version
Error: unknown flag: --version
Usage:

Flags:
  -h, --help             help for cli
      --len uint32        (default 100)
  -n, --name string      provide an user name (default "etc")
      --timeout uint32    (default 200)

unknown flag: --version
exit status 1
```

**Comment by marckhouzam** [comment]
Hi @avinassh, sorry you are running into problems. I'll try to help.

You probably should set the `root.Run` field so that the command had something to do when you call it; that's probably why you only see the help text.

The `--version` flag will only be created if you set the `rootCmd.Version` field.

I hope that fixes your problems.

**Comment by avinassh** [comment]
@marckhouzam thank you so much, it worked as I was expecting! Now that I look at the readme, it was mentioned:

> Cobra adds a top-level '--version' flag if the Version field is set on the root command. 

I somehow missed it.
