### ISSUE TITLE
Question - how to combine two Cobra CLIs into one?

### ISSUE THREAD

**Issue by zulh-civo** [spf13/cobra#1389]
I have the following commands for CLI A:

```
$ cli-a -h

Usage:
  cli-a [command]

Available Commands:
  command-a1       command description
  command-a2       command description
  command-a3       command description

Flags:
      --config string   config file (default is $HOME/.cli-a.json)
  -h, --help            help for cli-a

Use "cli-a [command] --help" for more information about a command.
```

And, for CLI B, I have the following commands:

```
$ cli-b -h

Usage:
  cli-b [command]

Available Commands:
  command-b1       command description
  command-b2       command description
  command-b3       command description

Flags:
      --kubeconfig string   path to kubeconfig file
  -h, --help                help for cli-b

Use "cli-b [command] --help" for more information about a command.
```

What I want to do now is, I want the CLI B (and all its subcommands) to be CLI A's subcommands like this:

```
$ cli-a -h

Usage:
  cli-a [command]

Available Commands:
  command-a1       command description
  command-a2       command description
  command-a3       command description
  cli-b            description about cli-b

Flags:
      --config string   config file (default is $HOME/.cli-a.json)
  -h, --help            help for cli-a

Use "cli-a [command] --help" for more information about a command.
```

So when user run `$ cli-a cli-b -h`, they will see:

```
$ cli-a cli-b -h

Usage:
  cli-a cli-b [command]

Available Commands:
  command-b1       command description
  command-b2       command description
  command-b3       command description

Flags:
      --kubeconfig string   path to kubeconfig file
  -h, --help                help for cli-b

Use "cli-a cli-b [command] --help" for more information about a command.
```

Both repos are in different Go module name / repository. I still want to offer CLI B to users to download if they don't prefer to download and use all features in CLI A. Most of the work for CLI B (features, bug fixes and etc) will be done in the CLI B repository and I'm thinking to combine/merge them two in my CLI A's CI pipeline.

Is this doable with Cobra? What's the best way to achieve this? How's the project structure/tree should look like? Any example?

And, if you look closer at example outputs above, when user runs `$ cli-a cli-b -h` or `$ cli-a cli-b command-bN [-h]`, I don't want the CLI A's root flag (`--config`) to appear and take effect. Instead, I want CLI B's root flag (`--kubeconfig`) to appear and take effect.

I'd really appreciate all inputs, pointers, examples and external resources here. Thank you in advance. 🙏🏼

**Comment by hitzhangjie** [comment]
Hello, I have tried this before as I have similar needs.

1. usage

you can expose information about the commands and flags of cli-b, and let cli-b expose an API to return this information to cli-a.

cli-a could generate the help message dynamically.

2. subcommand

Let cli-b as the subcommand of cli-a, I think you could add a subcommand named cli-b in cli-a. 
When invoke 'cli-a cli-b' it search  the command in $PATH.

**Comment by zulh-civo** [comment]
Thanks @hitzhangjie. I'll check them out.

**Comment by johnSchnake** [comment]
Sounds like you got an answer you were happy with. Closing as part of #1600.
