### ISSUE TITLE
How to get the output of a command executed?

### ISSUE THREAD

**Issue by valter-silva-au** [spf13/cobra#1395]
Hi All,
I would like to verify if my command executed successfully during my tests.
Currently I'm doing the following, which works:
```
//configure_test.go

...
args := []string{"configure", "create", "--mode", "non-interactive"}
out, err := executeCommandOnly(t, controller.ConfigureCmd(), args)
assert.Nil(t, err)
assert.Contains(t, out, "created successfully")
...

helper.go
...
func executeCommandC(cmd *cobra.Command, args []string) (command *cobra.Command, stdout string, err error) {
	buf := new(bytes.Buffer)

	rootCmd := controller.RootCmd()
	rootCmd.AddCommand(cmd)
	rootCmd.SetOut(buf)
	rootCmd.SetErr(buf)
	args = append(args, "--verbosity", "trace")
	rootCmd.SetArgs(args)

	command, err = rootCmd.ExecuteC()
	stdout = buf.String()
	return command, stdout, err
}
...

And finally my command configure:
...
case "create":
err = configureCreateCredentials(cmd, mode)
if err != nil {
	return fmt.Errorf("unable to create profile\n%v", err)
}
cmd.Printf("profile %s created successfully\n", profile)
...		
```

However, if I try to redirect the output of my command to a file, say:
```
mycli configure create --mode=non-interactive > result.txt
```

The file generated is empty, which is forcing me to change my command to:
```
...
fmt.Printf("profile %s created successfully\n", profile)
...		
```

And therefore making my tests to fail, since I can't get the output of my commands anymore.

Any tips or suggestions would be much appreciated!

Kind regards,
Valter Silva.

**Comment by marckhouzam** [comment]
Hi @valter-silva-au.  What you can do is to pass in an `io.Writer` to your `rootCmd`.  When creating the `rootCmd` during execution, use `os.stdout` but when creating it from the tests, use a `bytes.Buffer`.

I hope this helps.

**Comment by valter-silva-au** [comment]
Thank you @marckhouzam, I will give it a try. You're a legend mate!
