### ISSUE TITLE
Shorthand understands parameter without spaces or equal

### ISSUE THREAD

**Issue by felipe-avelar** [spf13/cobra#1399]
When using a help flag as `-help`, cobra understands as something like `myprogram -h elp`, this is the expected behavior? Shouldn't this be interpreted as unknown flag?

I'm asking this, because, if we have a shorthand that actually receives a parameter, lets say an `output` flag that the shorthand is `o`, if we do something like `myprogram -output ./out`, cobra understands `-o="utput"`, while, I think, it should say that `-output` is not a valid flag...
However, if this is the expected behavior, there is any workaround we can do to prevent this from happening?

Thanks for your attention and for this amazing tool. :)

**Comment by MarvinJWendt** [comment]
This should probably be reported to https://github.com/spf13/pflag/ which is used by Cobra to handle flags.

But I agree with you, this behavior could lead to serious issues. 
For example if a command like `taskmanager -kill docker` would result in `taskmanager -k ill`
If a program namend `ill` is running, it would be closed unexpectedly. I am sure there are better examples, but it proofs a point.
