### ISSUE TITLE
import-error when trying to "go get" cobra/cobra

### ISSUE THREAD

**Issue by Talebna** [spf13/cobra#1405]
when trying to install cobra executable with "go get -u github.com/spf13/cobra/cobra", I get

```
$ go get -u github.com/spf13/cobra/cobra                                                 
cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
	/usr/local/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
	/home/talebna/go_projects/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)

```  
Ubuntu 20.0.4

```
$ go version                                                                       
go version go1.15.4 linux/amd64

```
It seems like the github.com/hashicorp/hcl/hcl package was changed in the original repository.

**Comment by sugarcrm-zshearin** [comment]
I'm running into this too.  Some more info from hcl: https://github.com/hashicorp/hcl/wiki/Version-Selection

I think it should be either `github.com/hashicorp/hcl` (for v1) or `github.com/hashicorp/hcl/v2` (for v2) as the import statement

**Comment by sugarcrm-zshearin** [comment]
I found a workaround: https://github.com/spf13/cobra/issues/1345#issuecomment-777902620

**Comment by Talebna** [comment]
That's work ! Thank you @sugarcrm-zshearin
