### ISSUE TITLE
[cobra.dev] Invalid link

### ISSUE THREAD

**Issue by EmperorYP7** [spf13/cobra#1410]
<img width="1221" alt="Screenshot 2021-06-03 at 2 01 06 AM" src="https://user-images.githubusercontent.com/62606998/120548714-4751dc00-c410-11eb-878e-d906d908026a.png">

This link isn't working on prod.

**Comment by stmcginnis** [comment]
Looks like this might be better opened in https://github.com/spf13/cobra.dev

**Comment by umarcor** [comment]
This is a duplicate of #1391.

**Comment by johnSchnake** [comment]
Closing as duplicate.
