### ISSUE TITLE
Duplicate output - probably in error cases

### ISSUE THREAD

**Issue by jensklose** [spf13/cobra#1415]
Versions
---------
go version go1.16.4 linux/amd64
cobra 1.1.3

How to reproduce?
---------------------

Generate a new project with ```cobra init --pkg-name doublecheck```.
Generate a new command with ```cobra add version```.
Build the project or use ```go run```.

Output
--------
```
>go run main.go version
version called
```
```
> go run main.go vrsion
Error: unknown command "vrsion" for "doublecheck"

Did you mean this?
        version

Run 'doublecheck --help' for usage.
Error: unknown command "vrsion" for "doublecheck"

Did you mean this?
        version

exit status 1

```

Test with unknown command:
```
go run main.go foo
Error: unknown command "foo" for "doublecheck"
Run 'terrasec --help' for usage.
Error: unknown command "foo" for "doublecheck"
exit status 1
```

Expected behavior
--------------------

No double messages

**Comment by afbagwell** [comment]
We are observing this behavior as well with a bare-bones setup for a new CLI app my team is working on.

using Go 1.15 & Cobra 1.2.1

**Comment by ANGkeith** [comment]
removing the `cobra.CheckErr()` seemed to fix this issue for me 

```golang
func Execute() {
	cobra.CheckErr(rootCmd.Execute())
}
```
It should becomes this instead
```
Error: [error msg]
[Usage info]
```
