### ISSUE TITLE
Support choosing between repeated flags

### ISSUE THREAD

**Issue by madarez** [spf13/cobra#1424]
First off, thanks for the great package here!

Now, my use case requires me to take the first value of a flag when it gets repeated:
```bash
cmd --key val1 --key val2
```
Currently, there's no way to choose between the two, and we return the second value above.
In general, since there could be more than two occurrences of the same flag, it'd be ideal if the values of the same key could be handled by a user defined function to deal with such cases.

**Comment by m19c** [comment]
actually, there is a way to do so. `pflag.FlagSet` which is returned by `PersistentFlags()` allows to add a `pflag.Value` defined as follows:

```go
type Value interface {
	String() string
	Set(string) error
	Type() string
}
```

therefore, a custom type - lets say `MultiString` - can be implemented like this:

```go
type MultiString struct {
	value *[]string
}

func (s *MultiString) Set(value string) error {
	*s.value = append(*s.value, value)
	return nil
}

func (s *MultiString) Type() string {
	return "multiString"
}

func (s *MultiString) String() string {
	return fmt.Sprintf("[ %s ]", strings.Join(*s.value, ", "))
}

func (s *MultiString) First() string {
	return (*s.value)[0]
}
```

now you can use the new `MultiString` `pflag.Value` like this:

```go
var key = MultiString{Value: &[]string{}}

rootCmd.PersistentFlags().VarP(&key, "key", "k", "")
```

---

@spf13 i do not know if there is a need to add something like `MultiString` to cobra. If so, I would love to open a pr.

**Comment by johnSchnake** [comment]
There is a string slice flag type now. You could likewise use that custom flag type to simply error if the flag is given twice, or to allow it but if it already has a non-empty value to ignore it.

Seems like this issue could be closed now.
