### ISSUE TITLE
1.2.0 regression: flag completion issues

### ISSUE THREAD

**Issue by Luap99** [spf13/cobra#1437]
PR #1423 changed the location where flag completion functions are stored. It always stores them under the root cmd. This breaks Podman because we setup each cobra cmd struct individually with their flags before we join them to the root command.
So when we call  `cmd.RegisterFlagCompletionFunc()` the root cmd will not be the actual root cmd. When the `__complete` command tries to look up flag completions it will not find anything in the real root cmd and thus no completion is provided.

ref https://github.com/containers/podman/pull/10841

**Comment by Luap99** [comment]
Every program who calls `cmd.RegisterFlagCompletionFunc()` before joining the cmd to the root command will no longer have functional flag completion.

**Comment by marckhouzam** [comment]
Shoot, I didn't think about such a scenario, although it is pretty common. Sorry about that.
