### ISSUE TITLE
Avoid adding `completions` command by default

### ISSUE THREAD

**Issue by twmb** [spf13/cobra#1439]
v1.2.0 adds the completion command to a top-level command by default.

This is great for discovery if cobra users did not know of completions, but this is not great if cobra users already added completions on their own and deliberately have organized their command space.

I have a binary where `gen-autocomplete` is under `misc`, where miscellaneous stuff that users do not need to see all of the time exists. Another binary I am working on has a top level `generate`, where anything the binary generates exists. Another binary I have is providing autocompletion through yet another different manner.

Command organization is a difficult task, and I don't think that we should inherently opt in to a small top level `completion` command by default. This may be fine for small command spaces, but as command spaces grow large, organization becomes quite important.

Lastly, it's not currently possible to opt out of the `completion` command, because it is added during `Execute`.

Can the `completion` command be opt in, rather than impossible-to-opt-out?

Edit: also I do want to stress that I greatly appreciate the completion support in general -- it's my #1 reason to use cobra.

**Comment by marckhouzam** [comment]
Your points are valid.
Cobra allows you to disable or tweak the default completion command.  Please see https://github.com/spf13/cobra/blob/master/shell_completions.md#adapting-the-default-completion-command

We chose to enable this command by default to lower the barrier-to-entry for completion support.  We made the assumption that the programs already aware of Cobra's completion support would have an easier time disabling the command than the reverse. It was a bit of an aggressive approach but we hoped it would help more users.

Please let us know if the documentation is not clear enough on that topic.

Thanks

**Comment by twmb** [comment]
The documentation is quite clear, thank you. I hadnt thought to rereference that page since I was looking at it only last week.
