### ISSUE TITLE
Creating a Shell with Cobra

### ISSUE THREAD

**Issue by ColeDrain** [spf13/cobra#1440]
Hello team Cobra. Really great project you've done.

How would I go about creating a shell, for example, we have the Python shell. You type python in the CL, you get a shell, where you can run python commands..

Though my use case is similar, I want to create a SSH chat with cobra.

Thanks.

**Comment by umarcor** [comment]
@ColeDrain, I'm not sure your question is related to Cobra. Building a shell or any other application with golang is unrelated to Cobra. Cobra is a CLI library for handling commands/subcommands, flags, etc. It has no constraints with regard to the body of the programs you want to execute. It's just a utility for building fancy entrypoints.

Therefore, something such as the following MWE would be a good starting point for your specific application: [Building a container from scratch in Go - Liz Rice (Microscaling Systems)](https://youtu.be/Utf-A4rODH8?t=340). Once you have the codebase for implementing the SSH chat, then you can use cobra for enhancing how the users/admins start the program.

**Comment by ColeDrain** [comment]
Thanks for this reply, you have really cleared a lot for me. I appreciate your response. 🤗
