### ISSUE TITLE
v1.1.3 -> v1.2.1 version shorthand regression

### ISSUE THREAD

**Issue by markphelps** [spf13/cobra#1448]
👋🏻 It seems there is a minor regression when upgrading from v1.1.3 to v1.2.1 when it comes to generating the default `version` flag.

Example, in `1.1.3` when setting a version template like:

https://github.com/markphelps/flipt/blob/a333c6495fe0d787cc886b03f24c48e7cbfd3cae/cmd/flipt/main.go#L189

The root command would allow for using either the `-v` or `--version` to output the `VersionTemplate` like:

```
➜ ./bin/flipt --help
Flipt is a modern feature flag solution

Usage:
  flipt [flags]
  flipt [command]

...

Flags:
  -h, --help            help for flipt
  -v, --version         version for flipt
```

Upon upgrading to `v1.2.1`, the root command no longer seems to support the `-v` shorthand by default. Is there anyway I can configure this myself?

Ex: https://github.com/markphelps/flipt/pull/496/checks?check_run_id=2979287527#step:13:16

```
Flags:
  -h, --help            help for flipt
      --version         version for flipt
```

FWIW, `help` still seems to allow for both the shortand and longhand styles `-h` and `--help`

**Comment by jharshman** [comment]
@markphelps the code that _should_ be populating the default version flag, including the shorthand `v`, is here:
https://github.com/spf13/cobra/blob/de187e874d1ca382320088f8f6d76333408e5c2e/command.go#L1044-L1067

Are you setting `Version` on your Command structure?

**Comment by markphelps** [comment]
This seems to be some weird environmental difference between me running locally and my ITs which run using a debian image, so I'm just gonna close
