### ISSUE TITLE
Completion Error in fish 2.x

### ISSUE THREAD

**Issue by ImSingee** [spf13/cobra#1465]
In CentOS 7, the default version of fish is 2.x. And in fish 2.x the completion (myapp completion fish > /root/.config/fish/completions/myapp.fish) always report an error.

```
fish: Could not autoload item 'myapp', it is already being autoloaded.
This is a circular dependency in the autoloading scripts, please remove it.
```

**Comment by marckhouzam** [comment]
Hi @ImSingee.  I'm trying with centos:7 on docker.  I do see that the completion does not work but it is when I try to trigger it, not at load time.  This is how I built my docker to install fish 2:
```
     FROM centos:7
      RUN yum install -y which wget && \
          cd /etc/yum.repos.d/ && \
          wget http://download.opensuse.org/repositories/shells:fish:release:2/CentOS_7/shells:fish:release:2.repo && \
          yum install -y fish
```

That being said, I worry that fixing it for fish version 2 may be complicated.  Maybe the best solution would be to install fish 3?

**Comment by johnSchnake** [comment]
Due to the length of time since the initial response; I'm going to go ahead an close in an effort to clean up the backlog. Feel free to reopen if its still an issue you feel needs addressed.
