### ISSUE TITLE
Install error / dependency error

### ISSUE THREAD

**Issue by MichailVestnik** [spf13/cobra#1474]
hi! 

I wanted to install Cobra according to the instructions in the README Github document:

```shell
go get -u github.com/spf13/cobra
```
I got a lot of mistakes in response.
Then I tried the command from the documentation at cobra.dev

```shell
go get -u github.com/spf13/cobra/cobra
```
In both cases there is an error. 
![Снимок экрана от 2021-08-16 12-28-28](https://user-images.githubusercontent.com/87961969/129508307-02bf6a34-0f49-4ae9-adc1-189e4253e5ff.png)

**Comment by marckhouzam** [comment]
I believe your version of Go is too old.

**Comment by umarcor** [comment]
It is. You need Go 1.12, at least. Recommended Go >=1.15, since 1.14 is to be deprecated in a few days/weeks. See https://endoflife.date/go.

**Comment by MichailVestnik** [comment]
Thank you! The problem was that I installed Go from the Debian repository and not from the official site. 
I reinstalled Go and everything worked.
