### ISSUE TITLE
When using `cobra.NoArgs`, the flag of the boolean type is not parse correctly

### ISSUE THREAD

**Issue by hi-rustin** [spf13/cobra#1480]
When cobra.NoArgs is not set:

```sh
mycli some-cmd list --all true
```
Flag can be parsed normally.

When setting cobra.NoArgs:

```sh
mycli  some-cmd list --all true
```

It will prompt: unknown command "true" for "mycli  some-cmd list"

**Comment by asddongmen** [comment]
If I set the command like:
```go
command := &cobra.Command{
		Use:   "list",
		Short: "xx",
		Use:       "list",
		Args:      cobra.OnlyValidArgs,
		ValidArgs: []string{"true", "false"},
		Short:     "xx",
```

`mycli  some-cmd list --all true` works again.
This is very confusing.
