### ISSUE TITLE
feature/help request: support redirecting input output

### ISSUE THREAD

**Issue by MakDon** [spf13/cobra#1484]
We are trying to build a bot that accepts cli-like command and return text by the bot like native cli program.

When walking through the code, I found cobra [read args directly from os.Args](https://github.com/spf13/cobra/blob/master/command.go#L939), and print to stderr when errors.

Is there a way that input && output through `[]string` without redirecting `stdin`, `stdout` and `stderr`?   

For example, could i use cobra like:
```golang
outputText, err := cmd.Execute(flags ...string)
```

So i could embed cobra into the bot like this:
```golang
raw := bot.Accept() // sent by client like "bot help foo"
args := bot.ParseIntoSlice(raw) // args is a []string or string
output, err := cmd.Execute(args)
if err != nil{
    bot.ReturnErr(err)
}else{
    bot.ReturnText(output)
}
```

**Comment by marckhouzam** [comment]
Hi @MakDon.  

For args you can use `command.SetArgs([]string)`:
https://github.com/spf13/cobra/blob/4fd30b69ee2b62cf3bbecf0a423f8a1ee47f5f24/command.go#L233-L237

For output you can use `command.SetOut(io.Writer)` and `command.SetErr(io.Writer)` to redirect the output to a writer:
https://github.com/spf13/cobra/blob/4fd30b69ee2b62cf3bbecf0a423f8a1ee47f5f24/command.go#L247-L257

Hope this helps

**Comment by MakDon** [comment]
@marckhouzam Thanks very much. It works well.
I would re-open this issue if there's further update.
