### ISSUE TITLE
Retrieve fully issued command?

### ISSUE THREAD

**Issue by voodooGQ** [spf13/cobra#1489]
Is there any way with Cobra to retrieve the fully issued command (after the bin) by the user as a string? Example: `foo bar --baz bop` => `bar --baz bop`? Concatenating the values on the fly is possible, but hoping there's a built in function.

Thank you for the great framework!

**Comment by marckhouzam** [comment]
I think you can use `os.Args[1:]`

**Comment by voodooGQ** [comment]
Seems to be working as expected. Thanks @marckhouzam!
