### ISSUE TITLE
Redirection with cmd.Print is not working as expected

### ISSUE THREAD

**Issue by katexochen** [spf13/cobra#1490]
I want to use `cmd.Printf` to print the output of my command and be able to redirect the output on the command line or write it into a file like this:

```bash
mycommand version >> test.txt
```
But whatever I try, the output is still written to the terminal, and not to the file or the pipe.

I have the following sub command:
```go
var Version = "0.0.0"

func newVersionCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "version",
		Short: "Display version of this CLI",
		Long:  `Display version of this CLI`,
		Args:  cobra.NoArgs,
		Run: func(cmd *cobra.Command, args []string) {
			cmd.Printf("CLI Version: v%s \n", Version)
		},
	}
	// cmd.SetOut(os.Stdout) // if I uncomment this line, it works
	return cmd
}
```
If I set `cmd.SetOut(os.Stdout)` it works as expected, but according to the documentation, `os.Stdout` is the default out, isn't it? Replacing `cmd.Printf` with `fmt.Printf` also does the job.

**Comment by marckhouzam** [comment]
I'm not sure of the reasoning behind it but `cmd.printf` defaults to stderr.

The comment on the method says
`Printf is a convenience method to Printf to the defined output, fallback to Stderr if not set.`
Please see
https://github.com/spf13/cobra/blob/4fd30b69ee2b62cf3bbecf0a423f8a1ee47f5f24/command.go#L1216

So you to need to first call `cmd.SetOut(os.Stdout)`

I hope this helps

**Comment by katexochen** [comment]
Thanks @marckhouzam, I think the fallback to `Stderr` is quite confusing...
