### ISSUE TITLE
Completion for command with two positional arguments

### ISSUE THREAD

**Issue by katexochen** [spf13/cobra#1491]
Is there a way to archive completion for a command with two positional arguments? I have a command where I want the user to input two arguments like:
```bash
deploy 4 small
```
Where the first positional argument is a number and the second one is a size out of `[]string{"small","medium","large"}`.
How can I archive completion and validation of arguments for such a command?

**Comment by marckhouzam** [comment]
You just need to add the `ValidArgsFunction` field to your command and write the Go code that will check if it's the first arg being completed or not.  `ValidArgsFunction` is called when the user triggers shell completion

**Comment by katexochen** [comment]
I find the `ValidArgsFunction` quite hard to understand.

I think `args` will contain all full arguments, and `toComplete` will contain the unfinished string of the next argument.
But what is the `[]string` return value used for? Is it handled like a dynamically set `ValidArgs`?

I tried the following function, and the shell completion for the second arguments works a expected:
```go
func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
	if len(args) > 0 {
		return []string{"small", "medium", "large"}, cobra.ShellCompDirectiveDefault
	}
	return []string{}, cobra.ShellCompDirectiveDefault
}
```
Is this the way its supposed to be? And how would I validate that the first argument is a number? Should this also be validated inside the `ValidArgsFunction` function? Or in the `Args` property of the command?

**Comment by marckhouzam** [comment]
> I think args will contain all full arguments, and toComplete will contain the unfinished string of the next argument.

That's correct.

You can test things quickly by using the `__complete` command directly.  For example you can do
```
deploy __complete 4 sma<ENTER>
```
Here's some info on debugging this stuff https://github.com/spf13/cobra/blob/master/shell_completions.md#debugging

**Comment by katexochen** [comment]
Thanks for the help, @marckhouzam! The part with the completion works great.

But what about the validation? If I use the previous mentioned function I can still run
```bash
deploy 4 mini
```
without getting an error. How can I validate the arguments?

**Comment by marckhouzam** [comment]
> But what about the validation? If I use the previous mentioned function I can still run
> 
> ```shell
> deploy 4 mini
> ```
> 
> without getting an error. How can I validate the arguments?

So validation is done separately than completion.  For validation you can use the field `cmd.Args` or you can choose to do the validation yourself in your `Run` function.

**Comment by katexochen** [comment]
Okay, thanks for the explanation! :grinning: It's a bit strange that a function called `ValidateArgsFunction` doesn't validate but support completion.
