### ISSUE TITLE
slack link is not public

### ISSUE THREAD

**Issue by robberphex** [spf13/cobra#1493]
At README.md, there is a slack link:

> [![Slack](https://img.shields.io/badge/Slack-cobra-brightgreen)](https://gophers.slack.com/archives/CD3LP1199)

Is it for public discussion for the project?

But the slack link shows "You need to sign in to see this page.", and I cannot sign up for this page(or workspace).

@spf13 please fix this.

**Comment by marckhouzam** [comment]
You have to have a Slack account (free) and join the Gophers channel.

**Comment by umarcor** [comment]
I can confirm that I cannot access the Gophers workspace/channel:

![image](https://user-images.githubusercontent.com/38422348/134609640-9af03345-6883-45df-9b88-68a71a6be0f7.png)

**Comment by RobberPhex** [comment]
You cloud visit <https://invite.slack.golangbridge.org/> to get an invitation.

> I can confirm that I cannot access the Gophers workspace/channel:
> 
> ![image](https://user-images.githubusercontent.com/38422348/134609640-9af03345-6883-45df-9b88-68a71a6be0f7.png)

**Comment by anthonygedeon** [comment]
I'll work on this if the issue is still available

**Comment by jpmcb** [comment]
Slack link works. Clicking it for me takes me directly to the Cobra channel in the Gophers slack. You need a slack account there first.
