### ISSUE TITLE
Bash autocompletion adds command description to completed line

### ISSUE THREAD

**Issue by averms** [spf13/cobra#1508]
This is pretty much #1443 except I think I know how to reproduce it. I'm using `podman` as the program because I was told (containers/podman#12005) it uses cobra.

1. Add `TAB: menu-complete` to `.inputrc`.
2. Open `bash` and type `podman --c<TAB>`
3. Note that `podman --cgroup-manager  (Cgroup manager to use ("cgroupfs"|"systemd"))` is added to the current line.
4. Press enter and get ``bash: syntax error near unexpected token `('``

It is fixed with `--no-descriptions`, which I don't mind using but I just wanted to make sure the bug is chronicled.

**Comment by marckhouzam** [comment]
I've posted a fix in #1509.
/cc @Luap99
