### ISSUE TITLE
Add kyverno in the list of projects that use cobra 

### ISSUE THREAD

**Issue by CIPHERTron** [spf13/cobra#1518]
Add Kyverno among the [list of projects](https://github.com/spf13/cobra/blob/master/projects_using_cobra.md) that uses cobra internally.

- Kyverno - A k-native policy management engine
- CNCF Sandbox project
- https://kyverno.io/
- https://github.com/kyverno/kyverno

**Comment by jpmcb** [comment]
Happy to accept a PR for this!
