### ISSUE TITLE
Why is validateRequiredFlags() executed after PreRun/PreRunE?

### ISSUE THREAD

**Issue by jewes** [spf13/cobra#1521]
My use case is I want to check a required parameter is valid or not in PreRun. However, validateRequiredFlags() is executed before PreRun, so I get an empty value of the required parameter during executing PreRun.

So why is validateRequiredFlags() executed after PreRun/PreRunE? Can it be moved after executing ValidateArgs()? See related code below.

```
	if err := c.ValidateArgs(argWoFlags); err != nil {
		return err
	}
        
	for p := c; p != nil; p = p.Parent() {
		if p.PersistentPreRunE != nil {
			if err := p.PersistentPreRunE(c, argWoFlags); err != nil {
				return err
			}
			break
		} else if p.PersistentPreRun != nil {
			p.PersistentPreRun(c, argWoFlags)
			break
		}
	}
	if c.PreRunE != nil {
		if err := c.PreRunE(c, argWoFlags); err != nil {
			return err
		}
	} else if c.PreRun != nil {
		c.PreRun(c, argWoFlags)
	}

	if err := c.validateRequiredFlags(); err != nil {
		return err
	}
	if c.RunE != nil {
		if err := c.RunE(c, argWoFlags); err != nil {
			return err
		}
	} else {
		c.Run(c, argWoFlags)
	}
```

**Comment by jewes** [comment]
> Hi @jewes. I am having trouble understanding what is not working in your case. Why would an early validation of flags help?
> 
> Either way you may be interested in #700

#700 is exactly the same enhancement I was looking for.

**Comment by johnSchnake** [comment]
I think this should just be closed as a won't do. I'll leave open for a while longer if people want to continue the discussion though.

https://github.com/spf13/cobra/pull/700#issuecomment-1040763620
