### ISSUE TITLE
Why do these two commands use different capitalization

### ISSUE THREAD

**Issue by vaptu** [spf13/cobra#1531]
https://github.com/spf13/cobra/blob/d2c0cb310d527ce26e8a173aa0fbc901e5ce8780/completions.go#L602

https://github.com/spf13/cobra/blob/de187e874d1ca382320088f8f6d76333408e5c2e/command.go#L1080

**Comment by marckhouzam** [comment]
Duplicate of #1458 
Being fixed by #1455

**Comment by vaptu** [comment]
thanks
