### ISSUE TITLE
ZSH completions did not work due to incorrect .zshrc configuration

### ISSUE THREAD

**Issue by benjaminclauss** [spf13/cobra#1534]
This may not be an _actual_ issue but I figure:
1. Documentation and/or instructions could _maybe_ be improved.
2. Otherwise, this issue can serve as documentation and/or help others.

I upgraded Cobra to [v1.2.1](https://github.com/spf13/cobra/releases/tag/v1.2.1) to get completions automatically (as part of [v1.2.0](https://github.com/spf13/cobra/releases/tag/v1.2.0)).

I built my binary (e.g. `tool`).
I followed the instructions provided in `tool completion zsh -h`.

```
Generate the autocompletion script for the zsh shell.

If shell completion is not already enabled in your environment you will need
to enable it.  You can execute the following once:

$ echo "autoload -U compinit; compinit" >> ~/.zshrc

To load completions for every new session, execute once:
# Linux:
$ tool completion zsh > "${fpath[1]}/_tool"
# macOS:
$ tool completion zsh > /usr/local/share/zsh/site-functions/_tool

You will need to start a new shell for this setup to take effect.
```

After starting a new shell, I _expected_ completions to work but they would not.
For example, I would `tool st[tab][tab]` expecting subcommands to appear.

This was unexpected. Further, running `tool __complete st` would display the subcommands as expected.

```
❯ ./tool __complete st
start        Start something
status      Get the status of something
stop	        Stop something
```

At this point, I was a bit lost until I reviewed my `~/.zshrc`. For context, I have [ohmyzsh](https://github.com/ohmyzsh/ohmyzsh) installed.

I noted I had the following plugins:

```
# ZSH config

plugins=(
  git
  ...
  zsh-autosuggestions
  zsh-syntax-highlighting
  ...
)

# more ZSH config
```

It turns out, [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) should have been configured at the end of my `~/.zshrc` per the [FAQ](https://github.com/zsh-users/zsh-syntax-highlighting#why-must-zsh-syntax-highlightingzsh-be-sourced-at-the-end-of-the-zshrc-file). However, this is surprisingly not in the [install instructions](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md#oh-my-zsh).

I will open an [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) issue but perhaps Cobra could also benefit from emphasizing the importance of a correct `.zshrc` configuration.

**Comment by marckhouzam** [comment]
Coincidentally #1534 just mentioned an issue with completion and `zsh-syntax-highlighting`.  Maybe that is your problem?

**Comment by johnSchnake** [comment]
Going to close as motivated by #1600 ; it seems this is just duplicate of #1529 as well which has some extra context/conversation for those interested. Please reopen if you feel feel necessary.
