### ISSUE TITLE
root command + sub command both take arguments

### ISSUE THREAD

**Issue by AbbyDeng** [spf13/cobra#1535]
👋🏻 hi, i have read the `args_test.go` file here https://github.com/spf13/cobra/blob/master/args_test.go

i'm wondering if you have tested a case like this:
```
root $arg1 child $arg2
```
i'm trying to implement something like this but don't know what should i set for `root.Args` 
i now set the `Args` of `root` as `Args: cobra.MaximumNArgs(1)` but it always shows
```
Error: accepts at most 1 arg(s), received 3.
```
thank you! ❤️

**Comment by marckhouzam** [comment]
Hi @AbbyDeng. I don't think this is possible exactly.  I believe a similar question was asked with an answer in #1378, which I hope can help you.

**Comment by AbbyDeng** [comment]
thank you so much @marckhouzam

**Comment by marckhouzam** [comment]
Would you mind closing this issue @AbbyDeng if you found what you needed in #1378 ?

**Comment by AbbyDeng** [comment]
sure thing! :)
