### ISSUE TITLE
Upgrade viper to remove CVE found in indeirect dependencies

### ISSUE THREAD

**Issue by cboitel** [spf13/cobra#1538]
This project references viper 1.8.1 which was direct using  github.com/bketelsen/crypt v0.0.4 which was imported older versions leading to import github.com/miekg/dns v1.0.14 which suffers a CVE fixed since version 1.1.25 (latest version is v1.1.43).

Upgrading to viper 1.9.0 would remove the dependency to github.com/bketelsen/crypt and the indirectly imported dns module version suffering the CVE.

**Comment by jpmcb** [comment]
Closed by dependabot https://github.com/spf13/cobra/pull/1554

**Comment by umarcor** [comment]
Actually, not fixed. viper 1.9.0 does still depend on `github.com/miekg/dns v1.0.14`. See https://github.com/spf13/cobra/blob/master/go.sum#L207 and  #1539. We need viper maintainers to publish a new release in order to fix this issue.

**Comment by cboitel** [comment]
By closing this issue, you send a message "security isn't an issue in this project and anyone concerned by it shouldn't rely on us".

I wouldn't close issue unless you really mean to leave your product with an embedded CVE from dependencies you reference and use to provide. If so, we would all know that this project is not worth relying on since security isn't a concern. 

I was expecting to open issues at projects used to request fixes and bump the newer version when ready. At last, if some dependency does not intend to fix the issue, you should remove it by using another one or fork/fix it.

I did open an issue at viper: https://github.com/spf13/viper/issues/1257

**Comment by jpmcb** [comment]
Thanks for the heads up! Jumped the gun here!! Now that we have dependabot enabled, we should get that upgrade as soon as Viper pushes a new release.

**Comment by cboitel** [comment]
Bumping so issue doesn't get closed too early

**Comment by jpmcb** [comment]
Viper dependency was removed as part of a wider effort to reduce `cobra`'s dependency surface. The `cobra-cli` is now at https://github.com/spf13/cobra-cli

Ref: https://github.com/spf13/cobra/issues/1597

Go mod ref:
https://github.com/spf13/cobra/blob/9d15fe657a500065fb343f8a9d1474582147f828/go.mod#L5-L10
