### ISSUE TITLE
Interactive PersistentPreRun deadlocks CLI on completion

### ISSUE THREAD

**Issue by Airblader** [spf13/cobra#1543]
This isn't necessarily an actionable bug report as I believe it is behaving as intended. However, I wanted to share an issue I ran into and the solution I am using.

We register a `PersistentPreRun` function on the root command. In there, we check whether the configuration file for our CLI exists, and start an interactive prompt (using `promptui`) to ask the user whether they want to create a configuration. It looks something like this (though I left out some things for brevity, like not executing this for the `help` command):

```
cmd.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
	if configPath, ok := GetConfigPath(); !ok {
		createConfigPrompt := promptui.Prompt{
			Label:     "…",
			IsConfirm: true,
		}

		if _, err := createConfigPrompt.Run(); err != nil {
			return nil
		}

		if err := CreateDefaultConfig(); err != nil {
			return err
		}
	}

	return nil
}
```

The problem is, however, that this function also runs when auto-completing a command in the shell. However, this essentially "deadlocks" the CLI as the interactive prompt isn't shown, but does block further input, and the only way out is Ctrl+C.

The solution we came up with is to not run this function if we detect that we are within the auto-completion, which is internally represented as a "secret command":

```
cmd.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
	subCmd, _, _ := cmd.Find(args)
	if subCmd.Name() == cobra.ShellCompRequestCmd {
		return nil
	}

        // …
}
```

**Comment by Airblader** [comment]
I'm closing this as I only created it for documentation purposes and do not believe there to be an actual issue.

**Comment by marckhouzam** [comment]
@Airblader Thanks for helping the community like this!
I agree that your approach to solve your problem is probably the best one and I've seen other projects do something similar.

One improvement I think you can make is to consider that Cobra already tells `PersistentPreRun` what command is being called.  I haven't confirmed by testing but I believe you can then simply do:
```

cmd.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
	cmd.Name() == cobra.ShellCompRequestCmd {
		return nil
	}

        // …
}
```

**Comment by Airblader** [comment]
Thanks! Indeed I noticed this afterwards too and already made that change but forgot to edit this here.
