### ISSUE TITLE
But how achieve this with string value as people may need to consider 3 options :

### ISSUE THREAD

**Issue by sonali85** [spf13/cobra#1546]
But how achieve this with string value as people may need to consider 3 options :
without flag which should take default value
with flag no value
with flag string value

cmd.Flags().StringVarP(&flag, "flag", "f", "", "info")
in this all should work
1. cmd --flag "value"
2. cmd --flag
3. cmd. (without flag)

In my case 1st and 3rd is working but for 2nd it throws the error:
fatal error: flag needs an argument: 'f' in -f
here I wanted to consider all 3 conditions

**Comment by sonali85** [comment]
@umarcor

**Comment by umarcor** [comment]
@sonali85, cobra uses [spf13/pflag](https://github.com/spf13/pflag) for dealing with flags. I think that this issue is related to pflag, not to cobra.

**Comment by sonali85** [comment]
@umarcor ,
Thank you so much for the quick response. Was very helpful and informative

**Comment by movsb** [comment]
A flag without an argument is for boolean flags only. Neither [spf13/pflag](https://github.com/spf13/pflag) nor [pkg/flag](https://pkg.go.dev/flag) will allow you doing that.

**Comment by sonali85** [comment]
.
