### ISSUE TITLE
[Question] How to make arguments show up in usage text?

### ISSUE THREAD

**Issue by drognisep** [spf13/cobra#1564]
I've looked around to see if this is addressed elsewhere. I know how to require a non-zero number of arguments, but I'm not seeing a way to make an argument requirement show up in the generated usage documentation.

For example, let's say I create a command called `cli`, add a sub-command `dothings`, and set `dothings`'s `Args` field to require arguments with something like `cobra.MinimumNArgs(1)` or a validation function. How do I then get something like the following to show up when the `--help` flag is used?

```
$ cli dothings --help
Documentation for dothings.

Usage:
  cli dothings [flags] args <==== This

Flags:
  -h, --help                 help for dothings
```

It would be really great if I could set the text there too to something like "filesToParse" to make it clear what sort of arguments are needed. I'm sure I'm just missing something obvious, so any clarification would be great. Thanks! :)

**Comment by drognisep** [comment]
@spf13 
 I'm sure you're busy writing all the code, so when you get a moment would you mind taking a look at this, please? Thanks for putting such an awesome lib together! :)

**Comment by marckhouzam** [comment]
Hi @drognisep.  I believe the way to do what you want is to create your own help format.  I think you can do that with the `SetUsageFunc()`:
https://github.com/spf13/cobra/blob/178edbb247f35e466578211dcf5f4892dbbd369b/command.go#L266

**Comment by drognisep** [comment]
> Hi @drognisep. I believe the way to do what you want is to create your own help format. I think you can do that with the `SetUsageFunc()`:
> 
> https://github.com/spf13/cobra/blob/178edbb247f35e466578211dcf5f4892dbbd369b/command.go#L266

Are you saying I'd have to rewrite the usage info from scratch? Doesn't that mean I could no longer benefit from the generated `--help` docs? I hope I'm just missing something here.

**Comment by drognisep** [comment]
Well, I guess I could set a usage template based on [this](https://github.com/spf13/cobra/blob/178edbb247f35e466578211dcf5f4892dbbd369b/command.go#L491).

**Comment by nataliet57** [comment]
Hi @drognisep were you able to find a solution?

**Comment by drognisep** [comment]
> Hi @drognisep were you able to find a solution?

Hi, @nataliet57 ! In a more recent project I ended up setting the usage function on the flag set to include the args, and using the flag set's `FlagUsages` method to get the generated flag descriptions.

https://github.com/drognisep/certserver/blob/main/app/certcli/cacert.go

Cobra turns out to be a bit more than I need in most cases, so the example just uses the excellent pflag lib. I don't know off hand if the same methods are exposed in a Cobra context, but I hope it helps. 🤞

**Comment by steezeburger** [comment]
For anyone finding this in the future, you can accomplish this by updating your `Use` passed into the Cobra command

```
var getBalanceCmd = &cobra.Command{
	Use:   "get-balance [address]",
	Short: "Retrieves and prints the balance of an account.",
	Args:  cobra.MatchAll(cobra.ExactArgs(1), cobra.OnlyValidArgs),
	Run:   runGetBalance,
}
```
outputs like
```
Retrieves and prints the balance of an account.

Usage:
  astria-cli sequencer get-balance [address] [flags]

Flags:
  -h, --help         help for get-balance
      --url string   The URL of the sequencer to retrieve the balance from. (default "http://127.0.0.1:26657")

```

**Comment by fearnliu** [comment]
> For anyone finding this in the future, you can accomplish this by updating your `Use` passed into the Cobra command
> 
> ```
> var getBalanceCmd = &cobra.Command{
> 	Use:   "get-balance [address]",
> 	Short: "Retrieves and prints the balance of an account.",
> 	Args:  cobra.MatchAll(cobra.ExactArgs(1), cobra.OnlyValidArgs),
> 	Run:   runGetBalance,
> }
> ```
> 
> outputs like
> 
> ```
> Retrieves and prints the balance of an account.
> 
> Usage:
>   astria-cli sequencer get-balance [address] [flags]
> 
> Flags:
>   -h, --help         help for get-balance
>       --url string   The URL of the sequencer to retrieve the balance from. (default "http://127.0.0.1:26657")
> ```

And I found this in the source code:
<img width="920" alt="image" src="https://github.com/spf13/cobra/assets/16191685/d04be637-211f-4bd8-9b34-3269b844684c">
