### ISSUE TITLE
Is there a way to run the application in background?

### ISSUE THREAD

**Issue by pplmx** [spf13/cobra#1573]
If a golang application is to start a TCP server. I want to use cobra to provide `start`, `stop`, `restart`.
## Question:
	how to start this application in background by using cobra???
Could anyone give me some help?

## FYI
Here is my trial. The following logic can start TCP server, but not in background.
![image](https://user-images.githubusercontent.com/26994103/147336033-806cb53a-bbc1-4281-8cad-82378e25242f.png)

**Comment by umarcor** [comment]
What about addding ` &` when you run the command?

**Comment by pplmx** [comment]
It's okay. But doesn't cobra provide a way to run in the background?

**Comment by umarcor** [comment]
The foreground and the background are concepts that the caller of a program can deal with. The program itself cannot.

**Comment by pplmx** [comment]
Thanks for your reply. :)
