### ISSUE TITLE
Command.Context() returns nil instead of context.Background()

### ISSUE THREAD

**Issue by katexochen** [spf13/cobra#1578]
Documentation of the [Context() function](https://pkg.go.dev/github.com/spf13/cobra#Command.Context) states a `context.Background()` is returned, but the returned value is `nil`.

> Context returns underlying command context. If command wasn't executed with ExecuteContext Context **returns Background context**. 

```go
cmd := &cobra.Command{}
fmt.Printf("context is %v", cmd.Context()) // returns "context is <nil>"
```
[Go Playground](https://go.dev/play/p/C8jaQ-uQgEv)

It would be really nice if this could return a `context.Background()`, so functions that take a `Command` as parameter and use the context from that command could be tested. There is also no possibility to set this context manually right now.

**Comment by marckhouzam** [comment]
For info, setting the context manually has just been added in #1551
