### ISSUE TITLE
Test cobra cmd arguments

### ISSUE THREAD

**Issue by JCzz** [spf13/cobra#1580]
Hi

I am trying to test Cobra parsing in arguments in tests:

Note: `= GetCmd()` just return *cobra.Command

```
func TestSnippets(t *testing.T) {
	os.Args = append(os.Args, "snip", "create", "node --name='test'")
	myCmd := GetCmd)
	if err := myCmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
```

I get error: `unknown command "^\\QTestSnippets\\E$" for "root"`

Do you know why?

**Comment by marckhouzam** [comment]
I don't believe you should set `os.Args` but probably should use `command.SetArgs()`. You can look at cobra's `executeCommandC()` function to see an example of this.

**Comment by JCzz** [comment]
Thanks @marckhouzam
