### ISSUE TITLE
Don't touch my licence

### ISSUE THREAD

**Issue by jtagcat** [spf13/cobra#1596]
It'd be neat if cobra didn't touch an already existing LICENCE file. I have to revert changes every time I use cobra.

**Comment by jpmcb** [comment]
Hi @jtagcat - thanks for opening an issue.

Can you provide a few commands and user flow to reproduce the issue? Thanks much!

**Comment by jtagcat** [comment]
```sh
$ go get -u github.com/spf13/cobra
$ go version
go version go1.17.5 linux/amd64
$ ls ~/.cobra.yaml
"/home/jc/.cobra.yaml": No such file or directory (os error 2)
$ cd $(mktemp -d)
$ go mod init x
go: creating new go.mod: module x
$ cp /f/git/jc/git-id/LICENSE .
$ head -n2 LICENSE
                    GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007
$ cobra init
Your Cobra application is ready at
/tmp/tmp.m6R0lXbzOa
$ cat LICENSE # empty
```

**Comment by jtagcat** [comment]
Additionally, it'd be nice if I could opt-out of the in-each-file header, if that's ok.

**Comment by jpmcb** [comment]
Hmmm I see. So given an existing project with an existing licenses, you _don't_ want cobra to overwrite the license. I think that seems reasonable and we can definitely do that with a flag.

And for opting out of the in-file headers, I think we could also have a flag that does that.

**Comment by harjyotbagga** [comment]
I would like to work on this issue. Can you please assign this to me?

**Comment by jtagcat** [comment]
ah, the notification abuse bot has arrived!! /enthusiastic
