### ISSUE TITLE
🧹 Cleaning up issue backlog

### ISSUE THREAD

**Issue by johnSchnake** [spf13/cobra#1600]
We are aware of the fact that the backlog has grown and we want to work towards a better state.

To that end there will be an effort to do two thing:
 - tag issues with useful tags that will help triage
 - close issues that are no longer relevant

There are a number of issues that have been marked stale that may or may not really need addressed. As such, as we cleanup let's just make sure users are aware that if we closed their issue without properly addressing it that it was just an oversight in our effort to better support all the issues and that they are welcome to reopen it.

Creating this issue to reference in these issues that we close to help document the motivation for closure.

**Comment by umarcor** [comment]
@krader1961, although I do understand and share your frustration, please give @johnSchnake a break. During the last 1-2y @jpmcb has been maintaining this repo alone; and he could only focus on it a few days every 2-3 months. @johnSchnake arrived less than a week ago, and he already cleaned up more than 20 issues/PRs. Since he is not completely familiar with the codebase and the community yet, he is focusing on the most obvious stuff first, in order to reduce the volume. It's sensible that he focuses on "removing unnecessary/outdated stuff" rather than "merging content to master" in a project he just stepped into.

**Comment by jpmcb** [comment]
Hi @krader1961 - thanks for your feedback.

We all know that Cobra is an extremely important project used by thousands of devs around the world, supporting major systems & software like `kubernetes`, GitHub, Grafana, and many many more.

I am fully aware of how stale and poorly groomed the PRs are.

> @jpmcb has been maintaining this repo alone; and he could only focus on it a few days every 2-3 months.

@umarcor is right; this project has gone largely unmaintained outside of the little time I _can_ dedicate to getting releases out. Thankfully, Cobra is _extremely_ stable and doesn't require alot of consistent code changes anyways.

Please understand, _no one pays any of us for the work or time we put into Cobra_. This is _all best effort_, driven by the _community_. So please be patient and understand that we are attempting to make things better, easier for the collaborators to maintain, and generally better for the community.

I first suggested that we open an issue letting the community know we would be doing some cleanup. I am in full support of @johnSchnake going through and doing this. 

We are planning to do the same for PRs and I'm planning to triage many of them myself.

**Comment by johnSchnake** [comment]
No worries, I appreciate the support and also agree with the point @krader1961 is making. Luckily I am not the only maintainer and so we can focus on different areas. Someone with a better understanding of the norms for merging PRs on this repo can take the lead with PRs   while I'm continuing to engage with the issues.

Working on the backlog facilitates:
 - proper tagging of issues so other people can more easily pickup what else needs done
 - familiarizes myself with the ongoing types of issues the repo has
 - raises the general level of engagement
 - better allows myself and other maintainers to identify where efforts are best spent

Again, I don't disagree with the point that PRs are important and shouldn't have been left this long. The goal is for us to work to get both issues and PRs down; this particular issue is just focused on the former.

**Comment by johnSchnake** [comment]
Every issue has been tagged and there are no more issues with the legacy 'stale' tag. 🎉

Closing this!

We've gone from ~250 issues to 100 (exactly) once I close this one. I'd consider that a success.

**Comment by marckhouzam** [comment]
Thank you for the huge effort @johnSchnake, I'm sure the whole community appreciates, I know I do.
👏 👏 👏

**Comment by jpmcb** [comment]
Thank you for the incredible work done here! Big shout out to @johnSchnake - tons of help getting this cleaned up.
