### ISSUE TITLE
[Maintainers] Define a security policy

### ISSUE THREAD

**Issue by jpmcb** [spf13/cobra#1601]
Currently, we have no `SECURITY.md` or GitHub defined security policy.

This has led to issues being opened in the past that detail security vulnerabilities (usually that exist in dependent libraries, not cobra itself) without the maintainers being made aware first.

We should define a security policy, add it to a `SECURITY.md` file and update the GitHub security policy.

**Comment by umarcor** [comment]
For context:

https://github.com/spf13/cobra/blob/master/CONDUCT.md#deprecation
> Deprecation of Go versions or dependent packages will only occur in major releases. To reduce the change of this taking users by surprise, any large deprecation will be preceded by an announcement in the [#cobra slack channel](https://gophers.slack.com/archives/CD3LP1199) and an Issue on Github.

https://github.com/spf13/cobra/blob/master/CONDUCT.md#cve
> Maintainers will make every effort to release security patches in the case of a medium to high severity CVE directly impacting the library. The speed in which these patches reach a release is up to the discretion of the maintainers. A low severity CVE may be a lower priority than a high severity one.
