### ISSUE TITLE
Wrong value for a bool flag (flag false vs flag=false)

### ISSUE THREAD

**Issue by mtojek** [spf13/cobra#1606]
Hi Team,

I'm a bit confused with boolean flags. Consider the following code:

```go
package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

func main() {
	cmd := &cobra.Command{
		RunE: func(cmd *cobra.Command, args []string) error {
			b, err := cmd.Flags().GetBool("dry-run")
			fmt.Println(b, err)
			return err
		},
	}
	cmd.Flags().Bool("dry-run", true, "Dry-run mode")
	cmd.Execute()
}
```

Execute:

```
$ app --dry-run # 1
true <nil>
$ app --dry-run false # 2
true <nil>
$ app --dry-run=false # 3
false <nil>
```

Use case no. 1 is obvious, but use cases no. 2 and no. 3 should return the same result. Would you mind explaining if this is expected behavior? so that the `=` is necessary for this scenario?

Have a nice day!

**Comment by marckhouzam** [comment]
Thanks for the question @mtojek.

Boolean flags are a little different than other flags in the fact that they can be specified without a value.  So, if you do want to specify a value, you **must** use the `=` form.  In your example, `app --dry-run false` is not a valid format, you must use `app --dry-run=false`.

The reason behind that is that without the `=` form, it is not possible to tell the difference between a boolean flag without an argument and one with an argument.  Specifically, in you example 2 `app --dry-run false`, is `false` the value of the `--dry-run` flag, or is it an argument to the `app` command?  To solve this problem, the `=` must be used when specifying a value for a boolean flag.

**Comment by marckhouzam** [comment]
I'm going to go ahead and close this issue, but if you feel it was not answered properly, feel free to re-open.

**Comment by mtojek** [comment]
Hi @marckhouzam,

thanks for responding. I understand your explanation, but it is counterintuitive to me and error-prone. I understand that cobra follows the approach `--flag`/`--no-flag` instead of true/false, but maybe you can describe the use case in documentation?

**Comment by marckhouzam** [comment]
> I understand your explanation, but it is counterintuitive to me and error-prone. 

You are right that this can be confusing.  However, I believe that in practice this scenario is quite rare.  Users will either include a boolean flag or omit it, they normally won't include it with a value.

> I understand that cobra follows the approach `--flag`/`--no-flag` instead of true/false, but maybe you can describe the use case in documentation?

Sure, an improvement to the documentation is always good.  PRs welcomed.
