### ISSUE TITLE
Document how to test common flag parsing code

### ISSUE THREAD

**Issue by edmondo1984** [spf13/cobra#1607]
While I was able to find how to unit test a single Cobra command, I haven't figured out how to test that shared code for Cobra commands work correctly. Take the use case of a database connection service that might be useful for multiple commands: it is desireable to share it and to test it.

```go
cmd := &cobra.Command{} 
services.RegisterDatabaseServiceFlags(cmd)
cmd.SetArgs(some_args); 
myDatabase := services.CreateDatabaseService(cmd); 
```

However, when you try to change the args to test multiple scenarios, the code will always parse the default values of flags, since the SetArgs() call on the command just sets the internal variable. One option would be to modify the Run so to write to output the service struct and then perform assertions on the output.  Are there other alternatives, and what should be the best practice?

**Comment by edmondo1984** [comment]
I found out that the right command to invoke is ParseArgs. It actually works, maybe just worth documenting it?

**Comment by jpmcb** [comment]
Hi @edmondo1984 - thanks for raising this issue.

It probably is worth having some documentation that talks about how you can test commands. Can you provide a small snippet of what you found that works? And maybe we can turn it into some docs

**Comment by edmondo1984** [comment]
Hi @jpmcb I will submit a proposal for the documentation. I do have some other questions: is there a way to define conflicting flags and is there a way to define flags that have no default value? I think these are holes in the documentation as well
