### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by marckhouzam** [spf13/cobra#1611]
I suggest that we follow the wider git/github community trend and rename Cobra's 'master' branch to 'main'.
Renaming a branch is well handled by Github.  Github will even automatically redirect requests made to the old branch towards the new branch.  Details can be found here: https://github.com/github/renaming

The [helm](https://github.com/helm) organisation has renamed all its repos' main branches and it has been a very smooth effort.
 
How do the maintainers and community feel about that?

**Comment by jpmcb** [comment]
I 100% support this.

> Github will even automatically redirect requests made to the old branch towards the new branch. 

Oh wow, I remember doing this a few years back and there was quite a bit of pain since people had to update their local remote references.

I _think_ this is something that @spf13 will have to do by:
- [ ] Creating a `main` branch that mirrors `master`
- [ ] Set `main` as the default branch in the repository settings
- [ ] Delete `master` branch

**Comment by marckhouzam** [comment]
Actually it's all handled by GitHub now 😁
There's a setting that allows to change the name of the branch. It even warns users of the change and what to do when they land on the project page. I'll get screenshots a little later.

**Comment by marckhouzam** [comment]
I just did it on one of my repos, it took 20 seconds but it does require each local clone to be updated, but Github tells each user how to do it when they visit the projet page.  

Here is what I did: 
1- On the projet Github page go to `Settings -> Branches` and click the pencil on the top box to rename to `main`

![Screen Shot 2022-02-25 at 8 26 50 AM](https://user-images.githubusercontent.com/414402/155724164-c5106385-19d6-4cd9-963f-6efa19ee2af3.png)

2- When visiting the main project page Github tells each user how to fix their clone:

![Screen Shot 2022-02-25 at 8 28 18 AM](https://user-images.githubusercontent.com/414402/155724704-bee2864c-17d6-4642-8a86-411eb4da42c5.png)

@spf13 what do you think?

**Comment by spf13** [comment]
100% support this. I didn’t realize it was so easy to do now. I should do
it for all my projects. I’m on holiday now but will do it when I return.

**Comment by jpmcb** [comment]
> Please, do NOT do that.
That is not a rename, but the deletion and creation of a new branch.

Last time I did this (maybe early 2020?) there weren't great automated mechanism for doing this. So cool GitHub handles alot of this now! +1 for Marc's method 👏🏼

**Comment by marckhouzam** [comment]
Just waiting for @spf13 to have time to rename the branch

**Comment by spf13** [comment]
I just made this change. We are now "mained".

**Comment by spf13** [comment]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/173412/177892366-8f823256-5df7-4234-b4cd-1740a656beef.png">

**Comment by marckhouzam** [comment]
🎉🎉🎉

**Comment by marckhouzam** [comment]
I'll announce it on the #cobra slack channel.

**Comment by jpmcb** [comment]
Thanks Steve!!!
