### ISSUE TITLE
bash completion script created doesn't seem to work

### ISSUE THREAD

**Issue by nixomose** [spf13/cobra#1617]
I'd like to think I'm doing something wrong, but clearly you put a lot of effort into this and I don't see anybody else having this problem, so it's probably just me, but I'm not seeing what I'm doing wrong.

I've got my application, all the flags and commands work just as expected. When I run the bash completion creation script, it generates the script, but when I try and apply it, it gives me this error:

```
nixo@kmod3:~/git/go/nixomose/localblockdevice (master)$ ./lbd completion bash  > t
nixo@kmod3:~/git/go/nixomose/localblockdevice (master)$ . ./t
complete: usage: complete [-abcdefgjksuv] [-pr] [-DEI] [-o option] [-A action] [-G globpat] [-W wordlist]  [-F function] [-C command] [-X filterpat] [-P prefix] [-S suffix] [name ...]

```

the line in question is where it calls the complete command: 
```
if [[ $(type -t compopt) = "builtin" ]]; then
    complete -o default -F __start_
else
    complete -o default -o nospace -F __start_
fi

# ex: ts=4 sw=4 et filetype=sh
```
apparently it's supposed to have a parameter there on the end? I dunno.

any suggestions as to how to get this going would be appreciated. 

```
nixo@kmod3:~/git/go/nixomose/localblockdevice (master)$ lsb_release -a && uname -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
Linux kmod3 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by marckhouzam** [comment]
Hi @nixomose.

For some reason, the completion script is not getting a name for your program.  The line
```
complete -o default -F __start_
```
should actually be
```
complete -o default -F __start_lbd lbd
```
What do you set for the `Use` field of your root command?

**Comment by nixomose** [comment]
That is probably what I'm missing.  One moment.

**Comment by nixomose** [comment]
Yeah that was it. All working now.  Thanks.
