### ISSUE TITLE
Is it possible to remove error log output

### ISSUE THREAD

**Issue by fnoopv** [spf13/cobra#1631]
like this
![image](https://user-images.githubusercontent.com/24599198/158421460-492f7c95-dfba-4cea-93be-c27d6f90fb63.png)
The first line is the error message output by this package, can I disable or remove it,? I want to use the last line of my own defined error output

**Comment by johnSchnake** [comment]
Have you tried the `. SilenceErrors` and `.SilenceUsage` fields on the commands? https://chromium.googlesource.com/external/github.com/spf13/cobra/+/refs/heads/master/command.go#956

**Comment by fnoopv** [comment]
I didn't use these tags, thanks for your reply
