### ISSUE TITLE
Cannot set flagset to ExitOnError for command

### ISSUE THREAD

**Issue by tasherif-msft** [spf13/cobra#1633]
When creating a new command I'm unable to set the Flagset to `ExitOnError`
The setting to `ContinueOnError` causes cases where the return error code is 0 even though something has went wrong.

For example:
- Create a command with a persistent Flagset
- Line: https://github.com/spf13/cobra/blob/master/command.go#L1534 is eventually called
- If we run the command with an unsupported flag it will fail but the exit code will be 0 which is bad

**Comment by marckhouzam** [comment]
Maybe related to #582, #922, #1305, which is something we are having trouble fixing due to backwards-compatibility concerns.

@tasherif-msft can you provide a small example to reproduce the problem to better understand if this is the same or a different issue?

**Comment by tasherif-msft** [comment]
Hi @marckhouzam, yes it appears that this is a known issue then - I'm wondering is it not possible to create a new method that would accept this enum as a parameter when initializing the flatset?

**Comment by gapra-msft** [comment]
Hi @marckhouzam 

Here is a minimal repro 

https://go.dev/play/p/Ge_P9YLn_gO

If you run this command from the command line locally and run `echo $?` You should see the exit code set to 0.

**Comment by gapra-msft** [comment]
Hi @marckhouzam and @jpmcb,

I've created a draft PR of a possible solution to this problem. Could you take a look and see if it looks feasible? Then I can add some tests and open the PR. 

https://github.com/spf13/cobra/pull/1662
