### ISSUE TITLE
How to get order of different flags?

### ISSUE THREAD

**Issue by qsliu2017** [spf13/cobra#1637]
I'm developing a SQL tool. I want to repeat and combine file flags and command flags.

For instance, `mytool --file=1.sql --command=$SQL1 --file=2.sql --command=$SQL2` will execute `1.sql`, `$SQL1`, `2.sql`, and `$SQL2` as the same sequence as they're passed.

I use `Flags().StringSliceVarP()` to repeat single flag. But how can I combine and keep the order of `file` and `command` flags?

thanks!

**Comment by johnSchnake** [comment]
The string slice flags should just append to the slice so for each of the file/command flags they are in order.

I think what you're asking for though is to tell the difference between:
```
mytool --file=1.sql --command=$SQL1 --file=2.sql --command=$SQL2
```
and
```
mytool --file=1.sql --file=2.sql --command=$SQL1 --command=$SQL2
```

Is that correct? I would just ask whether or not that is really necessary; are you allowing a file without an associated command? Or a file with multiple commands?

If not, then I would just do validation that the slices are the same length then know that file[i] runs command[i].

If you can have 0 or N commands per file its harder. I'm guessing you could go through and iterate over the os.Args yourself but that would be a pain. Have you considered modifying the flag to take both?

E.g. a custom flag type of the form `--run=file:$CMD1,$CMD2`. You would just provide a custom type which satisfies the flag interface and then you'd be able to just have an object back it so you could easily refer to `flagValue.File` or `flagValue.Commands`.
