### ISSUE TITLE
use variable as Use in struct Command not work

### ISSUE THREAD

**Issue by shangc1016** [spf13/cobra#1641]
`var runCmd *cobra.Command = &cobra.Command{
	Use: "run",
}`

`var runCmd *cobra.Command = &cobra.Command{
	Use: utils.Name,
}
`

for above, the first work properly.
but the second doesn't work,  there's even no help describe use `go run . --help`,
and `Short` also face this problem.

**Comment by marckhouzam** [comment]
Hi @shangc1016.  Thanks for the report.

I don't see any reason for a difference in behaviour between the first and second example (assuming `utils.Name` is a non-empty string.

Can you provide a working example to reproduce the issue?

**Comment by shangc1016** [comment]
> 

Thanks for your reply. I check my code again, and found that i misuse the `init` function, i initialize the variable `utils.Name` in non-init function, so the variable (`utils.Name`) is used before it's initialize.

**Comment by marckhouzam** [comment]
Great.  I'm glad you found your problem.
