### ISSUE TITLE
Md docs generation flag for disabling the version number

### ISSUE THREAD

**Issue by andruwm** [spf13/cobra#1648]
The use case here is to optionally reduce git noise when docs `md` docs are checked in to git. Currently, large CLI applications may end up with dozens of documentation files to check in that have only a version number changed. Ideally, there would be a solution similar [to this](https://github.com/spf13/cobra/blob/master/doc/README.md#options) `DisableAutoGenTag` flag. Perhaps `DisableAutoGenVersion`.

**Comment by marckhouzam** [comment]
Thanks @andruwm.  Could you clarify what version you are referring to?
In the examples I found I see a date, not a version:
```
###### Auto generated by spf13/cobra on 24-Jan-2022
```
Is that what you mean?

**Comment by andruwm** [comment]
As it turns out, we had some internal dynamic descriptions that included the version number. This description was leaking into the documentation generation. Closing this issue!
