### ISSUE TITLE
am a complete biginner to coding, 

### ISSUE THREAD

**Issue by Kendores** [spf13/cobra#1650]
hello good day, am a complete beginner to programing and was following a tutorial instruction of a site, and then i ran into an issue when i tried these line of code below.
  //  go install github.com/spf13/cobra/cobra@latest
and get these issue.. 
// go: github.com/spf13/cobra/cobra@latest: module github.com/spf13/cobra@latest found (v1.4.0), but does not contain package github.com/spf13/cobra/cobra

**Comment by marckhouzam** [comment]
Hi @Kendores and welcome to programming 😉 
The Cobra command-line tool has recently moved to https://github.com/spf13/cobra-cli
You can read how to install it there but in short:
```
go install github.com/spf13/cobra-cli@latest
```
There are different tutorials on-line that are independent from the project and that, understandably, haven't been updated with this change.

**Comment by johnSchnake** [comment]
You may want to check what version of `go` you are using. If it is older it may try and do something different with `go install`?

**Comment by johnSchnake** [comment]
Just based on the time and lack of activity I'm going to close this and assume the issue got resolved; feel free to reopen if you feel there is more to discuss.
