### ISSUE TITLE
How to auto complete hidden flags?

### ISSUE THREAD

**Issue by hexlify** [spf13/cobra#1653]
My root command has a lot of persistent flags that are bound to viper config storage. All of them are used for overriding default app settings and therefore aren't necessary. Due to enormous help output I decided to mark all of them as hidden. 

Initial config looks like this:

```go
func AddConfigFlags(Cmd *cobra.Command) {
	cfgFlags := &pflag.FlagSet{}
	for k := range AllowedSettings {
		flagName := toFlagName(k)
		cfgFlags.String(flagName, "", "")
		_ = viper.BindPFlag(k, cfgFlags.Lookup(flagName))
	}
	cfgFlags.VisitAll(func(f *pflag.Flag) { f.Hidden = true })
	Cmd.PersistentFlags().AddFlagSet(cfgFlags)
}
```

Now I'm about to implement shell auto-completion but as #313 pr stated completion for hidden flags doesn't work. Any suggestions how to keep my help message short and enable auto-completion for these flags?

I'm thinking about `ValidArgsFunction` but it looks like it's not an option

**Comment by marckhouzam** [comment]
Hi @hexlify.  I don't think what you are trying to do is simple with the current implementation.
You could use `ValidArgsFunction` but you would need to set `DisableFlagParsing = true` for `ValidArgsFunction` to be called for flag names, but that would require you to do your own flag parsing (using Cobra functions, but still).

It may be simpler to take the opposite approach and to customize the help template.  Cobra allows you to customize the help message and you could then avoid printing your configuration flags, while keeping them unhidden, so that the completion logic would show them.

One thing to consider is that if you feel the help message gets too big when you have all your flags, then wouldn't the list of flags shown by the  completion choices also be too big?  But probably what makes it better for completions is that the user can start typing a prefix and shorten the list?

**Comment by hexlify** [comment]
Hi thanks for response.

About too many completion choices. Both bash and zsh have some kind of "protection" via shell interaction: `Display all 131 possibilities? (y or n)`. I often get in this situation while tabbing in a directory with too many files. Also, you can always shorten this list by typing. So I think it's quite user-friendly

Eventually I come up with this solution

I mark my global config flags via `Annotations` field. Now, initial config function looks like this:
```go
func AddConfigFlags(Cmd *cobra.Command) {
        cfgFlags := &pflag.FlagSet{}
	for k := range AllowedSettings {
		flagName := toFlagName(k)
		cfgFlags.String(flagName, "", "")
		_ = viper.BindPFlag(k, cfgFlags.Lookup(flagName))
	}
	cfgFlags.VisitAll(func(f *pflag.Flag) {
		if f.Annotations == nil {
			f.Annotations = map[string][]string{}
		}
		f.Annotations[ConfigFlagAnnotation] = []string{"true"}
	})
	Cmd.PersistentFlags().AddFlagSet(cfgFlags)
}
```
Then I introduced custom command type with method that filters out global config flags
```go
type command struct {
	*cobra.Command
}

// HasAvailableInheritedNoConfigFlags is used by usage template
func (c *command) HasAvailableInheritedNoConfigFlags() bool {
	return c.InheritedNoConfigFlags().HasAvailableFlags()
}

// InheritedNoConfigFlags is used by usage template
func (c *command) InheritedNoConfigFlags() *pflag.FlagSet {
	return filterOutConfigFlags(c.Name(), c.InheritedFlags())
}

func filterOutConfigFlags(name string, f *pflag.FlagSet) *pflag.FlagSet {
	res := pflag.NewFlagSet(name, pflag.ContinueOnError)

	f.VisitAll(func(f *pflag.Flag) {
		if _, ok := f.Annotations[internal.ConfigFlagAnnotation]; !ok {
			res.AddFlag(f)
		}
	})

	return res
}
```
And finally my custom usage func
```go
// UsageFunc copies default behavior of cobra.Command.UsageFunc() with only one difference:
// template rendering use command object
func UsageFunc(c *cobra.Command) error {
	t := template.New("top")
	t.Funcs(templateFuncs)
	template.Must(t.Parse(c.UsageTemplate()))
	err := t.Execute(c.OutOrStderr(), &command{c}) // data is our custom command object
	if err != nil {
		c.PrintErrln(err)
	}
	return err
}
```

Now both help and usage messages are short and easy to read

**Comment by hexlify** [comment]
Would like to see a solution that allows to customize whether flag should appear in shell completion and in help/usage message separately because current solution seems hacky

**Comment by Luap99** [comment]
I have the exact opposite use case in podman. We show the flags in help but do not want to get persistent flags to be completed on subcommands.

This is what I ended up doing: https://github.com/containers/podman/blob/6a9c21c4565a9c7ebe5c11bf4152a80cfa4398dc/cmd/podman/root.go#L194-L211

The basic idea is that you add a persistent pre run function and catch if the hidden completion commands is called. Then you just loop over the flags and set hidden to true/false depending on what you want.

**Comment by hexlify** [comment]
@Luap99 thanks for respond. Your solution sounds easier to implement

**Comment by hexlify** [comment]
Solution was found, closing issue
