### ISSUE TITLE
add flags with --

### ISSUE THREAD

**Issue by andycol** [spf13/cobra#1655]
I dont seem to be able to add flags using --
example i can add a flag called "full" with cobra add full
but if i want it to be -- full i cant add it with cobra add --full
Is there a way to allow flags to be run with --

**Comment by johnSchnake** [comment]
Can you give a concrete, reproducible example?

When you add a flag, the long form of the flag is always used with the `--long` format. If you specify the flag with a long and short flag (e.g. with the `StringP` instead of `String` method), only then do you get the single hyphen form like `-l`

**Comment by andycol** [comment]
so example i have

```var fullCmd = &cobra.Command{
	Use:   "full",
	Short: "Full setup",
	Long:  `A Full software setup.`,
	Run: func(cmd *cobra.Command, args []string) {
```
What i want to achieve is that instead of running go run main.go full i want to run go run main.go --full

**Comment by andycol** [comment]
Yes that answers the question, i will give it a go.
The reason i want to do this is i am in the process of migrating some old bash scripts into Golang and most of them ran with flags like
./install --full
./install --web-only

that kind of thing

**Comment by johnSchnake** [comment]
Yea, in that case I would make a series of flags and have the logic just switch on which flags are set and then invoke the right logic.

If you want you can still create the commands and just invoke the command explicitly as needed (e.g. `return fullInstallCmd.Execute()`)

Good luck and thanks for the question.
