### ISSUE TITLE
Godoc comment for ArgsLenAtDash

### ISSUE THREAD

**Issue by siddharthist** [spf13/cobra#166]
Hey there, I was reading through the Godoc for this project when I stumbled upon ArgsLenAtDash. It sounds like it might be useful for me, but I'm at a loss as to what it is. Would you mind explaining it to me?

My second thought is that it might be helpful for folks in the future to have a Godoc comment to explain what this function does. I could write a PR if that's easiest, once I understand the purpose of this function.

**Comment by eparis** [comment]
Yeah, the godocs are pretty terrible. Please help  :) 

| Command  | ArgsLenAtDash |
| ------------- | ------------- |
| `./cmd subcmd arg1 arg2 -- arg3 arg4` | 2  |
| `./cmd subcmd -- arg1 arg2 arg3 arg4` | 0 |
| `./cmd subcmd arg1 arg2 arg3 arg4` | -1 |

**Comment by eparis** [comment]
Note: this actually comes from the pflag FlagSet() so a better comment there, or a pointer there might also make good sense.

**Comment by zchenyu** [comment]
The current doc: "ArgsLenAtDash will return the length of f.Args at the moment when a -- was found during arg parsing."
still isn't super clear.

Is it accurate to say that it's the number of positional arguments found before the `--` ? and `-1` if no `--` is found ?
