### ISSUE TITLE
ZSH completions parse directive and debug line removal incorrectly

### ISSUE THREAD

**Issue by burmanm** [spf13/cobra#1667]
The ZSH completion currently tries to parse the directive "0:" from last line of the output text, however this isn't valid since this data is actually on the second to last line and the last line has more information which directive was output. The output ends like this:

```
:4
Completion ended with directive: ShellCompDirectiveNoFileComp
```

The failure to parse the directive correctly causes the error code never to be parsed correctly and the output always has these two extra lines that shouldn't be there.

**Comment by marckhouzam** [comment]
Hi @burmanm and thanks for the report.  I can understand the confusion with the last line you mention.
That line ("Completion ended with directive...") is printed on stderr which is ignored by the completion shell scripts.

The problem in your case is probably that `kubecm` redirects stderr to stdout, which will break the shell completion system.
This has happened to others before 😄.  
I believe this happens here: https://github.com/sunny0826/kubecm/blob/ba2a5393435edb9008eb712cc82e3194725bd1c2/cmd/root.go#L53
The `SetOutput()` function sets stderr and stdout to point to the same place.  That function is deprecated in favor of the two functions `SetOut()` and `SetErr()` as you can see here: https://github.com/spf13/cobra/blob/master/command.go#L250-L268

If you really want to have stderr print to stdout, then you need to change it just for the `__complete` command within a `PersistentPreRun`
 
You can see some documentation about this here: https://github.com/spf13/cobra/blob/master/shell_completions.md#debugging
Making this difference between stderr and stdout for shell completion allows to print debugging information to stderr without breaking the completion scripts.

I'm going to go ahead and close this but feel free to re-open if I misunderstood your situation.
