### ISSUE TITLE
Cobra-Cli init Error

### ISSUE THREAD

**Issue by aleite31** [spf13/cobra#1669]
Go version : 1.18.1

Error using cobra-cli ini :  Error: invalid character '{' after top-level value

**Comment by marckhouzam** [comment]
Thanks for the report @aleite31.  The cobra-cli has its own repository at https://github.com/spf13/cobra-cli.
Could you open your issue over there and provide the steps to reproduce your problem?

**Comment by aleite31** [comment]
Thanks !!
