### ISSUE TITLE
MarkFlagsRequiredTogether Is gone with v1.4.0

### ISSUE THREAD

**Issue by abdulrabbani00** [spf13/cobra#1671]
Perhaps this function was gone even beforehand. A few questions:
* Is there a reason it has been removed? 
* Can we add it back?

You guys might also want to update the [Readme](https://github.com/spf13/cobra/blob/master/user_guide.md#flag-groups)

**Comment by marckhouzam** [comment]
It is nice to already see interest  in the `MarkFlagsRequiredTogether()` @abdulrabbani00 !
The feature was not removed, it hasn't been released yet 😄 
It will be available in Cobra v1.5 which should be happening in the near future.

**Comment by abdulrabbani00** [comment]
This is absolutely hilarious 🤣🤣🤣🤣 thank you. I can't wait for this new feature 😁

**Comment by omani** [comment]
hi guys. I need this feature. can we release now? :D
