### ISSUE TITLE
Ability to generate docs with a folder structure that matches the command structure.

### ISSUE THREAD

**Issue by Brookke** [spf13/cobra#1677]
To my understand the documentation can only be generated in a flat structure. It would be great if there was a parameter that allows you follow the sub command structure.

Using the commands of the github cli as an example you would end up with a series of files:
```
gh_auth_login.md
gh_auth_logout.md
gh_auth_refresh.md
gh_codespace_code.md
gh_codespace_cp.md
gh_codespace_delete.md
...
```

it would be great if instead it would group by parent if the command is a sub command (perhaps you could specify the max depth) 

```
gh/
├─ auth/
│  ├─ index.md
│  ├─ login.md
│  ├─ logout.md
│  ├─ refresh.md
├─ codespace/
│  ├─ index.md
│  ├─ code.md
│  ├─ cp.md
│  ├─ delete.md
```

**Comment by jpmcb** [comment]
Hi @Brookke - I think this would be a great feature add.

Can you write up a little proposal of what the user flow would look like and where you imagine this fitting into cobra's existing generation APIs? 👀
