### ISSUE TITLE
Add `dependabot[bot]` to accounts in CLA Assistant

### ISSUE THREAD

**Issue by jpmcb** [spf13/cobra#1696]
Right now, attempting to enable dependabot to do automatic operations fails since it has not "signed" the CLA.

Example: https://github.com/spf13/cobra/pull/1688#issuecomment-1126803728
This fails since not all workflows have finished, primarily, the CLA check.

@spf13 - would it be possible for you to add `dependabot[bot]` in the CLA assistant dashboard?

Reference in CLA Assistant docs: https://github.com/cla-assistant/cla-assistant#can-i-allow-bot-user-contributions

**Comment by spf13** [comment]
Apologies for letting this one go stale. I added this tonight.
