### ISSUE TITLE
Reports an error for flags placed after the '--' flag terminator. 

### ISSUE THREAD

**Issue by joshi4** [spf13/cobra#17]
Firstly, thanks for building this package. 

One of the commands I am trying to build with this is an exec command. 

it works as follows: 

`rootCmd exec --booleanFlag1 arg1 -- python abc.py -u jondoe`

so while I have listed booleanFlag1 as a flag in the exec command it still parses the -u flag and reports an unknown flag error. 

The exec command's run function right now just prints the args that are passed to it. 

If i pass in arguments without `-` or `--` after the flag terminator everything works fine.

Here is a sample output: `[/key python abc.py thingie python abc.py thingie]` 

So the command used here was `rootCmd exec /key -- python abc.py thingie` 

Another question is why is the stuff after the terminator included twice in the args. 

I thought the flags and pflags library accounted for the flag terminator , am I missing something or not using the library correctly ?

**Comment by ncdc** [comment]
@spf13 any update on this issue? I didn't realize @joshi4 had a PR to try to fix this... I made one myself: https://github.com/spf13/pflag/pull/5. Would it be possible to merge in whichever one makes the most sense?

/cc @smarterclayton
