### ISSUE TITLE
Error: invalid character '{' after top-level value

### ISSUE THREAD

**Issue by huangxinbo** [spf13/cobra#1706]
go version go1.18.2 darwin/amd64
GO111MODULE="on"
```
cobra-cli init 
Error: invalid character '{' after top-level value
```

**Comment by Alphacode18** [comment]
Hey, how was this resolved?

**Comment by kcmvp** [comment]
ran into the same issue

**Comment by bunnycodego** [comment]
same here what the hell is this?

**Comment by fanux** [comment]
+1

**Comment by ebarti** [comment]
+1...

**Comment by marckhouzam** [comment]
The `cobra-cli` currently does not support go workspaces.  Please see https://github.com/spf13/cobra-cli/issues/26 for details.

**Comment by DarcyNing** [comment]
+1

**Comment by Kavyashah26** [comment]
I am also facing the same Issue. 
Anyone got any kind of solution for that ? Let me know and Help me figure out

**Comment by irkobl** [comment]
+1

**Comment by fkmatsuda** [comment]
+1

**Comment by NoverLoad** [comment]
删除或者修改你的go.work文件名 然后重新尝试

**Comment by NoverLoad** [comment]
删除或者修改你的go.work文件名  然后重新尝试

**Comment by Wixi105** [comment]
As @NoverLoad says, deleting your go.work file and running the cobra-cli init command fixes this problem. Cobra seems to not work with go workspaces just yet.
