### ISSUE TITLE
Usage is printed twice

### ISSUE THREAD

**Issue by rakanalh** [spf13/cobra#171]
Using the full example in readme as-is would result in printing usage information twice.

executing ```./myapp```  which only contains the code from the example, without any arguments or subcommands, would result in the following output:
```
Usage:
  app [command]

Available Commands:
  print       Print anything to the screen
  echo        Echo anything to the screen

Flags:
  -h, --help[=false]: help for app

Use "app [command] --help" for more information about a command.

Usage:
  app [command]

Available Commands:
  print       Print anything to the screen
  echo        Echo anything to the screen

Flags:
  -h, --help[=false]: help for app

Use "app [command] --help" for more information about a command.
```

Note how the usage is printed twice here.

PS: Many thanks for this great library.

**Comment by bep** [comment]
What version of Hugo are you using?

**Comment by rakanalh** [comment]
Not using Hugo. I am referring to the example on this [README](https://github.com/spf13/cobra/blob/master/README.md) on this repo. The issue also takes place in my project using cobra.
