### ISSUE TITLE
[completion] how to print error info with RegisterFlagCompletionFunc.

### ISSUE THREAD

**Issue by lixd** [spf13/cobra#1710]
i used RegisterFlagCompletionFunc to build dynamic completion.
```go
_ = cmd.RegisterFlagCompletionFunc("license", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		data, err := httpRequest()
		if err != nil {
                         // this is not work
                         fmt.Println("completion error:",err.Error())
			return nil, cobra.ShellCompDirectiveNoFileComp
		}
}
```
and want to print error info. but it does not work.
when i use
```bash
mycmd --myflag [tab][tab]
# the error info has splited
2h35m54.224688284s  [completion         error]              is                  to                  Unauthorized        
by                  due                 expired             reason              token  
```
**i can‘t get origin error print**. only with __complete can got it.
```bash
mycmd __complete --myflag ""[enter]
[completion error] Unauthorized due to reason token is expired by 2h38m9.850332898s
:4
Completion ended with directive: ShellCompDirectiveNoFileComp
```

**Comment by marckhouzam** [comment]
Hi @lixd.  You cannot currently print error messages for the users to see when doing shell completion.  When there is an error usually people return no completions.

If you want to debug your completion code yourself you can use the `__complete` command and add traces using one of Cobra's completion debugging functions such as`Cobra.CompError()`.  Please see this doc for debugging completion code: https://github.com/spf13/cobra/blob/master/shell_completions.md#debugging

If you are interested in printing a message to the actual user when they perform completion, the new ActiveHelp feature of #1482 will allow to do that (for bash and zsh only).

**Comment by marckhouzam** [comment]
Since this was answered and we didn't get any feedback I'll go ahead and close.
