### ISSUE TITLE
installing cobra

### ISSUE THREAD

**Issue by 4cecoder** [spf13/cobra#1711]
```shell
#go get -u github.com/spf13/cobra
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```
	
```shell
	#go install github.com/spf13/cobra@latest
package github.com/spf13/cobra is not a main package
```

**Comment by marckhouzam** [comment]
Hi @4cecoder, the cobra binary has moved to https://github.com/spf13/cobra-cli.
To install it: `go install github.com/spf13/cobra-cli@latest`

**Comment by greenseeker** [comment]
@marckhouzam cobra.dev's instructions are wrong then.

**Comment by jpmcb** [comment]
Right - we're aware that `cobra.dev` has drifted and it's primarily because we do not have that sites source code under our jurisdiction.

Duplicate of https://github.com/spf13/cobra/issues/1674

**Comment by cguess** [comment]
Just a heads up this isn't just an issue on cobra.dev, it's also wrong in the `Installation` portion of the README.

**Comment by marckhouzam** [comment]
I believe the installation instructions are correct because I’m that case we’re go getting the cobra module (not the cobra-cli binary)

**Comment by Sweetdevil144** [comment]
I see that the website still hasn't been updated. Okay, so is there any way we can correct this? I mean, we can update the entire wbesite and all occurances.
