### ISSUE TITLE
readme install using "go get" is failing

### ISSUE THREAD

**Issue by sgandon** [spf13/cobra#1723]
Hello I am trying to install cobra from the readme using go get and I get this error
```
go get -u github.com/spf13/cobra@latest
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

**Comment by sgandon** [comment]
I suppose it should be replaced by 
```
go install github.com/spf13/cobra@latest
```

**Comment by marckhouzam** [comment]
Hi @sgandon.  It depends what you are trying to do here. Are you trying to install the library itself or do you want to install the binary (cobra-cli, which used to be named cobra) used to help you generate your code?

For the library, for which the readme applies, you first need to create a go module for your program using `go mod init`.  Then the `go get` should work.

Maybe it should be in the readme...
It is part of the cobra-cli one: https://github.com/spf13/cobra-cli#initalizing-a-module

**Comment by sgandon** [comment]
indeed I realized that there where now 2 separate packages and I was trying to setup the cli with the wrong package.
I'll close this issue.
