### ISSUE TITLE
Alias

### ISSUE THREAD

**Issue by ankanroy-code** [spf13/cobra#1725]
how can i Alias

bin context create NAME
bin system connect add NAME

so  alias `context create` into `system connect add`
or 
alias `context`  into `system connect` and alias `create`  into `add`

a sample code structure
```
	contextCmd = &cobra.Command{
		Use:   "context add",
    Aliases: []string{"system connection"},
		Short: "Manipulate context lists and image indexes",
		Long:  contextDescription,
		RunE:  validate.SubCommandExists,
   Example: `podman context create`,
}

```

**Comment by marckhouzam** [comment]
Hi @ankanroy-code.

I don't think you can use aliases like that.  Aliases are for a specific command not a command path.

What you can do instead is create the two commands separately but have both of their Run() function call the same code.  You can probably have other fields of both commands also use some common code.

I'll let you try that out and see if it addresses your requirement sufficiently well.

**Comment by jpmcb** [comment]
+1 to what Marc said - aliases are for _specific_ commands. So if I have:

```go
var DeleteCmd = &cobra.Command{
	Use:   "delete <cluster name>",
	Short: "Delete an unmanaged cluster",
	RunE:    destroy,
	Aliases: []string{"rm"},
}
```

than after compiling, when running my program, i can use either the `delete` or `rm` commands:
```
$ my-program delete
$ my-program rm
```

**Comment by ankanroy-code** [comment]
@marckhouzam @jpmcb can I create a new command that executes a specific sub command. For example 
a command called `context`(defined inside system) that executes the sub command `connect`(a sub command inside system)

registered inside the system file
```
contextCmd = &cobra.Command{
		Use:   "context",
		Short: "Manage podman",
		Long:  "Manage podman",
		RunE:  validate.SubCommandExists,
}
```

**Comment by marckhouzam** [comment]
> @marckhouzam @jpmcb can I create a new command that executes a specific sub command. For example a command called `context`(defined inside system) that executes the sub command `connect`(a sub command inside system)
> 
> registered inside the system file

Since both `context` and `connect` are subcommands of the same `system` parent-command, then you can make one of them an alias to the other.
Or you can have both their `RunE` field call the same function as in your example, yes.
