### ISSUE TITLE
Avoid flag parsing in positional arguments and quoted strings

### ISSUE THREAD

**Issue by avinal** [spf13/cobra#1733]
### The problem
So I have a command defined as below:

```go
var solveCmd = &cobra.Command{
    Use: "solve",
    ...
    Args: cobra.ExactArgs(1),
    ...
}
```

This is meant to solve a prefix expression passed as a positional argument. So when I run:

```bash
./exp solve "+ + 7 * 4 5 + 2 1"
28
```
Even this works fine:

```bash
./exp solve "+ + 7 * 4 5 - 2 1"
30
```
But as soon as I change the first operator to subtraction (`-`), it gives me an error

```bash
./exp solve "- + 7 * 4 5 + 2 1"
Error: unknown shorthand flag: ' ' in - + 7 * 4 5 + 2 1
...
```

### Workaround

- One workaround suggested in issue #683 is to use `DisableFlagParsing: true`. But this won't be helpful if I want to add more flags i.e. `--step` or `-s` for enabling stepwise printing.
- The other one I found is if I place space before `-` it works, but this is bad from a user experience point of view. Plus I don't expect users to take care of this tiny detail when using my application.
```bash
./exp solve " - + 7 * 4 5 + 2 1"
25
```

### Expected solution

If there are positional arguments defined then avoid parsing them, in general, it should not parse anything passed inside quotes `" `. The primary purpose of explicitly mentioning quotes is to avoid unintended parsing errors IMO.

**Comment by Luap99** [comment]
The quotes are never send to the application. The program only gets an array of strings. The quotes are only used by your shell.

If you want flags and arguments starting with `-` you have to use `--` to signal the end of options to the parser:
`./exp solve -- "- + 7 * 4 5 + 2 1"`

From the GNU manual:
>  The argument -- terminates all options; any following arguments are treated as non-option arguments, even if they begin with a hyphen.

https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

**Comment by avinal** [comment]
Ok got it, Thanks!
Should I close this issue?
