### ISSUE TITLE
Summer 2022 release 🌞 

### ISSUE THREAD

**Issue by jpmcb** [spf13/cobra#1736]
Check back soon!

**Comment by umarcor** [comment]
Left pending in the previous releases (#1388, #1496, #1565, #1626):

- Approved by a maintainer but merge seems to have been forgotten:
  - #1646
    - #1643
      - #841
- #1387 
- #1467

Related to documentation/site rework:

- #1428

Some random cool ones:

- #1003
- #1572
- Maybe conflicting:
  - #1231
  - #1500

See also [Milestones: Next](https://github.com/spf13/cobra/milestone/3) and [Milestones: 2.0.0](https://github.com/spf13/cobra/milestone/1).

**Comment by umarcor** [comment]
@marckhouzam can you please create milestone 1.6.0, move the open issues/PRs from 1.5.0 and then close https://github.com/spf13/cobra/milestone/6?

**Comment by marckhouzam** [comment]
> @marckhouzam can you please create milestone 1.6.0, move the open issues/PRs from 1.5.0 and then close https://github.com/spf13/cobra/milestone/6?

Done.
Thank you @umarcor for helping organize the project! 👍

**Comment by jpmcb** [comment]
Let's do this soon! Fall is quickly approaching, I'll start going through anything that should make it in this release - thanks fall, as always, for your patience!
