### ISSUE TITLE
Getting "flag needs an argument" while flag has the default value

### ISSUE THREAD

**Issue by yaroslav-gwit** [spf13/cobra#1756]
Good day. I am a bit new to both Go and Cobra. I wrote a piece of software that does health checks (web checks only for now). Although the default value is defined, it's not working. Here is the exact output I am getting:
```
[yaroslav@hostname endpoint-checker]$ go run main.go web -f 
Error: flag needs an argument: 'f' in -f
Usage:
  endpoint-checker web [flags]

Flags:
  -a, --address string    Website address (required)
  -f, --file string       Use JSON file database to check multiple servers at once (default "db.json")
  -h, --help              help for web
      --no-ssl            Disable SSL related checks
      --port string       Website port (default "443")
      --protocol string   Website connection protocol (default "https")
  -s, --string string     Check if this string exists on the page

flag needs an argument: 'f' in -f
exit status 1
```

Here is the code I am using. Any suggestions are appreciated.
```
package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Use:   "endpoint-checker",
	Short: "Endpoint checker is a small program, that checks the health of your webiste",

	Run: func(cmd *cobra.Command, args []string) {
		// Empty function
	},
}

func Execute() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func init() {
	// Website related checks
	rootCmd.AddCommand(webCmd)

	// Address flag
	webCmd.Flags().StringVarP(&address, "address", "a", "", "Website address (required)")
	webCmd.Flags().StringVarP(&string_present, "string", "s", "", "Check if this string exists on the page")
	webCmd.MarkFlagsRequiredTogether("address", "string")

	webCmd.Flags().StringVarP(&file_database, "file", "f", "db.json", "Use JSON file database to check multiple servers at once")
	webCmd.MarkFlagsMutuallyExclusive("address", "file")

	// Port flag
	webCmd.Flags().StringVar(&port, "port", "443", "Website port")
	webCmd.Flags().StringVar(&protocol, "protocol", "https", "Website connection protocol")

	// SSL
	webCmd.Flags().BoolVar(&nossl, "no-ssl", false, "Disable SSL related checks")

	// Print version
	rootCmd.AddCommand(versionCmd)
}

var versionCmd = &cobra.Command{
	Use:   "version",
	Short: "Print the version number of the endpoint checker",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("Endpoint checker: v0.1")
	},
}

```

**Comment by marckhouzam** [comment]
Hi @yaroslav-gwit.  The default value of a flag is used when the flag is not specified on the command-line.

In your case, since you specify `-f` on the command-line, you need to specify a value explicitly.  If you think about it, why would the user type `-f` on the command-line if they are not going to specify a value? 🙂

Feel free to reopen if I didn't answer your question properly.

**Comment by AndyTitu** [comment]
I just stumbled upon this and I think there should be a way to achieve this via the `cobra.Command.Flags().VarPF()` functionality as such:

```
        cobraCommand := &cobra.Command{ ... }
	fileFlag := cobraCommand.Flags().VarPF(&reference, "file", "f", " Use JSON file database to check multiple servers at once")
	fileFlag.NoOptDefVal = "db.json"
```

**Comment by viccuad** [comment]
Stumbled upon this now.

> If you think about it, why would the user type -f on the command-line if they are not going to specify a value? 

In my case I want a flag `--log-fmt`, that if present starts logging with a default format. But one can specify the format if passing `--log-fmt=json` for example.

**Comment by sweetbbak** [comment]
Im in a similar boat. I wrote a CLI tool that allows the user to pass a custom "command" that is interpreted at runtime. 
for example `./cli_tool --tts` should indicate that they want the text played with text to speech with the defaults, but I'd also like to allow the user to pass a custom command to the tool like `./cli_tool --tts "xyz"`

**Comment by marckhouzam** [comment]
@sweetbbak you can achieve this with the `NoOptDefVal` field as mentioned above in https://github.com/spf13/cobra/issues/1756#issuecomment-1677439789

Note that with this option you *must* use the `=` with the flag: `./cli_tool --tts="xyz"`

**Comment by yaroslav-gwit** [comment]
You could also implement this within your own code, and not in `cobra` directly. For example:

Cobra declaration
```go
jailDeployCmd.Flags().StringVarP(&jailDeployCmdJailName, "name", "n", "NO", "Jail name")
```

Your custom code
```go
if jailDeployCmdJailName == "NO" {
    # simply ignore the case
    _ = 0
} else {
   deployNewJail(jailDeployCmdJailName)
}
```

Yes, I know it's not the best example (and not the best Go code, lol), but it just might give you some ideas. Most importantly - it will be transparent to the end users, which is what really matters at the end of the day.

**Comment by DanielHGimenez** [comment]
> I just stumbled upon this and I think there should be a way to achieve this via the `cobra.Command.Flags().VarPF()` functionality as such:
> 
> ```
>         cobraCommand := &cobra.Command{ ... }
> 	fileFlag := cobraCommand.Flags().VarPF(&reference, "file", "f", " Use JSON file database to check multiple servers at once")
> 	fileFlag.NoOptDefVal = "db.json"
> ```

Did it work for you? I tried here, but still having the same problem. I also tried to create the flag this way:
```
cmd.Flags().String(SOUND, "", "Set to the notification be a sound.")
flag := cmd.Flags().Lookup(SOUND)
flag.NoOptDefVal = ""
```

I'm trying to receive a sound flag. The use case is:
- If sound flag is not set/provided by the user, then nothing is done.
- If sound flag is provided, but no value is set, then I get the sound from config file.
- If sound flag is provided and the value is set, then I use the value to find the sound
