### ISSUE TITLE
cobra init: wrong import path

### ISSUE THREAD

**Issue by bep** [spf13/cobra#176]
```
./main.go:19: non-canonical import path "github.com/bep/alfn//cmd" (should be "")
./main.go:19: can't find import: "github.com/bep/alfn//cmd"
```

**Comment by eparis** [comment]
This is a cobra bug?  Why do you have `//` in your import path?

**Comment by bep** [comment]
This is @spf13 s new project ... And the double `/` *IS* the bug.

**Comment by eparis** [comment]
I don't see a main.go in cobra, what am I missing here? Am I supposed to be fixing something in cobra?

**Comment by bep** [comment]
https://github.com/spf13/cobra/blob/master/cobra/main.go
