### ISSUE TITLE
failed parse ~ to $HOME when use = in flag assignment

### ISSUE THREAD

**Issue by zhuwint** [spf13/cobra#1765]
I want to open file with filepath assigned in flag

This is my code
```go
package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var (
	file string

	rootCmd = &cobra.Command{
		Use:   "",
		Short: "",
		Long:  "",
		Run: func(cmd *cobra.Command, args []string) {
			if _, err := os.Stat(file); os.IsNotExist(err) {
				fmt.Println(err.Error())
			} else {
				fmt.Println(file)
			}
		},
	}
)

func init() {
	rootCmd.PersistentFlags().StringVarP(&file, "file", "f", "", "file path")
}

func main() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
	}
}
```

And the execute results are:

without =, successed parse ~ to $HOME 
```bash
root@LAPTOP-VFP625S5# ./main --file ~/.kube/config
/root/.kube/config
```
with =, failed parse ~ to $HOME
```
root@LAPTOP-VFP625S5# ./main --file=~/.kube/config
stat ~/.kube/config: no such file or directory
```

Is that any ways can make it parse ~ successful with = ?

**Comment by johnSchnake** [comment]
So the expansion is actually just happening on your terminal, not in cobra. Your app will have to handle the resolving; personally I've used https://github.com/mitchellh/go-homedir

You can see this by printing `os.Args` in the run logic and seeing that it comes to cobra already resolved.

**Comment by johnSchnake** [comment]
Feel free to reopen if there is something you think the cobra project can help with on this or if I misunderstood the issue. Best of luck.
