### ISSUE TITLE
Flags value match ./* on centos is not run correctly

### ISSUE THREAD

**Issue by ka-keung** [spf13/cobra#1770]
this test code is below: 

```go
package main

import (
 "fmt"
 "github.com/spf13/cobra"
)

var (
	RootCmd = &cobra.Command{}
       Src  string
)

func main()  {
    RootCmd.Flags().StringVarP(&Src, "src", "s", "","source dir")
    RootCmd.MarkFlagRequired("src")

   RootCmd.Run = func(cmd *cobra.Command, args []string) {
       fmt.Println(Src)
   }

    RootCmd.Execute()
}
```

it's correct run on windows platform:
`./test -s ./*` and success print `./*`

but in centos it will print this first match file name 

![20220804164303](https://user-images.githubusercontent.com/9947712/182804213-b53bc95c-f528-4aa2-b3fc-cb94f06f8246.png)

**Comment by marckhouzam** [comment]
Hi @ka-keung. This is normal. The shell first replaces `./*` with all its glob matches and then Cobra gets the first match.  I'm not sure how Windows handles the `*` in this case.

Try running `./test -s './*'` to prevent the shell from replacing the `*`.

**Comment by marckhouzam** [comment]
I'm going to go ahead and close this. Please reopen if the answer was not satisfactory.
