### ISSUE TITLE
//go:embed issues errors for template

### ISSUE THREAD

**Issue by saintmalik** [spf13/cobra#1773]
Hii guys,

so i have a template to be executed in my cli package which can kickstart a server and load the template, but i couldn't run the cli tool after build/installation.

i kept getting errors 

```2022/08/06 18:41:30 Error loading index template: template: pattern matches no files: `templates/creds.html```

how can i fix this please?

**Comment by johnSchnake** [comment]
I'm not sure I fully understand the problem, can you clarify a few things?

> i have a template to be executed
Is this a template that cobra-cli is consuming to generate your CLI? Or do you mean you already have a CLI tool built and it utilizes templates?

> i couldn't run the cli tool after build/installation
Is this the error that your CLI tool is giving, or do you mean when you run cobra-cli it gives you this error?
