### ISSUE TITLE
how can i use cobra deal with -delete like git ?

### ISSUE THREAD

**Issue by WRAllen** [spf13/cobra#1780]
when user input `git branch -delete` ,git will prompt user
```shell
error: did you mean `--delete` (with two dashes ?)
```
but, when i use flag like `cmd.Flags().StringVarP(&name, "delete", "d", "", "delete branch")`
when user input `xxx branch -delete` xxx is my cli name , cobra recognition -delete into -d elete, how can i deal with it like git.
(i know cobra suppot no space format for short flag)

**Comment by WRAllen** [comment]
i found a issue like my problem :https://github.com/spf13/cobra/issues/1399

**Comment by marckhouzam** [comment]
Thanks @WRAllen, this is a valid point.  Cobra uses spf13/pflag and I see this is being discussed there.  You may want to give your opinion in https://github.com/spf13/pflag/issues/314.

I'll close this as needing to be addressed in spf13/pflag.

**Comment by WRAllen** [comment]
@marckhouzam thinks
