### ISSUE TITLE
How to test a cobra CLI application?

### ISSUE THREAD

**Issue by silvioprog** [spf13/cobra#1790]
Hi.

I took a look at [the official guide](https://github.com/spf13/cobra/blob/main/user_guide.md), but couldn't find any information related to testing cobra applications.

So, is there any official documentation about this topic?

TIA for any help!

**Comment by silvioprog** [comment]
Edit: all references I found by google was to get inspiration from complex projects like helm, kubectl, hugo etc. 😞

Is there any "how to" guide instead of spending hours/days studying complex applications just to catch how to test a cobra CLI application?

**Comment by marckhouzam** [comment]
Hi @silvioprog . Mostly the tests I have seen are just Go tests that focus on testing different go functions that are implemented in the code base of the project (not testing Cobra functionality).

To make it easier on you you could look at the tests of the cobra-cli, which is a very small project using Cobra: https://github.com/spf13/cobra-cli/tree/main/cmd

**Comment by silvioprog** [comment]
Thanks a lot @marckhouzam!
Also found a post that helped me a lot. In case of more people looking about this: https://nayaktapan37.medium.com/testing-cobra-commands-in-golang-ca1fe4ad6657

**Comment by benoittgt** [comment]
I found it very interesting. https://github.com/govcms-tests/govcms-cli/blob/3216b7334c184e2cd52f013f588d2af9529b4929/docs/testing_cobra.md

**Comment by jsmartt** [comment]
Here's some example code that hopefully helps others get going:

```go
// cmd/root.go
package cmd

import (
	"github.com/spf13/cobra"
)

func NewRootCmd() *cobra.Command {
	rootCmd := &cobra.Command{
		Use:   "mycli",
		...
	}

	// Add child commands to the root command
	rootCmd.AddCommand(
		NewVersionCmd(),
	)

	return rootCmd
}
```

```go
// cmd/version.go
package cmd

import (
	"fmt"
	"github.com/spf13/cobra"
)

func NewVersionCmd() *cobra.Command {
	var versionCmdFormat string

	versionCmd := &cobra.Command{
		Use:   "version",
		Short: "Prints the version",
		RunE: func(cmd *cobra.Command, args []string) error {
			versionText := getVersionInfo(versionCmdFormat)
			fmt.Fprintln(cmd.OutOrStdout(), versionText)
			return nil
		},
	}

	versionCmd.Flags().StringVarP(&versionCmdFormat, "output", "o", "", "Output format. Allowed values: json, yaml")

	return versionCmd
}
```


```go
// cmd/version_test.go
package cmd

import (
	"bytes"
	"fmt"
	"testing"
)

func TestVersionCmd(t *testing.T) {
	t.Run("with no args", func(t *testing.T) {
		rootCmd := NewRootCmd()
		out := new(bytes.Buffer)
		rootCmd.SetOut(out)
		rootCmd.SetErr(out)
		rootCmd.SetArgs([]string{"version"})
		err := rootCmd.Execute()
		if err != nil {
			t.Errorf("got error %q", err)
		}
		outStr := out.String()
		expectedText := fmt.Sprintf("%s\n", constants.VERSION)
		if outStr != expectedText {
			t.Errorf("expected: %q; got: %q", expectedText, outStr)
		}
	})
}
```

Some of this is inspired by kustomize code.

Here are some learnings from along my journey:
- Always use the parent (ie root) command for setting arguments, output, etc. in your tests. [This code](https://github.com/spf13/cobra/blob/v1.9.1/command.go#L1089-L1092) forces the parent command to be executed, so setting arguments on a child command doesn't work.
- I found that the function to generate the commands were necessary for testing, as declaring the commands as global variables resulted in modified/dirty command instances in subsequent tests. This example ensures a new command instance is created for each test.
- Write all output to `cmd.OutOrStdout()` or `cmd.ErrOrStderr()`, so output can be captured in tests.
