### ISSUE TITLE
Why does '&' mark the end of an argument

### ISSUE THREAD

**Issue by frantjc** [spf13/cobra#1798]
As a simple example, if my `main` function looks like so:

```go
func main() {
	var (
		arg string
		cmd = &cobra.Command{
			Use:   "example",
			Run: func(cmd *cobra.Command, args []string) {
	                 	fmt.Println(arg)
			},
		}
	)

	cmd.Flags().StringVar(&arg, "arg", "", "example argument")

	if err := cmd.Execute(); err != nil {
		panic(err)
	}
}
```

then this happens:

```sh
example --arg s3://my-bucket?q1=hello&q2=there
s3://my-bucket?q1=hello
```

of course, I can just use quotes to make it work as expected:

```sh
example --arg 's3://my-bucket?q1=hello&q2=there'
s3://my-bucket?q1=hello&q2=there
```

but I'm curious why the former happens at all. Thanks!

**Comment by marckhouzam** [comment]
Hi @frantjc. The `&` is interpreted by the shell before it is even passed to Cobra. It tells the shell to run the preceding command in the background.
