### ISSUE TITLE
flag load error when has shorhand flag

### ISSUE THREAD

**Issue by yxxhero** [spf13/cobra#1810]
two flag:

-e string
--args sring

```
--args "-e abc"
```

expected:
-e ""
--args "-e abc"

result:
-e "abc"
--args "-e abc"

**Comment by marckhouzam** [comment]
Hi @yxxhero.  I cannot reproduce this behaviour.  Can you provide an example program where you see this?

**Comment by yxxhero** [comment]
@marckhouzam Thanks very much. I found the answer.
