### ISSUE TITLE
I/O redirection sign is not passed in cobra as argument

### ISSUE THREAD

**Issue by azhouwd** [spf13/cobra#1818]
Hi, when I was using the i/o redirection sign in the command, it seems they can't be read as an argument in cobra. For example `cmd save > t.tar`, I can't print out any argument in RunE function. However if I add a double quote to the > sign, `cmd save ">" t.tar`, I can print out all the arguments. Is there a way I can get all the arguments without adding double quote to the command?

**Comment by marckhouzam** [comment]
Hi @azhouwd.  It is the shell that interprets the special `>` character.  This happens before Cobra even gets called.  The only way I know to pass the special characters to Cobra is to escape them with a `\` or to use quotes.

Closing this as not something Cobra can "fix".
