### ISSUE TITLE
Setting a toggle flag to true does not work as expected

### ISSUE THREAD

**Issue by banjoh** [spf13/cobra#1821]
**Problem description**

In a cli program, if I create a boolean flag and default it to `true`, it does not get flipped to `false` when I pass in the flag. When the default is `false` it works as expected. Below is a sample program that best showcases the issue. 

```go
// main.go
package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Printf("toggle: %v\n", cmd.Flags().Lookup("toggle").Value)
	},
}

func main() {
	// Setting "true" as default is buggy
	rootCmd.PersistentFlags().BoolP("toggle", "t", true, "My fancy toggle")
	rootCmd.Execute()
}
```

When run, this is the output

```sh
✔ ~/repos/tst
[evans] $ go run main.go -t && go run main.go
toggle: true
toggle: true
✔ ~/repos/tst
[evans] $
```

When I change the default flag to `false` like below...
```go
rootCmd.PersistentFlags().BoolP("toggle", "t", false, "My fancy toggle")
```
...the output is as I would expect. See below 

```sh
✔ ~/repos/tst
[evans] $ go run main.go -t && go run main.go
toggle: true
toggle: false
✔ ~/repos/tst
```

**Environment**

* Here is my `go.mod` file

```
module github.com/banjoh/myapp

go 1.19

require github.com/spf13/cobra v1.5.0

require (
	github.com/inconshreveable/mousetrap v1.0.0 // indirect
	github.com/spf13/pflag v1.0.5 // indirect
)
```

* Mac M1, OS Monterey

**Comment by marckhouzam** [comment]
Hi @banjoh.  I agree this seems confusing but it's actually how boolean flags are meant to behave.

The default value is only used when the flag is not present.
When the flag is present, these are the rules:
1. -f or -f=true sets the flag to true
2. -f=false sets the flag to false

I think this becomes more clear in real world scenarios where three flag has a real purpose.  For example I could have `--no-dry-run` that defaults to true.  So when I actually use the flag like this `program install -no-dry-run` the user would still expect it to be true, or else it won't make sense.

Agreed?
