### ISSUE TITLE
cobra init/add etc.: generated Go code should be run through go fmt

### ISSUE THREAD

**Issue by bep** [spf13/cobra#183]
Right now the format  looks messy.

**Comment by apriendeau** [comment]
Surprisingly that is formatted.

**Comment by anthonyfok** [comment]
This issue is now dealt with in commit 1e63ad8: "Fine-tune the formatting of Cobra’s generated code".

A little bit more work is needed though for licenses other than Apache-2.0, to be dealt with in a future finalized form of Pull Request #194: "Improve Cobra Generator’s licensing helper".

**Comment by anthonyfok** [comment]
I think the new commit 4b09651 fixes the formatting for MIT, BSD-2-Clause and BSD-3-Clause licenses too, so they look good on a 80-column terminal (which I still use :wink:).

If you notice any other formatting issues, please re-open this issue.  Thanks!
