### ISSUE TITLE
Subcommand Group |  panic: Group id 'Group1' is not defined for subcommand 'app1 sub1'

### ISSUE THREAD

**Issue by KINGSABRI** [spf13/cobra#1831]
Hi everyone 
I'm trying to implement the subcommand group feature introduced in v[v1.6.0]. I followed the [test code](https://github.com/spf13/cobra/blob/1424b7b92743e634e20f611e99a495e411fa4732/command_test.go#L1770)

`/app1/cmd/root.go`
```go
func init() {
	cobra.EnableCaseInsensitive = true
	cobra.EnableCommandSorting = false

	rootCmd.CompletionOptions.DisableDefaultCmd = true 
	rootCmd.Flags().SortFlags = false
	rootCmd.PersistentFlags().SortFlags = false

	rootCmd.AddGroup(&cobra.Group{ID: "Group1", Title: "Group1 Subcommands:"})
}
```

 `/app1/cmd/sub1.go`
```go
var sub1Cmd = &cobra.Command{
	Use:     "sub1",
	GroupID: "Group1",
	Aliases: []string{"1"},
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("Hiii")
	},
}

func init() {
	rootCmd.AddCommand(sub1Cmd)
	sub1Cmd.Flags().SortFlags = false
	sub1Cmd.Flags().StringP("ipaddress", "i", "0.0.0.0", "IP address to listen to")
}

```

When I run the app I get 
```
panic: Group id 'Group1' is not defined for subcommand 'app1 sub1'
goroutine 1 [running]:
github.com/spf13/cobra.(*Command).AddCommand(0xd024e0, {0xc00024fd08, 0x1, 0x1?})
        /home/USER/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1223 +0x2d4
app1/cmd.init.3()
        /home/USER/Code/app1/cmd/sub1Cmd.go:47 +0x54
```

Q\ is there any complex example that wrapup all cobra's features?

**Comment by KINGSABRI** [comment]
Hi, 
I'm not sure why the issue is being submitted twice. 

Your advice regarding the issue is appreciated 

Thanks

**Comment by andig** [comment]
Same here. It's not obvious where the Groups need be added in order to be specified on the child command?

**Comment by aawsome** [comment]
The `AddGroup` command must be executed before the `AddCommand(sub1Cmd)` is executed. 

As both are in the `init()` functions in your example, according to https://stackoverflow.com/questions/32829538/init-order-within-a-package they are executed in lexical order, i.e. `init()` of `sub1.go` before `init()` of `root.go` which is the wrong order.

So, to solve your problem, either rename your files such that the file name of the go file defining the subcommand is lexical larger than the file name of the go file defining the root command. 

Another alternative is to change `init()` in `sub1.go` into `initSub1()` and add a `initSub1()` at the end of the `init()` funtion in `root.go`.

**Comment by andig** [comment]
Thanks for the explanation. This is a bit unfortunate from usability perspective as it introduces coupling between otherwise independent parts (except for being aware that there is a `rootCmd`). It would be helpful if the groups could be declared right when the `rootCmd` is first assigned (didn't check if that's the case due to internet issues, sorry).

**Comment by KINGSABRI** [comment]
Thank @aawsome for your answers and the solutions. I would've never guessed it from `AddGroup()` documentation. I also didn't know about Go's lexical order during the compilation.  

> I think you renamed your real subcommand
True


The alternative solution works just fine for me 

`/app1/cmd/root.go`
```go
func init() {
	cobra.EnableCaseInsensitive = true
	cobra.EnableCommandSorting = false

	rootCmd.CompletionOptions.DisableDefaultCmd = true 
	rootCmd.Flags().SortFlags = false
	rootCmd.PersistentFlags().SortFlags = false

	rootCmd.AddGroup(&cobra.Group{ID: "Group1", Title: "Group1 Subcommands:"})

	initSub1()
	initSub2()
	initSub3()
}
```


 `/app1/cmd/sub1.go`
```go
var sub1Cmd = &cobra.Command{
	Use:     "sub1",
	GroupID: "Group1",
	Aliases: []string{"1"},
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("Hiii")
	},
}

func initSub1() {
	rootCmd.AddCommand(sub1Cmd)
	sub1Cmd.Flags().SortFlags = false
	sub1Cmd.Flags().StringP("ipaddress", "i", "0.0.0.0", "IP address to listen to")
}

```

I also agree with @andig  regarding the inconvenience usability of this approach  

Thank you all
