### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by el2zay** [spf13/cobra#1837]
I've tried many times but it doesn't work, I always get a command not found when I do the `cobra` or `cobra-cli` command, on my Windows it works but not on my macOS and it's very annoying. 

Could someone help me please?

macOS Monterey 12.5.1
Go 1.19.2

**Comment by marckhouzam** [comment]
Did you install the cobra-cli first?
`go install github.com/spf13/cobra-cli@latest`

It will be installed under `$GOPATH/bin`, so you can run it using `$GOPATH/bin/cobra-cli`.

To simply run `cobra-cli`, you need to make sure `$GOPATH/bin` is on your `$PATH` environment variable.

**Comment by el2zay** [comment]
Thank you
