### ISSUE TITLE
cobra init: Should exit on invalid configuration

### ISSUE THREAD

**Issue by bep** [spf13/cobra#184]
Currently the generated Cobra application from `cobra init` takes an error from `ReadInConfig` to mean `no config` and just silently continues. 

Generated code should be `best practice` - and this doesn't look like it.

**Comment by apriendeau** [comment]
Just so I can understand for curiosity sake. What generated go code? I assume in the README but my bigger question is, how is that generated?

**Comment by wfernandes** [comment]
Yeah, I looked into this and I see that the generated `root.go` has the following code at the bottom.
```
	// If a config file is found, read it in.
	if err := viper.ReadInConfig(); err == nil {
		fmt.Println("Using config file:", viper.ConfigFileUsed())
	}
```

I know of a project that I'm currently working on that followed this same practice (coincidentally) and the error from `viper.ReadInConfig()` wasn't propagated correctly.

@jharshman If you'd like I can take a look into this 🙂
