### ISSUE TITLE
Using BashCompletionV2, failing PersistentPreRunE interferes with autocompletion

### ISSUE THREAD

**Issue by ArnoSen** [spf13/cobra#1848]
This applies to version 1.6.1 .
I have a bash completion script generated with GenBashCompletionV2 . When the PreRunE fails, there is a mix of usage information and parts of a bash error.

In my app that is internally used only and that I cannot share, the output of the autocomplete is like this:
```
cli [tab] bash: 
      --config string    config file (default is $HOME/.cli.yaml)
  -p, --profile string   Profile
      --token string     API token: syntax error in expression (error token is "string    config file (default is $HOME/.cli.yaml)
  -p, --profile string   Profile
      --token string     API token")
```

When I am using the V1 GenBashCompletion, then autocompletion produces the correct completion verbs for the application and only when submitting an actual command, it errors out with the PersistentPreRun error.

I suspect that is an edge case and is caused by the V2 bash completion calling `cli` itself whereby it is not handling correclty the error that is returned by PersistenPreRunE. But if you need a real code example please let me know.

**Comment by marckhouzam** [comment]
Thanks for the report.  What is the output of
```
cli __complete ''
```

**Comment by ArnoSen** [comment]
The output is:
```
$ cli __complete ''
Error: Error validating the profile: Token cannot be empty

Usage:
  cli __complete [command-line]

Aliases:
  __complete, __completeNoDesc

Flags:
  -h, --help   help for __complete

Global Flags:
      --config string    config file (default is $HOME/.cli.yaml)
  -p, --profile string   Profile
      --token string     API token
```
The error "Error validating the profile: Token cannot be empty" is the error returned by the PersistenPreRunE.

**Comment by marckhouzam** [comment]
The completion script will use anything printed on `stdout` by the `__complete` command, as completion choices.  But the script will ignore anything printed on `stderr`.  If you try `cli __complete '' 2> /dev/null`, which removes all output that is on `stderr` you can then see what the script will use for completion choices.

If the error from `PersistentPreRun` is printed to `stdout` it is possibly because your code does that when you call `root.Execute()`.  You should be able to tweak that and avoid the problem.

**Comment by ArnoSen** [comment]
The function that is set as PersistenPreRunE is only returning an error. There are no print statements in this function.

Also when I redirect stderr to /dev/null I see the error is not displayed:
```
$scli __complete '' 2> /dev/null
Usage:
  cli __complete [command-line]
(...)
```

And when not redirecting stderr to /dev/null, I do see the error:
```
$ cli __complete ''
Error: Error validating the profile: Token cannot be empty

Usage:
  scli __complete [command-line]
```

It therefore looks like the error is correctly written to Stderr but still there is interference.

**Comment by ArnoSen** [comment]
When I set the SilenceUsage in the the cobra.Command object to false, there are no bash errors nor any interference and the completion options fallback to files and dirs in the working directory.

**Comment by marckhouzam** [comment]
Sounds like a plan.  Depending on your situation, you may only want to set that option when your program is being called for the `__complete` command:
```
PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
	if cmd.Name() == cobra.ShellCompRequestCmd {
		// Silence errors when dealing with shell completion
		...
	}
	...
},
```
