### ISSUE TITLE
Consider removing stale-bot

### ISSUE THREAD

**Issue by jpmcb** [spf13/cobra#1858]
I think we've proven stale-bot has not been useful for this project: the long lead times and constant notifications are frustrating for community members and maintainers alike.

Example: https://github.com/spf13/cobra/issues/1658

We should consider removing stale-bot or at least remove it's ability to close issues/PRs

**Comment by jpmcb** [comment]
I'd like other maintainers thoughts on this too: @marckhouzam @johnSchnake

**Comment by marckhouzam** [comment]
Thanks for bringing this up. I admit the stale-bot is starting to get on my nerves 😅.

I'm ok with turning it off considering the realities of our project.

**Comment by umarcor** [comment]
I do also think it's good to remove it, unless until the status quo changes.
