### ISSUE TITLE
when will 1.7.0 release?

### ISSUE THREAD

**Issue by yxxhero** [spf13/cobra#1859]
hi. when will 1.7.0 release?

Thanks very much.

**Comment by marckhouzam** [comment]
Hi @yxxhero.  Thanks to @jpmcb  we've been doing a release every three or four months.  1.6.1 was released mid-October so I expect the next one to be in the first couple of months of 2023.

**Comment by yxxhero** [comment]
@marckhouzam Thanks very much.

**Comment by yxxhero** [comment]
https://github.com/spf13/cobra/pull/1781 @jpmcb
