### ISSUE TITLE
Completion problem

### ISSUE THREAD

**Issue by clementbolin** [spf13/cobra#1876]
Hello, I tried to write a small test application to test the auto-complete feature. I followed this [official documentation](https://github.com/spf13/cobra/blob/main/shell_completions.md) but nothing happens after the program execution

**Steps to reproduce:**

completion.go
```go
package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var CompletionCmd = &cobra.Command{
	Use:   "completion [bash|zsh|fish|powershell]",
	Short: "Generate completion script",
	Long: fmt.Println("how to use"),
	DisableFlagsInUseLine: true,
	ValidArgs:             []string{"bash", "zsh", "fish", "powershell"},
	Args:                  cobra.MatchAll(cobra.ExactArgs(1), cobra.OnlyValidArgs),
	Run: func(cmd *cobra.Command, args []string) {
		switch args[0] {
		case "bash":
			cmd.Root().GenBashCompletion(os.Stdout)
		case "zsh":
			cmd.Root().GenZshCompletion(os.Stdout)
		case "fish":
			cmd.Root().GenFishCompletion(os.Stdout, true)
		case "powershell":
			cmd.Root().GenPowerShellCompletionWithDesc(os.Stdout)
		}
	},
}
```

build the project with following command:
```
go build -o root main.go
source <(./root completion zsh)
./root [tab][tab]
```

Also if I tried to add bash completion I get the following error
```
go build -o root main.go
source <(./root completion bash)
=> /dev/fd/11:type:527: bad option: -t
```

**Environment**
```
macOS Monterey
version 12.2.1
Chip: Apple M1 Pro
```

**Comment by marckhouzam** [comment]
Hi @clementbolin.

I assume you are running the `zsh` shell.  In that case you cannot `source` the script.  Please see:
https://github.com/spf13/cobra/blob/main/shell_completions.md?plain=1#L45-L55

But if you want to "cheat" for zsh you can do what you did but also: `compdef _root root`
I say "cheat" because zsh does not recommend using `source` as it slows down the shell startup.

As for the bash error, did you start the `bash` shell first?

**Comment by clementbolin** [comment]
I had already done it, unfortunately I found myself with the following error
```
(eval):1: _main: function definition file not found
(eval):1: _main: function definition file not found
(eval):1: _main: function definition file not found
```

**Comment by marckhouzam** [comment]
You might have named your root command something else than `root`.  Your root command must have the same name (the `Use` field) as what you call your binary.

**Comment by clementbolin** [comment]
I updated my `rootCmd` like this:
```go
var rootCmd = &cobra.Command{
	Use:   "cobra_test",
	Short: "cobra_test command",
	Long:  `cobra_test
command`,
	SilenceUsage: true,
}
```
I followed each steps in the [readme](https://github.com/spf13/cobra/blob/main/shell_completions.md?plain=1#L45-L55)
```
$ echo "autoload -U compinit; compinit" >> ~/.zshrc
$ cobra_test completion zsh > "${fpath[1]}/_cobra_test"
```
after that I try to test the following command but nothing happen `./root [tab][tab]`

PS: my `${fpath[1]}` is equal to `~/.oh-my-zsh/plugins/docker`

**Comment by marckhouzam** [comment]
What is the name of your binary?  Is it `cobra_test` or `root`?

Try `cobra_test [tab][tab]`

**Comment by marckhouzam** [comment]
Oh, and start a new zsh shell first

**Comment by clementbolin** [comment]
Sorry I made a mistake with the copy and paste in the previous message, I just updated it.
Yes my binary is named `cobra_test` and I had launched a new shell

**Comment by marckhouzam** [comment]
What is the output of
```
head "${fpath[1]}/_cobra_test"
```

**Comment by clementbolin** [comment]
yes of course
```
#compdef cobra_test

# zsh completion for cobra_test                           -*- shell-script -*-

__cobra_test_debug()
{
    local file="$BASH_COMP_DEBUG_FILE"
    if [[ -n ${file} ]]; then
        echo "$*" >> "${file}"
    fi
```

**Comment by marckhouzam** [comment]
This looks right.
How about the output of `which cobra_test`?
