### ISSUE TITLE
Question: how to hide the description in the completion

### ISSUE THREAD

**Issue by Shihta** [spf13/cobra#1894]
As the red frame part:

![截圖 2023-01-13 下午11 46 37](https://user-images.githubusercontent.com/5186176/212361161-8201915c-d696-45cd-bc85-aa5ac95510be.png)

how to hide the description?

Thanks!

**Comment by marckhouzam** [comment]
Is `ccli` a tool you installed or a tool you wrote yourself?

**Comment by Shihta** [comment]
> Is `ccli` a tool you installed or a tool you wrote yourself?

I wrote myself, used the latest cobra (v1.6.1)

**Comment by marckhouzam** [comment]
Each call to `Gen*Completion()` for the different shells has a way to disable descriptions.  Those APIs use an argument for Bash completion v2 and fish, while zsh has `GenZshCompletionNoDesc()`. PowerShell uses `GenPowerShellCompletion()` for completions without descriptions (compared to `GenPowerShellCompletionWithDesc()`)

**Comment by Shihta** [comment]
thanks for the tip, I finally realized that there was a ready-made flag to use:

![截圖 2023-01-14 下午11 22 09](https://user-images.githubusercontent.com/5186176/212479736-4e77218a-579f-48dd-8747-33fe60460a86.png)

This doesn't seem to be in the document, I think it's worth mentioning

**Comment by marckhouzam** [comment]
Good point. Interested in posting a PR @Shihta ?
