### ISSUE TITLE
change trim charackter of Flags().IntSlice

### ISSUE THREAD

**Issue by zofi-cash** [spf13/cobra#1896]
Is it possible to parse a int slice using whitespaces instead of commas?
want to do something like

`app run --range 0 5` 
instead of
`app run --range 0,5`

**Comment by marckhouzam** [comment]
@zofi-cash 

> `app run --range 0 5`

This is not possible because Cobra wouldn't be able to know if the 5 is part of the list of integers or an argument to the run command.

But you can do
`app run --range 0 --range 5`
