### ISSUE TITLE
Generated output should be done with cobra command line tool

### ISSUE THREAD

**Issue by mwmahlberg** [spf13/cobra#190]
Currently, man pages / Markdown documentation / bash completion are generated when the respective command is called.

This is problematic. Let's take Linux for example. When a man page is generated, it might well not be generated by a user allowed to put it into the correct location. So the proper location can not be used for the path parameter of `GenManTree`. On the other hand, man pages should not be distributed over the file system.

Doing the generation via a special command does not prevent that, and would clutter the program with a command used only during installation.

It would be better to at least have an option to have man pages / Markdown / bash completion generated by the `cobra` command line tool.

**Comment by nicolaasuni** [comment]
I have experienced the same problem while working on the following project:
https://github.com/tecnickcom/rndpwd
I created a Makefile that includes targets to automatically build RPM and DEB packages for the GO application, so I was looking for a way to automate the generation of man pages to be packaged.
As @mwmahlberg pointed, the current solution clutter the program with code used only once during packaging or installation.
To generate the man page, after compiling the executable, I used the help2man application to generate the man page:
```
help2man -v version ./rndpwd > rndpwd.1
```
and then I edited the rndpwd.1 file to clean it up a bit.
Potentially I can add the help2man process in the Makefile but the automatic result is not so satisfactory.

**Comment by spf13** [comment]
It wouldn't be possible for the cobra command line tool to do this. It would need to have full access to the source of the program in question to be able to do this. That's much more problematic than a program generating it's own man page. I believe we can improve this command, and perhaps provide a better location for it, but functionally speaking it would need to remain part of the application. 

It's also entirely possible for the application to have an installer file that runs these gen commands and puts them where they go. That follows the traditional approach. It just so happens that Cobra based apps ship with a seamless way to keep man and other docs 100% up to date.
