### ISSUE TITLE
preserve ordering of completions passed to zsh autocomplete

### ISSUE THREAD

**Issue by h4ck3rk3y** [spf13/cobra#1900]
https://github.com/spf13/cobra/blob/6d978a911e7fff69b1ca2a873dd91d78ebca44cf/zsh_completions.go#L265

The way describes works with the following input - `apple cat bat`, it would sort it for you, and suggest `apple bat cat`. If we pass the `-V` flag we end up preserving the ordering of the passed completion,

a real world example,

```
CURRENT: 4, words[*]: your favorite command 
Truncated words[*]: your favorite command ,
lastParam: , lastChar: 
Adding extra empty parameter
About to call: eval your __complete favorite command  ""
completion output: dry-thunder
patient-field
twilight-shadow
edf1abc0bfc445b38d46a82585a8bfd0
edf78299bbbd453f9552a3b730d68834
edffa85eb3b14e22951f47e252c5fbbf
:4
last line: :4
directive: 4
completions: dry-thunder
patient-field
twilight-shadow
edf1abc0bfc445b38d46a82585a8bfd0
edf78299bbbd453f9552a3b730d68834
edffa85eb3b14e22951f47e252c5fbbf
flagPrefix: 
Adding completion: dry-thunder
Adding completion: patient-field
Adding completion: twilight-shadow
Adding completion: edf1abc0bfc445b38d46a82585a8bfd0
Adding completion: edf78299bbbd453f9552a3b730d68834
Adding completion: edffa85eb3b14e22951f47e252c5fbbf
Calling _describe
_describe found some completions
```

on pressing tab you get, dry-thunder edf1abc0bfc445b38d46a82585a8bfd0 edf78299bbbd453f9552a3b730d68834 edffa85eb3b14e22951f47e252c5fbbf patient-field twilight-shadow

if we change the above line to 

`if eval _describe -V "completions" completions $flagPrefix $noSpace; then`

we maintain the passed ordering. Would you be open to a contribution that gives users an option to preserve ordering?

**Comment by marckhouzam** [comment]
Thanks for the report @h4ck3rk3y .

I think this is tricky because even with the -v things will be dependent on the order the program returns the completions.

I guess that for this option too make sense the program would consciously order the Lissy of completions and specify to preserve the order?

We'd also have to look at how this case applies to the other three shells.

But I'm open to the idea.

**Comment by h4ck3rk3y** [comment]
Yep thats the idea, the person using the library would use a flag to preserve order and then send their ordered list.

Agree, we'll have to figure out how this applies to `ksh`, `fish` and `bash` too. Will see if I can make a contribution for this, sometime next week, time permitting.

**Comment by h4ck3rk3y** [comment]
Bash requires the the `nosort` option 

https://github.com/spf13/cobra/blob/badcce14f8e828cda4d8ac404a12448700de1441/bash_completionsV2.go#L354-L358, plugging in `-o nosort` here works.

**Comment by h4ck3rk3y** [comment]
I am not sure if `fish` supports this at all, someone had raised a PR a few years ago which didn't get merged and the two issues asking for this feature were marked as closed.

**Comment by marckhouzam** [comment]
Sounds like a nice addition. I'm looking forward to your contribution.

**Comment by h4ck3rk3y** [comment]
I went through the Cobra code a little more and I am thinking of doing it in the following way

1. Add another directive lets call it ShellCompDirectiveKeepOrder
2. Have some logic in the completion to check whether the directive is set, if it is set then add the `--keep-order` or equivalent flag for the underlying shell

This allows some granular control per validation function and if a user wants to start using it they just set the directive. Let me know if this makes sense!

**Comment by marckhouzam** [comment]
Brilliant! That sounds perfect.

**Comment by irvinlim** [comment]
+1 for this, just stumbled onto the same issue and came to the same findings about adding `-o nosort` for zsh.

Would love to provide any assistance if any help is needed support this!

**Comment by h4ck3rk3y** [comment]
i have created a pr using the directive logic i mentioned
