### ISSUE TITLE
cannot install go get deprecated

### ISSUE THREAD

**Issue by absynth76** [spf13/cobra#1906]
go version go1.18.5 linux/amd64

follow install guide:
```go get -u github.com/spf13/cobra/cobra```

giving:
```
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

go get is deprecated since go 1.17, released on 16 Aug 2021.

I tried out

```
go install  github.com/spf13/cobra@latest
package github.com/spf13/cobra is not a main package
```

and 
```
go install  github.com/spf13/cobra/cobra@latest
go: github.com/spf13/cobra/cobra@latest: module github.com/spf13/cobra@latest found (v1.6.1), but does not contain package github.com/spf13/cobra/cobra
```

update documentation is needed

**Comment by marckhouzam** [comment]
The Cobra CLI has moved to its own project, so:
`go install github.com/spf13/cobra-cli`

And for the library:
`go get -u github.com/spf13/cobra`

**Comment by absynth76** [comment]
I'm not familiar enough with golang I guess, does installing the cobra cli also install the library ? 
because if you execute the latest provided command, you end with
```
go get -u github.com/spf13/cobra
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

using golang 1.18

**Comment by marckhouzam** [comment]
You only need to install the library when you start using it in your project.
I believe you can start with the go install of the cobra-cli, generate your code and Go will guide you after that if you need to install the library or if it was done for you

**Comment by absynth76** [comment]
what I'm surprised about is that most of the tutorials, included the cloudguru one I follow, seems to rely on that "go get" feature, or this is a deprecated one, anyway, at a point in time, you'll have, and all other projects, to cope with that major change. 

I suppose you can close that discussion, I do understand maintenance is hard and adapting to this fast change can be problematic, but that's the way it is.

I'll end with this: on your main README, you have a command which simply does not work with latest go binary. Not very friendly for the end users/developers.

**Comment by earthaYan** [comment]
https://cobra.dev/  this official doc is still wrong

**Comment by MozeBaltyk** [comment]
to be more accurate the error is here: https://cobra.dev/#install
