### ISSUE TITLE
Command.Execute should return the Command

### ISSUE THREAD

**Issue by bep** [spf13/cobra#191]
See #168

The command is always run from the root and the caller will never know which command that is actually executed. So, even if the errors are propagated up the chain, it is hard to do proper centralized error handling without the command as context (usage logging etc).

An API change is maybe a hard sell, but what about a `Command.ExecuteC` or something?

**Comment by apriendeau** [comment]
I like the Command.ExecuteC for now but we have a lot of these functions popping up. We should clean it up for whenever we decided the time is right to release a new major breaking version.
