### ISSUE TITLE
Remove labels lifecycle/stale and lifecycle/rotten

### ISSUE THREAD

**Issue by umarcor** [spf13/cobra#1910]
As commented in #1908, we should remove [lifecycle/stale](https://github.com/spf13/cobra/labels/lifecycle%2Fstale) and [lifecycle/rotten](https://github.com/spf13/cobra/labels/lifecycle%2Frotten).

**Comment by marckhouzam** [comment]
Can I just do that blindly?  I assume it will remove those labels from every existing issues and PRs?  What about the ones closed by the bot?

**Comment by umarcor** [comment]
Yes, that will remove labels from existing issues an PRs. The ones closed by the bot will remain closed. I don't know how can we identify them. Maybe manually checking [`label:lifecycle/stale sort:updated-desc is:closed `](https://github.com/spf13/cobra/issues?q=label%3Alifecycle%2Fstale+sort%3Aupdated-desc+is%3Aclosed) and [`label:lifecycle/rotten sort:updated-desc is:closed `](https://github.com/spf13/cobra/issues?q=label%3Alifecycle%2Frotten+sort%3Aupdated-desc+is%3Aclosed)?

**Comment by marckhouzam** [comment]
I've reopened two PRs that had been closed by the bot and deleted the `lifecycle/rotten` and `lifecycle/state` labels.
