### ISSUE TITLE
Flag parsing error when flag value matches subcommand name

### ISSUE THREAD

**Issue by watsonian** [spf13/cobra#1913]
I seem to have run into a bug that surfaces when you pass a value into a flag that matches the name of a subcommand. For example, suppose you have a command like this:

```
tester --project configs --config dev configs
```

where `configs` is a subcommand, but we're also passing that in as the value to the `--project` flag. In that scenario, the value for `project` ends up being `--config` and the value for `config` ends up being empty. If you change the value being passed to `--project` to anything else, it works fine. It also starts working fine if you leave the value being passed to `--project` as is, but rename the subcommand.

Here's video demonstrating the issue:

https://www.loom.com/share/22d1caba74644c939e978fd3277a437d

And here's the sample code demonstrating the problem: [cobra-tester.zip](https://github.com/spf13/cobra/files/10745097/cobra-tester.zip)

**Comment by marckhouzam** [comment]
Is this the same as #1777 ?

**Comment by watsonian** [comment]
@marckhouzam Definitely sounds like the same issue, yeah. Seems like it's not actually fixed.

**Comment by marckhouzam** [comment]
Duplicate #1777 

Thanks for the test program @watsonian.  I did see the problem with it. So I wondered if you were using an old version of cobra but you were not. This is when I realized that the fix for this hasn't been released yet, as we can see from the milestone set for #1781 .

I have re-tried your test program with the main branch of cobra and it properly works in that case.

**Comment by watsonian** [comment]
@marckhouzam It looks like the actual fix for this was merged 4 months ago and still isn't released. Do you know when the next release will be?

**Comment by marckhouzam** [comment]
We usually do releases every four months, so one should be coming up soon.
