### ISSUE TITLE
Question: Is there an out-of-the-box way of getting the completion command to work properly?

### ISSUE THREAD

**Issue by matheuscscp** [spf13/cobra#1915]
I'm trying to add the `completion` command for this open-source project:

https://github.com/marcosnils/bin/

Here is my draft PR:

https://github.com/marcosnils/bin/pull/156

If I just upgrade cobra to the most recent version, the `completion` command invokes one of the commands of the project (`list`).

Another thing I tried was adding a definition for the `completion` command by adapting an example (this is the current state of my draft PR). In this case the `completion` seems to work, e.g. `completion -h` prints the help message for the `completion` command, and `completion zsh` also prints a script. But then I tried to load the script printed by `completion zsh` in my zsh shell in many different ways, and the completion simply didn't work.

I'm not sure what I'm doing wrong since I do have completions working properly for example for the `kubectl` and `flux` CLIs, which seem to be implemented using cobra as well.

Appreciate any help!

**Comment by marckhouzam** [comment]
"Cobra will automatically provide your program with a fully functional completion command, similarly to how it provides the help command." (from https://github.com/spf13/cobra/blob/main/shell_completions.md)

If you don't do anything, your program should automatically have a `completion` command at the root.

If you use `zsh`, you cannot source the script out-of-the box.
Run `<program> completion zsh -h` to get instructions (assuming you use Cobra's completion command).
But basically you if you program is `bin` you need to run `compdef _bin bin` in your shell to make completion work.
I will be posting a PR to have this done automatically; it affects too many people.

**Comment by matheuscscp** [comment]
> If you don't do anything, your program should automatically have a `completion` command at the root.

thanks for the information on how to load the script for zsh! i will try that in the morning and give an update.

however, this approach for adding the `completion` command (the default one) was exactly the one i tried first. all i did in my fork was upgrading cobra from 1.0.0 to 1.6.1 and test the command. i did see it on the root list of commands, however when i execute `./bin completion -h` i see the output of `./bin list -h`, i.e. the `completion` command has the behavior of `bin`'s `list` command. am i missing something? could this be a bug?

i tested a hypothesis where i guessed that maybe this was happening due to the unusual way with which `bin` instantiates the cobra commands, which is inside Go's `main()` function, instead of global vars or `init()` functions, but i also proved myself wrong. i made this change locally and tested, and the behavior i see is still the same, `completion` invokes `list`.

the only way i could make it work was copying and adapting an example of `completion` command that i found in the docs.

**Comment by marckhouzam** [comment]
The problem is because of this line: https://github.com/marcosnils/bin/blob/963a6f4010306b4efb3c32b5456fe7e66b4dba44/cmd/root.go#L32

The default `completion` command only gets added when you call cobra's `Execute()`. This means the call to `Find()` will not find it.  You will need to check for it yourself as you do here https://github.com/marcosnils/bin/blob/963a6f4010306b4efb3c32b5456fe7e66b4dba44/cmd/root.go#L108

This will also affect the hidden `__complete` command which may explain why completion doesn't work for you.

Here is an example from kubectl (note however that kubectl doesn't user the default completion command so it doesn't need to check for it):
https://github.com/kubernetes/kubectl/blob/04af20f5a9d2b56d910a36fec84f21164df65d32/pkg/cmd/cmd.go#L132

**Comment by matheuscscp** [comment]
thanks @marckhouzam! with that advice I was able to make the default `completion` work, apparently. however, looks like the autocompletion is still not working. I'm seeing this output when I press tab twice to check for `bin`'s main commands:

```shell
➜  bin git:(completion) source <(./bin completion zsh); compdef _bin bin
➜  bin git:(completion) ./bin \
 /home/pimenta/.local/bin/bin  -- v0.15.2::github.com/marcosnils/bin:OK
 Path                          -- :::Version::URL::::Status
```

and these are `bin`'s commands:

```shell
➜  bin git:(completion) ./bin -h
Effortless binary manager

Usage:
  bin [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  ensure      Ensures that all binaries listed in the configuration are present
  help        Help about any command
  install     Installs the specified project from a url
  list        List binaries managed by bin
  prune       Prunes binaries that no longer exist in the system
  remove      Removes binaries managed by bin
  update      Updates one or multiple binaries managed by bin

Flags:
      --debug     Enable debug mode
  -h, --help      help for bin
  -v, --version   version for bin

Use "bin [command] --help" for more information about a command.
➜  bin git:(completion) 
```

**Comment by marckhouzam** [comment]
See the second part of my previous answer: "This will also affect the hidden __complete"

The hidden __complete command needs to work fire completion to work.

You can test it like this: `./bin __complete ''`. Running the previous command should output all the completion choices that skilled be returned if you do `./bin <TAB>`

**Comment by matheuscscp** [comment]
> See the second part of my previous answer: "This will also affect the hidden __complete"
> 
> The hidden __complete command needs to work for completion to work.
> 
> You can test it like this: `./bin __complete ''`. Running the previous command should output all the completion choices that should be returned if you do `./bin <TAB>`
> 
> Note that the kubectl example I reference above, handles that very specific case you need to handle.

thanks!! sorry for the slow thinking here :sweat_smile: `bin` can now have the default completion command :grin: :

```shell
➜  bin git:(completion) ./bin
completion  -- Generate the autocompletion script for the specified shell
ensure      -- Ensures that all binaries listed in the configuration are present
help        -- Help about any command
install     -- Installs the specified project from a url
list        -- List binaries managed by bin
prune       -- Prunes binaries that no longer exist in the system
remove      -- Removes binaries managed by bin
update      -- Updates one or multiple binaries managed by bin
```
