### ISSUE TITLE
cobra arg with @ prefix doesn't parse in powershell

### ISSUE THREAD

**Issue by sanghunjlee** [spf13/cobra#1929]
When I'm using the [at] symbol in my cobra args, Command Prompt parses it correctly while PowerShell omits the arg regardless of where the @-prefixed arg is.

I set up a test cmd:
```go
var testCmd = &cobra.Command{
    Run: func(cmd *cobra.Command, args []string) {
        fmt.Println(strings.Join(args, " "))
    },
}
```

And this is when it's executed on PowerShell:
```
PS C:\...\cobra-test> cobra-test test hello @world
hello
```

And when it's executed on cmd.exe:
```
C:\...\cobra-test> cobra-test test hello @world
hello @world
```

**Comment by marckhouzam** [comment]
In PowerShell does using `@world` as an argument to another program work?  I wonder if this is normal PowerShell behaviour.  PowerShell may need you to escape the `@` character?

**Comment by sanghunjlee** [comment]
Ah... It seems like a normal PowerShell behavior.

I tried testing with a short python code:
```python
def main():
    print(sys.argv)
```

It yields:
```
PS C:\...\scripts> python cli-test.py hello @world
['cli-test.py', 'hello']
```

**Comment by marckhouzam** [comment]
You can probably escape that character and the program, in this case cobra will read it. I’ll go ahead and close this as not cobra issue.
