### ISSUE TITLE
feature: support more group flags

### ISSUE THREAD

**Issue by YoniRomm** [spf13/cobra#1936]
I had a use cases where I needed:
1. I had 2 group of flags and I needed that one flag from each group will be presented (but together something like `MarkFlagsRequiredTogether` but between 2 groups)
2. enforce the flag value to be from a list of options
3. enforce exactly 1 flag to be presented from a group (similar to `MarkFlagsMutuallyExclusive`)

**Comment by marevers** [comment]
EDIT: my PR should actually address point 1 as well. You can create two flag groups and set `MarkFlagsOneRequired` and `MarkFlagsMutuallyExclusive` for both. This will enforce at least one flag and not more than one from each group.

The only thing not covered is 2, which, if I understand correctly is not about the flag itself (its name) but its value? I think there is no way to do that currently out-of-the-box, but you could also implement your own logic to check if the flag value comes from a list of expected options.

**Comment by gabguy** [comment]
@marevers MarkFlagsOneRequired function does not exist on the latest release (1.7.0).
It was added under commit c81c46a, but there is no tag that includes this addition.
Can you please create another release with this code in it?

**Comment by marevers** [comment]
@gabguy I am not a maintainer, so I cannot create releases. I do know, however, that the addition of `MarkFlagsOneRequired` is planned for the next release (1.8.0).
