### ISSUE TITLE
RFE: env var for disabling descriptions

### ISSUE THREAD

**Issue by scop** [spf13/cobra#1937]
In https://github.com/scop/bash-completion/pull/905, we've added fallback 3rd party completion loaders for various known commands, including some cobra powered ones, and more are expected to be added later. However, as it stands, this mechanism does not have any way for users to specify `--no-descriptions` if that's their preference.

We could create a bash-completion specific way to accomplish this, but in my opinion this would be better placed in cobra proper. An environment variable would serve this nicely I think: something like `COBRA_COMPLETION_NO_DESCRIPTIONS(=non-empty-value)` could be equivalent as if `--no-descriptions` was passed in the generator command line.

**Comment by marckhouzam** [comment]
Agreed. I've been thinking about this for a long time but never actually pulled the trigger.  Thanks for bringing it up.

**Comment by scop** [comment]
Quick take on it in https://github.com/spf13/cobra/pull/1938
