### ISSUE TITLE
zsh: command not found: cobra on mac after installation

### ISSUE THREAD

**Issue by rngallen** [spf13/cobra#1964]
I have run `go install github.com/spf13/cobra-cli@latest` but cobra still not recognized on terminal.
How can I resolve this?

**Comment by marckhouzam** [comment]
You have to make sure your PATH variable includes $GOPATH/bin

**Comment by NelsonIg** [comment]
I had the same issue. I don't know why but i had two go paths:

- `/usr/local/go/bin/`
- `~/go/bin/`  

the command ```go install github.com/spf13/cobra-cli@latest``` put it into `~/go/bin/` and i the moved it to `/usr/local/go/bin`. Then it worked.

**Comment by Nickadimas79** [comment]
@

**Comment by Nickadimas79** [comment]
So I hit this problem trying to install Cobra.
I used Homebrew for GoLang.
The did the usual commands for Cobra `go get -u github.com/spf13/cobra@latest` and `go install github.com/spf13/cobra-cli@latest`. I've tried what feels like everything but no matter what I always get the `zsh: command not found: cobra-cli` error when I type `cobra-cli`.

I'm on a new MacBook Air, Apple silicon, if that's of any importance here.
I also do use a .zshrc file, obviously, and tried updating that at least a million different ways. At a complete loss here... any help would be greatly appreciated.

**Comment by Nickadimas79** [comment]
@marckhouzam I think I've become extremely confused having messed with this for so long. I thought I did that in my .zshrc file. Do you have any examples or can you point me in a direction of a good way to do that by chany?

**Comment by marckhouzam** [comment]
`export PATH=$GOPATH/bin:$PATH`

**Comment by Nickadimas79** [comment]
Yep... I've done that... doesn't do anything for me.
I've tried it both in the .zshrc and as just a command in the terminal to see if I could get it to do anything at all.

**Comment by Nickadimas79** [comment]
Before the export:
➜  ~ echo $PATH
/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin

And after:
➜  ~ echo $PATH
/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin

The only difference is he `bin` at the very beginning. Something is just very odd but I just have no idea where to look anymore.

Also... if this helps at all.
➜  ~ go env  GOPATH
/Users/joshmorehead/go

**Comment by marckhouzam** [comment]
Looks like your `GOPATH` variable is not set. I’m not sure who sets that but you can always do `export GOPATH=$(go env GOPATH)` to set it first

**Comment by jay-SP** [comment]
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN

**Comment by ashrafatef** [comment]
I uninstalled the go installation from my laptop (mac m1) , I installed fresh one and ran the following 

- export GOPATH=$(go env GOPATH)
- export GOBIN=$GOPATH/bin
- export PATH=$PATH:$GOBIN

that worked for me 👍
