### ISSUE TITLE
Check if help command was invoked

### ISSUE THREAD

**Issue by pawelbeza** [spf13/cobra#1965]
Hey everyone,
quick question is it possible to check if default [help command ](https://github.com/spf13/cobra/blob/main/user_guide.md#:~:text=checkout%20Hugo.-,Help%20Command,-Cobra%20automatically%20adds) was  invoked?  

Normally I would call  [`command.helpCommand.CalledAs() == ""`](https://pkg.go.dev/github.com/spf13/cobra#Command.CalledAs:~:text=func%20(*Command)-,CalledAs%20%C2%B6,-added%20in%20v0.0.2) but unfortunately [helpCommand](https://github.com/spf13/cobra/blob/284f4101043c4b1faebde411caec35a7b6e36494/command.go#L174) is not exported.  
Just to be clear I don't want to override default helper command and I know that I can call [Commands()
](https://pkg.go.dev/github.com/spf13/cobra#Command.Commands:~:text=func%20(*Command)%20Commands%20%C2%B6) and find helper command there but I'm looking for some cleaner solution 🧐 

To give you an example why I need that is that I'm writing command which needs some authentication for all commands except help and some others (I'm skipping it by adding appropriate CalledAs checks).

**Comment by marckhouzam** [comment]
I'm not sure I understood correctly, but maybe you can do:

`cmd.Name() == "help"`

**Comment by pawelbeza** [comment]
@marckhouzam 
Apologies I could give some example. Let's say user called `cmd help`, I want to check if cmd was called with subcommand `help` and if that's the case I would skip authentication. Normally you can check if given command was called with [CalledAs](https://pkg.go.dev/github.com/spf13/cobra#Command.CalledAs:~:text=func%20(*Command)%20CalledAs%20%C2%B6)  so I could do somethis like `helpCommand.CalledAs()`  but here the problem is that this [helpCommand](https://github.com/spf13/cobra/blob/284f4101043c4b1faebde411caec35a7b6e36494/command.go#L174) is not exported and I believe there is no getter for this field.

**Comment by marckhouzam** [comment]
`CalledAs` is normally used to know if a command was called using one of its aliases. 

You probably want to know if the command called is a help command, so you want cmd.Name().

A code example would clarify what you’re trying to do.
