### ISSUE TITLE
Misleading shorthand flag panic message

### ISSUE THREAD

**Issue by mdhender** [spf13/cobra#1987]
Adding a BoolVarP with shorthand code of "h" to any flagset generates a misleading panic message:

```
panic: unable to redefine 'h' shorthand in "mapgen" flagset: it's already used for "flag" flag
```

The error makes it seem like the issue is with the "mapgen" flagset (in this example) when it's actually from the default help flagset.

To recreate, add a BoolVarP to the root command and then run the command with no arguments.

```
var flag bool
func init() {
	rootCmd.Flags().BoolVarP(&flag, "flag", "h", false, "flag")
}
```

This is with v1.0.5.

**Comment by marckhouzam** [comment]
This sounds like a good thing to improve. PR welcomed.

**Comment by roshanavand** [comment]
This message is coming from the `pflag` library, I created a PR [here](https://github.com/spf13/pflag/pull/381).

**Comment by marckhouzam** [comment]
Thanks @roshanavand !
Let's close this one in favor of the other.
