### ISSUE TITLE
`cobra-cli init` should refuse to overwrite existing files

### ISSUE THREAD

**Issue by richardjharris** [spf13/cobra#2008]
If `cobra-cli init` is run in a directory that already contains `main.go`, the file is overwritten without warning. This is a bit surprising. It would be better to refuse to run in this case.

**Comment by marckhouzam** [comment]
Thanks @richardjharris .  The`cobra-cli` had moved to its own repository at https://github.com/spf13/cobra-cli

We may already have an issue related to yours.

**Comment by richardjharris** [comment]
I see you do https://github.com/spf13/cobra-cli/issues/88

Sorry about that, closed!
