### ISSUE TITLE
Improve folder layout for cobra generator

### ISSUE THREAD

**Issue by labkode** [spf13/cobra#201]
It would be good to let the cobra generator to create subfolders under cmd if the added command is not a child of RootCmd. This leads to clear code organisation.

I have the commands 
`appName upload`
`appName benchmark upload`

and with cobra they go to the same file: upload.go

A good approach would be:
cmd/upload.go
cmd/benchmark.go
cmd/benchmark/upload.go

BTW, thanks for such valuable tool!

**Comment by spf13** [comment]
I like this idea a lot. Please contribute :) It would be a small but welcome change.

**Comment by spf13** [comment]
see #266

**Comment by bogem** [comment]
Main discussion in #266.
