### ISSUE TITLE
How to call a command from another command with flags 

### ISSUE THREAD

**Issue by ssantoshp** [spf13/cobra#2014]
Hey, I am trying to call a command with a specific flag from another command but I've been struggling to make it work. Here is what I am doing:

```go
var startCmd = &cobra.Command{
	Use:   "start",
	Short: "The central command for the CLI.",
	Long: `start can execute any of the other commands in the CLI.`,
	Run: func(cmd *cobra.Command, args []string) {
		getCmd.SetArgs([]string{"--data", "price"})
		getCmd.Run(cmd, os.Args[1:])
               // getCmdRun(cmd, []string{"--data", "price"}) -> tried this as well but failed too
	},
}

func init() {
	rootCmd.AddCommand(startCmd)
	startCmd.AddCommand(getCmd)
}
```

Each time it raises a warning from the `getCmd` command saying my flag is not recognized. How do we do that?

**Comment by marckhouzam** [comment]
You have to explicitly parse the flags. I think you can use `getCmd.ParseFlags([]string{"--data", "price"})` before calling `Run`

**Comment by ssantoshp** [comment]
Hey, thanks for the quick reply but I still get the same error when doing:

```go
	Run: func(cmd *cobra.Command, args []string) {
		getCmd.ParseArgs([]string{"--data", "price"})
		getCmd.Run(cmd, os.Args[1:])
	},
```

By the way, I can confirm that my `get --data price` works.

**Comment by marckhouzam** [comment]
@ssantoshp you have to get the result of the ParseFlags function and pas the arguments to Run. Don’t use os.Args

**Comment by ssantoshp** [comment]
Just tried this and didn't work either:
```go
			args1 := []string{"--data", "price"}
			getCmd.SetArgs(args1)
			getCmd.Run(cmd, getCmd.PersistentFlags().Args())
```

**Comment by marckhouzam** [comment]
> @marckhouzam But I see in the doc `func (c * Command) ParseFlags(args []string) error`, ParseFlags seem to return an error not a string array... Therefore, it doesn't work either?

Sorry my mistake. 

You can look in the `getCompletions()` function in `completions.go` for an example where we parse flags and arguments

**Comment by ssantoshp** [comment]
I cannot call this function directly from Cobra, right?

**Comment by ssantoshp** [comment]
```go
	flagCompletion := true
	_ = finalCmd.ParseFlags(append(finalArgs, "--"))
	newArgCount := finalCmd.Flags().NArg()

	// Parse the flags early so we can check if required flags are set
	if err = finalCmd.ParseFlags(finalArgs); err != nil {
		return finalCmd, []string{}, ShellCompDirectiveDefault, fmt.Errorf("Error while parsing flags from args %v: %s", finalArgs, err.Error())
	}
```

Are you talking about this (just to make sure)?

**Comment by marckhouzam** [comment]
I haven’t tried this but I think this may work
```
getCmd.ParseFlags([]string{"--data", "price"})
getCmd.Run(getCmd, []string{})
```

**Comment by ssantoshp** [comment]
That worked, thanks!
