### ISSUE TITLE
MarkFlagsOneRequired is not in the current go package distribution.

### ISSUE THREAD

**Issue by tvandalovsky** [spf13/cobra#2031]
I am working on a Cobra, v1.7.0, app using go, v1.21, and was trying to use the design pattern of setting two flags, x and y, to basicCmd.MarkFlagsOneRequired("x", "y") and basicCmd.MarkFlagsMutuallyExclusive("x", "y") however I continue to get the error that MarkFlagsOneRequired is undefined and when I search for the command in cobra pkg.go.dev it doesn't appear. However, I see for the code for the method on Github so I'm wondering how I could resolve this issue?

https://pkg.go.dev/github.com/spf13/cobra@v1.7.0#section-readme -> cobra package page for reference

**Comment by reedwade** [comment]
The most recently tagged release is at https://github.com/spf13/cobra/tree/v1.7.0 (released in April)

`MarkFlagsOneRequired()` is newer and what you're seeing on the main branch.

To make use of that you'd need to specify a commit or "latest" in your cobra requirements instead of v1.7.0.

**Comment by jinleileiking** [comment]
> The most recently tagged release is at https://github.com/spf13/cobra/tree/v1.7.0 (released in April)
> 
> `MarkFlagsOneRequired()` is newer and what you're seeing on the main branch.
> 
> To make use of that you'd need to specify a commit or "latest" in your cobra requirements instead of v1.7.0.

WE NEED NEW TAG!
