### ISSUE TITLE
ld: warning: -bind_at_load is deprecated on macOS warning while running

### ISSUE THREAD

**Issue by rr-jino-jose** [spf13/cobra#2033]
`ld: warning: -bind_at_load is deprecated on macOS`

I see this error while running with cobra even in subcommands

```
go run main.go get --help                                                                                                          took  12s at  07:21:10 PM
# command-line-arguments
ld: warning: -bind_at_load is deprecated on macOS
```

cobra version in use: github.com/spf13/cobra v1.7.0

Any help is appreciated.

**Comment by jonathan-innis** [comment]
Seeing the same error as well. Has there been any investigation on what might be going on here?

**Comment by TheKLARKEN** [comment]
I was able to learn more about this issue by looking at the comment below. I haven't resolved it, since it doesn't show up in my compiled binary, but at least there's more info on it out there. :)

https://github.com/golang/go/issues/61558#issuecomment-1648748966

**Comment by marckhouzam** [comment]
Thanks @TheKLARKEN !
So it seems such warnings can be ignored and the Go project will be addressing them. 

I will close this since it’s not a cobra problem
