### ISSUE TITLE
local flags on the root command aren't accepted

### ISSUE THREAD

**Issue by amery** [spf13/cobra#2038]
I have a use case where the root command is the primary command and it has its own flags, and subcommands implement extra functionality. For the flags of a command not to be inherited by the subcommands one has to use LocalFlags(), but unfortunately they are ignored on the root

test case pushed to https://github.com/amery/cobra-issue-root-localflags

```go
package main

import (
	"log"

	"github.com/spf13/cobra"
)

func main() {
	rootCmd := &cobra.Command{
		Use:   "test",
		Short: "test issue with local flags at the root",
		Run: func(_ *cobra.Command, _ []string) {
			log.Print("hello")
		},
	}

	_ = rootCmd.LocalFlags().BoolP("enable-thing", "w", false, "enables thing only for the root command")

	err := rootCmd.Execute()
	if err != nil {
		log.Fatal(err)
	}
}
```

```
$ go run ./ -w
Error: unknown shorthand flag: 'w' in -w
Usage:
  test [flags]

Flags:
  -w, --enable-thing   enables thing only for the root command
  -h, --help           help for test

2023/10/05 17:21:37 unknown shorthand flag: 'w' in -w
exit status 1
```
Is this something that is expected to work (i.e. bug) or is this behaviour by design and I should make my own Parse logic?

as a side question, is there a way to define a boolean flag without long option?

**Comment by marckhouzam** [comment]
Try `rootCmd.Flags().BoolP(...`

**Comment by amery** [comment]
> Try `rootCmd.Flags().BoolP(...`

thank you, using Flags() instead of LocalFlags() works as intended. root flags aren't leaked to subcommands.

Thank you!
