### ISSUE TITLE
Installation Instructions Produce An Error

### ISSUE THREAD

**Issue by 4rc0s** [spf13/cobra#2042]
New to Go and starting with Cobra to build CLI apps as a learning exercise. Already hitting issues. Following the install instructions on Github and the Cobra website lead to this error:

```
$ go get -u github.com/spf13/cobra@latest
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

Trying the method suggested by Go's error message resulted in things like:

```
$ go install github.com/spf13/cobra/cobra@latest
go: downloading github.com/spf13/cobra v1.7.0
go: github.com/spf13/cobra/cobra@latest: module github.com/spf13/cobra@latest found (v1.7.0), but does not contain package github.com/spf13/cobra/cobra
```

This is on Linux with a new Go install (`go version go1.21.2 linux/amd64`).

**Comment by marckhouzam** [comment]
> go: go.mod file not found in current directory or any parent directory.
>	'go get' is no longer supported outside a module.

You first need to initialize your project: `go mod init <newModulePath>`

**Comment by 4rc0s** [comment]
Many thanks for the clarification.
