### ISSUE TITLE
Nested Query To set value

### ISSUE THREAD

**Issue by yonatan555** [spf13/cobra#2072]
I have this json:
{
  "otlp_agent_collectors": [
    {
      "interval_in_seconds": 2,
      "name": "watch_dog",
      "state": "disabled"
    },
    {
      "interval_in_seconds": 2,
      "name": "script",
      "state": "disabled"
    },
    {
      "interval_in_seconds": 2,
      "name": "otlp_agent",
      "state": "disabled"
    },
    {
      "interval_in_seconds": 2,
      "name": "mis",
      "state": "disabled"
    },
    {
      "interval_in_seconds": 2,
      "name": "blades",
      "state": "disabled"
    },
    {
      "interval_in_seconds": 2,
      "name": "deployment",
      "state": "disabled"
    },
    {
      "interval_in_seconds": 2,
      "name": "mds",
      "state": "disabled"
    },
    {
      "interval_in_seconds": 2,
      "name": "processes",
      "state": "disabled"
    }
  ],
   "script_collector_settings": {
    "metrics": []
  }
}

and I want to set a value using this query:
set(otlp_agent_collectors[2].state, "enabeld")
but it didn't work, what can I change the value?

**Comment by marckhouzam** [comment]
This should be opened on viper
