### ISSUE TITLE
Huge bash completions file that's very slow to source

### ISSUE THREAD

**Issue by memeplex** [spf13/cobra#2107]
I'm opening this issue because of repeated reports about rclone's bash completions file being too big and slow to load:

- https://github.com/rclone/rclone/issues/7000
- https://github.com/rclone/rclone/issues/7626
- https://github.com/rclone/rclone/issues/2909

A simple python script that heuristically detects large duplicated chunks was able to reduce the size of the script from 130000 lines to 5000 lines, so clearly there is room for improvement.

In https://github.com/rclone/rclone/issues/7000 it was stated that:

> We use the bash completion auto generator from the cobra package:
> https://github.com/spf13/cobra/blob/main/shell_completions.md
> If someone wants to fix this, it needs to be fixed in https://github.com/spf13/cobra/

**Comment by marckhouzam** [comment]
@memeplex You should use `GenBashCompletionV2()` instead of the legacy `GenBashCompletion()`

**Comment by marckhouzam** [comment]
I’m going to close this as there is a solution
