### ISSUE TITLE
How do I use multiple characters in a short parameter?

### ISSUE THREAD

**Issue by maijun-sec** [spf13/cobra#2111]
When I use multiple characters in a short parameter, I got the following error:
![image](https://github.com/spf13/cobra/assets/59104148/080c3b06-345d-4ead-be9c-37f55edde8c7)
How can I use multiple characters in this scenario? Thanks very much!

**Comment by maijun-sec** [comment]
The code I used to add arguments is as follows:
`func init() {
	rootCmd.Flags().BoolP("use-user-include", "uui", true, "Use user include search path.")
	rootCmd.Flags().StringP("xxxxxxxx", "x", "test", "testargadsfa")
}`

And I directly debug the code in GoLand IDE, and there is no arguments.

**Comment by capsci** [comment]
Hi @maijun-sec ; cobra cli can accept multichar shorthand.

[cobra](https://github.com/spf13/cobra/blob/main/README.md) mentions it is "Fully POSIX-compliant flags (including short & long versions)" and only allows single characters for shorthands (similar to many other GNU commands)

**Comment by marckhouzam** [comment]
As @capsci mentioned, the short parameter can only be a single character, so you cannot use "uui" as the second argument to `rootCmd.Flags().BoolP("use-user-include", "uui", true, "Use user include search path.")`

**Comment by maijun-sec** [comment]
ok. I know, thank you very much.
