### ISSUE TITLE
Release 1.8.1?

### ISSUE THREAD

**Issue by nirs** [spf13/cobra#2139]
There are few fixes since 1.8.0 - the fixes I'm interested in are mainly:

- a73b9c391a9489d20f5ee1480e75d3b99fc8c7e2
- df547f5fc6ee86071f73c36c16afd885bb4e3f28

I can build with latest cobra, but I would like to depend on released version.

**Comment by jpmcb** [comment]
Yes, I've been swamped recently, I'll get something out this week 👍🏼

**Comment by ichekrygin** [comment]
PIng...

**Comment by ichekrygin** [comment]
> Ping...

🫨 Just realize that @jpmcb responded last week (and not in May) ...

**Comment by jpmcb** [comment]
https://github.com/spf13/cobra/releases/tag/v1.8.1 has been cut - thank you everyone for your patience! 🚀 🐍

**Comment by nirs** [comment]
Thanks for the release!

I posted a PR to update cobra in the sample plugin to use the new help text improvements:
https://github.com/kubernetes/kubernetes/pull/125641
