### ISSUE TITLE
how to set `nil` as default value in `BoolVar`?

### ISSUE THREAD

**Issue by OpenWaygate** [spf13/cobra#2142]
I want to keep a variable as nil except explicitly set, but only `true` or `false` is allowed.
```go
myCmd.Flags().BoolVar(&isMine, "isMine", nil, "")
```

**Comment by marckhouzam** [comment]
In Go a bool cannot be nil but only true or false. If you’re thinking of the pointer you’re passing in, that cannot be nil as it must represent a location where cobra can write true or false
