### ISSUE TITLE
Is it possible to easily hide default flag values from help?

### ISSUE THREAD

**Issue by Drakmyth** [spf13/cobra#2150]
I have a command that displays the following in its help text:
```
Flags:
  -h, --help            help for sample
  -e, --enable-screen   Turn the screen on (default false)
  -S, --no-sound        Turn the sound off (default true)
  -s, --seed uint       Supply a randomization seed (default 9309262286194859912)
```
The default value for `seed` is supplied as `rand.Uint64()` so it is randomly generated every time the help is printed and will not be the actual value used when the flag is not supplied. Because of this, I would like to stop that flag from printing the default value into the help text.

I could do this by using 0 as a sentinel value, by adding a layer of indirection with a second variable, or by overriding the help text template, but all these approaches are rather inconvenient when the text itself is the only thing I'd like to change.

Similarly, I find the `(default true)` for the `--no-sound` option not entirely intuitive. I can, of course, explain it one way or the other in the description, or change the option name itself to make it less ambiguous, but again I'd prefer not to have to change the behavior or interface of my app just to make the help text easier to understand.

I'm very new to Cobra, but didn't see any clear way to disable the display of default values either on a per-flag basis or globally. Is there a way to do this without resorting to the approaches mentioned above?

**Comment by Drakmyth** [comment]
> if you don't want to show the default value you need to use the zero value. So if you flag is uint64 you can use 0 to show no default value.

I see. I wasn't aware of the `Changed` method. I was hoping I could just hide the default value from the help text without changing the actual default value I'm providing in the flag initialization, but as long as I can determine if the zero value was provided by the user or not that's fine.

> Regarding the boolean default I don't understand what is the issue
It's really the same issue. If I have a `--no-sound` flag that has a default of `true` the help text wording is confusing. Does `true` mean there is sound? Or does it mean "true, there is no sound"? I acknowledge this is more of an academic example as the easy answer is not to use negative-tense flags but it's another case where if the default value were hidden from the help text it would be immediately clear, so I was looking for a way of hiding it without having to change the logic or renaming the flag.

In any event, it sounds like there is no way of just hiding the default value from the help text without writing a custom template, but this can be worked around pretty trivially by checking for the zero value with the `Changed` method and providing the default in that check. Thank you for enlightening me to that approach!

**Comment by nirs** [comment]
> > Regarding the boolean default I don't understand what is the issue
> 
> It's really the same issue. If I have a `--no-sound` flag that has a default of `true` the help text wording is confusing. Does `true` mean there is sound? Or does it mean "true, there is no sound"? I acknowledge this is more of an academic example as the easy answer is not to use negative-tense flags 

Yes!

> but it's another case where if the default value were hidden from the help text it would be immediately clear, so I was looking for a way of hiding it without having to change the logic or renaming the flag.

How about:

```
$ cat main.go 
package main

import (
	"github.com/spf13/cobra"
)

func main() {
	c := &cobra.Command{
		Use: "test",
		Run: func(cmd *cobra.Command, args []string) {},
	}
	c.Flags().BoolP("enable-screen", "e", false, "Turn screen on")
	c.Flags().BoolP("enable-sound", "s", false, "Turn sound on")
	c.Execute()
}

$ go run main.go -h
Usage:
  test [flags]

Flags:
  -e, --enable-screen   Turn screen on
  -s, --enable-sound    Turn sound on
  -h, --help            help for test
```

This is more consistent and keeps the current behavior unless I got the negative flag wrong, which is common failure.

Also I don't know why you got "(default false)" for enable-screen - it should not have default  since false is the zero value.

**Comment by nirs** [comment]
@marckhouzam Do you think the docs should be improved in this area? Or maybe this should be documented better in pflag?

**Comment by Drakmyth** [comment]
> This is more consistent and keeps the current behavior unless I got the negative flag wrong, which is common failure.

Yeah, this is definitely the actual answer. While toying around with my application I had behavior enabled by default and my thought was to use the flag to disable it. After sitting with it, the better approach is definitely to have the behavior off by default and use the flag to enable.

> Also I don't know why you got "(default false)" for enable-screen - it should not have default since false is the zero value.

You're correct, false doesn't print. I was copy-pasting strings together to build that example text from my rather messy output and assumed it would output for both and that was sufficient for my question, but testing it with a default false shows it correctly does not print.

> @marckhouzam Do you think the docs should be improved in this area? Or maybe this should be documented better in pflag?

Just to throw my opinion in on this while I'm replying to the previous comment: I think this is probably a pretty niche case (as I couldn't find the answer in the existing docs nor did I see anyone else asking similar questions), so I don't know that I would expect an update. That said, if I were to think about what could have been documented that would have pre-empted me opening this ticket I have two thoughts:

1. Maybe highlight the two points you called out in your solution - that the zero value causes the default to not be printed in the help text, and that you can use the `Changed` method to tell whether the zero value was provided by the user or not. I see no reference to either of these in the current pflag readme or on the [cobra.dev](https://cobra.dev/) page.
2. More generally, I was not expecting to need to dig into pflag. I would classify Cobra's use of pflag as an implementation detail that a user need not concern themselves with unless they were experiencing some bug or trying to hook into the library at a deeper level. To be fair, the cobra.dev page makes it clear that Cobra relies on pflag for its handling of flags, but it is difficult to tell from a user's perspective which parts of the interface come from Cobra and which come from pflag. I had expected that any pflag features exposed to me would be documented on the Cobra page, and that there may be some features of pflag that would be wrapped by Cobra and not exposed and thus it would not necessarily be worthwhile to drill into the pflag documentation itself.

I don't mean to level that second point as a harsh criticism of this project, merely as an explanation of my mindset using a new library I had no experience with. I have found Cobra to be a wonderful tool and it has made it phenomenally easy to get a fully featured CLI app up and running, and I have profound appreciation for the both of you and the other contributors to this project for the wonderful work that has gone into it!
