### ISSUE TITLE
Help command fails on flags

### ISSUE THREAD

**Issue by marckhouzam** [spf13/cobra#2155]
If a user uses the `help` command with flags on the command-line the command will fail, even if the flags are valid.
For example, something like:
`prog help sub --myflag`
will fail with a flag error and will show the help of the `help` command instead of the expected help text:
```
$ prog help sub --myflag
Error: unknown flag: --myflag
Usage:
  prog help [command] [flags]

Flags:
  -h, --help   help for help
```
On the other hand, using `--help` works:
```
$ ./prog sub --myflag -h
Usage:
  prog sub [flags]

Flags:
  -h, --help     help for sub
  -m, --myflag   myflag help
```

The `help` command should work even if there are flags on the command-line, especially if those flags are valid.

**Comment by nirs** [comment]
I don't think this is a bug the help command should not be an alias to -h,--help. It it should be a way to get more in-depth help on a command, and in this case no arguments are needed.

**Comment by marckhouzam** [comment]
> I don't think this is a bug the help command should not be an alias to -h,--help. It it should be a way to get more in-depth help on a command, and in this case no arguments are needed.

Valid point.  
That is good enough for me.
