### ISSUE TITLE
[Question]  If I say exactly one parameter is required, how can I give a description so it it shows up if they --help

### ISSUE THREAD

**Issue by lknite** [spf13/cobra#2156]
## question ##
I'd like it to say something like, "appctl pull \<object\> [flags]":
```
$ ./appctl pull
Error: accepts 1 arg(s), received 0
Usage:
  appctl pull [flags]

Flags:
  -h, --help   help for pull

accepts 1 arg(s), received 0
```

I don't know what the arg will be, but I know it is a type 'object'.

## work around ##
This works but seems like the wrong approach because the flags are no longer auto-generated:
```
pullCmd.SetUsageTemplate("Usage:\n  appctl pull <name> [flags]\n" +
		"\n" +
		"Flags:\n  -h, --help   help for pull\n")
```

**Comment by marckhouzam** [comment]
There are different ways to override the help: https://github.com/spf13/cobra/blob/main/site/content/user_guide.md#defining-your-own-help

**Comment by lknite** [comment]
thank you
