### ISSUE TITLE
Any way to have a "persistent" parameter that appears before the subcommand?

### ISSUE THREAD

**Issue by davidmichaelkarr** [spf13/cobra#2159]
I'm trying to write a Cobra app where one parameter always appears before the subcommand, like this:

    app xx subcommand

All subcommands will need access to the "xx" value.

I've read about "persistent flags", but that seems like something different.

**Comment by marckhouzam** [comment]
I think you just need to extract `xx` from `os.Args` before calling `rootCmd.Execute()`

**Comment by nirs** [comment]
Is xx an option? (--xx yy)? Why it must be before the sub-command?

**Comment by davidmichaelkarr** [comment]
Actually, I guess I figured this out.  Digging into the code, I found the "SetArgs" function.  I just call it as:

    rootCmd.SetArgs(os.Args[2:])

Right after extracting the first parameter.

**Comment by marckhouzam** [comment]
Even better!  👍
