### ISSUE TITLE
how to add entry to `Available Commands` help section. 

### ISSUE THREAD

**Issue by mkyc** [spf13/cobra#2160]
I have pluggable app. I use `kubectl` approach to subcommands, so for example if I run `my-app subcommand` then `my-app` binary is searching for `my-app-subcommand` binary and runs it.

All is cool, but I wanted to add that `subcommand` entry into `my-app help` output. Now I have: 

```shell
Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  install     A brief description of your command
  upgrade     A brief description of your command
```

but I'd like to have 

```shell
Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  install     A brief description of your command
  upgrade     A brief description of your command
  subcommand   subcommand plugin
```

I can generate that `subcommand   subcommand plugin` line easily from directory where plugins are installed ... but I'm not sure what is the easiest way to add those entries to output. 

I don't really care if that is even in `Available Commands` section. It could be anywhere.

**Comment by marckhouzam** [comment]
The way kubectl does this is that it creates a "stub" command for each sub-command you have.  The Run function of that stub sub-command is the one that calls the corresponding binary.  By having such stub sub-commands, the help shows them automatically.

**Comment by mkyc** [comment]
Thx @marckhouzam ! 

With additional `cmd.DisableFlagParsing = true` that approach solves my problem nicely.
