### ISSUE TITLE
How to distinguish default value and manually set value of a flag?

### ISSUE THREAD

**Issue by OpenWaygate** [spf13/cobra#2161]
For a flag like this, I want to distinguish `false` between the default `false` and `--isLarge false`, is there a way to make it?

```
myCmd.Flags().BoolVarP(&isLarge, "isLarge", "l", false, "large or not")
```

**Comment by marckhouzam** [comment]
You can check if the flag was set on the command line. You do that by getting the flag and checking it’s `Changed` field.  Here is an example: https://github.com/spf13/cobra/blob/e94f6d0dd9a5e5738dca6bce03c4b1207ffbc0ec/completions.go#L531

**Comment by OpenWaygate** [comment]
Thank you, it works!
