### ISSUE TITLE
Root Command doesn't work with sub commands

### ISSUE THREAD

**Issue by gyanendrasng** [spf13/cobra#2162]
I used cobra-cli to make a new cobra project and added a subcommand to the root command, but once I add the subcommand the Run function in root command never runs even if the the subcommand isnt called.

main.go file
```
var RootCmd = &cobra.Command{
	Use:   "cli",
	Short: "A description of the task you want AI to perform",
	Run: func(cmd *cobra.Command, args []string) {
		println("Please provide a prompt")
		if len(args) == 0 {
			cmd.Help()
			return
		}
	},
}

var LoginCmd = &cobra.Command{
	Use:   "login",
	Short: "Login to CLI",
	Long:  `Login to CLI using your email and password.`,
	Run: func(cmd *cobra.Command, args []string) {
                println("Please provide a prompt")
	},
}

RootCmd.AddCommand(LoginCmd)

RootCmd.Execute()
```

Here is the output for all cases

`go run main.go` Help output for root command
`go run main.go` Login Command works
`go run main.go test(or any gibbrish)` Command not found, what I want is the Root command runs if the subcommand doesn't matches

**Comment by marckhouzam** [comment]
Set the `Args` field on the root command. You can use `cobra. ArbitraryArgs()` for instance.

**Comment by gyanendrasng** [comment]
Thanks for the answer, will be closing the issue
Thanks a lot
