### ISSUE TITLE
Issues with flags marked as mutually exclusive during testing

### ISSUE THREAD

**Issue by consolethinks** [spf13/cobra#2163]
If I set up two flags as mutually exclusive, and I set one or the other in separate test runs, then Cobra will still think that I have set them at the same time. Their values will be set correctly, but the error message about mutual exclusivity remains. 

Is there any way to get around this or to fix this?

**Comment by marckhouzam** [comment]
If all this happens in the same function you will need to test the flags as unset. Here is an example: https://github.com/spf13/cobra/blob/e94f6d0dd9a5e5738dca6bce03c4b1207ffbc0ec/completions_test.go#L276-L277
