### ISSUE TITLE
Weird behavior in terminal output.

### ISSUE THREAD

**Issue by torbenconto** [spf13/cobra#2169]
I am building a cli password manager using cobra and recently some odd behavior has been happening with the terminal output. Specifically, a newline is being printed before every single output ran by my program. I have tested this with every command on arch linux, ubuntu, and debian and seen the same behavior on each OS. This should be able to be reproduced by cloning my repo (https://github.com/torbenconto/gopwd) and simply running go run . inside of it (also happens when built and ran). I searched everywhere through my code to find something that would cause this behavior and came up empty handed, that's why I'm posting here. Some help in determining if it's simply an error with my code or a bug in cobra would be greatly appreciated. Thanks, Torben.
![image](https://github.com/user-attachments/assets/78952224-917c-4fcd-a994-883cb124dd22)

**Comment by itachi-19** [comment]
[Found the culprit](https://github.com/torbenconto/gopwd/blob/5deb44c87559327a7d346dee4bfdd7108cc8a08b/cmd/show.go#L102)

**Comment by torbenconto** [comment]
Thanks so much! It makes a lot of sense that it was in the init() now, I just couldn't find it.
