### ISSUE TITLE
Question: See if a flag was set by the user

### ISSUE THREAD

**Issue by DavidVorick** [spf13/cobra#23]
Is there a way that I can see if a user set a flag, vs. just used the default?

Desired behavior:
1. If no config file is specified, use default flag value.
2. If config file is specified, and the user did not set the flag, use the value in the config file
3. If config file is specified, but the user _did_ set the flag, use the value specified by the user, even if it's just the default flag value.

I'm trying to avoid the situation where a non-default is set in the config, but the user wants to force the program to use the default.

I have a hacky solution that involves parsing the flags twice using different defaults, is there a better approach?

**Comment by ghodss** [comment]
For posterity, the Changed boolean works great, and is definitely a useful addition. :)

**Comment by qiangli** [comment]
For those people like me wondering why it is not working; it took me a little debugging the cobra code to figure out: `Flags().Changed` wont work in the init function, it has to be in a later stage such as `Args` hook.
