### ISSUE TITLE
cobra init can't create subdirectories

### ISSUE THREAD

**Issue by drewwells** [spf13/cobra#231]
The docs mention that a typical cobra setup is

/app/main.go
/app/cmd/root.go

Most apps aren't setup this way and including cobra itself! For instance, doing this:

cobra init github.com/spf13/cobra/cobra // Unknown directory

A more typical Go setup is `github.com/org/project/cmd/cmdname` which are how the go cmd tools are setup https://github.com/golang/go/tree/master/src/cmd. Is there a way to configure cobra generate to create a cli like this?

**Comment by bogem** [comment]
I rewrote cmd in #428, so update the cmd please and now it should work.
