### ISSUE TITLE
Positional Args

### ISSUE THREAD

**Issue by alapidas** [spf13/cobra#233]
Is there a way to use positional arguments?  I read through the docs, but I'm not seeing it.

I do see an example in the README:

```
git clone URL --bare
```

but I can't find a way to do this where you describe the positional args for a command.

**Comment by apriendeau** [comment]
One of the advantages is that uses POSIX style flags where they can be placed anywhere vs go's default behavior of using only positional arguments. You can create a flag that only works for one command but it is not restricted to a certain position.

**Comment by johnSchnake** [comment]
I believe you just are supposed to use a PreRun command to grab/parse those arguments as needed (those which are not flags).

**Comment by bogem** [comment]
Take a look at #395
