### ISSUE TITLE
Question: How to use license text from config

### ISSUE THREAD

**Issue by mwmahlberg** [spf13/cobra#243]
Albeit `cobra` states it, a the field `licensetext` from the config file is ignored.

A proper documentation would be helpful, here.

**Comment by ianwalter** [comment]
It looks like this functionality doesn't actually exist. You can specify a `license` and if it matches one of the licenses included in cobra it will use that license but you can't specify your own. I'll submit a pull request to add this functionality which I think will also take care of #249.

**Comment by dc0d** [comment]
Still not fixed.

**Comment by mwmahlberg** [comment]
@jharshman I can recheck, if that is of any help.

**Comment by johnSchnake** [comment]
Trying to clean up the backlog (#1600) and I was unable to repro this. Using the example yaml from #261 
```
license:
  header: This file is part of {{ .appName }}.
  text: |
    {{ .copyright }}
    This is my license. There are many like it, but this one is mine.
    My license is my best friend. It is my life. I must master it as I must
    master my life.  
```
I did `cobra init --config mycfg.yaml` and the LICENSE file and headers were both customized as expected.

If you think this was closed prematurely, please reopen with more details about what steps you took to recreate the problem.
