### ISSUE TITLE
PersistentFlags not copied to sub commands

### ISSUE THREAD

**Issue by elliotpeele** [spf13/cobra#245]
It looks like you intended to copy PersistentFlags to sub commands via Command.mergePersistentFlags, however this doesn't appear to work. 

In my sample project, I have a PersistentPreRun that reads from a persistent flag. This works when the root command is executed. However, when called through sub1 or sub2 the PersistentPreRun fails when accessing the "toggle" command line value.

In my actual application, I have a debug flag which is defined at the root level including a similar PersistentPreRun for setting up log levels. When the PersistentPreRun is executed through a subcommand, the debug value is always false.
1. https://github.com/elliotpeele/cobratest

**Comment by bogem** [comment]
#414 maybe fixed your problem. Please check
