### ISSUE TITLE
MIT license file header, but Apache LICENSE file

### ISSUE THREAD

**Issue by colemanserious** [spf13/cobra#247]
Using `license: MIT` via my config file, I get MIT text in the source files (good) but an Apache v2 LICENSE file.  If folks don't notice this and adjust, they'll have a license compliance issue.  

Steps I used to reproduce (though no reliance expected on any particular github golang project): 
* Use a cobra.yaml that looks like:
`
author: Tina Coleman <colemanserious@gmail.com>
license: MIT
`
* cobra init github.com/colemanserious/furby-gobot --config .cobra.yaml
* cobra add burp 

Inspect the result main.go, cmd/burp.go, and LICENSE file.

**Comment by spf13** [comment]
This issue has been resolved. Thanks for the feedback.
