### ISSUE TITLE
Add ExecuteArgs or similar

### ISSUE THREAD

**Issue by tj** [spf13/cobra#251]
Looks like there's no `Execute` alternative that isn't coupled to `os.Args`, would you accept a PR?

Also as a side note is it possible to prevent parsing of flags after a command name? That's my end-goal here so if that's possible then great! The use-case is to "proxy" to another command, without `--` tough, otherwise effectively the same issue.

**Comment by spf13** [comment]
@tj 
Does SetArgs do what you want? 
https://godoc.org/github.com/spf13/cobra#Command.SetArgs

I think it would be a good feature to add the ability to skipFlagParsing or something which would be very useful for wrapper style programs. In this case the strings after the command would just be in the Args. 
Please feel free to submit a PR with this feature. It should be configured on a command without persisting to children.

**Comment by tj** [comment]
Awesome I missed SetArgs, that'll do for now! When I have some time I'll take a look at adding support here

**Comment by wreed4** [comment]
I know this is old, but it seems the SetArgs no longer does what it seems to suggest.  I am using it and still `os.Args[1:]` is being used.  I tracked it down to https://github.com/spf13/cobra/blob/master/command.go#L818 and subsequently https://github.com/spf13/cobra/blob/master/command.go#L854.  This means that the args that are actually passed to the command from the Flags, not from the Command itself.  Unless I'm doing something wrong, which is more than possible.

**Comment by oytuntez** [comment]
@wreed4  that is my experience as well.
