### ISSUE TITLE
Only one *PreRun* and *PostRun* allowed

### ISSUE THREAD

**Issue by Thor77** [spf13/cobra#253]
``` go
package main

import (
    "fmt"
    "github.com/spf13/cobra"
)

var RootCmd = &cobra.Command{
    Use: "test",
    Run: func(c *cobra.Command, args []string) {
        fmt.Println("Run")
    },
    PreRun: func(c *cobra.Command, args []string) {
        fmt.Println("PreRun")
    },
    PreRunE: func(c *cobra.Command, args []string) error {
        fmt.Println("PreRunE")
        return nil
    },
    PostRun: func(c *cobra.Command, args []string) {
        fmt.Println("PostRun")
    },
    PostRunE: func(c *cobra.Command, args []string) error {
        fmt.Println("PostRunE")
        return nil
    },
}

func main() {
    if err := RootCmd.Execute(); err != nil {
        fmt.Println(err)
    }
}
```

Expected output:

```
PreRunE
PreRun
Run
PostRunE
PostRun
```

Output:

```
PreRunE
Run
PostRunE
```

**Comment by algrebe** [comment]
@Thor77 Yes, I believe you are allowed to use either hook or hookE, not both. Using hookE returns the error back to you, so you can decide to do error handling and recovery.

**Comment by Thor77** [comment]
I know. I think that is a bug/missing feature, because there are some use-cases, where you want to use both.

**Comment by johnSchnake** [comment]
Being this old I'm sure this can be removed.

If someone ever wants to use two prerun hooks, just use the one that bubbles the error, call all the methods you want there, and return whichever error is relevant. The library itself doesn't need to support setting/using both.
