### ISSUE TITLE
Long description formatting

### ISSUE THREAD

**Issue by lordnynex** [spf13/cobra#262]
Hello,

I am really enjoying the ease of developing CLI applications with cobra. Out of boredom last night I started trying to augment the help output to be more useful. For organization I've created a  file in the cmd package that just defines a bunch of `cmdLongDescription`constants. It seems that leading whitespace is always trimmed from long description output. Is there any way around this?

What I'm attempting to do is kindof pointless but if possible I'd like to do it for fun. A really stupid example:

``` go
const (
    testCobraDesc = `
  ____      _
 / ___|___ | |__  _ __ __ _
| |   / _ \| '_ \| '__/ _' |
| |__| (_) | |_) | | | (_| |
 \____\___/|_.__/|_|  \__,_|

Who doesn't love figlet!?
`
)
```

``` bash
$ go run main.go testcommand --help
____      _
 / ___|___ | |__  _ __ __ _
| |   / _ \| '_ \| '__/ _' |
| |__| (_) | |_) | | | (_| |
 \____\___/|_.__/|_|  \__,_|

Who doesn't love figlet!?
```

The same thing happens for long descriptions that contain a 'blank line' before long text instead of ascii art.

**Comment by psuter** [comment]
Ran into the same issue today. Inserting a non-breakable space did not fool the trim function.

**Comment by dnephin** [comment]
The trim is only being done in `Command.HelpTemplate()` (https://github.com/spf13/cobra/blob/master/command.go#L324-L335), so you can fix this by setting a new one using `cmd.SetHelpTemplate()`. The template is pretty small, so it's not much duplication.

**Comment by psuter** [comment]
...but a zero-width space did the trick! (`"\u200B"`), because it's not part of the unicode standard list of whitespace characters.
