### ISSUE TITLE
Command with only hidden flags still shows "Flags:" section

### ISSUE THREAD

**Issue by johnSchnake** [spf13/cobra#267]
Create a command with 1 flag marked as hidden, run `./app command -h` and you see the "Flags:" header but no flags.  The command should be checking that there are _available_ flags, not just `.HasFlags` which is what the template does.

Example program:
```
package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

func main() {
	var s string
	RootCmd := &cobra.Command{
		Use: "mycmd",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Println("foo bar", s)
		},
	}
	RootCmd.Flags().StringVar(&s,"flagname","","a string flag",)
	RootCmd.Flags().MarkHidden("flagname")
	RootCmd.Execute()
}
```

Output of `go run onlyhidden.go -h`

```
Usage:
  mycmd [flags]

Flags:

```

**Comment by apriendeau** [comment]
When you call `.Flags()`, it returns an instance of `*flag.FlagSet`. So you are actually marking `pflag` to hide flags. So you are actually calling [flagset.MarkHidden](https://godoc.org/github.com/spf13/pflag#FlagSet.MarkHidden). You will need to create a template for the that command to hide the flags since its not actually telling cobra to hide anything.

**Comment by johnSchnake** [comment]
I agree that the hiding of a flag is handled on the pflags level by changing the hidden field on the flag and modifying the usage. However, the default usage template relies on the `HasFlags()` logic which I think is inappropriate in this user facing context.

Just like cobra checks if there are available subcommands before showing the subcommands header, we should be checking if there are available flags before showing the flags header.

**Comment by apriendeau** [comment]
I agree with you here and I think your solution is nicely put. I was thinking on how to solve this issue, you nailed it, IMO.

**Comment by johnSchnake** [comment]
OK, just waiting for pflag to get updated then will update cobra.

**Comment by eparis** [comment]
pflag done.
