### ISSUE TITLE
Shorthand flag redefinition doesn't print out error message before panic

### ISSUE THREAD

**Issue by ghodss** [spf13/cobra#27]
When I (accidentally) do a shorthand flag redefinition I get:

```
$ go run cmd/kubectl/kubectl.go get rc
panic: shorthand redefinition

goroutine 16 [running]:
runtime.panic(0x30d4a0, 0xc2080017a0)
        /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/panic.c:279 +0xf5
```

But in the code I see it's supposed to print out a message first:

```
if alreadythere {
        fmt.Fprintf(f.out(), "%s shorthand reused: %q for %s already used for %s\n", f.name, c, flag.Name, old.Name)
        panic("shorthand redefinition")
}
```

But the message isn't appearing. I think f.out() must not be flushing in time. If I change it to fmt.Printf(...), I get the correct behavior.

```
$ go run cmd/kubectl/kubectl.go get rc
get shorthand reused: 'h' for host already used for help
panic: shorthand redefinition

goroutine 16 [running]:
runtime.panic(0x30d3c0, 0xc208001520)
        /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/panic.c:279 +0xf5
```

**Comment by kris-nova** [comment]
> Perhaps an explicit panic isn't the best thing here.

I would be willing to +1 not using an explicit panic here. Also I think the error message 

> shorthand redefinition

could use a little more verbosity. Suggest:

> Unable to redefine $shorthandValue in cobra command $cmd

Maybe even a line as well. For me, I was debugging this panic and ofc the last place I greped for it was in the Cobra package 😄

**Comment by bogem** [comment]
It's because of these lines:
```go
func (c *Command) Flags() *flag.FlagSet {
	if c.flags == nil {
		c.flags = flag.NewFlagSet(c.Name(), flag.ContinueOnError)
		if c.flagErrorBuf == nil {
			c.flagErrorBuf = new(bytes.Buffer) // <--
		}
		c.flags.SetOutput(c.flagErrorBuf) // <--
	}

	return c.flags
}
```
The errors of flags just go to the memory and are not being printed
