### ISSUE TITLE
-bash: cobra: command not found

### ISSUE THREAD

**Issue by mdaymard** [spf13/cobra#270]
On MacOSX, I followed the README file, but could not use the cobra line command.
For example : 

cobra init github.com/spf13/newAppName

results in : 
-bash: cobra: command not found

**Comment by mdaymard** [comment]
Ok, I needed to add in the PATH : $GOPATH/bin

**Comment by pruse2402** [comment]
Am getting the same issue. what is the solution to resolve this one?
Thanks in advance.

**Comment by bjarkarim** [comment]
have you mange to fix the problem? i'm getting the same error

**Comment by mehlichmeyer** [comment]
@pruse2402 @bjarkarim if you guys still have this error, go to your home directory and edit your .bashrc (or .zshrc if you're using zsh like I do) and add your $GOPATH/bin to the list. In my case its 'GOPATH=$HOME/go' so I had to adjust my path 'PATH="entry1:entry2:$HOME/go/bin". That might explain a bit better what @mdaymard already said.

**Comment by amolasg** [comment]
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=${PATH}:$GOBIN

**Comment by gennaro-tedesco** [comment]
I am having installation problems too:
```
go get -u github.com/spf13/cobra/cobra
cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
	/usr/local/Cellar/go/1.16.2/libexec/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
	~/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)
```
my go paths being:
```
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=${PATH}:$GOBIN
```
Do I need to install extra dependencies?

**Comment by dockercore** [comment]
遇到下面的问题
”cobra not found“

解决问题的方法如下：

1.编辑这个文件 vim  ~/.zshrc

2. 把下面👇🏻三行代码复制下，保存退出
   export GOPATH=$HOME/go
   export GOBIN=$GOPATH/bin
    export PATH=${PATH}:$GOBIN

3.加载配置使其生效
   source ~/.zshrc

4.退出我们使用的编辑器或者iterm2终端，或者重启电脑即可。
  reboot

**Comment by felipeschossler** [comment]
I love u @[amolasg](https://github.com/amolasg) :heart:

**Comment by HorraceMuendo** [comment]
I have been experiencing the error for a while ,all you have to do is to change the path 
Just copy and paste this and it should work .......
 export PATH=$PATH:/usr/local/go/bin

**Comment by Fahad-Md-Kamal** [comment]
@amolasg Thanks man, Your answer saved me.
