### ISSUE TITLE
Cobra command doesn't work if GOPATH is multiple

### ISSUE THREAD

**Issue by ghost** [spf13/cobra#276]
I have a GOPATH containing multiple paths like this: `/ssd/go:/home/username/go`. The cobra command wouldn't work because it treats it as a single path, resulting in stupid messages and errors.  
GOPATH is supposed to be a list of directories separated by a colon, as specified here: https://golang.org/cmd/go/#hdr-GOPATH_environment_variable

**Comment by kbj** [comment]
There is a fix in my branch, but I can't figure out how to fix the tests. Does Travis CI supports a GOPATH with multiple entries?

**Comment by dc0d** [comment]
My other projects are working fine (I have 3 paths) and I've decided to try cobra. Seems it is not fixed:

`Error: Cobra only supports project within $GOPATH`

**Comment by jhernandezme** [comment]
I have the same issue with mulitple paths.
