### ISSUE TITLE
Reassign `-h` short flag for another function

### ISSUE THREAD

**Issue by patrickdappollonio** [spf13/cobra#291]
Hello,

Is there a way to remove the shortflag `-h` (and still keep `--help`) from Help? I'm working on a CLI app and people here would rather use `-h` for `hostname` instead of help.

**Comment by eparis** [comment]
I think the only way to accomplish this is to define the --help flag
yourself without the -h shorthand. You can see the `initHelpFlag()`
function for an example of how it is done automatically...

-Eric
