### ISSUE TITLE
Command allowing both arguments and subcommands

### ISSUE THREAD

**Issue by clns** [spf13/cobra#295]
Currently it's not possible to have subcommands and arbitrary arguments on the same command. Like a "default" or "catch all" subcommand that will receive the args, if no subcommand was matched.

One use case would be to have the root command working with files (thus arbitrary arguments), but also have some subcommands like `version`. Instead, I would have to add a new subcommand to root that would take the files args, which adds unnecessary typing when using it.

**Comment by dnephin** [comment]
PR #284 supports this behaviour. Setting any `Args` validator would skip `legacyArgs()` behaviour of not allowing both args and subcommands on the root command.

**Comment by bogem** [comment]
Fixed in #284
