### ISSUE TITLE
Suggestion for Help message

### ISSUE THREAD

**Issue by kujtimiihoxha** [spf13/cobra#297]
I have added aliases for some of my commands but they are not displaying on the help message.
I think it would be useful to display the command aliases in the help message by default.
**UPDATE**
I men it should be displayed in the main help message ex.
Now:

```
Available Commands:
  generate    A collection of useful generators
  new         create a new project
```

After:

```
Available Commands:
  generate, gen, g    A collection of useful generators
  new         create a new project

```

**Comment by alessandrozucca** [comment]
I came across the same problem, although you can override the default template and set it with `RootCmd.SetUsageTemplate(usageTemplate)`

**Comment by kujtimiihoxha** [comment]
@alessandrozucca  thanks for your help 👍
