### ISSUE TITLE
How do I make --help exit?

### ISSUE THREAD

**Issue by jersten** [spf13/cobra#298]
I can't find documentation anywhere; but when I run `somecommand --help` the program continues; how do I add a `os.Exit(0)` so that the program exits?

**Comment by dnephin** [comment]
https://github.com/spf13/cobra/blob/6a8bd97bdb1fc0d08a83459940498ea49d3e8c93/command.go#L665-L668

`cmd.Execute()` should return after printing the help, so you should be able to just exit after that.

You could also set `SetHelpFunc()` to exit before that if you wanted to.

**Comment by jersten** [comment]
What I ended up doing:

```
	setFlags()

	helpCmd := RootCmd.HelpFunc()

	helpFlag := false

	newHelpCmd := func(c *cobra.Command, args []string) {
		helpFlag = true
		helpCmd(c, args)
	}
	RootCmd.SetHelpFunc(newHelpCmd)

	if helpFlag {
		os.Exit(0)
	}

	err := RootCmd.Execute()
```
