### ISSUE TITLE
Usage output should default to stdout not stderr

### ISSUE THREAD

**Issue by eparis** [spf13/cobra#31]
It is very common to want to command --help | grep $something but since we default all help and usage to stderr this becomes a user annoyance.

I'm not the only person who is annoyed (even though I filed that one too):
https://github.com/GoogleCloudPlatform/kubernetes/issues/2177

I started poking this just a bit today but was hoping you might have suggestions on a good way to solve the problem...

**Comment by fabianofranz** [comment]
A similar issue was recently fixed in Docker:

http://www.projectatomic.io/blog/2015/01/improving-docker-error-messages/

**Comment by eparis** [comment]
https://github.com/spf13/cobra/pull/71
