### ISSUE TITLE
Os.Stdin to execute cobra commands

### ISSUE THREAD

**Issue by penshield** [spf13/cobra#310]
Dear Friends , 

I have developed a very simple cobra commands CLI application, it is called myapp. 
when i execute "myapp help" or "myapp times -t 10 something" everything works as expected.

but my production CLI app should have it is own custom command prompt, something like
# myapp

then you get 
myapp >>

i want the user then can write cobra commands in here simply like 

myapp >> help 

how can i redirect this os.stdin reader and give it to cobra for execution.

**Comment by dnephin** [comment]
I think this would be easy to do with something like https://github.com/abiosoft/ishell

You could do something like:

```go

shell := ishell.New()
cmd := &cobra.Command{...}

for _, command := range cmd.Commands() {
    name := command.Name()
    shell.Register(name, func(args ...string) (string, error) {
        cmd.SetArgs(append([]string{name}, args...))
        err := cmd.Execute()
        // Not sure what to return for the string here. command would already output to stdout
        return "", err
    }
}

shell.Start()

```

**Comment by penshield** [comment]
Dear dnephin , 

Thank you for your response , i managed to do it in another way , could you tell me what do you think ?

package main


import (
       "fmt"
        "positron/cmd"
       "os"
       "bufio"
       "strings"

       "log"
)

func main(){

       fmt.Println("Welcome to Positron Configuration Utility")



       reader := bufio.NewReader(os.Stdin)

       if err := cmd.RootCmd.Execute();err != nil{

              fmt.Println("Exiting.....")
              os.Exit(-1)
       }

       for {
              fmt.Print("Positron >>")
              text , _ := reader.ReadString('\n')
              //fmt.Printf("You have written : %s\n",text)
              text = strings.Trim(text,"\r\n")

              if strings.Compare(text,"quit") == 0{

                     log.Println("Exiting....")
                     os.Exit(0)
              }

              //split the text into pieces by spaces
              cmdPieces := strings.Split(text," ")

              command,args,err := cmd.RootCmd.Find([]string{cmdPieces[0]})

              if err != nil {
                     log.Printf("Unknown Command to execute : %s\n",text)
                     continue
              }

              args = append(args,cmdPieces[1:]...)

              command.Run(command,args)
              command.Execute()



       }
}

**Comment by bogem** [comment]
Your solution is ok
