### ISSUE TITLE
Can I disable sorting of flags for given command?

### ISSUE THREAD

**Issue by sameera-jayasoma** [spf13/cobra#316]
I've added following two flags a command.

initCmd.Flags().StringVarP(&username, "username", "u", "", "username")
initCmd.Flags().StringVarP(&password, "password", "p", "", "password")

Here is the output. Is there a way for me to print the list of flags without sorting them? Thanks.

Flags:
  -p, --password string   username
  -u, --username string   password

**Comment by alexdreptu** [comment]
I'm also interested in this. It would be really nice to have an option to disable sorting for flags. In some cases it would be best to have them in the order they were defined, because although they are sorted they look random when related options are far apart in the help print.

**Comment by bogem** [comment]
This issue is related to [spf13/pflag](https://github.com/spf13/pflag), because pflag is responsible for all flag manipulations.
The problem is, what when you add flag, [it adds to map](https://github.com/spf13/pflag/blob/master/flag.go#L731), so we should have an ordered map to make that enhancement.

**Comment by alexdreptu** [comment]
@bogem yes, realized that shortly after my comment while taking a closer look at cobra.

**Comment by bogem** [comment]
Now you can disable sorting flags for a single this way:
`initCmd.Flags().SortFlags = false`

**Comment by bogem** [comment]
This issue isn't closed properly. Continue in #404

**Comment by crobles-ppfa** [comment]
> SortFlags
Thank you
