### ISSUE TITLE
README misleadingly states any filesystem organization is allowed

### ISSUE THREAD

**Issue by MarkDBlackwell** [spf13/cobra#319]
[README.md](https://github.com/spf13/cobra/blame/7c674d9e72017ed25f6d2b5e497a1368086b6a6f/README.md#L142) says "[Y]ou are welcome to provide your own organization[.]" A diagram of a "typical" filesystem tree follows. It includes `appName/cmd/`.

However, rather than fully allow "your own organization," the current code ([cobra/cmd/helpers.go](https://github.com/spf13/cobra/blob/7c674d9e72017ed25f6d2b5e497a1368086b6a6f/cobra/cmd/helpers.go#L41)) apparently looks only in certain directories immediately under the project root: `cmd/`, `cmds/`, `command/` and `commands/`.

Should `README.md` be supplemented by language like, "as long as you assign your command directory one of the following names: `cmd/`, `cmds/`, `command/` or `commands/`"?

That would facilitate understanding IMO by new users, and help the growth of Cobra.

**Comment by jharshman** [comment]
This is correct. You are welcome to use your own file structure and many projects do. However, the cobra generator will not work with any file structure.

**Comment by MarkDBlackwell** [comment]
@jharshman Well. Surely, the fact that Cobra includes the phrase, "While you are welcome to provide your own organization" in its README implies that Cobra can handle "your own organization." Interestingly, it can't—as you, yourself, say.

The cobra generator will not work, with just _any_ file structure.
