### ISSUE TITLE
Cobra disagrees with archetypal example Hugo

### ISSUE THREAD

**Issue by MarkDBlackwell** [spf13/cobra#320]
Arguably, the archetypal example of a Cobra user is [Hugo](https://github.com/spf13/hugo). However, Hugo apparently doesn't match what Cobra currently generates for new projects (`{{appName}}/cmd/`). Instead, it contains the directory, [`hugo/commands/`](https://github.com/spf13/hugo/tree/f914774f6bcb2416004101112c0f2dd1cd664176/commands).

Which directory name for commands is the least confusing way to go? Is it:
1. What Cobra generates: `cmd/`? or
2. Hugo's usage: `commands/`?

Both work. Yet the difference seems needlessly confusing for new Cobra adopters. They likely will be experimenting with both Hugo and Cobra (as well as browsing the source of both) while learning Cobra.

Aligning both Cobra and Hugo to use the same directory name for commands (insofar as possible) would make such learning easier, and IMO help the growth of Cobra.

BTW, IMO the easiest name to learn is `commands/`.

**Comment by broady** [comment]
I agree. `cmd` also conflicts with the unwritten standard that direct children under `cmd` are main packages.

**Comment by hoop33** [comment]
I think it's now a written standard to use `cmd` -- https://github.com/golang-standards/project-layout

Recommend closing this issue.
