### ISSUE TITLE
docs: "Commands" should be called subcommands

### ISSUE THREAD

**Issue by MarkDBlackwell** [spf13/cobra#325]
README section [Overview](https://github.com/spf13/cobra/blame/7c674d9e72017ed25f6d2b5e497a1368086b6a6f/README.md#L38) says:

> Cobra provides:
> Easy subcommand-based CLIs: app server, app fetch, etc.

However, instead, elsewhere in the README (and also in its source, I suppose), Cobra calls `{{App}} server` and `{{App}} fetch` "commands."

For an example of this, README section [Concepts](https://github.com/spf13/cobra/blame/7c674d9e72017ed25f6d2b5e497a1368086b6a6f/README.md#L65) says:

> Cobra is built on a structure of commands, arguments & flags.
> **Commands** represent actions, **Args** are things and **Flags** are modifiers for those actions.

This conflicts with general Unix usage, which (e.g.) calls `git checkout mybranch` a "command" and (within it)`checkout` an "argument." Cobra's usage here IMO is less clear (as well as inconsistent with its README reference above to "subcommands").

Calling them "subcommands" IMO seems clearest for new users (as well as helping them by maintaining consistency with Unix).

Therefore, `server`, `fetch`, etc. IMO should be called "subcommands" (or "AppCommands") throughout the documentation, to help new users and others.

**Comment by marians** [comment]
I would also prefer a consistent nomenclature within the cobra docs and code. My preferred scheme would be

    <executable> <command> <subcommand> ...

but that might just be personal. (I don't think you'll find a standard in the unix world for this. For `git checkout`, some might call the entire thing the command, some might call `git` the command, some might call `git` the program, the binary, the executable, whatever.)
