### ISSUE TITLE
pflag / viper / cobra: Allow ENV to default flag values

### ISSUE THREAD

**Issue by smarterclayton** [spf13/cobra#33]
There are cases (running in Docker containers, bash scripts) where ENV vars are easier to set and pass down to a command than generating flag arguments on the fly.  It would be nice in the flags definition (or in a related mechanism) to attach an env var name to a flag such that in the absence of a flag, the env var is checked and used.  The var would probably be considered as "set" if detected as non-empty.  

Since pflags doesn't allow issues I'm raising it here - is there any interest in a pull that added the ability to map an ENV var to a flag?  Adding one *Var / *VarP / *P variant for each env option doesn't seem like a good idea - I was considering an ENV map that could be applied after flag checking:

```
cmd := &Command{}
// ... add flag "foo"
cmd.SetEnvironmentFlags(map[string]string{
   "foo": "MY_FOO_ENV_VAR_NAME",
})
```

When you ran a command after flag parsing the environment would be used to set unspecified values (or to prime the values of flags).

I can pull together a pull if this isn't seen as out of scope for cobra.

**Comment by spf13** [comment]
viper already does this. Do you need something beyond the functionality it provides?

**Comment by spf13** [comment]
I recognize this is a year old. I'm doing some horribly overdue housekeeping. close if no longer relevant.

**Comment by smarterclayton** [comment]
In practice we're just setting the default of a particular flag to the env value and relying on doc.  It's fine for now.

**Comment by estahn** [comment]
@spf13 I suppose the functionality is a bit unclear. Is there an example? (see https://github.com/spf13/viper/issues/461)
