### ISSUE TITLE
cobra init not working

### ISSUE THREAD

**Issue by danesparza** [spf13/cobra#330]
I'm using Go 1.7 on Windows.  I have used cobra on other projects.  I'm trying to start a new project and getting the following error:

`Error: Cobra only supports project within $GOPATH`.  

My GOPATH is a single path and is set correctly.  Several other projects build just fine.  Help!

**Comment by elliotmr** [comment]
I have exactly the same problem.  It has to do with windows case insensitivity.  I have my GOPATH set to "c:\Users\Elliot\go", but the comparison checks against "C:\Users\Elliot\go\..." with a straight string comparison.

Unfortunately filepath.Clean() does not normalize the drive letter and cobra uses a straight string comparison.

**Comment by tomdavidson** [comment]
I am on Debian Testing:

```
$ echo $GOPATH 
/home/tom/Projects/s4-go

$ echo $PWD
/home/tom/Projects/s4-go

$ cobra init
Error: Cobra only supports project within $GOPATH
```

**Comment by eparis** [comment]
I believe you would need $PWD == $GOPATH/src/$REPO/$PROJECT

**Comment by tomdavidson** [comment]
@eparis thanks for the reply. I'm pretty sure $PWD is suppose to be the current working directory. It was included in my comment to show that I am running `cobra init` from the the directory that is $GOPATH.

**Comment by elliotmr** [comment]
The point is that you wouldn't want to actually run the command directly in the $GOPATH dir, it needs to be a subdirectory where you actually want the application to be created.

**Comment by kytrinyx** [comment]
I ran into this on a couple of windows machines. In both cases:

- `GOPATH` was set
- `$GOPATH/src/github.com` existed
- The directory matching the user's username *did not exist* (`$GOPATH/src/github.com/<username>`)

To work around it we manually created their username directory, and then successfully ran the `cobra init github.com/<username>/<appname>` command.

/cc @spf13 @ashleymcnamara

**Comment by kytrinyx** [comment]
> The point is that you wouldn't want to actually run the command directly in the $GOPATH dir

@elliotmr I believe the desired behavior is that if you pass it an import path (not just a single directory name) then it creates it in the correct location, even if you're typing the command from somewhere else (e.g. the $GOPATH).

**Comment by kytrinyx** [comment]
@tomdavidson `cobra init` takes an argument which is the import path to your new application.

E.g.

```
$ echo $GOPATH
/Users/kytrinyx/code/go
C02RQ3BRFVH8:~ kytrinyx$ cobra init github.com/kytrinyx/thingy
Your Cobra application is ready at
/Users/kytrinyx/code/go/src/github.com/kytrinyx/thingy
```

**Comment by PeterMenage** [comment]
I'm having this issue. These fixes don't seem to do the trick for me. Any advice?
