### ISSUE TITLE
Had to add a "Type" method to satisfy the Value interface -- deviation from the pflag module

### ISSUE THREAD

**Issue by ericpromislow** [spf13/cobra#333]
I want to allow an option to be set multiple times on the command-line.  I added this code:

```
type envStrings []string

func (e *envStrings) String() string {
    return strings.Join(*e, ";")
}

func (e *envStrings) Set(value string) error {
    *e = append(*e, value)
    return nil
}
//...
var myFields envStrings
cmd.Flags().Var(&myFields, "my-field", "call --my-field for each field you want to visit")
```

The compiler complained that *envStrings doesn't implement the Type method, so I added one that takes no args and returns a hard-wired string. Now it's called, but Set() isn't, and I don't get my array populated. This works with the standard flag library. Bug, or is there something else I need to do?

**Comment by eparis** [comment]
I thought you just needed `String`, `Type`, and `Set`. Can you post your code?

**Comment by ericpromislow** [comment]
I did. The full code is part of a much larger system that I can't post anyway.

Where are the docs for the `Type` method?

**Comment by QiWang19** [comment]
I defined my flag struct and implement the `pflag.Value` interface.
How can I make this flag be used must with `=`, otherwise use the default value? 
```
--flag=value #valid
--flag value #value will not be assigned to flag
```
Implemented `IsBoolFlag()`,  but does not work
