### ISSUE TITLE
ValidArgs set, how test it

### ISSUE THREAD

**Issue by lojies** [spf13/cobra#341]
[https://github.com/spf13/cobra/blob/master/bash_completions.md](url) shows like this:
```bash
# kubectl get [tab][tab]
node                 pod                    replicationcontroller  service
```

but when i press tab, it shows file list of current dir.
how should i test this?

**Comment by eparis** [comment]
bash completions only work if you have generated and sourced them.
https://github.com/spf13/cobra/blob/master/bash_completions.md#generating-bash-completions-for-your-own-cobracommand
shows you and example of how to generate some completions.
You'd then need to do `. out.sh` to source them into your running bash shell before they would work...

**Comment by lojies** [comment]
@eparis thank you very much
