### ISSUE TITLE
Man page generator generates inconsistent file names and SEE ALSO references

### ISSUE THREAD

**Issue by knz** [spf13/cobra#342]
We encountered this in CockroachDB (xref https://github.com/cockroachdb/cockroach/issues/4917)
- `GenManTree` in `doc/man_docs.go` forces the command separator to be `"_"`, which causes `GenManTreeFromOpts` to generate file names for man pages to be `like_this.1`
- Meanwhile, `genMan` replaces spaces in names by `"-"` always.

As a result, when the reader reads the "SEE ALSO" section she might see a reference to `this-command(1)` whereas the command she has to type to read that man page is actually `man this_command`.

May I suggest to use dashes always, that is, set the options in `GenManTree` to use `"-"`.

**Comment by dnephin** [comment]
I ran into this problem as well, and submitted a fix in #294 (e291587027b16ffd7fb0e5bdd6bf203e8ed2620f).

I think you can use `GenManTreeFromOpts()` and pass `CommandSeparator: "-",` to do what you want.

**Comment by knz** [comment]
Please explain more. Why would you want to keep inconsistent default settings in the cobra code?

**Comment by dnephin** [comment]
Hmm, I'm not sure. I guess some people might be expecting the old file names and don't use `SEE ALSO` ? I wanted to keep backwards compatibility, so I left the old default and added it as an option.

**Comment by eparis** [comment]
owuld the right thing to do to fix 'see also'? as that would seem more backwards compat...

**Comment by knz** [comment]
Look either are fine, I think this is subjective really. I'm not a cobra developer so I can't really make a call on this. Just inform me what the best solution will be; if my PR #343 ought to be written another way make a comment there and I'll update it accordingly.

**Comment by anthonyfok** [comment]
I agree with @knz, especially this is the way `git` sub-command man pages work too, where `-` dashes are used to represent spaces, and sometimes, actual `-` dashes.

On the other hand, `_` underscores means actual underscores in the command name, e.g. `kbd_mode`, `xinput_calibrator`.  I couldn't really find an example (outside of cobra-generated man pages) in my /usr/share/man/man1/ directory where the `_` underscore is used to represent a space.

So, yes, I think I will simply go ahead and accept @knz's PR #343.

**Comment by knz** [comment]
Thank you!

**Comment by anthonyfok** [comment]
Thank you for bringing this up and providing the patch!  :-)
