### ISSUE TITLE
Support for completion in other shells (fish, zsh, etc.)

### ISSUE THREAD

**Issue by gaocegege** [spf13/cobra#350]
cobra supports bash_completion,  that's awesome. Is there a way to support other shells?

ref https://github.com/kubernetes/kubernetes/issues/30763

**Comment by xh3b4sd** [comment]
Kind of duplicate of #107. Lets upvote there and get some movement.

**Comment by babysnakes** [comment]
Please see my note in #107. I'll appreciate any input on my trial at native zsh completion.

Thanks.

**Comment by boynux** [comment]
We are also interested in FiSH integration.

**Comment by z3ntu** [comment]
It looks like #1048 added support for fish shell and there's e.g. #1070 for zsh

**Comment by kri5** [comment]
I took a quick look at the code handling completion in the helm command, and there seems to be a slight issue with renamed binaries, where the generated completion would not have a proper name.

Nowadays fish completion is derivated from the bash one, and there is a bash snippet in case the binary has been renamed from the default.

A Better way of handling it might be to pass the binary name as the name passed when creating the Root cobra command, and so it will propagate everywhere else.

Feel free to comment on this, and i'll try to implement it

**Comment by marckhouzam** [comment]
With Cobra now offering shell completion for `bash`, `zsh`, `fish` and `powershell`, I believe we can close this issue.

/cc @jharshman @jpmcb
