### ISSUE TITLE
Question about arbitrary flags

### ISSUE THREAD

**Issue by punchybeauty** [spf13/cobra#352]
Hello! New user here. Sorry if this is already answered; I couldn't find anything in my searches. 

Suppose I wanted to use cobra for a program that took a command line, similar to xargs:

```bash
xargs -n 3 ls -la

# or, for clarity:

xargs -n 3 -- ls -la
```

In this example, `-n 3` would be a flag defined on my cobra command, and I would expect the arguments array provided to my run function to be `ls -la` (or `-- ls -la`).

Trying this out of the box, I get an unknown flag error. What can I configure to make this work?

Thanks! :smile:

**Comment by dnephin** [comment]
Use `cmd.Flags().SetInterspersed(false)`. Flag parsing will stop after the first non-flag arg.

You can also set `cmd.DisableFlagParsing = true`, but you'll have to handle flag parsing yourself.

**Comment by punchybeauty** [comment]
Thanks! This worked great :smile:
