### ISSUE TITLE
Let user decide whether deprecated flags shown in help message or not

### ISSUE THREAD

**Issue by bruceauyeung** [spf13/cobra#358]
recently i faced a problem:
my application wanna those deprecated flags (with nonempty Deprecated message) displayed in help messages. but i found method `FlagUsages()` in `flag.go` has these logic:
`
if len(flag.Deprecated) > 0 || flag.Hidden {
			return
		}`

this makes flags being marked deprecated has no chance to be shown in help except for flag's Deprecated message being set nonempty. but this is not what i want. i want deprecated flags are showed in help message with its nonempty usage message.

i think it's better if cobra let user decide whether deprecated flags shown in help message or not.
cobra can add an extra paramter `hidden bool` with default value `true` to `MarkDeprecated()` method
it may looks like :
`func (f *FlagSet) MarkDeprecated(name string, usageMessage string, hidden bool) error`

**Comment by Fjolnir-Dvorak** [comment]
if deprecated flags should be shown. Should it be configured per each individual flag or one config option for all?
I would like to try to implement this issue.
