### ISSUE TITLE
Invalid long option confused as shorthand option

### ISSUE THREAD

**Issue by whitlockjc** [spf13/cobra#368]
Imagine I have a command option with a long and short hand of `--org` and `-o` respectively.  If I supply `-org mine` instead of `--org mine` or `-o mine`, Cobra parses as if I had supplied `-o rg`.  Is this by design?

**Comment by eparis** [comment]
yes. this is POSIX flag parsing. `-` and `--` are different. I still think golang was wrong in the decision to make them the same.

**Comment by whitlockjc** [comment]
I realize `-` and `--` are different but Cobra is treating `-org` as `-o rg` which shouldn't have anything to do with that.  I do understand _why_ this is happening, I just wasn't sure if it was a POSIX or some other standard to make this by design.  I'm surprised this hasn't come up more in the CLI world since it's pretty common to use the first letter of a long option as it's short hand equivalent, which seems to be the reproduction recipe.

I guess now I have to figure out how to work around this.

**Comment by eparis** [comment]
I think that `-omine` is POSIX acceptable which leads to this case. Is that were this question comes from?

**Comment by whitlockjc** [comment]
Well, if POSIX says that `-omine` is equivalent to `-o mine`, then there is no issue because Cobra is doing the right thing.  I'm trying to say that from a consumption perspective, if you meant to type `--org mine` but instead typed `-org mine` _(Notice the singular `-`)_, the fact that POSIX treats `-org mine` as `-o rg mine` makes it almost impossible to identify when someone fat fingers a long option.  I can't tell if the user meant to pass `rg` to `-o` or if they meant to type `--org`.

**Comment by eparis** [comment]
Agreed :-(   set the 5th bullet point: https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

not sure the best way to make this happier. We could maybe have a helper that does some 'short arg looks like long arg' heuristic, but it would still be up to the pflag user to do something with that helper....

**Comment by whitlockjc** [comment]
Agreed.  I'm not sure there is a solid approach to solving this.  I mean, you could come up with something for the 80% use case but for the 20%, you'd be in the same boat we are now regardless.

Since Cobra is operating within the POSIX standard, I think it would be crazy to change.  So I will close this issue.  Thanks for your time in discussing this.
