### ISSUE TITLE
Feature: Simple validation of IntVarP flags

### ISSUE THREAD

**Issue by marians** [spf13/cobra#376]
I'd like to (optionally) define a minimum and maximum value for a IntVarP flag, just like I can define a default value. Cobra should automatically validate the value when the flag is used and exit with an error if it doesn't fulfil the requirement.

If that's already possible, I was just not able to find it and would be happy for a pointer. Thanks!

**Comment by eparis** [comment]
You could propose your new Value type to spf13/pflag (or some extension to the existing int type?). I can't say if it would or would not be accepted, but that's where any PR would need to go. Thus I'm going to close this one. Thank you for the idea!
