### ISSUE TITLE
Additional docs on flags setup?

### ISSUE THREAD

**Issue by goarchit** [spf13/cobra#377]
Suspect I'm just being a bit dense.  I had a nice sample program working with Viper and Pflag and am now trying to convert to Cobra.

Alas, I'm finding it difficult to find clear documentation on things like what the parameters of StringP are.  Some are faily obviously, but not things like the 3rd null string.

Doc on where the boundries are between Cobra and Viper and Pflag would be good too.  e.g. Which basic functions does Cobra do and which must still be done by hand.  For instance:  apparently Cobra is doing the pflag work, but not all of the viper work since I apparently still need to BindPFlag for all StringP()s, and SetDefault for everything.  Likewise, its unclear what the viper config Name is, or other viper function settings like AddConfigPath.

Example are cool, but are not a substitute for clear documentation in context of what is trying to be accomplished.  e.g.  Documenting StringP needs to talk about full-text, legal abbreviations, short and long descriptions, not type string, []byte, etc.

Does such documentation exist?

**Comment by variadico** [comment]
pflag documentation is here: https://godoc.org/github.com/spf13/pflag
