### ISSUE TITLE
Cobra and Viper not working together

### ISSUE THREAD

**Issue by ybbus** [spf13/cobra#382]
Hi.

I tried the example to bind cobra flags to viper:

```go
MyCmd.Flags().String("port", "8080", "listen on port")
viper.BindPFlag("port", MyCmd.Flags().Lookup("port"))
```

but I get the following error message:

> Cannot use MyCmd.Flags().Lookup("port") (type *Flag) as type *pflag.Flag

Any idea?

**Comment by apriendeau** [comment]
I went through the example. Here is the code that I used:

**cmd/root.go**
```go
package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var RootCmd = &cobra.Command{
	Use:   "hugo",
	Short: "Hugo is a very fast static site generator",
	Long: `A Fast and Flexible Static Site Generator built with love by spf13 and friends in Go.
	Complete documentation is available at http://hugo.spf13.com`,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("HUGO!!")
	},
}

func init() {
	RootCmd.PersistentFlags().StringP("author", "a", "YOUR NAME", "Author name for copyright attribution")
	viper.BindPFlag("author", RootCmd.PersistentFlags().Lookup("author"))
}
```

**main.go**
```go
package main

import (
	"fmt"
	"os"

	"{path to cmd directory}/cmd"
)

func main() {
	if err := cmd.RootCmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(-1)
	}
}
```

It could be a different version of viper or cobra. Could you please try running `go get -u github.com/spf13/cobra` and `go get -u github.com/spf13/viper`? Then try to run the code again and see if the issue still occurs?

**Comment by ybbus** [comment]
Hi.

Thanks for your reply. Now it works, but I don't know exactly what fixed it.
I think it was some kind of import issue.
The IDE imported the wrong module.

Alex
