### ISSUE TITLE
Explanation in docs about setting/accessing flags

### ISSUE THREAD

**Issue by bengadbois** [spf13/cobra#388]
When using cobra and viper together, it wasn't clear (to me) that you can only access the flags after the cobra.Command has run Execute().

For example:
```golang
var RootCmd = &cobra.Command{                                                                                                                
    Use:   "root",                                                                                                                         
    Short: "explanation",                                                                 
}

func init(){
    RootCmd.PersistentFlags().BoolP("verbose", "v", false, "Print extra troubleshooting info.")                  
    viper.BindPFlag("verbose", RootCmd.PersistentFlags().Lookup("verbose"))

    //this returns nil, since RootCmd hasn't Execute() yet
    fmt.Println("%+v", viper.Get("verbose"))
}
```

While this is fine behavior, it wasn't obvious the binding happens post-Execute(). I had to dig through the docs a while and came across this issue: https://github.com/spf13/viper/issues/100

**Comment by eparis** [comment]
if you really didn't want to call execute you might be able to do:
```
cmd, flags, err := RootCmd.Find(os.Argv[1:])
cmd.ParseFlags(flags)
```
And then the `viper.Get()` might work...   not 100% sure...

**Comment by gumieri** [comment]
I'm facing the same issue. Would be really nice if I could get some configs using the viper to execute something and defining according it the default value for some flag.

I am defining the path to git to get the branch name to define as default value of one flag, but it's returning `<nil>` at `init()`.

Is there a better way to do it?

**Comment by bogem** [comment]
@gumieri can you please provide an example of code for your issue?

**Comment by gumieri** [comment]
I'm a beginner with Go programming, surely exists another way to do what I'm trying to do. But, there is:

On my `cmd/root.go`:
```go
func init() {
	cobra.OnInitialize(initConfig)

	RootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.act.yaml)")
	RootCmd.PersistentFlags().IntVarP(&issueID, "issue_id", "i", 0, "The Issue ID.")
}
```

On other commands:
```go
func getIssueID() int {
	if issueID == 0 {
		gitPath := viper.Get("git.path")
		gitRegex := viper.Get("git.regex")

		if gitPath != nil && gitRegex != nil {
			issueID, _ = git.IssueIDFromBranch(gitPath.(string), gitRegex.(string))
		}
	}

	if issueID == 0 {
		log.Fatal(errors.New("issue_id (-i) is missing"))
	}

	return issueID
}
```

I did it because I was not able to get the value from `viper.Get("git.path")` or any other to set the default value on `RootCmd.PersistentFlags().IntVarP(&issueID, "issue_id", "i", 0, "The Issue ID.")` instead of `0`.

Is there any better way to do it?

**Comment by bogem** [comment]
I really try to help you, but I can't understand, what the issue you are facing.
What does viper do wrong? What the problem with the default flag of flags? Please describe your issue more detailed.

**Comment by gumieri** [comment]
Sorry for the lack of information / description.

The place to define a flag is in the `func init()` right? The functions has the third (or second if not "Var") to define the "default" value to it.

In my case I get the "default" value according the Git branch name, but I use a regex and the git path from the config file (using the viper). But in the `func init()` the viper returns `<nil>`  even with the `cobra.OnInitialize(initConfig)` on the beginning of it.

It is a bit confusing why the viper does not appear to work in the `func init()` and would be really nice if could work.

**Comment by bogem** [comment]
> The place to define a flag is in the func init() right?

Right.

> In my case I get the "default" value

Default value of which flag/viper key?

> But in the func init() the viper returns <nil> even with the cobra.OnInitialize(initConfig) on the beginning of it.

Where and how do you use viper in init? Please provide code examples.

> It is a bit confusing why the viper does not appear to work in the func init() and would be really nice if could work.

Actually, it should work in init() func, but I can't understand how your issue concerns to setting/accessing flags.
