### ISSUE TITLE
Additional help for flags

### ISSUE THREAD

**Issue by krasi-georgiev** [spf13/cobra#392]
I am thinking to add a bit more help for some docker commands like
docker container list --filter --help

to show all available filters

the list is long and likely to grow so it becomes unreadable if  put this in the main help section with 
docker container list --help

I am willing to open pull request if you think this would be good to implement.

exited=<int> containers with exit code of <int>
status=(created|restarting|running|removing|paused|exited|dead)
label=key or label="key=value" of a container label
isolation=(default|process|hyperv) (Windows daemon only)
id=<ID> a container's ID
name=<name> a container's name
is-task=(true|false)
ancestor=(<image-name>[:<tag>], <image id>, or <image@digest>)
before=(<container id> or <container name>)
since=(<container id> or <container name>)
volume=(<volume name> or <mount point destination>)
network=(<network id> or <network name>)
health=(starting|healthy|unhealthy|none)

**Comment by eparis** [comment]
Maybe you could add a custom help function for the 'list' subcommand. It won't be easy since you'll have to parse the 'flag' yourself out of args...  You might be able to make use of the `pflag.FlagSet.ParseAll()` function to help. I'm not sure...

I like the idea I think...

What should `docker container list --flag1 --filter --help` show?

**Comment by krasi-georgiev** [comment]
> What should docker container list --flag1 --filter --help show?


logically I think --help should show the help for the last arg in the list -- filter in this case.

> How about docker container list --filter=whatever --help?

still show all available options for --filter

what do you think?

**Comment by krasi-georgiev** [comment]
@eparis sorry for the reminder , but I really want to work on this before I loose motivation 😄 

or if you don't have the time maybe ping another maintainer that can approve or deny the proposal.

**Comment by eparis** [comment]
@spf13 I'm not entirely convinced, but I'm also not against the idea.
@krasi-georgiev I guess I think I'd want to see and discuss the code to do it. As long as it is backwards compatible and doesn't seem like a maintenance nightmare I'm pretty flexible.

**Comment by krasi-georgiev** [comment]
ok , I will wait 1-2 days to see if  @spf13 has any additional comments or guidance and I will start with this.

@eparis - do you think that --help applying to the last command of flag in the list is logical? https://github.com/spf13/cobra/issues/392#issuecomment-282391996

**Comment by eparis** [comment]
Yes. Although if the LAST flag does not have special help information we should should the command help.  So `docker container list --filter-whatever --otherflag --help` would show the `list` help, not the `--filter` help.

**Comment by spf13** [comment]
I'm pretty against this idea. Flags should modify the command, not the other flags. This is a serious break of usability principles. 

`docker container list --help`
and 
`docker container list --filter=whatever --help` 
should do the same thing. 

In other words, the  `--help` flag always applies to the command.

**Comment by krasi-georgiev** [comment]
@spf13 I would really appreciate some other other idea how to solve the following problem.

currently one of the help lines for 
`docker container list --help`

shows
`-f, --filter filter   Filter output based on conditions provided`
but no mention of all available filters.

I tried adding the  filters in the same help page , but they are too many and clutter the page

here is s link to that shows all available filters
https://docs.docker.com/engine/api/v1.25/#operation/ContainerList

there are many other commands that support filters so this is not an edge case.

**Comment by spf13** [comment]
The issue is you are trying to use a flag to do something a command should
be doing.

For this specific use case I'd suggest looking into adding a dedicated
helper `docker help filters` or `docker container list filters` or similar.
You also could extend the help command for `container list help` to use a
different help output.
