### ISSUE TITLE
GenManTree and GenMarkdownTree require the output directory to exists. No error shown.

### ISSUE THREAD

**Issue by 1138-4EB** [spf13/cobra#401]
I was trying `GenManTree` and `GenMarkdownTree` unsuccessfully but without any error, until I realized that the directory in which the results are to be saved must exist prior to executing the binary. I think it would be helpful to make cobra either:

- Display an error message if the target directory does not exist.
- Create the target directory.

**Comment by bogem** [comment]
Actually, these functions return errors. Maybe you forgot to receive these errors. I think, you wrote just `doc.GenManTree(...args...)` but it should be `err := doc.GenManTree(...args...)`

**Comment by bogem** [comment]
But anyway I will make a PR to fix docs and add code to make these dirs for convenience.

**Comment by 1138-4EB** [comment]
Well, it was stupid of me. Sorry for bothering you.

Anyway, thanks for adding it explicitly.
