### ISSUE TITLE
Adding flags Dynamically

### ISSUE THREAD

**Issue by venkat-cliqr** [spf13/cobra#413]
Hello All,
We are using cobra to build a cli for our product and have an interesting use case. I want to add flags and the corresponding contextual help based on the value of another flag e.g
if a user types

cli add account 

we would show
Flags:
 --type string Account Type

But if a user types

cli add account --type vendor
we would like to show
Flags:
 "--type string  Account Type"
 "--vendorurl string Vendor URL"

I have tried attaching new Persistent flags in the execution of the Run/ PreRun of the account subcommand. The debug flags seems to show the command's flags have been updated but the output only shows the original declared flags.
I also tried creating a new cobra.Command and replacing that with the current subcommand. In this case 
"cli add account --type vendor help" or "cli add account --type vendor" work fine and show both the flags for type and vendorurl but
"cli add account --type vendor --help" shows the original output without the new flag.

Any suggestions if this is possible to do ?

Thanks
Venkat

**Comment by bogem** [comment]
Why don't you just document it?
```
--type string Account Type
--vendorurl string Vendor URL (requires --type vendor)
```
So this help will be shown independent of value of other flags.

**Comment by bogem** [comment]
Ping

**Comment by bogem** [comment]
Ping

**Comment by tigp** [comment]
Folks, is this feature available, as I have a config with dynamic objects and it would be cool override the config fields with flags. I have a thought to not depend on init function and initialise the commands after the config is loaded, but maybe something useful exists already?
