### ISSUE TITLE
Are commands with un-runnable parents deliberately undiscoverable?

### ISSUE THREAD

**Issue by mrkishi** [spf13/cobra#43]
In a program with a command structure such as `./program section command -flags`, why do un-runnable `section`s not appear in the `program`'s "Available Commands?"

You can list the child commands with `program help section`, but there's no way to find out that `section` exists. Is this intentional for some reason?

Thank you :)

**Comment by eparis** [comment]
hopefully this works now and we have a test to make sure it works...
