### ISSUE TITLE
question: how to find what flags is been called in the command

### ISSUE THREAD

**Issue by zer09** [spf13/cobra#434]
hello good day,
still learning cobra, is there a way to find out what flags is called when a command is executed?
I tried to use the `Flag.Changed` field to check if the default value is changed. but what if bool type of flags and have a default value of true. calling `Flag.Value` even the flag is not set it will return true.

Example I want to use it like this.
on a version command it has 2 flags 'number' and 'builddate'.

I would like to use it like this
`app version --number`
then only the version number will print.
`app version --builddate`
then only the build date will only print.
calling both of them will show both values.

thanks.

**Comment by bogem** [comment]
You can also iterate all activated flags by `versionCmd.Flags().Visit(...)`. More [here](https://godoc.org/github.com/spf13/pflag#FlagSet.Visit)

**Comment by zer09** [comment]
@bogem  thank you so much, I got it working. I like the `FlagSet.Visit`, it was clean.

**Comment by masterxavierfox** [comment]
@zer09 Do you mind elaborating your solution with an example thanks.

**Comment by zer09** [comment]
@masterxavierfox I forgot about this, but it will just iterate all the supplied flags, then you can check the flag information https://godoc.org/github.com/spf13/pflag#Flag.

Something like this
```
func checkFlags(f *Flag){
  if(f.Name == "something"){
    // do Something
  }
}

func main(){
  flagset.Visit(checkFlags);
}
```

**Comment by dmjones** [comment]
Also see the suggestion here: https://github.com/spf13/cobra/issues/453#issuecomment-303548563

**Comment by dmjones** [comment]
See the solution at https://github.com/spf13/cobra/issues/453#issuecomment-303548563. Using `Changed` will indicate if the user has set the value (even if to the same value as the default).
