### ISSUE TITLE
pflag / cobra: Parse string map values from command line

### ISSUE THREAD

**Issue by fuhrmannb** [spf13/cobra#435]
I have a use case where I want to parse a string map from command line as follow:
```
$ mycommand --string-map-option "a=b,c=d"
```
I haven't seen any method into cobra flags to parse the result as `map[string]string`.

For now, I have implemented in my project a basic version that satisfies `pflag.Value` interface. I use `cmd.Flags().Var()` to use the previous value and it's working well.

It will be interesting to directly have this parser into cobra and pflag packages. I think this flag parser can be helpful to the community.
If you are OK with this idea, I can propose a Pull Request based on my current implementation.

**Comment by bogem** [comment]
This issue is for https://github.com/spf13/pflag.

**Comment by fuhrmannb** [comment]
I have created spf13/pflag#129 issue. I close this one which is non relevant.
