### ISSUE TITLE
Regression in flag parsing Count flags

### ISSUE THREAD

**Issue by ncw** [spf13/cobra#443]
A command line which used to be OK

    rclone -v copy

Now fails with

```
Error: unknown command "copy" for "rclone"

Did you mean this?
	copy
	copyto

Run 'rclone --help' for usage.
```

I have run git bisect and the commit which introduced the problem is 9890b7b2e9070f2aaa7bad4ec94252098320a81c by @bogem 

The problem seems to be the `-v` flag which [is defined as](https://github.com/ncw/rclone/blob/master/fs/config.go#L60)

	verbose         = CountP("verbose", "v", "Print lots more stuff (repeat for more)")

This is a special sort of flag which can take a parameter or not so I suspect the changes in that commit didn't take account of `Count` type flags.

**Comment by bogem** [comment]
Does 'rclone copy -v' work?

**Comment by ncw** [comment]
> Does 'rclone copy -v' work?

yes it does.

Putting the verb first is a workaround for the problem.

However there are 1000s of scripts out there with `rclone -v copy` in because that is what I wrote in the docs!

**Comment by bogem** [comment]
Very strange what `rclone -vv copy` works.

**Comment by bogem** [comment]
The problem is in spf13/pflag. I fix it now.

**Comment by bogem** [comment]
I found out the problem. I fix it now.

**Comment by bogem** [comment]
Actually it was related to all flags you define for CommandLine in `rclone/fs/config.go`.
So `rclone -u copy`,  `rclone -q copy` ... don't work too.

**Comment by ncw** [comment]
I can confirm that fixes it :-)  Thanks for a super speedy fix.

**Comment by bogem** [comment]
You're welcome!
