### ISSUE TITLE
cobra init on windows powershell and cmd

### ISSUE THREAD

**Issue by zer09** [spf13/cobra#448]
I am just curious, executing `cobra init` on cmd it can create the command successfully but executing the `cobra init` on powershell it will got  an error `Error: Cobra only  supports project within $GOPATH`.

**Comment by bogem** [comment]
What is cmd?

**Comment by zer09** [comment]
I mean the "command prompt" on windows

**Comment by bogem** [comment]
Which arguments do you have with `cobra init`? In which directory do you execute `cobra init`? Is this directory in $GOPATH?

**Comment by zer09** [comment]
yes it inside the GOPATH directory, I didn't put any argument in `cobra init` so it will just create the root.go in cmd directory.

**Comment by bogem** [comment]
Please update the cobra/cmd (`go get -u github.com/spf13/cobra/cobra`) and send the output.

**Comment by bogem** [comment]
Actually, I see you use old version of cobra/cmd. I rewrote it in #428 and by the way fixed #330, which is copy of your issue, I think.

**Comment by zer09** [comment]
I got this when executing the `cobra init` on powershell without any arguments
```
PS F:\go\src\samp\test3> cobra init
Error: Cobra supports project only within $GOPATH: Rel: can't make F:\go\src\samp\test3 relative to
PS F:\go\src\samp\test3>
```

while this one is on the command prompt on the same directory, also without any arguments
```
F:\GO\src\samp\test3>cobra init
Your Cobra application is ready at
F:\GO\src\samp\test3.

Give it a try by going there and running `go run main.go`.
Add commands to it by running `cobra add [cmdname]`.

F:\GO\src\samp\test3>
```

**Comment by zer09** [comment]
It could be a file permission on the powershell side?
I will try it using administrator.

**Comment by bogem** [comment]
Do you have $GOPATH set in your powershell (`echo $GOPATH`)?

**Comment by bogem** [comment]
(I accidentally closed the issue)

**Comment by zer09** [comment]
My GOPATH is already part on System Variables(if I am correct that is already system-wide), so I just added it by now on the User-Path and System-Path.

I tried running it on the  a normal user and administrator user but still got this
```
PS F:\go\src\samp\test5> cobra init
Error: Cobra supports project only within $GOPATH: Rel: can't make F:\go\src\samp\test5 relative to
PS F:\go\src\samp\test5>
```

but here is the weird thing, I think.

I navigate to the directory where I want to execute it, then do right-click while holding the shift key, then click `Open PowerShell window here` then execute `cobra init` and got this.
```
PS F:\GO\src\samp\test5> cobra init
Your Cobra application is ready at
F:\GO\src\samp\test5.

Give it a try by going there and running `go run main.go`.
Add commands to it by running `cobra add [cmdname]`.
PS F:\GO\src\samp\test5>
```

**Comment by bogem** [comment]
Please update the cobra/cmd (`go get -u github.com/spf13/cobra/cobra`) and execute it one more time.

**Comment by zer09** [comment]
Sorry I tried it, but still no avail.

**Comment by bogem** [comment]
Do you become same output?
Please send me it.

**Comment by zer09** [comment]
yes still the same.
```
PS F:\go\src\samp\test5> cobra init
Error: Cobra supports project only within $GOPATH: Rel: can't make F:\go\src\samp\test5 relative to
PS F:\go\src\samp\test5>
```

**Comment by bogem** [comment]
Please update the cobra/cmd (`go get -u github.com/spf13/cobra/cobra`) and execute it one more time.

**Comment by zer09** [comment]
WOW! thanks it works.

**Comment by bogem** [comment]
You're welcome!
