### ISSUE TITLE
Document flags' SortFlags option

### ISSUE THREAD

**Issue by bogem** [spf13/cobra#452]
There is an ability to disable sorting the flags in help, but it's not documented in cobra docs.
Was introduced in #414.

**Comment by mattstratton** [comment]
In the short term, can you share how to use this? I have looked through the PR and the code, and I'm not seeing exactly.

**Comment by bogem** [comment]
@mattstratton 
To disable sorting of flags, just turn the `SortFlags` field of any flagset **before** setting the flags:
```go
var cmd = &cobra.Command{ ... }

func init() {
    cmd.Flags().SortFlags = false
    cmd.Flags().Bool("a", false, "a flag")
    cmd.Flags().Bool("b", true, "b flag")
    ...
}
```
