### ISSUE TITLE
Support IsSet() method on flags

### ISSUE THREAD

**Issue by nikhiljindal** [spf13/cobra#453]
To distinguish when the flag got default value because user didnt set any or user explicitly set the flag to same value as the default value.

**Comment by bogem** [comment]
Flags already have field [`Changed`](https://godoc.org/github.com/spf13/pflag#Flag):
```
flag := cmd.Flags.Lookup("someFlag")
if flag != nil && flag.Changed {
    // user set the flag
}
```

**Comment by bogem** [comment]
You can use Changed func to check it:
if cmd.Flags().Changed("someFlag") {
    // user set the flag
}

**Comment by nikhiljindal** [comment]
Thanks! That worked.

**Comment by xieyuschen** [comment]
Could we also provide a function like:
```go
func (f *FlagSet) GetChangedList() []string 
```
So we could register a handler map to process the corresponding flags.

**Comment by johntdyer** [comment]
@xieyuschen  that would be nice
