### ISSUE TITLE
There is no way to conditionally run a function before running subcommands

### ISSUE THREAD

**Issue by kissgyorgy** [spf13/cobra#458]
I have two level deep subcommand structure. I have "backends" for which I need to load configuration before any second-level subcommands run, but the first-level subcommands are only showing help, in which case I don't want to load configuration because these can be extremely expensive (e.g. coming from a database or network). So I would like to show only the help when running a first-level subcommand, but I need to load the configuration when a second-level sub command is run, because without it, I can't run the second-level subcommands.
Currently, this is not possible in Cobra because `cobra.OnInitialize` will always run before any command, `PersistentPreRun` hook will always run before the second-level subcommand and `PersistentPostRun` hook will always run too late.
I was thinking about setting a boolean `dontLoadConfiguration` somewhere when running first-level subcommands (when showing only help), but there is not a point I could check that either.

Coming from Python, with the use of the great Click framework, [it's possible to determine in the main command if a sub command is going to be executed](http://click.pocoo.org/5/api/#click.Context.invoked_subcommand) with the `Context.invoked_subcommand` boolean. This would be nice for Cobra too.

Okay, I lied a little bit :) because setting the same `loadConfiguration` function in *every single* subcommand of the library (I have dozens) is possible in the `PreRun` hooks in the second-level subcommands, but it's really tedious. Ideally, I would like to set it once in the `rootCmd` and forget it and happily develop new subcommands without forgetting to set `loadConfiguration` once again...

**Comment by bogem** [comment]
> I need to load the configuration when a second-level sub command is run, because without it, I can't run the second-level subcommands.

> PersistentPreRun hook will always run before the second-level subcommand

**Comment by bogem** [comment]
And you can create one function for initializing the DB/network and call it in `Run` func of every command you need.

**Comment by kissgyorgy** [comment]
> And you can create one function for initializing the DB/network and call it in Run of every command you need.

That's exactly what I described at my last paragraph which you can see if you read it. It's okay if you don't read it or don't care, but don't reply in that case because it makes no sense.

**Comment by bogem** [comment]
Sorry, I was sleepy yesterday evening and didn't notice it.
Could you please give a concrete example of your problem?

**Comment by kissgyorgy** [comment]
I don't have fully working code yet, but a basic organization. For example, I have a subcommand:

```golang
var certCmd = &cobra.Command{
	Use:   "cert",
	Short: "Issue, sign, revoke, list and view certificates.",
	Long:  `Issue, sign, revoke, list and view certificates.`,
}

var issueCertCmd = &cobra.Command{
	Use:    "issue",
	Short:  "Issue new certificate.",
	Long:   "Issue new certificate.",
	PreRun: loadBackend,
	Run:    issueCert,
}

var showCertCmd = &cobra.Command{
	Use:    "show",
	Short:  "Show certificate details.",
	Long:   "Show certificate details.",
	PreRun: loadBackend,
	Run:    showCert,
}

var showCACertCmd = &cobra.Command{
	Use:    "show-ca",
	Short:  "Show CA certificate details.",
	Long:   "Show CA certificate details.",
	PreRun: loadBackend,
	Run:    showCACert,
}

var revokeCertCmd = &cobra.Command{
	Use:    "revoke",
	Short:  "Revoke certificate.",
	Long:   "Revoke certificate.",
	PreRun: loadBackend,
	Run:    revokeCert,
}

var deployCertCmd = &cobra.Command{
	Use:    "deploy",
	Short:  "Deploy certificate.",
	Long:   "Deploy certificate.",
	PreRun: loadBackend,
	Run:    deployCert,
}

var sendCertCmd = &cobra.Command{
	Use:    "send",
	Short:  "Send certificate by email.",
	Long:   "Send certificate to a given email address.",
	PreRun: loadBackend,
	Run:    deployCert,
}

var listCertsCmd = &cobra.Command{
	Use:    "list",
	Short:  "List all certificates.",
	Long:   "List all certificates.",
	PreRun: loadBackend,
	Run:    listCerts,
}

var convertCertCmd = &cobra.Command{
	Use:    "convert",
	Short:  "Convert a certificate from PEM to DER or back.",
	Long:   "Convert a certificate from PEM to DER or vice versa.",
	PreRun: loadBackend,
	Run:    convertCert,
}
```

which is insane amount of duplication IMO. And this is just the minimal number commands I absolutely need to implement, and have other commands like this one too.
So I would like to call `loadBackend` somewhere near my `rootCMD` and conditionally check if there will be a subcommand running, so the definitions would be 

```golang
...
var listCertsCmd = &cobra.Command{
	Use:    "list",
	Short:  "List all certificates.",
	Long:   "List all certificates.",
	Run:    listCerts,
}

var convertCertCmd = &cobra.Command{
	Use:    "convert",
	Short:  "Convert a certificate from PEM to DER or back.",
	Long:   "Convert a certificate from PEM to DER or vice versa.",
	Run:    convertCert,
}
...
```
and I would not have to set them for new commands also.

**Comment by kissgyorgy** [comment]
Actually if I leave out `Run` from sub-commands (which only print help by default) and define `PersistentPreRun` exactly happening what I want 😄  sorry. Then this is just maybe a small documentation issue.

**Comment by kissgyorgy** [comment]
Okay, my problem is clear now. The [OnInitialize function documentation]( https://godoc.org/github.com/spf13/cobra#OnInitialize) should describe what it's doing, because currently it doesn't say anything useful.

**Comment by kissgyorgy** [comment]
Meh, still not good, because I have a `RootCmd` like this:
```golang
var RootCmd = &cobra.Command{
	Use:   "certmaestro",
	Short: "Certmaestro command line interface.",
	Long:  `Certmaestro is a toolkit to make it easy to handle your own PKI infrastructure.`,
	PersistentPreRun: loadBackend,
        Run: printHelpOrVersion,
}

func init() {
	f := RootCmd.PersistentFlags()
	f.StringVarP(&configFile, "config", "c", "", "config file (default is $HOME/.certmaestro.toml)")
	f.BoolVarP(&showVersion, "version", "V", false, "Show version.")
}

func loadBackend(cmd *cobra.Command, args []string) {
    // getting configuration from database
}

func printHelpOrVersion(cmd *cobra.Command, args []string) {
	if showVersion {
		printVersion(cmd, args)
	} else {
		cmd.Help()
	}
}
```

and I definitely don't want to load configuration before running the main command, but this case it will always run when I invoke `RootCmd`, but I only want to run if the `printVersion` is running (I need to have the config to be able to run verbose version for the configured backend) not `cmd.Help`

**Comment by kissgyorgy** [comment]
Okay, I was able to do what I want by setting the same `loadBackend` function only for the first-level subcommands which is acceptable, but the documentation sections I mentioned above should be rewritten. Sorry for the spam 😄

**Comment by CannibalVox** [comment]
I'm altogether not really happy with persistentprerun altogether- I have the following setup:

 - root command (about a dozen subcommands under this)
     - resource modify parent command (child of root command with about a dozen subcommands under this)

There's a bunch of API connections I'd like to initialize before running all commands, and I'd like to do a resource seek & open a connection to the resource for the resource modify parent command.

Obviously I can call the first at the beginning of each individual command, and call the second immediately after that in each individual resource modify command.  But, you know, that's what I'd expect a prerun command in a hierarchical command structure to do for me.  It's not clear why only one persistentprerun will run, or the one will run is not the root but the mid-tier command.  Both of those are the opposite of what I'd expect.

**Comment by sourcec0de** [comment]
@CannibalVox @kissgyorgy @bogem hey guys, figured I would drop this here. Not sure if you're still looking for a solution but for passing dependencies I know I'm going to need for all my commands I use embedded structs to achieve this. Hopefully, this is helpful.

I actually achieved this through creating a `RootCmdExtended` struct and embedding `*cobra.Command`.
This way in `root.go` `init()` I'm able to call an initializer attach any dependencies I need to the `RootCmdExtended` struct.

`root.go`
```go
type RootCmdExtended struct {
	*cobra.Command
	Pubsub *pubsub.Client
}

func (cmd *RootCmdExtended) initPubSub() {
	// initialize and set my client
	cmd.Pubsub = client
}

var RootCmd = &RootCmdExtended{
	Command: &cobra.Command{
		Use:   "",
		Short: "",
		Long: ``,
	},
}

init () {
	RootCmd.initPubSub()
	// this allows us to ensure any variables or flags have been loaded
	// before initialization as well so you can use them in your  initPubSub()
	// now RootCmd.PubSub is available globally for all commands
}
```

`command.go`

```go
var commandCmd = &cobra.Command{
	Use:   "othercommand",
	Short: "",
	Long:  ``,
	Run: func(cmd *cobra.Command, args []string) {
		// RootCmd.PubSub is accessible and initialized
	},
}

```
