### ISSUE TITLE
#32 erroneously omits long description as well for <command> help

### ISSUE THREAD

**Issue by k4rtik** [spf13/cobra#46]
Trying out @spf13's tutorial at http://spf13.com/presentation/first-go-app/ (step 1) I discovered that when there is no subcommand added, default `help` fails:

```
k4rtik at PlatiniumAir in ~/Projects/go/src/github.com/k4rtik/planet
$ go run main.go help

Usage:
  dagobah [flags]

 Available Flags:
  -h, --help=false: help for dagobah
Error: unknown command "help"
Run 'help' for usage.

dagobah: invalid command [`help`]
Run 'dagobah help' for usage
unknown command "help"
Run 'help' for usage.

exit status 255
```

This seems to have originated from the merge of #32

**Comment by k4rtik** [comment]
Previous expected output for comparison:
```
k4rtik at PlatiniumAir in ~/Projects/go/src/github.com/k4rtik/firstGoApp-Planet
$ go run main.go help
Dagobah provides planet style RSS aggregation. It
is inspired by python planet. It has a simple YAML configuration
and provides it's own webserver.

Usage:
  dagobah
  dagobah [command]

Available Commands:
  help [command]            Help about any command


Use "dagobah help [command]" for more information about that command.
```

**Comment by bogem** [comment]
Send me a code of your app please

**Comment by bogem** [comment]
I think, it's because of `if err := cmd.Execute(); err != nil { ...`. If you will not receive errors (just `cmd.Execute()`), it will solve the issue.

**Comment by bogem** [comment]
Ping

**Comment by k4rtik** [comment]
Sorry, unfortunately, I am not interested in pursuing this any further. It's been too long, I am closing the issue. Please feel free to reopen but I may not be of any help.
