### ISSUE TITLE
Error from RootCmd.PersistentPreRunE printed twice, with usage string

### ISSUE THREAD

**Issue by ahmetb** [spf13/cobra#464]
I have a PersistentPreRunE set on my RootCmd. It is simply:

```
func check(cmd *cobra.Command, args []string) error { return errors.New("foo error") }
```

when I run my command, I get:

```
$ ./my-tool Error: foo error
Usage:
  my-tool my-subcommand [flags]

Flags:
  -h, --help   help for list

Global Flags:
  -p, --project string   Google Cloud project ID

foo error
```

Problems:

1. why is `foo error` printed twice (at the very beginning and at the very end)?
2. why is the full usage string printed? Is there a way to prevent it?

**Comment by bogem** [comment]
1. I think, it's because you print an error returned from `cmd.Execute()`. `Execute` func already [prints](https://github.com/spf13/cobra/blob/master/command.go#L738) an error if it occurred in `PersistentPreRunE`.
2. You can prevent it with `cmd.SilenceUsage = true`.

**Comment by ahmetb** [comment]
@bogem thanks for the answer. When I SilenceUsage=true, duplicate printing looks worse:

```
$ my-tool -s
Error: unknown shorthand flag: 's' in -s
unknown shorthand flag: 's' in -s
```

**Comment by bogem** [comment]
Probably, it's because you print an error returned from `cmd.Execute()` like this:
```go
if err := cmd.Execute(); if err != nil {
    fmt.Println(err)
}
```
but `cmd.Execute()` prints errors automatically as I said before. So just delete all error handling in your app and leave only `cmd.Execute()` call.

**Comment by ahmetb** [comment]
actually my main.go is already just:

    func main() { cmd.Execute() }

and yet I'm still getting errors printed twice, so I'll reopen this.

**Comment by ahmetb** [comment]
oh turns out I had this in `root.go`


```
func Execute() {
	if err := RootCmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

```

**Comment by rayjohnson** [comment]
That part in the rootCmd is generated by the cobra command line tool when generating framework.  Should it?

**Comment by weibeld** [comment]
Maybe it should really be removed from the Cobra generator tool, as it is confusing, especially for beginners, who are the most likely ones to use the Cobra generator.
