### ISSUE TITLE
Question: Can I have args/flags between rootcmd and subcommand

### ISSUE THREAD

**Issue by hjma29** [spf13/cobra#467]
I'm trying to have something like the following.

parentCmd <arg1 or flag1> subCommand <arg2 or flag2>

the use case is

show **module** --module-name="module 1" **port** --port-name="port 1"

module is parent command and port is sub command and I want to display the port 1 on module 1.

**Comment by dnephin** [comment]
#299 adds support for this

**Comment by hjma29** [comment]
thank you!
