### ISSUE TITLE
Question: Maximum width

### ISSUE THREAD

**Issue by gtirloni** [spf13/cobra#468]
It seems that when I adjust my terminal window, the line breaks in the help messages go up to 120 characters (even if the window is larger). Is this by design?

I'm using gnome-terminal 3.24.2.

**Comment by bogem** [comment]
No, it's not by design.
I can't reproduce it actually on iTerm 3.4.beta1:
![2017-06-18 8 55 56](https://user-images.githubusercontent.com/13235519/27258785-1c135de6-5404-11e7-9b83-451a671113da.png)

**Comment by gtirloni** [comment]
Interesting. I can reproduce it on gnome-terminal and xterm.

Please see below. First I have a small window and the line breaks are added. Then I increase the window size but the new output only goes up to 120 chars.

![screenshot from 2017-06-18 06-23-42](https://user-images.githubusercontent.com/5902830/27259667-d32a18fa-53ee-11e7-921e-5596111e4df7.png)

gnome-terminal does line wrapping ("rewrap on resize") but the behavior is the same with that setting turned off.

**Comment by bogem** [comment]
Cobra doesn't add any line breaking and can't physically redraw the help output by resizing a terminal window.
I think, it's a bug/feature of gnome-terminal.

**Comment by gtirloni** [comment]
Thanks for clarifying, I wanted to confirm it wasn't something in cobra.
