### ISSUE TITLE
Add custom flags to help subcommand

### ISSUE THREAD

**Issue by kashishm** [spf13/cobra#478]
Can I add custom flags to the help subcommand?

**Example**
```
hugo help -a
hugo help -l
```

**Comment by bogem** [comment]
Yes, but please update the cobra at first: `go get -u github.com/spf13/cobra'.
```go
package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

func main() {
	cmd := &cobra.Command{
		Use:  "app",
		Long: "QWEQWE",
		Run:  func(cmd *cobra.Command, args []string) {},
	}

	cmd.AddCommand(&cobra.Command{
		Use:  "app",
		Long: "QWEQWE",
		Run:  func(cmd *cobra.Command, args []string) {},
	})

	helpCmd := &cobra.Command{
		Use:   "help [command]",
		Short: "Help about any command",
		Long: `Help provides help for any command in the application.
	Simply type ` + cmd.Name() + ` help [path to command] for full details.`,

		Run: func(c *cobra.Command, args []string) {
			cmd, _, e := c.Root().Find(args)
			if cmd == nil || e != nil {
				c.Printf("Unknown help topic %#q\n", args)
				c.Root().Usage()
			} else {
				cmd.InitDefaultHelpFlag() // make possible 'help' flag to be shown
				fmt.Println("CUSTOM")
				cmd.Help()
			}
		},
	}

	helpCmd.Flags().BoolP("aflag", "a", true, "a")
	helpCmd.Flags().BoolP("lflag", "l", true, ";")
	cmd.SetHelpCommand(helpCmd)
	cmd.Execute()
}
```

**Comment by kashishm** [comment]
Thanks, It works.

**Comment by gennaro-tedesco** [comment]
I am trying to reproduce the above but I am getting an error as `SetHelpCommand not declared by package cmd`, the same error occurring using any of the custom help functions [specified here](https://github.com/spf13/cobra#defining-your-own-help); I guess it is a problem of imports: what file (in a Cobra app) must specify the custom help?

It could be very helpful to specify where the set of functions
```
cmd.SetHelpCommand(cmd *Command)
cmd.SetHelpFunc(f func(*Command, []string))
cmd.SetHelpTemplate(s string)
```
must be used: it is unclear where to put them (see error above) and the notation is slightly incorrect (if `cmd` the instance of a command then it cannot be the same name as the argument of the function, so it is hard to understand which is which).
