### ISSUE TITLE
Default config path contradicts the system default from windows and the xdg-definitions for linux

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [spf13/cobra#479]
The configruation path of cobra generated files defaults to "$HOME" which is no place the configruation belongs to. For windows there is the environment variable %APPDATA% which is always set and for linux systems it should be best practive to use the $XDG_CONFIG_HOME environment variable which defaults to $HOME/.config and must not be set.

Reference with explanation: [StackOverflow](https://stackoverflow.com/questions/11113974/what-is-the-cross-platform-way-of-obtaining-the-path-to-the-local-application-da/39868933#39868933)
Reference to xda: [freedesktop.org env vars](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html)

**Comment by Fjolnir-Dvorak** [comment]
Found project to easily solve system-dependend config path's: [github.com/shibukawa/configdir](https://github.com/shibukawa/configdir). Licensed under MIT. Will create a merge-request tomorrow containing the fix.

**Comment by Fjolnir-Dvorak** [comment]
I am not finding any System or Environment variables for Darwin/MacOS. I do not want to hard-code those strings. I will look a few days longer for a sollution.

**Comment by bogem** [comment]
What do you think about backward compatibility?
Currently users have config in their home path, but after this change a lot of people will encounter a problem that their configs are not to be found.
I don't think this issue is a real problem for users.

**Comment by Fjolnir-Dvorak** [comment]
It would not change anything for them. My change only changes the behaviour of new projects. The config path is defined when generating a new project using Cobra.
But every new project would have the correct config settings. And I think that the temptation is quite low to change the config path from $xdg_config_home to $home.
