### ISSUE TITLE
Execute several commands at once.

### ISSUE THREAD

**Issue by x8core** [spf13/cobra#482]
For example i have command called "Init". What i should to write in this command, if i want when i start this command "Init" it will trigger to execute some number of subcommands?

**Comment by bogem** [comment]
What's the problem to just call the `Run` func of needed subcommands?
```go
package main

import (
	"github.com/spf13/cobra"
)

var c1 = &cobra.Command{Use: "c1", Run: runC1}
var c2 = &cobra.Command{Use: "c2", Run: runC2}

func runC1(cmd *cobra.Command, args []string) {
	// do something
}

func runC2(cmd *cobra.Command, args []string) {
	// do something
	runC1(cmd, args)
	// do somethind
}

func init() {
	c1.AddCommand(c2)
}

func main() {}
```

**Comment by x8core** [comment]
Thanks. This is exactly what i need. Maybe you can add it in examples of Readme.
Code of example may be shorten.
`var initCmd = &cobra.Command{
	Use:   "init",
	Short: "",
	Long: "",
	Run: func(cmd *cobra.Command, args []string) {
		cmd1.Run(cmd, args)
		cmd2.Run(cmd, args)
		cmd3.Run(cmd, args)
	},
}`

**Comment by bogem** [comment]
> Maybe you can add it in examples of Readme.

No, I think it's obvious solution

> But maybe code can it be more simple like that?

But Run and Execute are different things actually. It depends on what you need.
