### ISSUE TITLE
Change the description for default help flag

### ISSUE THREAD

**Issue by kashishm** [spf13/cobra#483]
```
> app --help

  -h, --help               help for app
```
Can we capitalize the first letter of description of `help` flag i.e `Help for app`? or is there a way to override the description for the `help` flag?
I think it is hardcoded in [command.go](https://github.com/spf13/cobra/blob/master/command.go#L756). I want this for the root command and all the subcommands. So adding `help` flag manually will be my last option.
```
app.Flags().BoolP("help", "h", false, "Help for "+app.Name())
```

**Comment by kashishm** [comment]
I found the following solution. Just wanted to check if it Is the recommended way
```go
for _, c := range append(RootCmd.Commands(), RootCmd) {
	c.Flags().BoolP("help", "h", false, "Help for "+c.Name())
}
```

**Comment by bogem** [comment]
Duplicate of #480
