### ISSUE TITLE
Long description formatting

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [spf13/cobra#484]
The long description formatting is handling line breaks in the IDE as a new Line. Also Tab characters are not removed at the beginning of the line.

**Example:**
```
var (
	GameCMD = &cobra.Command{
		Use:   "game",
		Short: "Utilities modifying the game data.",
		Long: `This package interacts directly with the game files
			or wil generate and deploy them. To archive that it looks
			for the location of the game files inside the windows registry.`,
	}
)
```

The example above uses tab characters for indentation (it is the default behaviour of the IDE and "go fmt" is not replacing it with whitespaces which leads to a valid code design pattern.) and new-lines to make it human-readable (line length, and "abc" + "def" + "ghi" is quite ugly).

**My suggestion:**
1. Minify the long description (deleting all tabs, newlines and double spaces).
2. parse '\n' to a "by the user forced" newline
3. Soft wrap the whole text and indent it as needed.

**Comment by bogem** [comment]
It's because you use [raw string literal](https://golang.org/ref/spec#String_literals).
Fix is:
```go
var (
	GameCMD = &cobra.Command{
		Use:   "game",
		Short: "Utilities modifying the game data.",
		Long: "This package interacts directly with the game files" +
			"or wil; generate and deploy them.\nTo archive that it looks" +
			"for the location of the game files inside the windows registry.",
	}
)
```
