### ISSUE TITLE
Please make Mousetrap hook optional

### ISSUE THREAD

**Issue by dwall80** [spf13/cobra#486]
Re this file: https://github.com/spf13/cobra/blob/master/command_win.go

There is an alert which comes up on windows if you attempt to run the app from explorer (eg as GUI). Whilst this is no doubt useful to many/most users, I've had to fork your otherwise wonderful package to address this as I am creating an installer app that does run as a GUI if called from explorer and runs as a cli app if called from the command line, It would be great if we could pass in a custom hook or at least have a way of skipping this particular hook when it is a hindrance.

NOTE: I would submit a PR but my current fix is to delete the file - If you have ideas about how you would like this implemented (if at all) then please let me know and I'll be happy to put something together. I'm guessing a SkipMousetrapCheck config that defaults to false would be the simplest way to maintain backwards compatibility.

**Comment by bogem** [comment]
There is already a PR (#383) for this, but without progress.
I will fix it today later.

**Comment by dwall80** [comment]
Thanks for the quick response and resolution
