### ISSUE TITLE
Flags, LocalFlags, LocalNonPersistentFlags, etc

### ISSUE THREAD

**Issue by rmsj** [spf13/cobra#488]
I have a number of commands with same flag name - but meaning something different for the command.
When I set the flags with Flags or LocalFlags I have an error that the flag is repeated.

If I set as LocalNonPersistentFlags the repeat error disappears but none of my flags are recognised anymore.

**Comment by bogem** [comment]
Actually, it's not possible now to set flags with the same name for command.
#299 fixes it.

**Comment by bogem** [comment]
And if you want to set local flag, you should use only `Flags()` function. Otherwise flag won't be added.

**Comment by eparis** [comment]
`cmd.Flags()` and `cmd.PersistentFlags()` are the only places you should set new flags. The other functions are useful to get back information about sets of flags, but you will likely have unexpected behavior if you try to set flags on those.

**Comment by rmsj** [comment]
What you mean by local flag is just for a single command?
Because it still validates, saying, for example, my command "authorize", flag "auth" is being repeated on command "check", who happens to have a flag with same name, another meaning.
So this is not possible?

**Comment by bogem** [comment]
> What you mean by local flag is just for a single command?

Yes

> Because it still validates, saying, for example, my command "authorize", flag "auth" is being repeated on command "check", who happens to have a flag with same name, another meaning.
So this is not possible?

Sorry, but can you please provide clearer example?

**Comment by rmsj** [comment]
Yep, sure.

One of my commands I have:

`	commandOneCmd.Flags().StringP("auth", "a", "", "Some desc here")
	viper.BindPFlag("auth", commandOneCmd.Flags().Lookup("auth"))
`

On another command I have:

`	commandTwoCmd.Flags().StringP("auth", "a", "", "Some desc here.")
	viper.BindPFlag("auth", commandTwoCmd.Flags().Lookup("auth"))
`

Command two has a few other flags but I get the error that the "auth" flag is repeated.
I thought it would be specific for that command only.

**Comment by bogem** [comment]
It's very strange.
Is `commandOne` parent of `commandTwo`?

**Comment by rmsj** [comment]
Nope.
Hold on I will try again.

**Comment by rmsj** [comment]
Yep, confirmed.
If I set the flag in command one and then get it set for command 2, I got the error:
`panic: commandOne flag redefined: auth`

**Comment by bogem** [comment]
Can you please provide a code of this issue?

**Comment by rmsj** [comment]
Ok, I've removed and recreated my commands.
Looks like it's all fine. No idea. Thanks for following up and sorry for taking your time.
