### ISSUE TITLE
how to pass debug tag to trigger log printting

### ISSUE THREAD

**Issue by hjma29** [spf13/cobra#489]
I wonder what's the way to pass a tag in CLI into code to trigger log.Println output to console. By default I want all log.Println information hidden but if I want to debug the code, I want to pass "-d true" tag to trigger output to terminal. some syntax like

show <different show sub commands, multi tiers> --debug

I tried the following code but it looks like init() execute before the "--debug" bool tag can change my default "debugmode" from false to true

```
var 	debugmode  = false

func init() {

showCmd.PersistentFlags().BoolVarP(&debugmode, "debug", "d", true, "Debug:true,false")

	//if commandflag -d is not set, then we should change default logger destination to discard
	if !debugmode {
		log.SetOutput(ioutil.Discard)
	}

}
```

**Comment by bogem** [comment]
Could you please explain your problem clearer?

**Comment by hjma29** [comment]
sorry for confusion. I ended up using  

`cobra.OnInitialize(initConfig)`

and put above if !debugmode statement in func(initConfig) and it resolved the issue for me
