### ISSUE TITLE
TestGolden{Add,Init}Cmd may fail if $HOME/.cobra.yaml exists

### ISSUE THREAD

**Issue by anthonyfok** [spf13/cobra#505]
Simply setting the author or license in $HOME/.cobra.yaml would cause TestGolden{Add,Init}Cmd to fail during a `go test` run.

This is a minor issue, and it doesn't affect the Reproducibility tests because they are not going to put a $HOME/.cobra.yaml on those automated test machines.

**Comment by bogem** [comment]
> Simply setting the author or license in $HOME/.cobra.yaml would cause TestGolden{Add,Init}Cmd to fail during a go test run.

How?
