### ISSUE TITLE
Build failing on circleci

### ISSUE THREAD

**Issue by bpicode** [spf13/cobra#506]
It seems that I introduced a build failure via https://github.com/spf13/cobra/pull/497. Sorry for that. The tests in zsh_completions_test.go do not compile.

Background:
circleci builds with go 1.5, which does not support testing.T.Run.

Shall I fix this or would it be better to upgrade the circle runner (and thus the go version)?

**Comment by anthonyfok** [comment]
Thanks for the heads up!

I changed the "OS use for builds" from "Ubuntu 12.04 (Precise)" (Go 1.5.3) to "Ubuntu 14.04 (Trusty)" (Go 1.8.3) according to https://circleci.com/docs/1.0/language-go/.  Hope that setting sticks and actually works for the next push to the repository!

**Comment by bpicode** [comment]
OK thx.

**Comment by bogem** [comment]
This issue is fixed as #507 passed the tests.
