### ISSUE TITLE
Is it possible to create a cobra CLI with autocompletion for windows cmd?

### ISSUE THREAD

**Issue by kubawi** [spf13/cobra#509]
The docs aren't exactly clear. Can you only use autocomplete function on linux/unix?

**Comment by Fjolnir-Dvorak** [comment]
There is no auto-completion script for windows at the moment, which does not mean ther will not be, if it is possible, if someone is willing to implement that feature

**Comment by bogem** [comment]
Duplicate of https://github.com/spf13/cobra/issues/387
