### ISSUE TITLE
Use PersistentFlag to toggle other flags

### ISSUE THREAD

**Issue by gbraad** [spf13/cobra#510]
I want to use a way to toggle features on and off, but so far I have not succeeded when using a `Flags` or `PersistentFlags`. However, when using `os.GetEnv("enable-experiment") works as an alternative approach.

```go
const enableExperimental = "enable-experimental"

var hasEnabledExperimental bool = false

func init() {
       RootCmd.PersistentFlags().Bool(enableExperimental, false, "Enable experimental features.")
}

var RootCmd = &cobra.Command{
       Use:   "mytool",
       Short: "My awesome tool does ...",
       Long:  `My awesome tool does ... and so much more.`,
       PersistentPreRun: func(cmd *cobra.Command, args []string) {
              hasEnabledExperimental = viper.GetBool(enableExperimental)
       }
}
```

Another file does the following:

```go
const commandName = "start"

func init() {
       startCmd = &cobra.Command{
              Use:   commandName,
              Short: "Starts ... ",
              Long: `Starts ... and so much more.`,
              Run: runStart,
       }

       startUpFlagSet := flag.NewFlagSet(commandName, flag.ContinueOnError)
       if hasEnabledExperimental {
                // at this stage does the bool 'hasEnabledExperimental' have value 'false' under any condition?
                startUpFlagSet.Bool(startFlags.Service.Name, false, "Install service (experimental)")
                startUpFlagSet.String(startFlags.ExtraStartUpFlags.Name, "", "Specify optional flags")
       }

       startCmd.Flags().AddFlagSet(startUpFlagSet)

       RootCmd.AddCommand(startCmd)
}
```

The problem is that `hasEnabledExperimental` has the value `false` at the time the `init()` is run for the command. This results that the command will fail with an `unknown flag`. What can I do to add flags that are also included in the help text when requested.

**Comment by bogem** [comment]
Hello!
The problem is that you wrongly get a value of flag. Change this line:
```go
```
to this:
```go
hasEnabledExperimental = RootCmd.PersistentFlags().Bool(enableExperimental, false, "Enable experimental features.")
```

**Comment by gbraad** [comment]
```
var hasEnabledExperimental bool = false;

init(){
       RootCmd.PersistentFlags().BoolVar(&hasEnabledExperimental, enableExperimental, false, "Enable experimental features.")
}
```

does not set the value early enough, as:

```
func init() {
       if hasEnabledExperimental {
              fmt.Println("Never true")
       }
}
```

never sets the value in time to be evaluated as true. I have a branch with the code here: https://github.com/gbraad/minishift/commit/df05eebda1dfa93972a76d592e06c4fc3d88d3cf

**Comment by bogem** [comment]
`init()` is evaluated even before parsing the flags (flag are parsed in `cmd.Execute()`) and it's not possible to get a value of flag in `init` function.

**Comment by gbraad** [comment]
Clear... so it is not possible to do what we want.

**Comment by eparis** [comment]
If you need to know the flag value in `init()` (or any time before `Execute()`) you are going to have parse the command line yourself. I was hoping you could use https://godoc.org/github.com/spf13/pflag#ParseAll to make that easier, but I think it would error out and wouldn't really be useful to get your `enableExperimental` value.
