### ISSUE TITLE
Question about using command's config file for subcommands

### ISSUE THREAD

**Issue by nnutter** [spf13/cobra#525]
I'm new to Go and to Cobra/Viper so it's likely I'm trying to do something overly complicated and I'm not seeing much documentation about integrating Cobra subcommands with a command's config file.  I am creating a command with sub-commands and would like to support pulling flag values from Viper so that there is basically a hierarchical lookup from command line to a subsection in config file to flag default.

In a command file I can have an `init()` like,

```go
func init() {
	subCmd1.AddCommand(subCmd2)

	subCmd2.Flags().String("flag1", "my default", "my usage")
	viper.BindPFlag("subCmd1.SubCmd2.flag1", subCmd2.Flags().Lookup("flag1"))
}
```

But what I think I want is to be able to `BindPFlags` but to a sub-tree of the config,

```go
func init() {
	subCmd1.AddCommand(subCmd2)

	subCmd2.Flags().String("flag1", "my default", "my usage")

	viper.BindPFlags(subCmd2.Flags(), "subCmd1.subCmd2")
}
```

So in `Run()` when I do `viper.GetString("flag1")` it would essentially be the same as `viper.GetString("subCmd1.SubCmd2.flag1")`.

The motivation being to avoid having to call `viper.BindPFlag()` _n_ times which I assume is also the motivations for `viper.BindPFlags()`.

Is there a way to do this already or, maybe, a recommended alternative?

**Comment by kunickiaj** [comment]
Did you figure this out? looking to do something similar.

**Comment by nnutter** [comment]
I don't remember clearly but I believe I did not.
