### ISSUE TITLE
Is it possible to use internal cobra functionality to parse a string as if it was a command line argument?

### ISSUE THREAD

**Issue by EIrwin** [spf13/cobra#533]
I am writing a slack bot that is more or less emulating a CLI tool.

The slack bot will send the command `text` to an HTTP endpoint where its my responsibility to parse it.

I obviously don't want to write my own logic for parsing this when Cobra is much better at it, however I don't see any way to accomplish this.

For example, a simple cobra exampe might be the following:

```go

func main() {
	var times int

	var cmdGet = &cobra.Command{
		Use:   "echo {phrase}",
		Short: "blah short",
		Long:  `blah blah long`,
		Args:  cobra.MinimumNArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			for i := 0; i < times; i++ {
				fmt.Println("Echo: " + strings.Join(args, " "))
			}
		},
	}

	var rootCmd = &cobra.Command{Use: "app"}
	rootCmd.PersistentFlags().IntVarP(&times, "times", "t", 1, "times to echo")

	rootCmd.AddCommand(cmdGet)
	rootCmd.Execute()
}
```

However, I would need some way to initialize my `rootCmd` and everything below it from a string such as the following

```go
func main() {
	var times int

	var cmdGet = &cobra.Command{
		Use:   "echo {phrase}",
		Short: "blah short",
		Long:  `blah blah long`,
		Args:  cobra.MinimumNArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			for i := 0; i < times; i++ {
				fmt.Println("Echo: " + strings.Join(args, " "))
			}
		},
	}

	var rootCmd = &cobra.Command{Use: "app"}
	rootCmd.PersistentFlags().IntVarP(&times, "times", "t", 1, "times to echo")

	rootCmd.AddCommand(cmdGet)

	
	cmdText := getCommandTextFromHTTPEndpoint(...)
	
	cmd := cobra.Parse(cmdText)
	
	rootCmd.Run(...)
}
````

Is there any way to do this? Would this need to involve Viper as it is more-or-less using the CLI parsing capabilities of Cobra, but using it throughout my application.

**Comment by hugows** [comment]
@EIrwin Hi, did you find a way to do it?

**Comment by pomdtr** [comment]
For future readers, you can achieve this using the `SetArgs` command: `https://github.com/spf13/cobra/blob/v1.6.0/command.go#L268`
