### ISSUE TITLE
Provide all the dependency license files along with `cobra init`

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [spf13/cobra#535]
Go requires the user to provide the BSD License along the program and cobra requires the user to provide a copy of the APACHE license. The user has the option to choose a license he/she wants to use.
It would be kind if all the license files of the dependencies could be deployed along the rootCMD file on `cobra init`.

**Comment by Fjolnir-Dvorak** [comment]
I could make an merge request for that including a list with the dependencies used by cobra alongside the licenses and the copyright notices if wished.

**Comment by bogem** [comment]
`Go requires the user to provide the BSD License along the program`
Really?
