### ISSUE TITLE
Question: Can Cobra create watch-like CLIs?

### ISSUE THREAD

**Issue by variadico** [spf13/cobra#545]
Is it possible to use Cobra to create CLIs like `watch` or `parallel`? For example, `watch` expects flags be passed first, then everything else is interpreted as a command.

```
SYNOPSIS
    watch [options] command
```

For example:
```shell
watch -n 4 ls -al
# -n is a flag that belongs to watch, 
# while "ls" and "-al" are args passed to watch.
```

I know we can use `--` with Cobra, but I would like to mimic `watch` and not require users to type `--` every time.

**Comment by dnephin** [comment]
Yes you can:

```go
cmd := &cobra.Command{...}
cmd.Flags().SetInterspersed(false)
```

**Comment by variadico** [comment]
Perfect! Exactly what I need! Thanks!
