### ISSUE TITLE
cobra init error 

### ISSUE THREAD

**Issue by shaocongcong** [spf13/cobra#551]
macOS High Sierra （10.13）, go get cobra :
  # github.com/spf13/cobra
./command.go:423:12: fs.ShorthandLookup undefined (type *pflag.FlagSet has no field or method ShorthandLookup)
./command.go:1219:10: c.lflags.SortFlags undefined (type *pflag.FlagSet has no field or method SortFlags)
./command.go:1219:32: c.Flags().SortFlags undefined (type *pflag.FlagSet has no field or method SortFlags)
./command.go:1397:18: c.parentsPflags.SortFlags undefined (type *pflag.FlagSet has no field or method SortFlags)

**Comment by bogem** [comment]
Please install cobra with -u flag: go get -u github.com/spf13/cobra
