### ISSUE TITLE
Don't use "slice" word for --help of slice flags

### ISSUE THREAD

**Issue by ahmetb** [spf13/cobra#559]
If I have a StringSlice flag, I get this in --help:

      -r, --role stringSlice   Description of this flag bla bla bla

`stringSlice` flag is coming from cobra. It doesn't make sense to anyone who's not using Go, which just happens to be the programming language the command line tool is written in.

I think this should read:

      -r, --role strings...   Description of this flag bla bla bla

or 

      -r, --role=string [-r,--role=string[, ...]   Description of this flag bla bla bla

or some sort of better notation indicating the flag can be used for multiple times. Right now it's too cryptic (and forcing me to add explanation to the description of the flag).

**Comment by dnephin** [comment]
I like the term `strings` or `list` for this. Although I think this issue probably needs to be opened on `spf13/pflag` since the code for this is here:  https://github.com/spf13/pflag/blob/master/string_slice.go#L56-L58

**Comment by bogem** [comment]
@dnephin is right. It's better to open this issue in pflag's repo.

**Comment by ahmetb** [comment]
Thanks moved there. 
https://github.com/spf13/pflag/issues/148
