### ISSUE TITLE
Add golden tests for cobra/doc

### ISSUE THREAD

**Issue by bogem** [spf13/cobra#562]
We already have [golden tests for cobra/cmd](https://github.com/spf13/cobra/tree/master/cobra/cmd/testdata). Make the same for cobra/doc with https://godoc.org/github.com/gotestyourself/gotestyourself/golden.

**Comment by dnephin** [comment]
In case you might be interested https://godoc.org/github.com/gotestyourself/gotestyourself/golden is a library for comparing multi-line strings to golden files. On failure the error message includes a diff created by using [difflib](https://github.com/pmezard/go-difflib/).

It also provides a command line flag for easily updating the golden files when you want to update the expected value.

**Comment by bogem** [comment]
@dnephin It looks really nice. I think I will use it.
