### ISSUE TITLE
Allow subcommands to set `SilenceUsage`

### ISSUE THREAD

**Issue by jessicayuen** [spf13/cobra#564]
Currently if the root command has `SilenceUsage` set to true, it appears that I am unable to set this setting to `false` for child commands that don't want to follow this pattern. Is this expected behavior?

**Comment by bogem** [comment]
[There is a comment](https://github.com/spf13/cobra/blob/master/command.go#L800), that "if root command has SilenceUsage flagged, all subcommands should respect it".
```go
func (c *Command) ExecuteC() (cmd *Command, err error) {
		...

		// If root command has SilentUsage flagged,
		// all subcommands should respect it
		if !cmd.SilenceUsage && !c.SilenceUsage {
			c.Println(cmd.UsageString())
		}

		...
}
```

So it's expected, but I don't think that it's correct behaviour. Why all subcommands must respect it?

**Comment by jessicayuen** [comment]
Yes, I did see that comment too. Agree that I don't think it should be the correct behavior. Subcommands should be able to override that flag.

**Comment by bogem** [comment]
We better fix it in v2.0.0

**Comment by seh** [comment]
The behavior came in with 03aabcda72c59d327a9090c0e156b42e46bdd323, as part of #169. Note the title:
> adds a way for errors to silenced down the stack

That is, the idea was to configure things once at the top and have it apply down through the tree. That's convenient, though It's not clear why the general should win over the specific. My guess is that there was a global flag interpreted by a root command that was meant to control the behavior of subcommands.

**Comment by bogem** [comment]
The main problem here is, that there is no simple way to detect, if `SilenceUsage` field is set to false by user or unset at all. `SilenceUsage` is a boolean field and its default value is false, and we can't distinguish it from the situation, when `SilenceUsage` is to false by user.

**Comment by bogem** [comment]
> it will be inconvenient to set this field explicitly on each command.

But the advantage here is more explicit and simpler behaviour of cobra and it will be clearer to see if command silences the usage.

**Comment by AdamSLevy** [comment]
A better way is to add a PersistentSilenceUsage which would be preserved down to subcommands.
