### ISSUE TITLE
Could the cobra show deprecated message in the help output

### ISSUE THREAD

**Issue by yuexiao-wang** [spf13/cobra#566]
Could the cobra show deprecated message in the help output? 

for example
$ kubectl.sh exec -h | grep -e '-p'
-p POD_NAME is DEPRECATED and will be removed in a future version. Use exec POD_NAME instead.

**Comment by yuexiao-wang** [comment]
@bogem PTAL

**Comment by bogem** [comment]
Not yet. Planned in v2.0.0.
It's actually a duplicate of #358.

**Comment by yuexiao-wang** [comment]
@bogem when will be released for v2.0.0?
