### ISSUE TITLE
Commands called via alias do not expose that fact.

### ISSUE THREAD

**Issue by tep** [spf13/cobra#568]
When a command a) has defined aliases and it is b) invoked through one of those aliases, there is no way to determine whether the command was called by its primary name or one of the aliases.

**Comment by tep** [comment]
This should be resolved by PR #567

**Comment by frederikhors** [comment]
Nope, @github-actions.

**Comment by marckhouzam** [comment]
@frederikhors I can confirm this now works thanks to #567. I've actually made use of it here
https://github.com/spf13/cobra/blob/8c638d3f9077b692f7d12a212a74be98326d11a2/custom_completions.go#L102

**Comment by johnSchnake** [comment]
Resolved via the mentioned PR; closing.
