### ISSUE TITLE
Subcommands issue

### ISSUE THREAD

**Issue by NinaSW** [spf13/cobra#603]
I use the following code to support those command:

> 1. rtr convert toTOML /path/to/source
> 2. rtr convert toREADME /path/to/source

the `convert` should be the `main` command the `toTOML` and `toREADME` should be like sub-commands or flags

while it's working in the main (root) the help show just the convert 

This is the help

    Usage:
      rtr [command]
    
    Available Commands:
      convert     Print anything to the screen
      help        Help about any command
    
    Flags:
      -h, --help   help for rtr
    
    Use "rtr [command] --help" for more information about a command.

**Question**  - I want somehow to have the toTOML & toREADME will be shown in sub-commands section or flags

i've created this program that runs and illustrate the issue

    package main
    
    import (
    	"fmt"
    	"github.com/spf13/cobra"
    )
    
    func main() {
    	var cmdConvert = &cobra.Command{
    		Use:   "convert",
    		Short: "Print anything to the screen",
    		Run:nil,
    	}
    	var cmdTOML = &cobra.Command{
    		Use:   "toTOML",
    		Short: "convert to TOML",
    		Run: func(cmd *cobra.Command, args []string) {
    			fmt.Println("inside convert to TOML to path: " , args[0])
    		},
    	}
    	var cmdREADME = &cobra.Command{
    		Use:   "toREADME",
    		Short: "convert to readme",
    		Run: func(cmd *cobra.Command, args []string) {
    			fmt.Println("inside convert to README to path: " , args[0])
    		},
    	}
    	var rootCmd = &cobra.Command{Use: "rtr"}
    	cmdConvert.AddCommand(cmdTOML,cmdREADME)
    	rootCmd.AddCommand(cmdConvert)
    	rootCmd.Execute()
    }

I try also to add 
	`cmdConvert.PersistentFlags().StringVar(&toTOML, "toTOML", "", "toTOML")`

but I when I debug it and run it like 

go run main.go convert toTOML /go/src/

and also 

    go run main.go convert --toTOML /go/src/

it doesn't do to the `cmdTOML Run` function with the path.

I need to go to the `RUN` function according to the provided command and get the path (the last argument), how I can do it ?

**Comment by bogem** [comment]
Hello, @NinaSW!
Try to use blank func (func(cmd *cobra.Command, args []string) {}) instead of nil in convert function.
