### ISSUE TITLE
How to tell if NoArgs has been set.

### ISSUE THREAD

**Issue by rayjohnson** [spf13/cobra#605]
I've been working on a replacement for the man page generator for Cobra.  (https://github.com/rayjohnson/cobra-man). I wanted a bit more control over how the
man page was generated.

One thing I wanted to do was figure out if a command was expecting to have args or not.
Currently, I require the user to set an annotation to tell if the command takes no args.

That is kind of unfortunate because they probably also set cmd.Args = cobra.NoArgs.
However, I know of no way to tell if they did that.  You can't do cmd.Args == cobra.NoArgs
in go I can not see another way to check if that was set.

I'm hoping someone here might know of a way to check if it was set?

Ray

**Comment by dnephin** [comment]
I'm not sure if it's the best option, but you can compare a function using the function name: https://play.golang.org/p/1zChEgr954e

So you could check for `getFunctionName(cmd.Args) == "cobra.NoArgs"`

**Comment by rayjohnson** [comment]
Well, I got it working - thank you so much for the tip!

Interestingly, the Name returned is fully qualified.  Mine looked like this:
github.com/rayjohnson/zap/vendor/github.com/spf13/cobra.NoArgs

I should carve out some time to play with the reflect package some more.  :)

Thanks!

Ray
