### ISSUE TITLE
Alternate input/output source for testing

### ISSUE THREAD

**Issue by hbagdi** [spf13/cobra#607]
What is the way to test Cobra apps?

I was looking for a debug method to set alternate source of input.
Specifically, Cobra reads os.Args to determine what to do.
Writes to os.Args are not effective so, is there a way to set input source?

Same for output, is it possible to redirect output?

I'm trying to do testing using Go's unit test framework itself.

**Comment by hbagdi** [comment]
Apologies for opening this issue.

The required functions are:

https://godoc.org/github.com/spf13/cobra#Command.SetArgs
https://godoc.org/github.com/spf13/cobra#Command.SetOutput

**Comment by edio** [comment]
I think it would be great to be able to distinct standard output and error output.

It is not uncommong for commands to report warnings to stderr. For example, take unix's `ls`

```
$ ls -l /does/not/exist /tmp
ls: cannot access '/does/not/exist': No such file or directory
/tmp:
total 27776
...
```

If I were to write this in go, I'd want to be sure, that `ls: cannot access ...` won't get to stdout, as it may be piped further. So I'd like to have test for that. With current _cobra_ code it is not possible to test this behavior.

It looks like a very straightforward and simple change and we can even make it backward compatible with current API.

If there's interest and/or maintainers are open for this change, I'd be willing to work on it.
