### ISSUE TITLE
cobra_test.go:1253: Normalizing flag names should not result in duplicate flags

### ISSUE THREAD

**Issue by nim-nim** [spf13/cobra#608]
Hi,

I'm probably doing something wrong, cobra builds but unit tests fail

--- FAIL: TestNormConsistent (0.00s)
	cobra_test.go:1253: Normalizing flag names should not result in duplicate flags
FAIL

Any idea what's causing this?

**Comment by nim-nim** [comment]
[build.log](https://github.com/spf13/cobra/files/1609318/build.log)
[root.log](https://github.com/spf13/cobra/files/1609319/root.log)

**Comment by johnSchnake** [comment]
Outdated; tests seem to pass now and the test presumably got renamed to `TestConsistentNormalizedName` for those interested in the future.
