### ISSUE TITLE
Please update to cobra 0.0.1

### ISSUE THREAD

**Issue by nim-nim** [spf13/cobra#611]
Cobra has finaly made its first release; please update the code to use it

Right now building with wobra 0.0.1 results in

github.com/theupdateframework/notary/cmd/notary
_build/src/github.com/theupdateframework/notary/cmd/notary/delegations.go:168:39: cmd.Out undefined (type *cobra.Command has no field or method Out)
_build/src/github.com/theupdateframework/notary/cmd/notary/keys.go:180:25: cmd.Out undefined (type *cobra.Command has no field or method Out)
_build/src/github.com/theupdateframework/notary/cmd/notary/keys.go:339:20: cmd.Out undefined (type *cobra.Command has no field or method Out)
_build/src/github.com/theupdateframework/notary/cmd/notary/keys.go:436:54: cmd.Out undefined (type *cobra.Command has no field or method Out)
_build/src/github.com/theupdateframework/notary/cmd/notary/keys.go:548:12: cmd.Out undefined (type *cobra.Command has no field or method Out)
_build/src/github.com/theupdateframework/notary/cmd/notary/tuf.go:562:36: cmd.Out undefined (type *cobra.Command has no field or method Out)
_build/src/github.com/theupdateframework/notary/cmd/notary/tuf.go:625:6: cmd.Out undefined (type *cobra.Command has no field or method Out)

**Comment by bogem** [comment]
There is no `Out` method in Command. You can use only [OutOrStderr](https://godoc.org/github.com/spf13/cobra#Command.OutOrStderr) or [OutOrStdout](https://godoc.org/github.com/spf13/cobra#Command.OutOrStdout).

**Comment by nim-nim** [comment]
Sorry, bad project, too many tabs open :( and too late
