### ISSUE TITLE
How to get the value of the BoolVar to be false in this case 

### ISSUE THREAD

**Issue by researchlab** [spf13/cobra#613]
I hope to get the false value, but always get true from toggle and tog boolean varaibles.
$ ./demo --toggle false --tog false
I hope get the following answer:
tog= false  err= <nil>
toggle= false

But I got the following one:
tog= true  err= <nil>
toggle= true

here is the demo code:

```go
package cmd
import (
	"fmt"
	"os"
	"github.com/spf13/cobra"
)

var (
	toggle bool
)

var RootCmd = &cobra.Command{
	Use: "demo",
	Run: func(cmd *cobra.Command, args []string) {
		tog, err := cmd.Flags().GetBool("tog")
		fmt.Println("tog=", tog, " err=", err)
		fmt.Println("toggle=", toggle)
	},
}

func init() {
	RootCmd.PersistentFlags().BoolVarP(&toggle, "toggle", "t", false, "toggle bool")
	RootCmd.Flags().BoolP("tog", "o", false, "tog bool")
}

func Execute() {
	if err := RootCmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(-1)
	}
}
```

is there any error in above codes ?

**Comment by eparis** [comment]
I made some minor changes to your program and hopefully this explains things. Basically, booleans can only take arguments via `--bool=[true|false]` or for short names `-b=[true|false]`. You cannot use `--bool [true|false]` nor can you use the shorthand `-b[true|false]`. For flags with `NoOptDefVal` pflag is unable to tell if the argument was meant for the flag or if it was meant for the generic `args []string`

```
$ ./test
args: []string{}
tog: false
toggle: false

$ ./test --tog
args: []string{}
tog: true
toggle: false

$ ./test --tog --toggle
args: []string{}
tog: true
toggle: true

$ ./test --tog false --toggle
args: []string{"false"}
tog: true
toggle: true

$ ./test --tog false --toggle false
args: []string{"false", "false"}
tog: true
toggle: true

$ ./test --tog=false --toggle=false
args: []string{}
tog: false
toggle: false

```

**Comment by researchlab** [comment]
I got it, Thank you very much. @eparis

**Comment by icfantv** [comment]
@eparis @researchlab I just ran into this and found another place in our codebase where we use boolean flags and it looks like a super simple way to account for this is to use `strconv.FormatBool(...)`.  Not saying it's the most ideal way, but it's very simple and works for `BoolVar` flags.
