### ISSUE TITLE
Add ability to disable mousetrap in PreRun

### ISSUE THREAD

**Issue by ogimenezb** [spf13/cobra#619]
Sometimes we just want to be able to disable mousetrap for certain commands, we could maybe move the moustrap hook after PreRun so we can disable it depending on the command.

What do you think about that?

**Comment by Niondir** [comment]
+1 I need this as well. Making `preExecHookFn` public would already help.

**Comment by Niondir** [comment]
Oh just set `cobra.MousetrapHelpText = ""`

**Comment by Niondir** [comment]
You can just disable it globally and build in your own mousetrap check where ever you need it. I don't think we should over complicate the feature inside cobra.
