### ISSUE TITLE
Question on Usage

### ISSUE THREAD

**Issue by damianoneill** [spf13/cobra#624]
Is there way to iterate over all the command / sub commands and generate usage for all of them?  I'd like a way to get this output to include in an external web page for our tool using cobra.  

Thanks for an amazing library. 
Damian.

**Comment by dnephin** [comment]
https://github.com/spf13/cobra#generating-documentation-for-your-command

**Comment by damianoneill** [comment]
Thankyou @dnephin, much appreciated.

**Comment by damianoneill** [comment]
@dnephin I just ran the example from the your documentation and got the following error, do you have any thoughts on this? 

````bash
$ go run markdown.go
# command-line-arguments
./markdown.go:35:28: cannot use kubectl (type *"k8s.io/kubernetes/vendor/github.com/spf13/cobra".Command) as type *"github.com/spf13/cobra".Command in argument to doc.GenMarkdownTree
````

Example code 

````golang
package main

import (
	"io/ioutil"
	"log"
	"os"

	"k8s.io/kubernetes/pkg/kubectl/cmd"
	cmdutil "k8s.io/kubernetes/pkg/kubectl/cmd/util"

	"github.com/spf13/cobra/doc"
)

func main() {
	kubectl := cmd.NewKubectlCommand(cmdutil.NewFactory(nil), os.Stdin, ioutil.Discard, ioutil.Discard)
	err := doc.GenMarkdownTree(kubectl, "./markdown")
	if err != nil {
		log.Fatal(err)
	}
}
````

**Comment by dnephin** [comment]
There is some explanation here: https://stackoverflow.com/a/45315194/444646

Remove `vendor/k8s.io/kubernetes/vendor`, or use a package manager like `dep`, `vndr`, or `glide`, which will handle this for you.
