### ISSUE TITLE
Reassign -h flag for something else other than help?

### ISSUE THREAD

**Issue by deckarep** [spf13/cobra#637]
I have an app that i'm porting to Go that really must leverage the -h flag for a --hosts flag usage scenario.

How can I either use the -h flag or disable the in-built help feature or change the default behavior for help with getting the following panic?

```
panic: unable to redefine 'h' shorthand in "run" flagset: it's already used for "hosts" flag
```

If I need to forgo the default help feature and roll my own command so I can avoid the conflict I'm fine doing that. Unfortunately I don't see a way to do that without avoiding the panic above.

**Comment by deckarep** [comment]
Ok, looks like i simply needed to add my own default flag for this and not use the short "h" version.  This allows the "h" to be repurposed in another flag.

Example:
```
runCmd.PersistentFlags().BoolVarP(&helpFlag, "help", "", false, "Help default flag")
``

**Comment by eparis** [comment]
I know we check for a flag called "help" before we create the default help flag. I be we'd be very happy if you sent a patch which checked if -h was already defined and din't try to define -h to mean help in that case (but to still define --help)
