### ISSUE TITLE
dep not finding viper on Go 1.8.x

### ISSUE THREAD

**Issue by mdelapenya** [spf13/cobra#639]
Hello, I'm using `cobra` for a CLI tool and I have a problem when running `dep ensure` on CI: https://travis-ci.org/mdelapenya/lpn/jobs/343756743

```shell
vendor/github.com/spf13/cobra/cobra/cmd/licenses.go:22:2: cannot find package "github.com/spf13/viper" in any of:
	/home/travis/gopath/src/github.com/mdelapenya/lpn/vendor/github.com/spf13/viper (vendor tree)
	/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/github.com/spf13/viper (from $GOROOT)
	/home/travis/gopath/src/github.com/spf13/viper (from $GOPATH)
```

As you can see, it fails if GO version is 1.8.x, but passes when GO is 1.9.x:

https://travis-ci.org/mdelapenya/lpn/builds/343756742

Any help here?

Thanks!

**Comment by integrii** [comment]
I am not sure this is your solution, but it looks like you (travisCI) are running `dep ensure` to pull dependencies.  You should only do this if all your dependencies are listed in your dep `Gopkg.toml` - even then its probably still a bad idea.  Your repo does not have a Gopackg.toml, so running `go dep` tries to create one.  While this may pull dependencies and work sometimes, its not the same as a `go get`.

You should probably do a go get somewhere in your build, then a dep ensure, if you want to enforce a Gopkg.toml (which you don't seem to have in your project).

**Comment by mdelapenya** [comment]
Hey @integrii, thanks for your feedback here.

I do have the Gopkg.toml (https://github.com/mdelapenya/lpn/blob/develop/Gopkg.toml), and I think all my dependencies are listed there 🤔 

As this is a tiny, pet project, I used `dep` from the beginning the have all dependencies managed by `dep`.

**Comment by integrii** [comment]
Oh, I was looking at your master branch instead of your develop branch!

That said, the missing package is `github.com/spf13/viper` and I don't see that in the Gopkg files you linked.  Maybe you need to run `dep ensure -add github.com/spf13/viper`?

That said, it is not exactly clear to me what was different in your 1.9 and 1.8 builds.

**Comment by mdelapenya** [comment]
Thanks again for your help.

I added the `viper` dependency, committed it, and added back 1.8.x version of Golang to Travis, and it fails: https://travis-ci.org/mdelapenya/lpn/builds/346929118

```
vendor/github.com/spf13/cobra/cobra/cmd/licenses.go:22:2: cannot find package "github.com/spf13/viper" in any of:
	/home/travis/gopath/src/github.com/mdelapenya/lpn/vendor/github.com/spf13/viper (vendor tree)
	/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/github.com/spf13/viper (from $GOROOT)
	/home/travis/gopath/src/github.com/spf13/viper (from $GOPATH)
```

**Comment by mdelapenya** [comment]
To be honest, I think I don't need the 1.8.x validation, but keeping this open just to put it on the table just in case there is a problem with dependencies

**Comment by integrii** [comment]
You're welcome  I'm happy to help.

I think it failed this time because your tests are failing in 1.8. I don't see logs in this failed build involving dependencies not being found. That's progress!

**Comment by mdelapenya** [comment]
But the error is clear: cannot find package `viper`...

I created a `viper` branch with Go 1.8.x, and tests in verbose mode: https://github.com/mdelapenya/lpn/tree/viper Travis build here: https://travis-ci.org/mdelapenya/lpn/builds/347169932

**Comment by mdelapenya** [comment]
I think I understood the problem: `dep ensure` is pruning anything that is not directly imported, and as `viper` is a transitive dependency of `cobra`, then it's pruned.

I believed 🤞 this build https://travis-ci.org/mdelapenya/lpn/builds/347174080 would work, as I removed `dep ensure` from travis. In the end, that was your first guess and suggestion about the issue. But it didn't 😢 

But I got this message (https://travis-ci.org/mdelapenya/lpn/jobs/347174081#L561):
```
# github.com/mdelapenya/lpn/vendor/github.com/spf13/cobra/cobra/cmd
vendor/github.com/spf13/cobra/cobra/cmd/licenses.go:59: undefined: userLicense
vendor/github.com/spf13/cobra/cobra/cmd/licenses.go:60: undefined: userLicense
vendor/github.com/spf13/cobra/cobra/cmd/licenses.go:95: undefined: er
``` 
`go test ./...` is executing `vendor` tests, as explained here: https://github.com/golang/go/issues/19090. My question is: is cobra/cmd passing in 1.8.x branch?

**Comment by mdelapenya** [comment]
As expected, executing `go test -v $(go list ./... | grep -v /vendor/)` fix the issue, which just excludes `vendor` folder

**Comment by seeruk** [comment]
To help anybody else coming across this, you can always just explicitly add viper as a dependency, and add it to the `required` section in your `Gopkg.toml`, this will make dep install viper without complaining about it, and should allow you to continue as normal.
