### ISSUE TITLE
Default unrecognized args to some flag

### ISSUE THREAD

**Issue by scottmeyer** [spf13/cobra#640]
I have a application where I provide a flag argument to specify an ID. 

`app create -i foo`
`app update -i foo`
`app delete -i foo`

I constantly forget to type `-i`.

Is there a way that I can take an unrecognized argument and automatically assign it to a flag so that
`app create -i foo` and `app create foo` mean the same thing?

**Comment by eparis** [comment]
I think you'd have to do that yourself in `Run()`. Look at the `args []string` you get and put `args[0]` where ever `-i` would go....

**Comment by scottmeyer** [comment]
I thought about something like that, but because sub-commands are supported, I'm not sure how to tell if it's a sub-command or not.

**Comment by scottmeyer** [comment]
Maybe I can use the PreRun hooks of the each subcommand to evaluate? Is there support to list all commands/flags? Maybe something like there is in viper with `viper.AllKeys()`?

**Comment by eparis** [comment]
There is cmd.Flags().VisitAll() and cmd.Commands().

**Comment by scottmeyer** [comment]
Thanks for the answers, this worked for me:

```
func parseDefault(cmd *cobra.Command, args []string) {
	var arg string
	if len(args) > 0 {
		arg = args[0]
	}

	for _, cmd := range cmd.Commands() {
		if cmd.Use == arg || cmd.Name() == arg || cmd.Short == arg {
			return
		}
	}

	var setID= true
	visitor := func(flag *pflag.Flag) {
		if flag.Name == arg || flag.Shorthand == arg {
			setID = false
			return
		}
	}

	cmd.Flags().VisitAll(visitor)

	if setID {
		log.Debugf("Assigning unknown value '%v' to -i", arg)
		ID= arg
	}
}
```
