### ISSUE TITLE
The output of `cmd help` and `cmd --help` differs

### ISSUE THREAD

**Issue by benkeil** [spf13/cobra#647]
If you use `cmd --help` the output contains the `--version` hint, `cmd help` does not include it.

It would be great if you can call `cmd version` by default too (like `cmd --version`).

**Comment by krysennn** [comment]
Hi,

I'm facing about same problem, and the reason is: `--help` call HelpTemplate and `help` call UsageTemplate.

You can override these template with:
- cmd.SetHelpTemplate
- cmd.SetUsageTemplate

**Comment by johnSchnake** [comment]
Stale but also asked/answered. Closing. Thanks all for the issue and the solution.
