### ISSUE TITLE
Short --version flag (-v/--version)

### ISSUE THREAD

**Issue by prologic** [spf13/cobra#654]
I know `--version` was implemented originally in #584 and later fixed in #595 .

Can we have the option to have a short flag in addition to the long flag?

I would like (*for consistency's sake*):

```#!bash
mycli -v
```

and:

```#!bash
mycli --version
```

Thanks!

**Comment by rajatjindal** [comment]
Hi @prologic 

-v is used by multiple popular projects to expose verbosity level of logs (kubectl, kops etc), and therefore I think adding -v for version will break them. 

disclaimer: i am not member of cobra project and this is just my view.

Thanks
Rajat Jindal

**Comment by eparis** [comment]
Lots of project use --verbose/-v.  Such projects must continue to work.  (and @rajatjindal has contributed. which makes him a member of the cobra community if he likes it or not!)

You might get away with things by only adding the long+short version if both the long and short flags are not in use. And only creating the long version if `-v` is in use by another flag....

**Comment by eparis** [comment]
https://github.com/spf13/cobra/pull/671 added `-v` unconditionally, I'm closing it. If someone adds -v anytime it is not used, I'll take that patch,

**Comment by 030** [comment]
@eparis Based on your comment this issue should be closed.

**Comment by hairyhenderson** [comment]
@eparis I've attempted to implement what you're looking for in #996 - PTAL
