### ISSUE TITLE
Is there a good way to reconstruct the original command-line invocation?

### ISSUE THREAD

**Issue by kevincwells** [spf13/cobra#656]
Is there a good way to reconstruct the original command used to invoke the application from within a `Run` or `PreRun`? I've scanned through the docs and came up with the solution below, but it feels fragile. Apologies if I've just missed it in the docs, or if there's a much simpler way I've overlooked.

Example: Let's say someone called my application with `rootcmd sub1 sub2 --flag1 arg1 arg2`.  I would like to be able to reconstruct that string in the `Run` or `PreRun` of `sub2`.

The best solution I've come up with so far is effectively:

```go
var sub2 = &cobra.Command{
	Use:   "sub2",
	Run: func(cmd *cobra.Command, args []string) {
		
		command := []string{cmd.Name()}

		// Loop up parents, prepending name
		for p := cmd.Parent(); p != nil; p = p.Parent() {
			command = append([]string{p.Name()}, command...)
		}

		// For every set flag, append its name and value
		cmd.Flags().Visit(func(flag *pflag.Flag){
				command = append(command, "--" + flag.Name + "=" + flag.Value.String())
			})

		// Append the args
		command = append(command, args...)

		fmt.Println(strings.Join(command, " "))
	},
}
```

I know this will not preserve the order of flags and (because I'm not using the new `cmd.CalledAs()` function) will always give me the canonical name for a command, rather than any alias used. Are there any other differences/gotchas I'm missing?

**Comment by eparis** [comment]
Kubernetes does something to try to get the flags (and hide the couple they want to hide) https://github.com/kubernetes/kubernetes/blob/09f321c80bfc9bca63a5530b56d7a1a3ba80ba9b/pkg/kubectl/cmd/util/factory_client_access.go#L354
I don't think there is a great answer, but walking parents + reparsing is probably the least brittle.

**Comment by johnSchnake** [comment]
I dont think we munge the os.Args, only use it. However, realize that in testing situations you often set the command args and I dont think it goes through the os.Args value.

Otherwise seems like a satisfactory answer was given; between traversing parents and gathering flags, args, etc, os.Args, I think this can be closed. Feel free to reopen of there are more questions.
