### ISSUE TITLE
License header is not treated as template in generator

### ISSUE THREAD

**Issue by sbuzonas** [spf13/cobra#675]
The docs for the [generator configuration](https://github.com/spf13/cobra/tree/master/cobra#configuring-the-cobra-generator) leads one to believe that the license header is a template.

The *init* and *add* commands should `executeTemplate` on `project.License().Header` and `license.Header` respectively.

**Comment by wfernandes** [comment]
@jharshman I took a look into this and it seems that we have two options: 
1. **We update the [cobra/README](https://github.com/spf13/cobra/blob/090d94f4743e6590e11c154c45ccbca01a6eaf9a/cobra/README.md#configuring-the-cobra-generator) to reflect the current behavior.** 
1. We make the changes required to address the issue in case we want to support LICENSE templating. 

Currently the code has two paths that I see.
 For `cobra init` it calls [`createLicenseFile`](https://github.com/spf13/cobra/blob/090d94f4743e6590e11c154c45ccbca01a6eaf9a/cobra/cmd/project.go#L67) which ignores the `header` field.

However for `cobra add` it calls [`getLicense`](https://github.com/spf13/cobra/blob/090d94f4743e6590e11c154c45ccbca01a6eaf9a/cobra/cmd/licenses.go#L57) which creates a `License` object from the `license.header` and `license.text` but no templating.

In both cases we don't really do any templating (other than the `copyright` field in `createLicenseFile`) so I think it would be best to just update the [cobra/README](https://github.com/spf13/cobra/blob/090d94f4743e6590e11c154c45ccbca01a6eaf9a/cobra/README.md#configuring-the-cobra-generator) to remove template variables.

If we'd like to do the templating we can add that later in a future feature add. WDYT?

**Comment by jharshman** [comment]
@wfernandes yeah at this point I think it would be best to update the README to reflect that we don't support templating those fields.
