### ISSUE TITLE
How to set flags in test?

### ISSUE THREAD

**Issue by davidcpell** [spf13/cobra#678]
Some of my command function relies on `cmd.Flags().Changed()`. I'd like to write some tests that validate behavior when certain flags are used or not used. In testing my commands I'm able to simulate the passing of args like this:

```go
cmd.SetArgs(args)
```

I've been trying to find an equivalent way to set flags forever but can't seem to figure out the right methods to call.  Based on the [comment](https://github.com/spf13/cobra/blob/4dab30cb33e6633c33c787106bafbfbfdde7842d/command.go#L200-L201) for `SetArgs()` I figured I'd be able to just pass args like this:

```go
// in command definition
setCmd.Flags().StringVarP(&QueueNameFlag, "queue-name", "Q", "", "The name of the queue")

// the test
cmd.SetArgs([]string{"products_worker", "--queue-name=foo"})
cmd.Execute()
```

However, when I do that, I get:

```
Error: unknown flag: --queue-name
```

Any help on this?

**Comment by copernico** [comment]
Hi, I'm having the same issue, how did you solve it?
