### ISSUE TITLE
Allowing display of root commands in sections

### ISSUE THREAD

**Issue by odinath** [spf13/cobra#682]
Hi folks and thanks for Cobra!

I'm using your library to create a plugin to Cloud Foundry.  Its help output is displaying all root commands organized within sections. See the following example below:

![image](https://user-images.githubusercontent.com/486170/39071390-e079257a-44b4-11e8-9e1b-6a4b62794ac9.png)

To ease the plugin adoption and to ensure a proper user experience, I'm trying my best to get my Cobra-based help output aligned with the one of Cloud Foundry.

I was wondering if Cobra is currently allowing for such an organization, where root commands can be gathered and displayed within main sections? If not, is it part of your roadmap?

Thanks for your reply.

**Comment by odinath** [comment]
Seems the library already provides such a feature through 'annotations':
![image](https://user-images.githubusercontent.com/486170/39134383-7ea6fd36-46e4-11e8-97f1-b59fd48220b1.png)
Could you please confirm and provide examples on how to proceed?

**Comment by ghostsquad** [comment]
I'm also curious how this works. I'm not sure how you use the annotations to group commands.

**Comment by ghostsquad** [comment]
Not stale

**Comment by johnSchnake** [comment]
Agree that annotations is confusing at best; it seems like maybe that functionality was removed? There isn't any use of it in the code but you could concievably but data in there and write your own custom usage func which would loop over the data and print what you need.

https://github.com/spf13/cobra/issues/836 is asking the same thing though and has more discussion to follow there.

Closing as duplicate.
