### ISSUE TITLE
Add Support for Plugins

### ISSUE THREAD

**Issue by pbnj** [spf13/cobra#691]
Hi,

I apologize in advance if this has been previously requested. A cursory search did not yield related issues.

I would love to see a plugin-based architecture support in Cobra.

Some Go apps/CLIs have achieved this plugin-based architecture using [`go-plugin`](https://github.com/hashicorp/go-plugin) library (e.g. Hashicorp's Terraform, Nomad, Packer). `go-plugin` itself achieves this via gRPC contract between host and child processes. Other Go apps have achieved similar plugin-based architecture by executing external binaries that satisfy a JSON contract (e.g. [Buffalo](https://github.com/gobuffalo/buffalo/blob/master/plugins/plugins.go)).

Heroku's Node.js [Open CLI Framework](https://oclif.io/docs/plugins.html) supports [plugins](https://oclif.io/docs/plugins.html).

It would be nice to have plugin support in our beloved CLI library/framework.

Based on consensus from the Cobra maintainers & contributors on this feature request, I could also try to tackle this challenge. 

I'm curious what/how everyone else feels about this?

Thank you.

**Comment by shahidhk** [comment]
Another implementation to look at is from `kubectl` ([docs](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/)), which is a binary execution model.

**Comment by arrase** [comment]
You can do it with the https://golang.org/pkg/plugin/ , a plugin example:

```
import (
        "fmt"

        "github.com/spf13/cobra"
)

// buildCmd represents the build command
var PluginCmd = &cobra.Command{
        Use:   "test",
        Short: "A brief description of your command",
        Long: `A longer description that spans multiple lines and likely contains examples
and usage of using your command. For example:

Cobra is a CLI library for Go that empowers applications.
This application is a tool to generate the needed files
to quickly create a Cobra application.`,
        Run: func(cmd *cobra.Command, args []string) {
                fmt.Println("Test called")
        },
}
```

Then load it

```cobraplugins.Load(rootCmd, "test/test.so")```

From https://github.com/arrase/cobraplugins

And then:

```
$ go run main.go
A longer description that spans multiple lines and likely contains
examples and usage of using your application. For example:

Cobra is a CLI library for Go that empowers applications.
This application is a tool to generate the needed files
to quickly create a Cobra application.

Usage:
  cobraplugins [command]

Available Commands:
  test       A brief description of your command
  help       Help about any command

Flags:
      --config string   config file (default is $HOME/.cobra-plugins.yaml)
  -h, --help            help for cobraplugins
  -t, --toggle          Help message for toggle

Use "cobraplugins [command] --help" for more information about a command.
```
Run the plugin

```
$ go run main.go test
Test called
```

**Comment by johnSchnake** [comment]
Great comment and solution. Closing as answered; if it is already achievable with the other library I don't think it is a high priority to integrate it natively at this time. If more feedback comes back as such we can reconsider.
