### ISSUE TITLE
can add nuclio to the list of projects using cobra

### ISSUE THREAD

**Issue by yaronha** [spf13/cobra#699]
[nuclio](https://github.com/nuclio/nuclio) is a new and fast trending Serverless framework over Docker or Kubernetes, it is using cobra and viper, you can add it to the list of projects 

Yaron

**Comment by rabbah** [comment]
so is [openwhisk](https://github.com/apache/incubator-openwhisk-cli) ;)

**Comment by johnSchnake** [comment]
I'm not certain (I'm a pretty new maintainer) but I think if you want to add a project to the list you can put up a PR and its a pretty easy review. Feel free to tag me in the PR if this is something you're still interested in.

Considering the age of this ticket and the fact the followup PR doesn't really need this issue to justify it, I'm going to close this.
