### ISSUE TITLE
Negate arg (like the find command)

### ISSUE THREAD

**Issue by sevagh** [spf13/cobra#701]
Bad title, apologies, but I don't know how to express it.

With GNU find, the following is possible:

`$ find . -name '*a*' -not -name '*b*'`

Does this library provide a way to do that? I want to provide an interface like:

`$ locate-device --type x,y,z --color red,green --not --type a,b,c --not --color blue`. Any suggestions?

**Comment by eparis** [comment]
I can't think of a 'good' way to make this library do so. About the best I can think of is to use https://godoc.org/github.com/spf13/pflag#ParseAll and hack something together yourself...  pseudo code:

```
import os
import spf13/cobra
import spg13/pflag

func RunE(cmd *cobra.Command, args []string) error {
   not := false
   parseFunc := func(f *pflag.Flag, value string) error {
     if f.Name == "not" {
        not = true
        return nil
     }
    if not {
        not = false
        $do whatever in your program to indicate f is negated
    }
   }
  pflag.ParseAll(parseFunc)
}
```
