### ISSUE TITLE
Override default help and usage methods

### ISSUE THREAD

**Issue by benkeil** [spf13/cobra#702]
Can I override the default help and usage messages and add additional functionality?

I want to print the default text, but I must return another exit code.

**Comment by bacongobbler** [comment]
You can call a command's `SetHelpFunc` function to add additional functionality to `helpFunc`. You can also change the template using `SetHelpTemplate`.

https://github.com/spf13/cobra/blob/67fc4837d267bc9bfd6e47f77783fcc3dffc68de/command.go#L306-L307
https://github.com/spf13/cobra/blob/67fc4837d267bc9bfd6e47f77783fcc3dffc68de/command.go#L238

**Comment by johnSchnake** [comment]
Asked and answered.
