### ISSUE TITLE
Identifing child command being executed from root.go 

### ISSUE THREAD

**Issue by kasunsiyambalapitiya** [spf13/cobra#718]
I have created a simple CLI application that has only two child command (`init` and `version`) in `Go` using the [cobra][1] framework. I have a requirement to identify which child command being executed from `root.go` and do some task if it is the `version` command. How do I achieve it? Please find the source code of `root.go` below.

    package cmd
    
    import (
    	"os"
    	"github.com/renstrom/dedent"
    	"github.com/spf13/cobra"
    )
    
    var (
    	rootLongDesc = dedent.Dedent(`
    	My sample App
    	`)
    )
    
    var RootCmd = &cobra.Command{
    	Use:   "app",
    	Short: "sample App",
    	Long:  rootLongDesc,
    }
    
    func Execute() {
    	RootCmd.AddCommand(InitCmd)
    	RootCmd.AddCommand(versionCmd)
    	if err := RootCmd.Execute(); err != nil {
    		os.Exit(-1)
    	}
    }
    
    func init() {
    	cobra.OnInitialize(InitConfig)
    	cobra.EnableCommandSorting = false
    	RootCmd.PersistentFlags().BoolVarP(&Verbose, "verbose", "v", false, "Enable verbose mode")
    }

    func InitConfig() {
    
    	// Need to catch that the `version` child command being executed and do some task
    
    }

  [1]: https://github.com/spf13/cobra

**Comment by eparis** [comment]
I'm sorry, but, you can't. At least, cobra doesn't necessarily help you. We do not process the command line, and thus don't determine the child command being executed, until the call to `RootCmd.Execute()`. During `init()` you might be able to call https://godoc.org/github.com/spf13/cobra#Command.Find on the root command to get it to do the arg parsing and tell you which child command will be run. I don't know if that will cause any other problems later, probably not.

Though I should point out, when called via Execute() we do things like add a `help` and `version` command, which wouldn't exist if you called `rootcmd.Find()` in `init()`

**Comment by scriptonist** [comment]
```
cmd, err = cmd.ExecuteC()
if err != nil {
	os.Exit(1)
}
fmt.Println(cmd.CommandPath())
```
Are you looking for this @kasunsiyambalapitiya
