### ISSUE TITLE
Non-english / Other Languages (i18n) in CLI Apps ?

### ISSUE THREAD

**Issue by jsmith-dev** [spf13/cobra#719]
Is there a 'standard' pattern / way to support multiple languages for the CLI msg output that the user interacts with?

If we start using this library we will want to support our users in 12+ languages for message output.

**Comment by pascal-oliva** [comment]
I have the same question about howto translate Cobra message : 
like : (from --help)
"Usage" : 
"Available Commands"
"Flags"

**Comment by Goutte** [comment]
See https://github.com/spf13/cobra/issues/1134
