### ISSUE TITLE
Generator should support Go modules

### ISSUE THREAD

**Issue by anuraaga** [spf13/cobra#720]
Go modules will be released soon, and the cobra generator should be updated to respect them. Currently, it always generates into `GOPATH`, but when run in a repository that has a `go.mod` file, it should instead generate into the current directory.

**Comment by matejvelikonja** [comment]
is there any workaround for this?

**Comment by tkivisik** [comment]
I believe my problem is related.

When I run `cobra init` or `cobra add my_special_command` using Go 1.11.1 in a Go project folder outside of `GOPATH`, having `go.mod`, it outputs:

> Using config file: /home/user/.cobra.yaml
> Error: Rel: can't make /home/user/path/to/non-gopath/my_project relative to

**Comment by artooro** [comment]
I just moved the project into the GOPATH in order to use cobra init/add and them moved it back into my project folder which worked fine.
Hope at some point it will support go modules though.

**Comment by obloquy** [comment]
From bash or similar shells you can use:
`$ GOPATH=$HOME/workspace cobra add my_new_command
my_new_command created at /home/me/workspace/src/gitlab.com/me_again/my_project/cmd/my_new_commnd_roll.go`

**Comment by jharshman** [comment]
This should be resolved by #817 .
