### ISSUE TITLE
local flag overwriting other local flags with same name?

### ISSUE THREAD

**Issue by shoekstra** [spf13/cobra#722]
Hi,

I'm pretty new to golang so hoping I'm not missing something simple here.

I've been using cobra with great success but come across what, to me, looks like a potential bug unless I misunderstand how to use it.

While writing my cli app I have the following in `cmd/instance_list.go` and `cmd/vpc_list.go` respectively:

```
func init() {
        instanceCmd.AddCommand(instanceListCmd)
        ...
        instanceListCmd.Flags().StringVarP(&sortBy, "sort-by", "s", "name", "field to sort by")
}
```

```
func init() {
        vpcCmd.AddCommand(vpcListCmd)
        ...
        vpcListCmd.Flags().StringVarP(&sortBy, "sort-by", "s", "name", "field to sort by")
}
```

All good, everything works as expected (both default to `name`).

I've just added a new sub command to display routes, and now the default sort field should be `CIDR`, so in `cmd/vpc_route_list.go` I have:

```
func init() {
        vpcRouteCmd.AddCommand(vpcRouteListCmd)
        ...
        vpcRouteListCmd.Flags().StringVarP(&sortBy, "sort-by", "s", "cidr", "field to sort by")
}
```

Now `&sortBy` is set to `cidr` for all instances of `sortBy`, instead of locally for `vpcRouteListCmd`, thus the `instance list` and `vpc list` commands are trying to sort by CIDR instead of by name.

Am I doing something wrong here?

Thanks in advance for any pointers!

**Comment by seanjoe** [comment]
how can you fix it, I come across the same one @shoekstra
