### ISSUE TITLE
Error messages for "wrong" flags

### ISSUE THREAD

**Issue by gj52** [spf13/cobra#731]
pls see https://discourse.gohugo.io/t/errors-with-0-47-minify/13662/4

If command1 supports flag1, and command2 does not use flags1, please give a hint for this!
sample:

```
hugo server  --verbose --watch --minify
Error: unknown flag: --minify

```
command server does not support --minify   

The error message should give the hint, that --minify is not supported by command server

**Comment by johnSchnake** [comment]
As an older ticket this seems to have been solved; cobra does tell you when it doesnt recognize a flag.
