### ISSUE TITLE
.cobra.yaml

### ISSUE THREAD

**Issue by Wulfheart** [spf13/cobra#733]
Hello,

I'm currently trying out the cobra generator. The docs say to simplify the process I should use a .cobra.yaml file. Where shall I save it? It's unclear for me.

Thank you.

**Comment by Fjolnir-Dvorak** [comment]
$HOME/.cobra.yaml.
you can find it in the [README.md](https://github.com/spf13/cobra#example-1) documented or by running the command `$ cobra --help`

**Comment by ms4720** [comment]
Are there any other options for .cobra.yaml other than a global file or putting it on the CLI every time? 

does one of the following exist:

- env var to set 
- project root directory, is there a .git/ dir in it
- Current directory first

**Comment by Fjolnir-Dvorak** [comment]
Cobra is using viper as configuration framework as mentioned in the documentation. Viper supports environment variables. Link to documentation:[https://github.com/spf13/viper#working-with-environment-variables](https://github.com/spf13/viper#working-with-environment-variables)

Cobra has only $HOME configured as the configPath, so no, viper is not looking into the current directory for configuration files. An idea to bypass the home directory as configuration path would be to create an alias which sets the config-flag to another directory/file.

What do you mean with your second point if there is a .git directory in it?
But no, cobra does not generate any git directories.

**Comment by ms4720** [comment]
I am learning some basic Go to add an env var for the CLI options, hopefully soon, to make it play nice with ondir for the env setup.  Not a breaking change

**Comment by ms4720** [comment]
The .Git comment would mean the root of the git repository you are working in. A good place to override global config with local options
