### ISSUE TITLE
cobra.OnInitialize not calling the specified initialization routine

### ISSUE THREAD

**Issue by lpar** [spf13/cobra#748]
I've generated a blank app using `cobra init` and defined a flag. I print the value of the flag after `cmd.Execute()` has been called.

When I build and run the app, `init()` is called in `cmd/root.go`, and it calls `cobra.OnInitialize(initConfig)`. However, Cobra never called `initConfig`, so no config files are ever loaded.

Complete example is at https://github.com/lpar/verde, it's entirely generated code apart from fmt.Println statements and the line to define the `actor` option. Using Go 1.11.

**Comment by ybbkrishna** [comment]
Should comment Run block in rootCmd of root.go

**Comment by lpar** [comment]
I was assuming that flags like --help and other config options would work whether the utility was going to take any action or not. That is, my expectation would be that the command line parsing would always be run, and then the program might do nothing depending on the arguments. Having it not parse flags at all if there's no command word was not at all what I expected.

Maybe the simple fix is that the codegen should generate code that works for all cases, rather than requiring that the user spot and uncomment something if no additional commands have been defined yet.

**Comment by realB12** [comment]
Thanks for the hint. Really not very intuitive! It should be documented at least!
