### ISSUE TITLE
List global pflags only from selected packages?

### ISSUE THREAD

**Issue by leonhandreke** [spf13/cobra#751]
I use cobra in a project that pulls in a library (rclone) that also uses pflags to define its flags. The result is that the "Global Flags" section in the help message for our various commands is polluted with flags defined somewhere in rclone that our users don't and shouldn't have to care about.

Is there a way in Cobra to selectively only show flags from our own package (or more simply, a list of flags that we explicitly supply) in the help message? I've already searched around a bit and couldn't find a way to do this.

Thanks!

**Comment by clee** [comment]
For anyone else who comes across this problem in the future, I've discovered a hack/workaround that you can use to un-pollute your command-line flags.

In your `main()` function, before you do anything else, call:

`pflag.CommandLine = pflag.NewFlagSet("name", pflag.ExitOnError)`

This should remove any flags that were added by libraries automatically.
