### ISSUE TITLE
More control over hidden commands

### ISSUE THREAD

**Issue by MichaelMure** [spf13/cobra#753]
Currently tagging a command as `Hidden` means multiple things:

- the command is not listed in the help text of its parent
- the bash/zsh completion is not generated
- the yml/md/man/rest documentation is not generated

I would be nice to have more control. In particular, it's a common pattern to hide commands useful only for low level usage or integration in scripts. But you usually still want to generate the documentation and probably the shell completion as well.

**Comment by alexcom** [comment]
By the way  ZSH completion does not exclude hidden commands unlike bash completion.
