### ISSUE TITLE
Cobra and VGO?

### ISSUE THREAD

**Issue by andrewmeissner** [spf13/cobra#756]
I wonder if I'm maybe missing something...

When I run `cobra help init`, this is what I see:

```
PS C:\Users\Andrew> cobra help init
Using config file: C:\Users\Andrew\.cobra.yaml
Initialize (cobra init) will create a new application, with a license
and the appropriate structure for a Cobra-based CLI application.

  * If a name is provided, it will be created in the current directory;
  * If no name is provided, the current directory will be assumed;
  * If a relative path is provided, it will be created inside $GOPATH
    (e.g. github.com/spf13/hugo);
  * If an absolute path is provided, it will be created;
  * If the directory already exists but is empty, it will be used.

Init will not use an existing directory with contents.
```
If I'm reading that correctly, I should be able to run `cobra init myApp` and have cobra create the structure in the current directory.  This isn't the case.

```
PS C:\Users\Andrew\Desktop\definitelyNotGOPATH> pwd

Path
----
C:\Users\Andrew\Desktop\definitelyNotGOPATH


PS C:\Users\Andrew\Desktop\definitelyNotGOPATH> cobra init myApp
Using config file: C:\Users\Andrew\.cobra.yaml
Your Cobra application is ready at
C:\Users\Andrew\go\src\myApp.

Give it a try by going there and running `go run main.go`.
Add commands to it by running `cobra add [cmdname]`.

PS C:\Users\Andrew\Desktop\definitelyNotGOPATH> echo $env:GOPATH
C:\Users\Andrew\go

PS C:\Users\Andrew\Desktop\definitelyNotGOPATH> cobra init .\rightHerePlease
Using config file: C:\Users\Andrew\.cobra.yaml
Error: Cobra supports project only within $GOPATH: Rel: can't make C:\Users\Andrew\Desktop\definitelyNotGOPATH\rightHerePlease relative to
```

It seems to always create it in the `GOPATH`.  I'm hoping to be able to use go 1.11's dependency manager (vgo) with cobra, vgo doesn't work in the `GOPATH` and it looks like cobra only works _in_ the `GOPATH`.  Am I missing something blazingly apparent?  If not, are there plans to make cobra compatible with go 1.11's built in dependency manager?

Thanks!

**Comment by jharshman** [comment]
Cobra generator only works in your `GOPATH`.  Since I was moving from dep to modules (vgo), I just generated what I needed on my project in the `GOPATH` and copied it over.  Hacky but it works.

**Comment by andrewmeissner** [comment]
@jharshman that will work for me on a personal project, but for my work projects that's not really an option.  Other people shouldn't have to deal with that nuance.

Additionally, Go's roadmap includes completely abandoning the use of a `GOPATH`, so I guess I'm wondering if cobra plans to make any necessary changes to stay relevant.  I would hope so because it is an incredibly amazing project!  I've used it as well as viper for a great deal of my work projects.  :)

**Comment by jharshman** [comment]
@andrewmeissner I agree, although I still use that workaround at work :).
I'm sure this isn't a huge change code wise, working on a PR to add support.

**Comment by noandrea** [comment]
Hi, this should also resolve issue #720

**Comment by jharshman** [comment]
@noandrea @andrewmeissner all tests have passed on #817 .  Just waiting review and merge.
I encourage those interested to pull the branch, build and test drive it if interested.

**Comment by andrewmeissner** [comment]
![Alt Text](http://www.reactiongifs.com/r/exc.gif)
