### ISSUE TITLE
Throw error on em/en dash

### ISSUE THREAD

**Issue by stanislavkozlovski** [spf13/cobra#760]
en (–) and em (—) dashes are unicode characters which look awfully similar to a hyphen.
http://www.thepunctuationguide.com/hyphen-and-dashes.html

At my company, we've had long debugging sessions examining why our application didn't work the way we intended it to. It turned out that it all came from the initial CLI command, where we use `cobra`.
The current behavior is that an argument with given an em dash (e.g `—-arg`) is totally ignored. We also think that the rest of the string is ignored too (e.g `—-arg --something` - something doesn't get passed either).

Could the library throw an error or at least provide a warning such that we can catch problems like these easily? These dashes are not easily recognizable, especially in a terminal. They're very easy to accidentally copy from somewhere and aren't always obvious.

PS: I can volunteer to fix this if you believe it's the right approach

**Comment by wanghong230** [comment]
+1

**Comment by nguyenlienviet** [comment]
We have this problem in our CLI, too.

**Comment by cndoit18** [comment]
I think you can use the function "PreRunE" in the struct "Command" to implement verification instead of modifying the framework.

**Comment by stanislavkozlovski** [comment]
Why is this still not addressed?

**Comment by stanislavkozlovski** [comment]
It would be good to address this nasty bug

**Comment by jharshman** [comment]
I wouldn't consider this a bug in the code. The the em dash is not a recognized way of specifying a flag on the command line.

**Comment by stanislavkozlovski** [comment]
I think it would be the mark of a good CLI library to address these sort of user errors
