### ISSUE TITLE
Connecting a StringToString parameter with viper does not seem work.

### ISSUE THREAD

**Issue by FredrikFolkesson** [spf13/cobra#778]
Hi.

I am trying to connect a `map[string]string` parameter to Viper and it does not seem to work.

In my `init` function I do

```
cmd.PersistentFlags().StringToString("headers", nil, "Headers to use when connecting..")
viper.BindPFlag("headers", cmd.PersistentFlags().Lookup("headers"))
```

and then in the `cmd` function I do
```
headersMap := viper.GetStringMapString("headers")
//use the headers
```

The problem seems to be that what is "saved" in Cobra for the value `headers` is something of the type `StringToString` and not `map[string]string` as I would have thought.
(that is the value of the type I get if I do `cmd.Flag("headers").Value.Type()`

If I save my parameter value by directly specifying the map like this:

```
cmd.PersistentFlags().StringToStringVar(&headersMap, "headers", nil, "Headers to use when connecting ")
```
It correctly saves the value in the map. But then I would have to check that the map is not empty and if it is save the value from viper in the map.

I don't know If this is a bug or If I am missing something?

Thanks!

**Comment by FredrikFolkesson** [comment]
No one?

**Comment by den-is** [comment]
hm... I've encountered the same issue. But since this issue is quite silent, apparently there is proper way to handle maps between cobra and viper? 
I would be glad if anyone shares that tip.

**Comment by johnSchnake** [comment]
So the underlying issue was fixed? Going to go ahead and close but feel free to reopen if I misinterpreted.
