### ISSUE TITLE
Conflicted with specified version of pflags in k8s packages

### ISSUE THREAD

**Issue by xxx7xxxx** [spf13/cobra#788]
![image](https://user-images.githubusercontent.com/3148017/48619902-ff494600-e9d8-11e8-9451-7616f5a3ac6c.png)

Because the cobra does not specify its own version of pflags when I use k8s packages where they specify a very old commit[1]. And I will get compilation error `vendor/github.com/spf13/cobra/command.go:31:25: undefined: pflags.ParseErrorsWhitelist` while trying to compile our own project.

I can specify the version (such as master, newest commit) in my own `glide.yaml`, but I think it crossed the line to maintain the version of the vendor(pflags) of the vendor(cobra).

Could we manage pflags on our own or even include pflags code directly in corba?

[1]. https://github.com/spf13/pflag/commit/9ff6c6923cfffbcd502984b8e0c80539a94968b7

**Comment by bernardolm** [comment]
+1

**Comment by bdjibril** [comment]
+1

**Comment by jpmcb** [comment]
Going through and cleaning up some issues - it seems this was addressed with the adoption of go mod in late march 2019. Thanks for noting this issue and please feel free to open a new one if you're seeing similar problems!
