### ISSUE TITLE
Cobra won't show help if cmd is not Runnable

### ISSUE THREAD

**Issue by vinicyusmacedo** [spf13/cobra#790]
I have a subcommand that has no Run function. 

```
var containerCmd = &cobra.Command{
	Use:   "container",
	Short: "Global settings for running containers",
}

func init() {
	configCmd.AddCommand(containerCmd)
	containerCmd.PersistentFlags().String("networkEndpoint", "", "Specify a network endpoint (in case you need to network between containers)")
	viper.BindPFlag("networkEndpoint", containerCmd.PersistentFlags().Lookup("networkEndpoint"))
}
...
```

It only shows the usage when it's added to the rootCmd. When it is not, it only shows the short description. It won't show the help even if I pass the `--help flag`. It should show the usage when I pass the help flag or no arguments. 

I noticed two things:

1. Cobra returns "help requested" if the command is not runnable
https://github.com/spf13/cobra/blob/fe5e611709b0c57fa4a89136deaa8e1d4004d053/command.go#L724-L726
2. Cobra only renders the Usage if the command is runnable
https://github.com/spf13/cobra/blob/fe5e611709b0c57fa4a89136deaa8e1d4004d053/command.go#L432-L434

I added `HasFlags` to this template and it always displays the usage. 

It might be related to https://github.com/spf13/cobra/issues/206#issuecomment-392349759

**Comment by umarcor** [comment]
Hi @vinicyusmacedo! In #842 the management of errors from non-runnable commands is modified. Please, have look, as it may suit your use case.

**Comment by vinicyusmacedo** [comment]
@umarcor hi, sorry for taking too long. 

I believe it should help, though I'm not sure if the Help template will render in this case.
