### ISSUE TITLE
command.GenZshCompletion should exclude commands that marked as hidden

### ISSUE THREAD

**Issue by ghost** [spf13/cobra#792]
Greetings!
Recently I created completions for both BASH and ZSH for my cli tool and noticed that command "completion" that I marked hidden is shown in ZSH version.
Here's what I do:

    command := &cobra.Command{
    		Use:    "completion",
    		Short:  "Generate shell completion",
    		Hidden: true,
    	}
    command.AddCommand(&cobra.Command{
    		Use:   "zsh",
    		Short: "Generate zsh completion",
    		Run: func(cmd *cobra.Command, args []string) {
    			if path == "" {
    				rootCmd.GenZshCompletion(os.Stdout)
    			} else {
    				rootCmd.GenZshCompletionFile(path)
    			}
    		},
    	})

Here's what I got:

    » acli completion zsh
    #compdef acli

    _arguments \
      '1: :->level1' \
      '2: :->level2' \
      '3: :_files'
    case $state in
      level1)
        case $words[1] in
          acli)
            _arguments '1: :(backup completion config ... )'
          ;;
          ...

It seems that BASH completion excludes hidden command. So ZSH one should do it also.

**Comment by marckhouzam** [comment]
The zsh completion logic has been modified a while back to align with bash.
Hidden commands are no longer suggested.
