### ISSUE TITLE
Making cobra init module aware?

### ISSUE THREAD

**Issue by arschles** [spf13/cobra#795]
The `cobra init` help text really clearly describes how it works for different names that you give it on the command line (thank you for that awesomeness btw 🎉). I noticed that they each seem to behave differently when run outside the GOPATH, and I'm not sure if that behavior is right or wrong. Here's what I've noticed:

>* If a name is provided, it will be created in the current directory;

This seems to always create under the `GOPATH`:

```➜  code cobra init thing
Your Cobra application is ready at
/Users/aaschles/gocode/src/thing

Give it a try by going there and running `go run main.go`.
Add commands to it by running `cobra add [cmdname]`.
```

(the same goes for when I do not have a `GOPATH` explicitly set)

>* If no name is provided, the current directory will be assumed;

When I run this outside the `GOPATH`, I get this error:

```
➜  code cobra init      
Error: Rel: can't make /Users/aaschles/Dropbox/code relative to 
```

>* If a relative path is provided, it will be created inside $GOPATH
> (e.g. github.com/spf13/hugo);

This seems to work as advertised (see below). If cobra were to gain support for modules, it would be great to be able to override this (e.g. with an env var or a CLI flag maybe?) so that you can create the new app under the current directory.

```
➜  code cobra init abc/def
Your Cobra application is ready at
/Users/aaschles/gocode/src/abc/def

Give it a try by going there and running `go run main.go`.
Add commands to it by running `cobra add [cmdname]`.
```

>* If an absolute path is provided, it will be created;

This seems to fail outside the GOPATH (in the below example, `~/Desktop/thing` already exists)

```
➜  code cobra init ~/Desktop/thing
Error: can't read path info: lstat /Users/aaschles/Desktop/thing: no such file or directory
```

>* If the directory already exists but is empty, it will be used.

This also seems to fail with a similar error as above:

```
➜  gomark git:(master) pwd
/Users/aaschles/Dropbox/code/gomark
➜  gomark git:(master) cobra init
Error: Rel: can't make /Users/aaschles/Dropbox/code/gomark relative to 
```

This was all tested with Cobra v0.3.0. I actually ran `go get github.com/spf13/cobra@v0.0.3` using modules to get the binary.

I have some ideas on how to fix/alter each behavior but I wanted to bring up the bugs/behaviors first to see what folks think.

Looking forward to it 😄

**Comment by patrick-motard** [comment]
I would like this feature because I have existing repositories that are not golang projects, that I would like to place a cobra CLI app within. I don't want to have to put my existing repo in my GOPATH since only my go specific code lives there.

**Comment by tsal** [comment]
At the moment, I'm stuck manually copying the generated files from the GOPATH to the module location I'm working out of.  It would be really nice for this to just generate in the path it's executed under, using the go.mod information to figure out the mappings.

I have exactly the same use-case as @patrick-motard 

Is there any chance a PR would be accepted for this?

**Comment by dmoles** [comment]
Note that even if you manually copy generated files from GOPATH into your module and get them working, you `cobra add` will still fail, presumably for the same reasons:

```
$ cobra add pos
Error: Rel: can't make /Users/david/Projects/ephemera/asb relative to 
```

**Comment by tsal** [comment]
Yeah, I learned that the hard way.  I ended up creating a separate private repo and a separate GOPATH for the package.

**Comment by AdamSLevy** [comment]
I work around this currently by creating a symlink inside of `GOPATH` to the path on my system of the go module I'm working in.

So if the project is `github.com/AdamSLevy/project` and I'm working in `~/project` and I want to create a command line inside of `project` (which contains a single top level `go.mod` file), then I create a symlink
```
ln -s ~/project $GOPATH/github.com/AdamSLevy/project
```

**Comment by jharshman** [comment]
Relevant issue: https://github.com/spf13/cobra/issues/756
PR: https://github.com/spf13/cobra/pull/817

**Comment by SrslyJosh** [comment]
It'd be great to get this or another solution merged.

**Comment by jharshman** [comment]
#817 merged

**Comment by arschles** [comment]
Super late to the game, but this is awesome to see. I've been enjoying module-aware `cobra init` for a while now and didn't give some thought to coming back and saying thanks to everyone who made it happen. So...... thanks 😄
