### ISSUE TITLE
Cobra will not create a new project in a non empty directory

### ISSUE THREAD

**Issue by magick93** [spf13/cobra#813]
I'm trying to create a new cobra cli project using `cobra init mycli` however it fails with:

```
Error: Cobra will not create a new project in a non empty directory: /home/anton/go/bin/src/mycli
```

However, the directory is empty:
```
ls -a
.  ..
```

**Comment by talmdal** [comment]
Similiar, but not the same... My directory was not totally empty... it had a skeleton Makefile, .gitignore and a vscode workspace file. Maybe this message should only occur if there is already go files in the directory, but allow other file types,

**Comment by jharshman** [comment]
Cobra's `init` command has been re-worked and no longer fails on non-empty directories. 
#817
