### ISSUE TITLE
Request: install goodfirstissue github app for spf13/cobra

### ISSUE THREAD

**Issue by rajatjindal** [spf13/cobra#815]
Hi @eparis , @spf13 

I've written a simple github webhook app to tweet 'goodfirstissue' issues whenever we report one. Request you to kindly consider installing it for spf13/cobra repo.

Permissions this app need: read permission on issues and metadata.
Twitter Handle used to tweet: [@goodfirstissue](https://twitter.com/goodfirstissue)
Source code of the app/webhook: https://github.com/rajatjindal/goodfirstissue
Instructions to install github app: https://github.com/rajatjindal/goodfirstissue#how-to-install

thank you for considering and looking forward for hearing any feedback that you might have.

Thanks
Rajat Jindal

**Comment by johnSchnake** [comment]
Due to the lack of activity in 3y on this I'm going to go ahead and close. I don't think this is consistent with some of the other choices of integrations as well (e.g. automatic tweets).
