### ISSUE TITLE
Flag without value

### ISSUE THREAD

**Issue by jjzcru** [spf13/cobra#818]
Hi i just want to know if it is posible to declare a flag just with the shorthand and without requiring a value something like `docker-compose up -d` just the flag alone

**Comment by MarkusFreitag** [comment]
Yes, you can use a boolean flag to achieve this behaviour.
example: `rootCmd.BoolVarP(&verbose, "verbose", "v", false, "verbose output")`

**Comment by filinvadim** [comment]
Same question.

**Comment by umarcor** [comment]
> Same question.

Same answer, I guess:

> You can use a boolean flag to achieve this behaviour:
> `rootCmd.BoolVarP(&verbose, "verbose", "v", false, "verbose output")`

**Comment by sonali85** [comment]
But how achieve this with string value as people may need to consider 3 options :
without flag which should take default value 
with flag no value
with flag string value

**Comment by mehran-prs** [comment]
@sonali85 I've not checked this solution but maybe you can check if the flag is provided by using `Changed` prop on the flag. e.g., `cmd.Flag("flag").Changed`.

Maybe someone can test it and let others know the result.

**Comment by InerkyJad** [comment]
@mehran-prs 
it's not working, just tried, and i couldn't find any docs containing an example of a positional argument without the flag `--flag`
my code:
```go
rootCmd.AddCommand(flipCmd)
flipCmd.Flags().StringP("image", "i", "", "Image path (required)")
flipCmd.Flag("image").Changed = true
```

note, tried the same at the root level, no change

**Comment by InerkyJad** [comment]
a working work around would be to use `args` instead of flags, and it does seam more logical since the wanted behavior is one of a positional argument and not of a flag so it seams like it's better to use `args`

example of a small command that takes in one positional argument:
```go
var flipCmd = &cobra.Command{
	Use:        "flip image [flags]", // name the argument
	Short:      "Flip an image horizontally or vertically, if no flag is provided, the image is flipped horizontally",
	Long:       `Flip an image.....`,
	Args:       cobra.MinimumNArgs(1), // force the argument to be passed
	ArgAliases: []string{"image"}, // your argument
	Run: func(cmd *cobra.Command, args []string) {
		
                if len(args) > 1 {
			println("You can only flip one image at a time or pass * to flip all images in the directory")
			os.Exit(1)
		}
		var path string = args[0]


                // *********************    your argument is 100% present, otherwise the user would be looking at the help menu
		

		}
	},
}

func init() {
	rootCmd.AddCommand(flipCmd)
	flipCmd.Flags().BoolP("horizontal", "H", false, "Flip horizontally")
	flipCmd.Flags().BoolP("vertical", "V", false, "Flip vertically")
}
```
