### ISSUE TITLE
Generate a toctree in ReST 

### ISSUE THREAD

**Issue by multimeric** [spf13/cobra#819]
For most people using the [ReST generator](https://github.com/spf13/cobra/blob/master/doc/rest_docs.md), they will be ultimately building their documentation with [Sphinx](http://www.sphinx-doc.org/en/1.5/index.html). However, ideally Sphinx wants all documents included using a [`toctree` directive](http://www.sphinx-doc.org/en/1.5/markup/toctree.html). For example:

```rest
.. toctree::
   :maxdepth: 2

   intro
   strings
   datatypes
   numeric
```

However, what cobra generates is an index file that looks more like:
```
* `singularity apps <singularity_apps>` 	 - apps <image path>
* `singularity build <singularity_build>` 	 - Build a new Singularity container
* `singularity capability <singularity_capability>` 	 - Manage Linux capabilities on containers
* `singularity exec <singularity_exec>` 	 - Execute a command within container
* `singularity inspect <singularity_inspect>` 	 - Display metadata for container if available
* `singularity instance <singularity_instance>` 	 - Manage containers running in the background
* `singularity keys <singularity_keys>` 	 - Manage OpenPGP key stores
* `singularity oci <singularity_oci>` 	 - Manage OCI containers
```

This works (once you add the `linkHandler` tweak mentioned [here](https://github.com/spf13/cobra/blob/master/doc/rest_docs.md#customize-the-output)), but because it's not part of the toctree, it won't appear in the sidebar or any tables of contents.

As far as I can tell, there's no way to get Cobra to generate a toctree as above, which is an issue because it means I will have to manually create one, and keep it up to date with the CLI, instead of having Cobra build it automatically. 

Is this possible? If not, should toctree generation be an option in `GenReSTTreeCustom`?

**Comment by codyaray** [comment]
Yeah I ended up copying the doc/rest_utils.go and manually modifying it to add a `toctree` as well as a few other customizations (like "Summary" instead of "Synopsis")
