### ISSUE TITLE
Is there  a way to not show `Global Flags` on --help.

### ISSUE THREAD

**Issue by rhatdan** [spf13/cobra#821]
In `podman` we are converting to cobra, but one of the problems I have with it, is that when I execute a command like

podman run --help

The global flags at the bottom of the help scroll off the top level local commands that I actually am interested in.
Almost no users will use the GloablFlags, but they are the thing that ends up showing up in the terminal.

**Comment by rhatdan** [comment]
@baude FYI

**Comment by eparis** [comment]
you'd basically have to replace the stock usage template with your own:
https://github.com/spf13/cobra/blob/master/command.go#L389

**Comment by rhatdan** [comment]
Thanks.
