### ISSUE TITLE
Supporting ENVVARS

### ISSUE THREAD

**Issue by alexec** [spf13/cobra#825]
I'd like to support reading values from an environment, this is because there are often many arguments that are used repeatedly:

```
argocd app create guest-book --grpc-web --insecure ...
argocd app sync guest-book --grpc-web --insecure
```

Which might be easier to do using:

```
export ARGOCD_OPTS="--grpc-web --insecure"
argocd app create guest-book
argocd app sync guest-book
```

I'm aware you can have a config file. This would take precedence over that file, but lower precedence to command line parameters.

**Comment by eparis** [comment]
I believe that spf13/viper is able to wire up ENV vars to flags. But I don't know viper well.

**Comment by alexec** [comment]
I'll investigate.

**Comment by alexec** [comment]
I hard coded in the end.
