### ISSUE TITLE
properly returning multiple exit codes 

### ISSUE THREAD

**Issue by marcb1** [spf13/cobra#837]
What's the proper way to return multiple exit codes inside my run function.
For example I want to return an exit code of 2 and 0 on non-error, based on the behavior of the function.
Should I just use `os.Exit`, or is there a better way to do so via the API.

**Comment by eparis** [comment]
I don't think there is really anything better than os.Exit in cobra.

**Comment by marcb1** [comment]
perfect, thanks!
