### ISSUE TITLE
non-golang computer

### ISSUE THREAD

**Issue by icobani** [spf13/cobra#843]
Hi guys,

I encountered a problem when i try deploy.

I write a simple cli exe in my development machine. Running smoothly. but i have a error like bellow when copy this exe to another non-golang computer.

`Error: exec: "go": executable file not found in %PATH%`

I dont want to install golang other computer. 

I think I'm skipping some things.

**Comment by eparis** [comment]
You want to use `go build` or `go install` to create a compiled binary. Then you run that binary. Not `go run`.

**Comment by icobani** [comment]
Yes i compile this project with go build and copy this exe another computer.

**Comment by icobani** [comment]
Like this
On my development computer
![Image](https://content.screencast.com/users/Ibrahim_Cobani/folders/Snagit/media/71bbf1ea-612c-4975-a124-60008762eefe/03.21.2019-21.14.png)

Error from another computer. Running smoothly
![image](https://content.screencast.com/users/Ibrahim_Cobani/folders/Snagit/media/ea57db5f-9cc9-4a18-bfab-6d1aafb3c0c9/03.21.2019-21.17.png)

**Comment by umarcor** [comment]
Did you try to build it statically, `CGO_ENABLED=0 go build -a`?

**Comment by icobani** [comment]
Ok I understand now. I copied helpers.go in my project from example. But this file have init function. I removed this method and everything is ok now.
