### ISSUE TITLE
windows app start error

### ISSUE THREAD

**Issue by mutavci** [spf13/cobra#844]
hi,
I want to run my application directly,
I set the default value

```
 if len(os.Args[1:]) == 0 {
		args := append([]string{"run"}, os.Args[1:]...)
		rootCmd.SetArgs(args)
	}

```
but  I'm getting a warning

> This is a command line tool.
> 
> You need to open cmd.exe and run it from there.

**Comment by ironsmile** [comment]
Hello @mutavci ! I've stumbled on the exact same thing. By default `cobra` does something called a "mouse trap" and does not allow you to run the application under Windows by clicking on the executable from explorer.exe. To disable this behaviour you can do the following:

```go
package main

"github.com/spf13/cobra"

func init() {
	cobra.MousetrapHelpText = ""
}
```

See the [documentation above MousetrapHelpText](https://godoc.org/github.com/spf13/cobra#pkg-variables) which explains this.

**Comment by mutavci** [comment]
@ironsmile  thank u

**Comment by cdujeu** [comment]
Hi, for the sake of google indexation (if anyone else is hitting this issue), this is particularly annoying when building an app with the `-ldflags "-H windowsgui"`. When double-clicking on the built executable, app starts then silently fails after 3 or 4 seconds. The suggested change does fix the problem.
