### ISSUE TITLE
Global command authentication and disabling on certain commands

### ISSUE THREAD

**Issue by lorenzoaiello** [spf13/cobra#859]
**Background**
I have an CLI using Cobra that interfaces with APIs that require authentication. There is a "login" command I've added that will generate the appropriate authentication tokens for other requests. If the last generated token has expired, I am preemptively requiring the user log in again.

**Problem**
As the CLI use cases are growing, there is a growing delta of commands that do and do not require authentication. At the moment, the authentication checks are handled in the root `PersistentPreRun` func and there is a hard-coded list of commands that are "exempt" from the authentication checks.

**Ask**
I'm interested in learning if others have experienced a similar issue or might have any recommendations on how best to resolve this.

**Initial Solutions**
I've come up with a couple of alternative solutions that I'm happy to handle the PR work for if they are the direction that the community agrees on.

- Extend `cobra.Command` to allow multiple hooks per command
- Extend `cobra.Command` to include the ability to add additional global elements that could be used for multiple purposes (not just authentication flags)

**Comment by johnSchnake** [comment]
I'm not sure I follow the asks:
>Extend cobra.Command to allow multiple hooks per command

There are pre/run/post hooks already; if you want multiple prerun hooks, just set the prerun to be call each of them in turn. I'm not sure I understand why you're limited here.

> Extend cobra.Command to include the ability to add additional global elements that could be used for multiple purposes (not just authentication flags)

I'm not sure I follow this one at all; what do you mean "additional global elements" and where do you mean to add them?

When you have multiple commands use the same set of flags you can typically just have a method that adds a handful at one time. You could, for instance, have something like:

```
c1 := newCmdWithAuth(...)
c2 := newCmdWithoutAuth(...)
```

Where those just return cobra commands with the auth or other default flags setup. That or something like:
```
c1 := *cobra.Command{}
addAuthFlags(c1)
```

Motivated by #1600 and the lack of activity on this issue I'm going to close it. Feel free to reopen if you want to discuss further.
