### ISSUE TITLE
Generating markdown documentation for "additional help topics"

### ISSUE THREAD

**Issue by aarzilli** [spf13/cobra#862]
Additional help topics are intentionally skipped when generating markdown (and other formats) documentation. For example: https://github.com/spf13/cobra/blob/v0.0.3/doc/md_docs.go#L136 and https://github.com/spf13/cobra/blob/v0.0.3/doc/md_docs.go#L103. 
Given that the sole purpose of additional help topics is to be help topics I think they should be included in the generated documentation. Or at least there should be an option to do that.

**Comment by mescanne** [comment]
I agree -- I'm having the same challenge. I'm not sure the rationale for excluding it in the first place. There are manpages for non-commands, e.g., man hosts usually brings up a manpage for the configuration file /etc/hosts. I would be inclined to just change it to include additional help topics, but it's not clear what this may break or even why it would matter.

**Comment by eparis** [comment]
That doesn't seem unreasonable. Although such pages shouldn't be part of man(1) since it wouldn't be for a command. Maybe in man(7) ?

**Comment by mescanne** [comment]
Would make sense -- in my case, I just want to have markdown generated. It would allow me to have all of the documentation contained within the CLI, but then exposed through generated markdown.

**Comment by mescanne** [comment]
I've put together a pull request here:
https://github.com/spf13/cobra/pull/966

Happy to have feedback -- this is the minimal set of changes I used to
generate my documentation.

Mark
