### ISSUE TITLE
Bash completion duplicated flags with and without equals signs 

### ISSUE THREAD

**Issue by weibeld** [spf13/cobra#868]
I have three flags for a sub-command, two of which are required.

At the beginning, everything looks ok (I think it's a design choice that only the required flags are completed, but not the optional ones):

```bash
$ cmd sub --[tab][tab]
--a-required=    --b-required=
```

But when I fill in one flag and then continue completing, it looks like this:

```bash
$ cmd sub --a-required=foo --[tab][tab]
--a-required    --b-required    --c-optional
--a-required=   --b-required=   --c-optional=
```

So, when there is already one flag on the command line, the behaviour is like this:

1. The optional flag is suggested too
2. Each flag is suggested in a version with and without an equals sign

Here is an example: https://asciinema.org/a/E6ozfI3nfZlZaiEMx4zpJArq5

Furthermore, this only happens when the flag already on the command line has a `=` between the flag name and the value. If flag name and value are separated by a space instead of a `=`, then the behaviour is as expected:

```bash
$ cmd sub --a-required foo --[tab][tab]
--a-required=    --b-required=
```

**Comment by weibeld** [comment]
I'm already working on a PR to fix these issues.

**Comment by marckhouzam** [comment]
I see this too.  
I think the quick solution is to add the missing non-equal form of required flags.
So instead of only having
```
must_have_one_flag+=("--required=")
```
it would need to be
```
must_have_one_flag+=("--required")
must_have_one_flag+=("--required=")
```

**Comment by johnSchnake** [comment]
Based on the time since response; going to close this as completed based on your advice.
