### ISSUE TITLE
Consistency in handling unknown commands/Expose findSuggestions()

### ISSUE THREAD

**Issue by colin-axner** [spf13/cobra#870]
The default handling of subcommands is to accept [arbitrary arguments](https://github.com/spf13/cobra/blob/f619abc1d7edb30544d1c956719d203ace73e9b1/args.go#L9-L24). If a subcommand is misspelled it prints out the help screen, but if a flag is added then it prints out the error was an unknown flag instead of an unknown command. For example, `root subcommand unknown --flag` returns `ERROR: unknown flag: --flag`. Expected behavior should be `ERROR: unknown command "unknown"`. 

One workaround I found is to DisableFlagParsing which turns flags into arguments. However, then the help screen is returned rather than the unknown command error. I found adding validation in the run works as a quick fix:
```
func validateArgs(cmd *cobra.Command, args []string) {
    if len(args) > 0 {
        fmt.Printf("ERROR: unknown command \"%s\" for \"%s\" \n\nDid you mean this?\n\t%v\n", args[0], cmd.CalledAs(), cmd.SuggestionsFor(args[0])[0])

    } else {
        fmt.Println(cmd.Help())
    }  
    return
}
```

Is there any other way of achieving this desired result? This seems like a function that cobra should support.

Furthermore why is `cmd.findSuggestions()` private where as `cmd.SuggestionsFor` public? I think it would be useful to expose findSuggestions so users could simply call a function that returns the full suggestion string instead of manually implementing it like I did above. Not sure if that should be a separate issue, but I think it would be a useful and easy fix.

**Comment by mkrump** [comment]
Have the same question. Was curious as to the best way to handle this.

**Comment by chrisgilmerproj** [comment]
Can you give an example of how you used the workaround? I'd love to take a shot at using it myself.

**Comment by colin-axner** [comment]
[Here](https://github.com/cosmos/cosmos-sdk/blob/280734d0e37f16b725906ec2b151c0b20e7dfaf1/client/cmd.go#L10) is my workaround. [Here](https://github.com/cosmos/cosmos-sdk/blob/280734d0e37f16b725906ec2b151c0b20e7dfaf1/x/auth/client/cli/tx.go#L16) is how I setup the command fields. Hope this helps!

**Comment by umarcor** [comment]
This is partially being addressed in #842.

**Comment by chrisgilmerproj** [comment]
Thanks a ton for the example!

**Comment by johnSchnake** [comment]
Seems to have been resolved:
```
➜ ./tmp sub2
Error: unknown command "sub2" for "main"

Did you mean this?
	sub

Run 'main --help' for usage.
➜ ./tmp sub2 --foo
Error: unknown command "sub2" for "main"

Did you mean this?
	sub

Run 'main --help' for usage.
```

**Comment by colin-axner** [comment]
Hi! Has it been included in a release? From quick testing, I'm able to reproduce the issue on v1.3.0. The example you reference uses subcommands in relation to the root command `main`. That works fine, but I'd expect something like:
```
./tmp sub sub2 --foo
Error: unknown flag: --foo
```
to occur. Can you confirm this?
