### ISSUE TITLE
adding Command childs

### ISSUE THREAD

**Issue by JAicewizard** [spf13/cobra#874]
instead of doing cmd.AddCommand() you can add the commands in the definition of cmd so that the CLI structure can be found in a single place and is easily traversal in code.

**Comment by jharshman** [comment]
@JAicewizard is this an issue you are experiencing or a suggestion? Either way can you be more detailed in your report?

**Comment by JAicewizard** [comment]
This is a suggestion.

Commands are rarely added at runtime, most are predefined.
It would be nice to be able to do something like this:

```
var commandName = &cobra.Command{
	Use:     "usage",
	Short:   "short description",
	Run:     function,
	Children: []*Command{
		ChildCommands,
	},
}
```
Instead of having this:
```
func main(){
	commandName.AddCommand(ChildCommands...)
}
```

Currently the only thing happening in the AddCommand is pre-calculations but those are all done with very little benefit and could be moved elsewhere(not pre-calculating or in an init function).
The only usage I found for `commandsMaxUseLen`, `commandsMaxCommandPathLen` and `commandsMaxNameLen` was in padding functions. I doubt that those would be called very often and that it would have an overall performance impact to have them not be pre-calculated.

**Comment by JAicewizard** [comment]
see https://github.com/JAicewizard/cobra/commit/09f0d088e590ec4dbfe77c631e5ccb56f5116cb5 for a version where you dont pre-calculate the padding lengths.
I will try to make it my fork fully implement this suggestion, then after you accept the feature itself I will open a merge request.

**Comment by JAicewizard** [comment]
because of the VAST amount of public getters using the parent, I don't think its possible to make the commands field public without breaking new code in some situations. removing some getters from the public API would make it almost but I assume that would break someones code and is not desirable.
Although I personally think the API is a bit bloated, I can't make decisions about that. I'll leave it at this.

**Comment by jharshman** [comment]
Thanks for your suggestion @JAicewizard, at this point in time, I think it would be best to avoid breaking changes to the API.  This is something to keep in mind for the future though.
