### ISSUE TITLE
have flag but don't need the flag's value

### ISSUE THREAD

**Issue by 609127400** [spf13/cobra#877]
sometimes, i just want to add a flag but don't need it's value, such as 'ssh -h' or 'tar -cvf' or 'myexe -s' to tell  my program's function a answer about only yes or no

**Comment by JAicewizard** [comment]
I think that would be a bool flag, I think they work that way

**Comment by eparis** [comment]
Thank you @JAicewizard that would have been my answer as well. Sound like you want to use bool flags!
