### ISSUE TITLE
zsh_completions produces indeterministic output

### ISSUE THREAD

**Issue by bmwiedemann** [spf13/cobra#890]
@babysnakes might know the code.

Steps to reproduce on openSUSE or Debian
```bash
osc checkout openSUSE:Factory/rclone && cd $_
osc build
```

probably from using some unsorted hash output.

observed diff has low entropy, so sometimes 2 builds have identical results by chance
```diff
--- old//usr/share/zsh/_rclone  2019-06-12 18:56:07.000000000 +0000
+++ new//usr/share/zsh/_rclone  2019-06-09 12:00:00.000000000 +0000
@@ -17,9 +17,6 @@
   ;;
   level2)
     case $words[2] in
-      serve)
-        _arguments '2: :(dlna ftp http restic webdav)'
-      ;;
       config)
         _arguments '2: :(create delete dump edit file password providers show update)'
       ;;
@@ -29,6 +26,9 @@
       help)
         _arguments '2: :(backend backends flags)'
       ;;
+      serve)
+        _arguments '2: :(dlna ftp http restic webdav)'
+      ;;
       *)
         _arguments '*: :_files'
       ;;
```

This output is generated by
./rclone genautocomplete zsh completion.zsh
via a call to GenZshCompletion

This bug was found while working on reproducible builds for openSUSE.

**Comment by babysnakes** [comment]
Hi @bmwiedemann,

I'll try to look at it tomorrow but please provide a link to download the code. I don't know `osc` but when trying to run the command in your instructions it seems to require user/password and I don't want to register if I don't have to.

**Comment by eparis** [comment]
That would happen if you were explicitly setting `cmd.Flags().SortFlags = false` but shouldn't be the default case...

**Comment by babysnakes** [comment]
@eparis @bmwiedemann The reason I wanted to look at the code is that the diff looks a little weird, looking at the template I don't see how it would generate it (there's no `$words[2]` only `"$words[1]"`. However it seems to me that the problem is with command sorting and not flags (which
is `EnableCommandSorting` ?)

**Comment by bmwiedemann** [comment]
Source is https://github.com/ncw/rclone/tree/v1.47.0 aka https://github.com/ncw/rclone/archive/v1.47.0.tar.gz

**Comment by babysnakes** [comment]
@bmwiedemann,  You are using the old completion system. Because you mentioned me I thought that you are using the new system. Forget everything I said, I was confused 😄 .

@eparis please take over, I know nothing about the old system.

**Comment by bmwiedemann** [comment]
Oh, I didnt expect new software to use such old code.

**Comment by bmwiedemann** [comment]
I also tested rclone-1.48.0 and it also has this issue.

**Comment by eparis** [comment]
I mean, it looks like this is 2 year old version of cobra and suffers from a problem that doesn't exist anymore. Nor sure what else we can do here. That old code is iterating over a map, so it makes sense why it would be unpredicable...

https://github.com/ncw/rclone/blob/v1.47.0/vendor/github.com/spf13/cobra/zsh_completions.go#L109

**Comment by MichaelMure** [comment]
You can use my PR to "fix" the old generator: https://github.com/spf13/cobra/pull/801

**Comment by bmwiedemann** [comment]
Proposed it there https://github.com/ncw/rclone/pull/3289 
Thanks for your help. Nothing left to be done here...

**Comment by bmwiedemann** [comment]
They updated cobra to 0.0.5 now. All working fine.
