### ISSUE TITLE
why does 'cobra init' require --pkg-name when go.mod is present?

### ISSUE THREAD

**Issue by josharian** [spf13/cobra#891]
The first line of go.mod contains the fully qualified import path of the module. Could `cobra init` just use it?

**Comment by jharshman** [comment]
That assumes a `go.mod` file is present which is not required for `init` in a new directory.

**Comment by josharian** [comment]
Right. But when it is present (as it was in my case), cobra could use it.

**Comment by jharshman** [comment]
I don't see any immediate problem with that functionality.  If you want to open up a PR with your suggested changes, tag me and I'll take a look.

**Comment by josharian** [comment]
Hmmm. Blocked on https://github.com/golang/go/issues/31761, in particular, the addition of golang.org/x/mod/modfile.

**Comment by jharshman** [comment]
@josharian if this is blocked and has no immediate resolution I think it's appropriate to close this issue.

**Comment by josharian** [comment]
As you wish.
