### ISSUE TITLE
glide is unable to fetch the following packages

### ISSUE THREAD

**Issue by VineethReddy02** [spf13/cobra#897]
## "k8s.io/kubernetes/pkg/kubectl/cmd/util" 

glide is unable to retrieve above dependencies

```package main

import (
	"log"
	"io/ioutil"
	"os"
	"k8s.io/kubernetes/pkg/kubectl/cmd"
	cmdutil "k8s.io/kubernetes/pkg/kubectl/cmd/util"
	"github.com/spf13/cobra/doc"
)

func main() {
	kubectl := cmd.NewKubectlCommand(cmdutil.NewFactory(nil), os.Stdin, ioutil.Discard, ioutil.Discard)
	err := doc.GenMarkdownTree(kubectl, "./")
	if err != nil {
		log.Fatal(err)
	}
}
```

My use case here is am trying to generate markdown docs from cobra library as mentioned in docs.
And bashcompletions for kubectl command (which is kubectl plugin).

**Comment by jharshman** [comment]
Feels like an issue with Glide and not with Cobra. You might want to submit an issue on that project instead.

Just out of curiosity, are you getting any error messages from running glide:
`glide get github.com/spf13/cobra`

**Comment by jharshman** [comment]
@VineethReddy02 have you resolved your issue?

**Comment by VineethReddy02** [comment]
@jharshman sorry for the late reply. I managed to make it work, I had an issue with ```glide.yaml```
