### ISSUE TITLE
any possible to have only argument's shorthand

### ISSUE THREAD

**Issue by hellflame** [spf13/cobra#918]
```go
command := &cobra.Command{
		Use: "cmd",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Println(cmd, args)
		},
	}
command.PersistentFlags().BoolVarP(&args.TestConfig, "", "t", false, "test config file")
```

I thought if there is no error occur, it should be some issue. also, flags with only shorthand is reasonable and common in many programs like `ls`

![image](https://user-images.githubusercontent.com/7326970/61917171-5814a980-af7e-11e9-98e4-c54b64e04f02.png)

**Comment by jharshman** [comment]
@hellflame, this is coming from the pflag package.  Here's a link to the GoDoc:
https://godoc.org/github.com/spf13/pflag

I think the functionality you're looking for is in there. If not, https://github.com/spf13/pflag would be the appropriate place to create an issue.

**Comment by jharshman** [comment]
@hellflame I'd rather you don't cross reference this issue from pflag here. Please post your issue on the pflag repo.
