### ISSUE TITLE
unknown command return 

### ISSUE THREAD

**Issue by yujianFresh** [spf13/cobra#919]
when I execute **go run main.go -h**,
it can print 
```
a token transfer tool

Usage:
  token-tool [flags]
  token-tool [command]

Available Commands:
  eth         eth chain command
  help        Help about any command

Flags:
  -h, --help   help for token-tool

Use "token-tool [command] --help" for more information about a command.
```
then I execute **go run main.go token-tool -h**
it return 
```
unknown command "token-tool" for "token-tool"
Error: unknown command "token-tool" for "token-tool"
Run 'token-tool --help' for usage.
```

can anyone show me the question ?

**Comment by umarcor** [comment]
`token-tool` seems to be the name of the app/binary. Since you are not building it, but running it instead, there is no need to provide `token-tool` as an argument. It is incorrect, indeed. You should provide one of the two valid subcommands instead (`eth` or `help`). So:

```
go run main.go eth -h
```

or

```
go build
./token-tool -h
./token-tool eth -h
```

**Comment by johnSchnake** [comment]
Thanks for the question. Seems asked and answered, so I'll go ahead and close.
