### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [spf13/cobra#931]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

P.S - [Fuzzit CLI](https://github.com/fuzzitdev/fuzzit) is also based on awesome cobra:)

Cheers,
Yevgeny

**Comment by eparis** [comment]
I love testing. All the testing. If you have a PR I'll very happily take a look.  Though I wonder if we are more likely to find problems in pflag instead of here in cobra...

**Comment by yevgenypats** [comment]
@eparis I think you are right, pflag would be the right place to write fuzz tests at least in the beginning. So I'll Contribute the PR in pflag https://github.com/spf13/pflag.

Also, I need to mention that we have a [reward program](https://fuzzit.dev/2019/08/12/announcing-rewards-for-go-rust-oss-projects/) in case you have time/want to implement this yourself I would be happy to reward you as well as get unbiased feedback on how smooth the integration was. Let me know what you prefer.
