### ISSUE TITLE
ambiguous import: found github.com/ugorji/go/codec in multiple modules when i use cobra and gin both

### ISSUE THREAD

**Issue by KowloonZh** [spf13/cobra#938]
I noticed viper v1.4.0 use the package "github.com/ugorji/go v1.1.4 // indirect", but cobra v0.0.5 still used viper v1.3.2

So can you upgrade cobra go.mod with viper 1.4.0

**Comment by plo-** [comment]
Yes it's really annoying... Thanks in advance!
