### ISSUE TITLE
Remove type of variable (ex-string)  in flags when using StringVar in cobra commnad

### ISSUE THREAD

**Issue by rishav-csenitjsr** [spf13/cobra#941]
when i am using flag (using StringVar), flag is showing like this:

  **--config  string  config file (default is $HOME/.xyz.yml)**

I don't want to show the type of variable in my flag i.e. I want my cobra to show below flag :

  **--config               config file (default is $HOME/.xyz.yml)**
can you please fix this issue @eparis

**Comment by umarcor** [comment]
Hi @rishav-csenitjsr! I think that this might be handled by pflag, and not by cobra. Please, see https://github.com/spf13/cobra/blob/master/command.go#L478.

**Comment by jharshman** [comment]
@rishav-csenitjsr , @umarcor is correct, please make your issue or PR on the pflag repo.

**Comment by rishav-csenitjsr** [comment]
Thanks a lot @umarcor @jharshman
