### ISSUE TITLE
Idea: Can we take inputs in flag like --arr=["a", "b", "c"]

### ISSUE THREAD

**Issue by rishav-csenitjsr** [spf13/cobra#942]
while using cobra flags, can I take values of flag like ["a", "b"] from the command line ?
@eparis @spf13 @jharshman

**Comment by jharshman** [comment]
@rishav-csenitjsr This is outside the scope of the Cobra package.

The godocs for pflag should answer your question. https://godoc.org/github.com/spf13/pflag#FlagSet.StringSlice
