### ISSUE TITLE
Set Bool Flag in RootCMD

### ISSUE THREAD

**Issue by ClaytonNorthey92** [spf13/cobra#965]
I am using the `BoolVar` method to set a package variable to the value of a boolean flag passed in the cli, but it is always set to false.  I am wondering what I am doing wrong.

Quickest way to reproduce:
command:
```
go run main.go --debug=true
```

`main.go`
```go
package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{}

var debug bool

func main() {
	rootCmd.PersistentFlags().BoolVar(&debug, "debug", false, "set log level to debug")

	if debug == false {
		panic(fmt.Sprintf("incorrect %b\n", debug))
	}
}
```

`go.mod`
```
module logrus-bug

go 1.12

require github.com/spf13/cobra v0.0.5 // indirect

```

The above panics because `debug` is alway `false`. From what I understand, `BoolVar` should be setting the package variable to `true` since I passed that in the cli with `--debug=true`.

**Comment by umarcor** [comment]
I'm afraid that you example produces the same output as:

```go
package main

import (
	"fmt"
)

var debug bool

func main() {
	if debug == false {
		panic(fmt.Sprintf("incorrect %b\n", debug))
	}
}
```

Please, read the documentation carefully. You can use the generator (https://github.com/spf13/cobra#using-the-cobra-generator) to create a basic project, or you can use https://github.com/spf13/cobra/blob/master/cobra/main.go and https://github.com/spf13/cobra/blob/master/cobra/cmd/root.go as a reference.

**Comment by ClaytonNorthey92** [comment]
okay I was trying to create the smallest example I could to reproduce what I thought was an error, maybe I did something, wrong, will keep looking

**Comment by umarcor** [comment]
> okay I was trying to create the smallest example I could to reproduce what I thought was an error, maybe I did something, wrong, will keep looking

```go
package main

import (
  "fmt"
  "os"

  "github.com/spf13/cobra"
)

func main() {
  if err := rootCmd.Execute(); err != nil {
    fmt.Println(err)
    os.Exit(1)
  }
}

var debug bool

var rootCmd = &cobra.Command{
  Use:   "hugo",
  Short: "Hugo is a very fast static site generator",
  Run: func(cmd *cobra.Command, args []string) {
	if debug == false {
		panic(fmt.Sprintf("incorrect %b\n", debug))
	}
  },
}

func init() {
    rootCmd.PersistentFlags().BoolVar(&debug, "debug", false, "set log level to debug")
}
```

```sh
root@6b26c49a8617:~/maingo# go run main.go 
panic: incorrect %!b(bool=false)


goroutine 1 [running]:
main.glob..func1(0x719820, 0x7380e0, 0x0, 0x0)
        /root/maingo/main.go:24 +0xc5
github.com/spf13/cobra.(*Command).execute(0x719820, 0xc00007a1b0, 0x0, 0x0, 0x719820, 0xc00007a1b0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x719820, 0xc000000100, 0xc000042f50, 0x40625f)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /root/maingo/main.go:11 +0x31
exit status 2
root@6b26c49a8617:~/maingo# go run main.go --debug
root@6b26c49a8617:~/maingo# 
```

**Comment by ClaytonNorthey92** [comment]
you're right I was not detailed enough, but I did get it working with using local flags for the command I wanted to run, you can disregard

thank you for your quick response though 👍
