### ISSUE TITLE
Undefined variables in README.md example

### ISSUE THREAD

**Issue by srybacki** [spf13/cobra#967]
The variables `projectBase` and `userLicense` are used  in the [README.md example](https://github.com/spf13/cobra#example), but the variables are not declared in the example code.  Should the variables be declared as package-level variables like `cfgFile`?

**Comment by umarcor** [comment]
Actually, `cfgFile` was added just a couple of months ago. As @jharshman [commented](https://github.com/spf13/cobra/pull/924#issuecomment-518292844):

> It should be noted that copying/pasting from the README into your source code isn't advised as the examples are just code snippets. You should use the cobra generator instead.
