### ISSUE TITLE
Failed when install: pflag.ParseErrorsWhitelist

### ISSUE THREAD

**Issue by lewki** [spf13/cobra#984]
go get -u github.com/spf13/cobra/cobra
# github.com/spf13/cobra
github.com/spf13/cobra/command.go:34:25: undefined: pflag.ParseErrorsWhitelist

**Comment by umarcor** [comment]
@lewki, please provide some info about your context. The procedure seems to work as expected in a clean environment:

```sh
# docker run --rm -it golang bash
root@f9b8ff38a65a:/go# go get -u github.com/spf13/cobra/cobra
root@f9b8ff38a65a:/go# exit
exit

# docker run --rm -it golang bash
root@b2024f83c268:/go# mkdir /tmp/mytmp
root@b2024f83c268:/go# cd /tmp/mytmp/
root@b2024f83c268:/tmp/mytmp# go get -u github.com/spf13/cobra/cobra
root@b2024f83c268:/tmp/mytmp# exit
exit
```

**Comment by lewki** [comment]
thx,   my go version go1.13  conflict with previous version 1.11 .
