### ISSUE TITLE
shell completion should behave uniformly for bash and zsh when sourced

### ISSUE THREAD

**Issue by srlehn** [spf13/cobra#986]
I was under the assumption that because `. <(app genshcomp)` ("app genshcomp" returns shell completion code) worked for bash that the generated zsh code should behave the same for zsh. I can't see any reason to block this behaviour for zsh if only a single line has to be added (https://github.com/spf13/cobra/pull/887).

For my portable application I value the ability to directly inject the completion code into the running shell without having to save a temporary file or additional commands.

I suggest reopening https://github.com/spf13/cobra/pull/887, at least for me it works fine.

**Comment by corneliusweig** [comment]
Big :+1:

**Comment by marckhouzam** [comment]
This article gives some reason why sourcing a completion script isn't great: https://medium.com/@jzelinskie/please-dont-ship-binaries-with-shell-completion-as-commands-a8b1bcb8a0d0

That being said, what you can do is add the missing compdef line to your .zshrc (or something of the sort) and then sourcing the completion file will work.

**Comment by marckhouzam** [comment]
I believe @jharshman has confirmed he prefers to follow zsh's best practices and not include the `compdef` line in the script: https://github.com/spf13/cobra/pull/1070#discussion_r408961812

The program using Cobra can easily choose to add this line itself.

@jharshman I believe we can close this issue.

**Comment by jharshman** [comment]
Yes, that is correct @marckhouzam.  Closing this issue.
