### ISSUE TITLE
Subcommand after a positional arg

### ISSUE THREAD

**Issue by amreo** [spf13/cobra#997]
Is possible to add a subcommand after a positional arg like the following command ```ip link set enp4s0 up``` (enp4s0 == arg, up == subcommand)?

**Comment by umarcor** [comment]
This should already be supported. See https://github.com/spf13/pflag#command-line-flag-syntax:

> Unlike the flag package, flags can be interspersed with arguments anywhere on the command line before this terminator.

**Comment by jharshman** [comment]
@amreo 
https://github.com/spf13/cobra#concepts

This is something you would have to handle yourself.  It's worth noting in your example, that `enp4s0` and `up` are both arguments.
ref: https://github.com/shemminger/iproute2/blob/master/ip/iplink.c
